cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass an isolated TEST_BINARY_DIR")
endif()
get_filename_component(_cmake_dir "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
# Each run owns a new fixture; never remove an existing user-supplied directory.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef _id)
set(_source "${TEST_BINARY_DIR}/${_id}/source")
set(_build "${TEST_BINARY_DIR}/${_id}/build")
file(MAKE_DIRECTORY "${_source}/rom/example" "${_source}/arch/all-unix/example")
configure_file("${CMAKE_CURRENT_LIST_DIR}/manifest-reconfigure/CMakeLists.txt"
  "${_source}/CMakeLists.txt" COPYONLY)
file(WRITE "${_source}/rom/example/mmakefile.src" "#MM example-includes : kernel-exec-includes\n")
file(WRITE "${_source}/arch/all-unix/example/mmakefile.src" "FILES := original\n")
file(WRITE "${_source}/mmake.config.in" "ignoredir upstream-cache\n")
file(MAKE_DIRECTORY "${_source}/upstream-cache")
file(WRITE "${_source}/upstream-cache/mmakefile.src" "FILES := ignored-by-upstream\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -G Ninja -S "${_source}" -B "${_build}"
  "-DAROS_MANIFEST_HELPER=${_cmake_dir}/AROSManifests.cmake" COMMAND_ERROR_IS_FATAL ANY)

function(check_build expected_count)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target manifest-check
    COMMAND_ERROR_IS_FATAL ANY)
  file(READ "${_build}/configure-count.txt" _count)
  if(NOT _count STREQUAL "${expected_count}")
    message(FATAL_ERROR "Expected ${expected_count} configurations, got ${_count}")
  endif()
  file(READ "${_build}/built.txt" _built)
  set(_expected "")
  file(GLOB_RECURSE _manifests LIST_DIRECTORIES FALSE
    "${_source}/rom/mmakefile.src" "${_source}/arch/mmakefile.src" "${_source}/incoming/mmakefile.src"
    "${_source}/rom/mmakefile" "${_source}/arch/mmakefile" "${_source}/incoming/mmakefile")
  list(SORT _manifests)
  foreach(_manifest IN LISTS _manifests)
    if(_manifest MATCHES "/mmakefile$" AND EXISTS "${_manifest}.src")
      continue()
    endif()
    file(RELATIVE_PATH _relative "${_source}" "${_manifest}")
    file(SHA256 "${_manifest}" _hash)
    string(APPEND _expected "${_relative}:${_hash}\n")
  endforeach()
  if(NOT _built STREQUAL _expected)
    message(FATAL_ERROR "Build consumed stale manifest metadata")
  endif()
endfunction()

check_build(1)
check_build(1)
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1 COMMAND_ERROR_IS_FATAL ANY)
file(APPEND "${_source}/rom/example/mmakefile.src" "#MM example-includes : new-includes\n")
check_build(2)
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1 COMMAND_ERROR_IS_FATAL ANY)
file(APPEND "${_source}/arch/all-unix/example/mmakefile.src" "FILES += override\n")
check_build(3)
file(MAKE_DIRECTORY "${_source}/rom/new-module")
file(WRITE "${_source}/rom/new-module/mmakefile.src" "FILES := added\n")
check_build(4)
file(MAKE_DIRECTORY "${_source}/incoming/new-module")
file(WRITE "${_source}/incoming/new-module/mmakefile.src" "FILES := upstream\n")
check_build(5)
file(REMOVE "${_source}/rom/new-module/mmakefile.src")
check_build(6)
file(REMOVE "${_source}/incoming/new-module/mmakefile.src")
check_build(7)
check_build(7)
# Build trees are excluded without requiring a particular directory name.
file(MAKE_DIRECTORY "${_source}/cmake-build-test/cache")
file(WRITE "${_source}/cmake-build-test/CMakeCache.txt" "# generated build tree\n")
file(WRITE "${_source}/cmake-build-test/cache/mmakefile.src" "FILES := not-a-source-input\n")
# Adding the top-level directory changes the inventory, but its contents do not.
check_build(8)
file(APPEND "${_source}/cmake-build-test/cache/mmakefile.src" "FILES += still-not-an-input\n")
check_build(8)
file(APPEND "${_source}/upstream-cache/mmakefile.src" "FILES += still-ignored\n")
check_build(8)
file(MAKE_DIRECTORY "${_source}/.hidden-state")
file(WRITE "${_source}/.hidden-state/mmakefile.src" "FILES := editor-or-sandbox-state\n")
check_build(8)
file(WRITE "${_source}/incoming/new-module/mmakefile" "#MM incoming : layer\n")
check_build(9)
file(APPEND "${_source}/incoming/new-module/mmakefile" "#MM incoming : added\n")
check_build(10)
file(WRITE "${_source}/incoming/new-module/mmakefile.src" "#MM source-preferred : layer\n")
check_build(11)
file(APPEND "${_source}/incoming/new-module/mmakefile" "# stale generated counterpart\n")
check_build(11)
file(REMOVE "${_source}/incoming/new-module/mmakefile.src")
check_build(12)
file(REMOVE "${_source}/incoming/new-module/mmakefile")
check_build(13)
check_build(13)
message(STATUS "Manifest edits, layer edits, additions, removals and no-op regeneration checks passed")
