cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass an isolated TEST_BINARY_DIR")
endif()
get_filename_component(_source "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
include("${_source}/cmake/AROSMmakeBuild.cmake")
set(AROS_TARGET linux-x86_64)
set(AROS_CONFIG_BUILD_DIR "${TEST_BINARY_DIR}/config")
file(MAKE_DIRECTORY "${AROS_CONFIG_BUILD_DIR}/bin/linux-x86_64/gen/config")
file(WRITE "${AROS_CONFIG_BUILD_DIR}/bin/linux-x86_64/gen/config/target.cfg" "FAMILY := unix\n")
set(AROS_SOURCE_DIR "${TEST_BINARY_DIR}/source")
set(MODULE_PATH compiler/example)
set(MODULE_BASE_SOURCES stdc/jump+handler.c)
set(MODULE_RESOLVED_LAYERS "first;second")
set(MODULE_LAYER_MANIFEST_LAYERS "first;second")
set(MODULE_LAYER_OVERRIDES "first:../stdc/jump+handler.s;second:jump+handler.c")
file(MAKE_DIRECTORY "${AROS_SOURCE_DIR}/compiler/example/stdc"
  "${AROS_SOURCE_DIR}/compiler/example/other" "${AROS_SOURCE_DIR}/arch/first/example"
  "${AROS_SOURCE_DIR}/arch/first/stdc" "${AROS_SOURCE_DIR}/arch/second/example")
file(WRITE "${AROS_SOURCE_DIR}/compiler/example/stdc/jump+handler.c" "#error generic stub\n")
file(WRITE "${AROS_SOURCE_DIR}/arch/first/stdc/jump+handler.s" "")
file(WRITE "${AROS_SOURCE_DIR}/arch/second/example/jump+handler.c" "")
if(SCENARIO STREQUAL "ambiguous")
  list(APPEND MODULE_BASE_SOURCES other/jump+handler.c)
  file(WRITE "${AROS_SOURCE_DIR}/compiler/example/other/jump+handler.c" "")
elseif(SCENARIO STREQUAL "missing")
  set(MODULE_LAYER_OVERRIDES "first:missing/jump+handler.s")
elseif(SCENARIO STREQUAL "missing-addition")
  set(MODULE_LAYER_ADDITIONS "first:missing/extra")
endif()
_aros_resolve_module_sources(_sources)
if(SCENARIO)
  message(FATAL_ERROR "Invalid ${SCENARIO} metadata was accepted")
endif()
if(NOT _sources STREQUAL "${AROS_SOURCE_DIR}/arch/first/example/../stdc/jump+handler.s")
  message(FATAL_ERROR "Relative/extension override or layer precedence lost: ${_sources}")
endif()
foreach(_case IN ITEMS ambiguous missing missing-addition)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DTEST_BINARY_DIR=${TEST_BINARY_DIR}/${_case}"
    "-DSCENARIO=${_case}" -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "(Ambiguous base source|Could not resolve declared layer (override|addition))")
    message(FATAL_ERROR "Invalid ${_case} override did not fail explicitly: ${_out}${_err}")
  endif()
endforeach()

set(AROS_SOURCE_DIR "${_source}")
set(MODULE_PATH compiler/crt)
set(MODULE_MMAKE_NAME compiler-stdlib)
_aros_parse_mmake_module("${_source}/${MODULE_PATH}/mmakefile.src")
set(MODULE_BASE_SOURCES stdc/longjmp stdc/setjmp)
foreach(_base IN LISTS MODULE_BASE_SOURCES)
  if(NOT _base IN_LIST MODULE_MMAKE_PARSED_FILES)
    message(FATAL_ERROR "CRT fixture no longer describes the upstream manifest: ${_base}")
  endif()
endforeach()
_aros_parse_mmake_module("${_source}/arch/x86_64-all/crt/mmakefile.src")
set(MODULE_RESOLVED_LAYERS x86_64-all)
set(MODULE_LAYER_MANIFEST_LAYERS x86_64-all)
set(MODULE_LAYER_OVERRIDES)
foreach(_asm IN LISTS MODULE_MMAKE_PARSED_ARCH_ASMFILES)
  list(APPEND MODULE_LAYER_OVERRIDES "x86_64-all:${_asm}")
endforeach()
_aros_resolve_module_sources(_sources)
foreach(_name IN ITEMS longjmp setjmp)
  if(NOT "${_source}/arch/x86_64-all/crt/../stdc/${_name}.s" IN_LIST _sources)
    message(FATAL_ERROR "CRT did not select the declared assembly ${_name}: ${_sources}")
  endif()
endforeach()

# The declared ../fenv is found through the module-directory VPATH fallback.
set(MODULE_MMAKE_NAME compiler-m)
_aros_parse_mmake_module("${_source}/arch/x86_64-all/crt/mmakefile.src")
set(MODULE_BASE_SOURCES)
set(MODULE_LAYER_OVERRIDES)
set(MODULE_LAYER_ADDITIONS)
foreach(_file IN LISTS MODULE_MMAKE_PARSED_ARCH_FILES)
  list(APPEND MODULE_LAYER_ADDITIONS "x86_64-all:${_file}")
endforeach()
_aros_resolve_module_sources(_sources)
if(NOT "${_source}/arch/x86_64-all/crt/fenv.c" IN_LIST _sources)
  message(FATAL_ERROR "Math runtime lost its declared fenv implementation: ${_sources}")
endif()
message(STATUS "CRT layer overrides/additions, source-directory fallback, precedence and failure checks passed")
