cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass an isolated TEST_BINARY_DIR")
endif()
get_filename_component(_cmake_dir "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef _id)
set(_root "${TEST_BINARY_DIR}/${_id}")
set(_src "${_root}/source")
set(_build "${_root}/build")
file(MAKE_DIRECTORY "${_src}/data")
configure_file("${CMAKE_CURRENT_LIST_DIR}/static-files/CMakeLists.txt" "${_src}/CMakeLists.txt" COPYONLY)
set(_recipe [=[
#MM example : setup
example :
	@if [ -d $(SRCDIR)/$(CURDIR)/inputs ] ; then $(MKDIR) $(AROSDIR)/Devs/Drivers ; $(CP) $(SRCDIR)/$(CURDIR)/inputs/* $(AROSDIR)/Devs/Drivers ; fi
#MM
setup ::
    %mkdirs_q $(AROSDIR)/Storage $(AROSDIR)/Devs/Printers
]=])
file(WRITE "${_src}/data/mmakefile.src" "${_recipe}")
function(run)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Command failed (${_result}): ${ARGN}\n${_out}${_err}")
  endif()
endfunction()
function(build)
  run("${CMAKE_COMMAND}" --build "${_build}" --target static-files -j 6)
endfunction()
function(noop)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target static-files
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 OR NOT _out MATCHES "no work to do" OR _out MATCHES "Re-running CMake")
    message(FATAL_ERROR "Expected no-op without regeneration: ${_out}${_err}")
  endif()
endfunction()
function(compare name)
  run("${CMAKE_COMMAND}" -E compare_files "${_src}/data/inputs/${name}" "${_build}/runtime/Devs/Drivers/${name}")
endfunction()
function(reject recipe diagnostic)
  file(WRITE "${_src}/data/mmakefile.src" "${recipe}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${_src}" -B "${_build}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "${diagnostic}")
    message(FATAL_ERROR "Expected ${diagnostic}, got (${_result}): ${_out}${_err}")
  endif()
endfunction()
run("${CMAKE_COMMAND}" -G Ninja -S "${_src}" -B "${_build}"
  "-DAROS_CMAKE_DIR=${_cmake_dir}" -DAROS_STATIC_GRAPH=ON)
build()
if(NOT IS_DIRECTORY "${_build}/runtime/Storage" OR NOT IS_DIRECTORY "${_build}/runtime/Devs/Printers")
  message(FATAL_ERROR "Double-colon/space-indented mkdirs recipe was not translated")
endif()
if(EXISTS "${_build}/runtime/Devs/Drivers")
  message(FATAL_ERROR "Missing optional input must not create a destination")
endif()
noop()
file(MAKE_DIRECTORY "${_src}/data/inputs")
file(WRITE "${_src}/data/inputs/First" "one\n")
file(WRITE "${_src}/data/inputs/Second" "two\n")
build()
compare(First)
compare(Second)
noop()
file(WRITE "${_src}/data/inputs/.hidden" "not a shell wildcard input\n")
noop()
if(EXISTS "${_build}/runtime/Devs/Drivers/.hidden")
  message(FATAL_ERROR "Hidden file was copied")
endif()
run("${CMAKE_COMMAND}" -E sleep 1)
file(APPEND "${_src}/data/inputs/First" "edited\n")
build()
compare(First)
file(WRITE "${_src}/data/inputs/Third" "upstream addition\n")
build()
compare(Third)
# A separate manifest can explicitly own the copy destination directory.
file(MAKE_DIRECTORY "${_src}/owner")
file(WRITE "${_src}/owner/mmakefile.src" [=[
#MM example : directory-owner
#MM
directory-owner ::
    %mkdirs_q $(AROSDIR)/Devs/Drivers
]=])
build()
noop()
file(REMOVE_RECURSE "${_build}/runtime/Devs/Drivers")
file(REMOVE_RECURSE "${_build}/runtime/Devs/Printers")
build()
if(NOT IS_DIRECTORY "${_build}/runtime/Devs/Printers")
  message(FATAL_ERROR "Missing setup directory was not recreated")
endif()
compare(First)
compare(Second)
compare(Third)
noop()
file(REMOVE "${_src}/data/inputs/Third")
build()
# Like the legacy CP recipe, source removal drops the producer but does not
# delete previously staged files. A clean tree contains only current inputs.
file(REMOVE "${_build}/runtime/Devs/Drivers/Third")
noop()
file(REMOVE_RECURSE "${_src}/owner")
build()
file(REMOVE_RECURSE "${_src}/data/inputs")
build()
file(REMOVE_RECURSE "${_build}/runtime/Devs/Drivers")
noop()
file(MAKE_DIRECTORY "${_src}/data/inputs")
reject("${_recipe}" "has no matching source files")
file(WRITE "${_src}/data/inputs/First" "one\n")
file(MAKE_DIRECTORY "${_src}/data/inputs/Subdirectory")
reject("${_recipe}" "requires immediate source files")
file(REMOVE_RECURSE "${_src}/data/inputs/Subdirectory")
file(WRITE "${_root}/unowned" "outside source tree\n")
file(CREATE_LINK "${_root}/unowned" "${_src}/data/inputs/Unowned" SYMBOLIC)
reject("${_recipe}" "requires an owned source")
file(REMOVE "${_src}/data/inputs/Unowned")
reject("${_recipe}\ninputs/First :\n\t@echo generated\n" "cannot adopt a generated prerequisite")
reject("${_recipe}\ninputs/% : source/%\n\t@echo generated\n" "cannot adopt a generated prerequisite")
file(MAKE_DIRECTORY "${_src}/data/other-inputs")
file(WRITE "${_src}/data/other-inputs/First" "conflicting producer\n")
string(REPLACE "/inputs" "/other-inputs" _other "${_recipe}")
string(REPLACE "example :" "other :" _other "${_other}")
reject("${_recipe}\n#MM example : other\n${_other}" "Conflicting static-file producers")
string(REPLACE " ; fi" " ; echo unexpected ; fi" _bad "${_recipe}")
reject("${_bad}" "Unsupported static copy recipe")
string(REPLACE "$(CP)" "$(CP) -r" _bad "${_recipe}")
reject("${_bad}" "Unsupported static copy recipe")
string(REPLACE "example :\n" "example : unexpected\n" _bad "${_recipe}")
reject("${_bad}" "targets/prerequisites")
string(REPLACE "$(AROSDIR)/Devs/Drivers" "${_root}/escaped" _bad "${_recipe}")
reject("${_bad}" "outside.*runtime|outside.*system|Unsafe static")
file(MAKE_DIRECTORY "${_build}/runtime/Devs/Drivers")
file(CREATE_LINK "${_root}/unowned" "${_build}/runtime/Devs/Drivers/First" SYMBOLIC)
reject("${_recipe}" "escapes the native runtime tree")
file(REMOVE "${_build}/runtime/Devs/Drivers/First")
string(REPLACE "$(SRCDIR)/$(CURDIR)/inputs" "${_build}/generated" _bad "${_recipe}")
reject("${_bad}" "requires an owned source")
file(MAKE_DIRECTORY "${_src}/data/generated")
file(WRITE "${_src}/data/generated/First" "stale\n")
file(READ "${_src}/CMakeLists.txt" _fixture)
file(WRITE "${_src}/CMakeLists.txt" "set(AROS_LEGACY_BUILD_DIR \"${_src}/data/generated\")\n${_fixture}")
string(REPLACE "$(SRCDIR)/$(CURDIR)/inputs" "${_src}/data/generated" _bad "${_recipe}")
reject("${_bad}" "requires an owned source")
file(WRITE "${_src}/data/mmakefile.src" "${_recipe}")
run("${CMAKE_COMMAND}" -S "${_src}" -B "${_build}")
build()
compare(First)
noop()
message(STATUS "Guarded flat-directory copies, inventories, ownership and no-op checks passed")
