cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass TEST_BINARY_DIR")
endif()
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
string(RANDOM LENGTH 10 ALPHABET abcdef0123456789 _id)
set(_root "${TEST_BINARY_DIR}/${_id}")
set(_src "${_root}/src")
set(_build "${_root}/build")
file(MAKE_DIRECTORY "${_src}/first" "${_src}/second" "${_src}/include"
  "${_src}/config-snapshot/bin/linux-x86_64/gen/config")
configure_file("${CMAKE_CURRENT_LIST_DIR}/programs/CMakeLists.txt" "${_src}/CMakeLists.txt" COPYONLY)
set(_config "${_src}/config-snapshot/bin/linux-x86_64/gen/config/target.cfg")
set(_config_text "FAMILY := unix\nCPPFLAGS = $(USER_CPPFLAGS)\nCFLAGS = $(USER_CFLAGS)\nLDFLAGS = $(USER_LDFLAGS)\nNOSTARTUP_LDFLAGS := -nostartfiles\n")
file(WRITE "${_config}" "${_config_text}OBJ_SUFFIX := initial\n")
file(WRITE "${_src}/mmake.config.in" "defaulttarget image\n")
file(WRITE "${_src}/mmakefile.src" "#MM image : one two\n")
file(WRITE "${_src}/support.c" "int support(void) { return 0; }\n")
file(WRITE "${_src}/extra.h" "#define EXTRA_VALUE 1\n")
file(WRITE "${_src}/first/value.h" "#define VALUE 1\n")
file(WRITE "${_src}/first/main.c" "#include \"value.h\"\nextern int helper(void); volatile int value; void _start(void) { value = VALUE + helper(); }\n")
file(WRITE "${_src}/first/helper.c" "int helper(void) { return 2; }\n")
file(WRITE "${_src}/second/main.c" "volatile int value; void _start(void) { value = 3; }\n")
set(_first [=[
DEST := $(GENDIR)/$(CURDIR)/$(OBJ_SUFFIX)
USER_LDFLAGS := -nostdlib -no-pie
%build_prog mmake=one progname=First files="main helper" objdir="$(DEST)" targetdir=$(AROSDIR)/C usestartup=no
DEST := $(GENDIR)/wrong-later-directory
]=])
set(_second [=[
USER_LDFLAGS := -nostdlib -no-pie
%build_progs mmake=two files=main objdir=$(GENDIR)/$(CURDIR)/batch targetdir=$(AROSDIR)/C usestartup=no
]=])
file(WRITE "${_src}/first/mmakefile.src" "${_first}")
file(WRITE "${_src}/second/mmakefile.src" "${_second}")
set(_obj "${_build}/output/gen/first/initial")
set(_other "${_build}/output/gen/second/batch/main.o")
set(_output "${_build}/output/AROS/C/First")
function(run)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Command failed (${_result}): ${ARGN}\n${_out}${_err}")
  endif()
endfunction()
function(build)
  run("${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs -j 4)
endfunction()
function(noop)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 OR NOT _out MATCHES "no work to do" OR _out MATCHES "Re-running CMake")
    message(FATAL_ERROR "Expected unchanged graph and outputs: ${_out}${_err}")
  endif()
endfunction()
function(reject reason)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  string(REGEX REPLACE "[ \t\r\n]+" " " _message "${_out}${_err}")
  if(_result EQUAL 0 OR NOT _message MATCHES "${reason}")
    message(FATAL_ERROR "Expected ${reason}: ${_out}${_err}")
  endif()
endfunction()
run("${CMAKE_COMMAND}" -G Ninja -S "${_src}" -B "${_build}"
  "-DAROS_TEST_SOURCE=${_repo}" -DAROS_TEST_AUTO_PROGRAMS=ON)
build()
foreach(_path IN ITEMS "${_obj}/main.o" "${_obj}/main.d" "${_obj}/helper.o" "${_other}" "${_output}")
  if(NOT EXISTS "${_path}")
    message(FATAL_ERROR "Missing manifest-defined program output: ${_path}")
  endif()
endforeach()
include("${_build}/programs/aros-programs-one-native/program.cmake")
if(NOT MMAKE_PROGRAM_OBJDIR STREQUAL _obj OR EXISTS "${_build}/output/gen/wrong-later-directory")
  message(FATAL_ERROR "Object directory was not captured at the selected rule")
endif()
file(READ "${_obj}/main.d" _deps)
if(NOT _deps MATCHES "main[.]o:" OR NOT _deps MATCHES "value[.]h")
  message(FATAL_ERROR "Named depfile lost its object/header dependency: ${_deps}")
endif()
noop()
file(SHA256 "${_output}" _old)
file(TIMESTAMP "${_other}" _other_before "%s")
run("${CMAKE_COMMAND}" -E sleep 1)
file(WRITE "${_src}/first/value.h" "#define VALUE 42\n")
build()
file(SHA256 "${_output}" _new)
file(TIMESTAMP "${_other}" _other_after "%s")
if(_old STREQUAL _new OR NOT _other_before STREQUAL _other_after)
  message(FATAL_ERROR "Custom depfile did not isolate the header rebuild")
endif()
file(REMOVE "${_obj}/main.o" "${_output}")
build()
noop()
file(SHA256 "${_output}" _before_move)
file(WRITE "${_config}" "${_config_text}OBJ_SUFFIX := moved\n")
set(_obj "${_build}/output/gen/first/moved")
build()
if(NOT EXISTS "${_obj}/main.o" OR NOT EXISTS "${_obj}/helper.o")
  message(FATAL_ERROR "Configuration edit did not move program objects")
endif()
file(SHA256 "${_output}" _after_move)
if(NOT _before_move STREQUAL _after_move)
  message(FATAL_ERROR "Object-directory-only change altered the program binary")
endif()
noop()
string(REPLACE "$(GENDIR)/$(CURDIR)/$(OBJ_SUFFIX)" "$(OBJDIR)/nested" _nested "${_first}")
file(WRITE "${_src}/first/mmakefile.src" "${_nested}")
set(_obj "${_build}/programs/aros-programs-one-native/obj/nested")
build()
if(NOT EXISTS "${_obj}/main.o" OR EXISTS "${_obj}/nested/main.o")
  message(FATAL_ERROR "Per-program objdir incorrectly rebound global OBJDIR")
endif()
noop()

# The build-time guard must catch a directory swap without needing a manifest
# edit or CMake regeneration. Do not write any output through the new symlink.
file(MAKE_DIRECTORY "${_root}/outside")
file(RENAME "${_obj}" "${_obj}-saved")
file(CREATE_LINK "${_root}/outside" "${_obj}" SYMBOLIC)
reject("outside the native build tree")
if(EXISTS "${_root}/outside/main.o" OR EXISTS "${_root}/outside/main.d")
  message(FATAL_ERROR "Compiler wrote through an escaped object directory")
endif()
file(REMOVE "${_obj}")
file(RENAME "${_obj}-saved" "${_obj}")
build()
file(WRITE "${_root}/outside/sentinel" "untouched\n")
file(REMOVE "${_obj}/main.d" "${_obj}/main.o")
file(CREATE_LINK "${_root}/outside/sentinel" "${_obj}/main.d" SYMBOLIC)
reject("outside the native build tree")
file(READ "${_root}/outside/sentinel" _sentinel)
if(NOT _sentinel STREQUAL "untouched\n")
  message(FATAL_ERROR "Compiler overwrote an escaped depfile")
endif()
file(REMOVE "${_obj}/main.d")
build()

# Both declarations have main.c, so a shared object directory is a conflict,
# including when its second spelling is an internal symlink alias.
string(REPLACE "$(GENDIR)/$(CURDIR)/batch" "${_obj}" _collision "${_second}")
file(WRITE "${_src}/second/mmakefile.src" "${_collision}")
reject("Duplicate program producer")
file(CREATE_LINK "${_obj}" "${_build}/alias" SYMBOLIC)
string(REPLACE "$(GENDIR)/$(CURDIR)/batch" "${_build}/alias" _collision "${_second}")
file(WRITE "${_src}/second/mmakefile.src" "${_collision}")
reject("Duplicate program producer")
file(WRITE "${_src}/second/mmakefile.src" "${_second}")
foreach(_invalid IN ITEMS "" relative "$(GENDIR)/../escape" "$(GENDIR)/two paths" "@unconfigured@" "$(unsupported call)")
  string(REPLACE "objdir=\"$(DEST)\"" "objdir=\"${_invalid}\"" _bad "${_first}")
  file(WRITE "${_src}/first/mmakefile.src" "${_bad}")
  reject("objdir requires a normalized absolute path")
endforeach()
foreach(_invalid IN ITEMS "${_src}/first" "${_src}/config-snapshot/objects" "${_root}/outside" "${_build}/alias-outside")
  if(_invalid STREQUAL "${_build}/alias-outside")
    file(CREATE_LINK "${_root}/outside" "${_invalid}" SYMBOLIC)
  endif()
  string(REPLACE "objdir=\"$(DEST)\"" "objdir=\"${_invalid}\"" _bad "${_first}")
  file(WRITE "${_src}/first/mmakefile.src" "${_bad}")
  reject("outside the native build tree")
endforeach()
file(WRITE "${_build}/not-a-directory" "not a directory\n")
string(REPLACE "objdir=\"$(DEST)\"" "objdir=${_build}/not-a-directory" _bad "${_first}")
file(WRITE "${_src}/first/mmakefile.src" "${_bad}")
reject("Program objdir is not a directory")
file(CREATE_LINK "${_build}/missing-directory" "${_build}/dangling" SYMBOLIC)
string(REPLACE "objdir=\"$(DEST)\"" "objdir=${_build}/dangling" _bad "${_first}")
file(WRITE "${_src}/first/mmakefile.src" "${_bad}")
reject("dangling symlink")

# An embedded reference tree is inside the native build but still not a valid
# output location, even through a symlink with a native-looking spelling.
file(COPY "${_src}/config-snapshot/" DESTINATION "${_build}/reference")
file(READ "${_src}/CMakeLists.txt" _project)
string(REPLACE "\${CMAKE_SOURCE_DIR}/config-snapshot" "\${CMAKE_BINARY_DIR}/reference" _embedded "${_project}")
file(WRITE "${_src}/CMakeLists.txt" "${_embedded}")
file(CREATE_LINK "${_build}/reference" "${_build}/reference-alias" SYMBOLIC)
foreach(_invalid IN ITEMS "${_build}/reference/objects" "${_build}/reference-alias/objects")
  string(REPLACE "objdir=\"$(DEST)\"" "objdir=${_invalid}" _bad "${_first}")
  file(WRITE "${_src}/first/mmakefile.src" "${_bad}")
  reject("cannot use the legacy build tree")
endforeach()
file(WRITE "${_src}/CMakeLists.txt" "${_project}")
file(WRITE "${_src}/first/mmakefile.src" "${_nested}")
build()
noop()
message(STATUS "Program object directories, named depfiles, isolation, path safety and no-op checks passed")
