cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass an isolated TEST_BINARY_DIR")
endif()
get_filename_component(_cmake_dir "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef _id)
set(_root "${TEST_BINARY_DIR}/${_id}")
set(_src "${_root}/source")
set(_build "${_root}/build")
file(MAKE_DIRECTORY "${_src}/data/first" "${_src}/data/second" "${_src}/data/first/subdir")
configure_file("${CMAKE_CURRENT_LIST_DIR}/static-files/CMakeLists.txt" "${_src}/CMakeLists.txt" COPYONLY)
set(_helper [=[WILDCARD = $(shell cd $(SRCDIR)/$(CURDIR); for file in $(1); do if [ -f $$file ]; then printf "%s" "$$file "; fi; done)
]=])
set(_rules [=[
GROUPS := first second
f := must-not-leak
FILES := $(foreach f, $(GROUPS), $(foreach s, $(filter-out $(f)/skip, $(call WILDCARD, $(f)/*)), $(AROSDIR)/Fonts/$(s)))
#MM
example: $(strip $(FILES)) $(AROSDIR)/state-$(f)
$(AROSDIR)/Fonts/% : %
	@$(CP) $< $@
$(AROSDIR)/state-must-not-leak : state
	@$(CP) $^ $@
# Unreachable unsupported patterns must not be executed or rejected.
$(AROSDIR)/Other/% : generated/%
	@unexpected $< $@
]=])
set(_recipe "${_helper}${_rules}")
file(WRITE "${_src}/data/mmakefile.src" "${_recipe}")
file(WRITE "${_src}/data/state" "foreach variable restored\n")
file(WRITE "${_src}/data/first/one" "one\n")
file(WRITE "${_src}/data/first/skip" "excluded by filter-out\n")
file(WRITE "${_src}/data/second/two" "two\n")
function(run)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Command failed (${_result}): ${ARGN}\n${_out}${_err}")
  endif()
endfunction()
function(build)
  run("${CMAKE_COMMAND}" --build "${_build}" --target static-files -j 6)
endfunction()
function(noop)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target static-files
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 OR NOT _out MATCHES "no work to do" OR _out MATCHES "Re-running CMake")
    message(FATAL_ERROR "Expected no-op without regeneration: ${_out}${_err}")
  endif()
endfunction()
function(compare name)
  run("${CMAKE_COMMAND}" -E compare_files "${_src}/data/${name}" "${_build}/runtime/Fonts/${name}")
endfunction()
function(reject recipe diagnostic)
  file(WRITE "${_src}/data/mmakefile.src" "${recipe}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${_src}" -B "${_build}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "${diagnostic}")
    message(FATAL_ERROR "Expected ${diagnostic}, got (${_result}): ${_out}${_err}")
  endif()
endfunction()
run("${CMAKE_COMMAND}" -G Ninja -S "${_src}" -B "${_build}"
  "-DAROS_CMAKE_DIR=${_cmake_dir}" -DAROS_STATIC_LOCAL=ON)
build()
compare(first/one)
compare(second/two)
if(EXISTS "${_build}/runtime/Fonts/first/skip" OR EXISTS "${_build}/runtime/Fonts/first/subdir")
  message(FATAL_ERROR "WILDCARD/filter-out must select only requested regular files")
endif()
noop()
file(WRITE "${_src}/data/first/.hidden" "not inventoried\n")
noop()
run("${CMAKE_COMMAND}" -E sleep 1)
file(APPEND "${_src}/data/first/one" "edited\n")
build()
compare(first/one)
file(WRITE "${_src}/data/second/new" "upstream addition\n")
build()
compare(second/new)
file(REMOVE "${_build}/runtime/Fonts/first/one")
build()
compare(first/one)
file(REMOVE "${_src}/data/second/new")
build()
# CP does not prune old destinations; removed inputs must lose their producer.
file(REMOVE "${_build}/runtime/Fonts/second/new")
noop()
file(MAKE_DIRECTORY "${_src}/data/third")
file(WRITE "${_src}/data/third/three" "new group\n")
string(REPLACE "first second" "first second third" _more "${_recipe}")
file(WRITE "${_src}/data/mmakefile.src" "${_more}")
build()
compare(third/three)
noop()
reject("${_recipe}\n$(AROSDIR)/Fonts/first/% : first/%\n\t@$(CP) $< $@\n" "Ambiguous static pattern")
reject("${_recipe}\n$(AROSDIR)/Fonts/first/one : first/one\n" "relying on an implicit recipe")
string(REPLACE "@$(CP) $< $@" "@$(CP) -r $< $@" _bad "${_recipe}")
reject("${_bad}" "Unsupported static copy pattern")
string(REPLACE "Fonts/% : %" "Fonts/% : % state" _bad "${_recipe}")
reject("${_bad}" "Unsupported static copy pattern")
reject("${_recipe}\nfirst/% : generated/%\n\t@echo generated\n" "cannot adopt a generated prerequisite")
reject("${_recipe}\nfirst/one :\n\t@echo generated\n" "cannot adopt a generated prerequisite")
string(REPLACE "Fonts/% : %" "Fonts/% : missing/%" _bad "${_recipe}")
reject("${_bad}" "requires an existing source file")
string(REPLACE "$(AROSDIR)/Fonts/% : %\n\t@$(CP) $< $@" "" _bad "${_recipe}")
reject("${_bad}" "without a native producer")
file(WRITE "${_root}/unowned" "outside source tree\n")
file(CREATE_LINK "${_root}/unowned" "${_src}/data/first/escape" SYMBOLIC)
reject("${_recipe}" "requires an owned source")
file(REMOVE "${_src}/data/first/escape")
file(MAKE_DIRECTORY "${_build}/runtime/Fonts/first")
file(REMOVE "${_build}/runtime/Fonts/first/one")
file(CREATE_LINK "${_root}/unowned" "${_build}/runtime/Fonts/first/one" SYMBOLIC)
reject("${_recipe}" "escapes the native runtime tree")
file(REMOVE "${_build}/runtime/Fonts/first/one")
string(REPLACE "first second" "../.." _bad "${_recipe}")
reject("${_bad}" "requires a source-relative pattern")
string(REPLACE "[ -f $$file ]" "[ -e $$file ]" _bad "${_recipe}")
reject("${_bad}" "Unsupported static WILDCARD definition")
reject("${_rules}" "Unsupported static WILDCARD definition")
file(WRITE "${_src}/data/first/space name" "cannot be a Make word\n")
reject("${_recipe}" "Unsupported static WILDCARD source")
file(REMOVE "${_src}/data/first/space name")
file(MAKE_DIRECTORY "${_src}/data/prebuilt")
file(WRITE "${_src}/data/prebuilt/stale" "generated source cache\n")
file(READ "${_src}/CMakeLists.txt" _fixture)
file(WRITE "${_src}/CMakeLists.txt" "set(AROS_LEGACY_BUILD_DIR \"${_src}/data/prebuilt\")\n${_fixture}")
string(REPLACE "first second" "prebuilt" _bad "${_recipe}")
reject("${_bad}" "requires an owned source")
file(WRITE "${_src}/CMakeLists.txt" "${_fixture}")

# Use the real, unchanged font manifest and data, selecting only its exported
# local quick rule. The global font aggregate also includes unmigrated ports.
file(REMOVE "${_src}/data/mmakefile.src")
file(COPY "${_cmake_dir}/../workbench/fonts/" DESTINATION "${_src}/data")
file(READ "${_src}/data/mmakefile" _fonts)
string(REPLACE "workbench-fonts-quick" "example" _fonts "${_fonts}")
file(WRITE "${_src}/data/mmakefile" "${_fonts}")
file(MAKE_DIRECTORY "${_root}/config/config")
file(WRITE "${_root}/config/config/make.cfg" "${_helper}")
run("${CMAKE_COMMAND}" -S "${_src}" -B "${_build}" "-DAROS_LEGACY_BUILD_DIR=${_root}/config")
build()
file(GLOB _outputs "${_build}/runtime/Fonts/*/*")
set(_count 0)
foreach(_output IN LISTS _outputs)
  file(RELATIVE_PATH _relative "${_build}/runtime/Fonts" "${_output}")
  if(_relative MATCHES "^(first|second|third)/")
    continue()
  endif()
  compare("${_relative}")
  math(EXPR _count "${_count} + 1")
endforeach()
if(_count EQUAL 0)
  message(FATAL_ERROR "Real font manifest selected no files")
endif()
noop()
string(REPLACE "[ -f $$file ]" "[ -e $$file ]" _bad "${_helper}")
file(WRITE "${_root}/config/config/make.cfg" "${_bad}")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target static-files
  RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "Unsupported static WILDCARD definition")
  message(FATAL_ERROR "Helper configuration edit did not invalidate the graph: ${_out}${_err}")
endif()
file(WRITE "${_root}/config/config/make.cfg" "${_helper}")
build()
noop()
message(STATUS "Static WILDCARD/pattern ownership, rebuild and real font manifest checks passed (${_count} font files)")
