cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass TEST_BINARY_DIR")
endif()
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
string(RANDOM LENGTH 10 ALPHABET abcdef0123456789 _id)
set(_src "${TEST_BINARY_DIR}/${_id}/src")
set(_build "${TEST_BINARY_DIR}/${_id}/build")
file(MAKE_DIRECTORY "${_src}/commands" "${_src}/upstream/pkg" "${_src}/archives"
  "${_src}/include" "${_src}/config" "${_src}/config-snapshot/bin/linux-x86_64/gen/config")
configure_file("${CMAKE_CURRENT_LIST_DIR}/programs/CMakeLists.txt" "${_src}/CMakeLists.txt" COPYONLY)
file(WRITE "${_src}/config/aros.cfg" "")
file(WRITE "${_src}/config-snapshot/bin/linux-x86_64/gen/config/target.cfg" [=[
FAMILY := unix
CPPFLAGS = $(USER_CPPFLAGS)
CFLAGS = $(USER_CFLAGS)
LDFLAGS = $(USER_LDFLAGS)
NOSTARTUP_LDFLAGS := -nostartfiles
]=])
file(WRITE "${_src}/support.c" "int support(void) { return 0; }\n")
file(WRITE "${_src}/extra.h" "#define EXTRA_VALUE 5\n")
file(READ "${_repo}/config/make.tmpl" _template)
file(WRITE "${_src}/config/make.tmpl" "${_template}")
set(_source [=[
#include "value.h"
int _start(void) { return VALUE; }
]=])
file(WRITE "${_src}/upstream/pkg/Main.c" "${_source}")
file(WRITE "${_src}/upstream/pkg/value.h" "#define VALUE 1\n")
set(_patch [=[
--- a/value.h
+++ b/value.h
@@ -1 +1 @@
-#define VALUE 1
+#define VALUE 7
]=])
file(WRITE "${_src}/commands/fix.diff" "${_patch}")
set(_manifest [=[
FETCH := fixture-fetch
FETCHDIR := $(TARGETDIR)/Ports/example
ARCHSRCDIR := $(FETCHDIR)/pkg
%fetch mmake=$(FETCH) archive=package suffixes="tar.gz" location=$(SRCDIR)/archives archive_origins=$(SRCDIR)/archives destination=$(FETCHDIR) patches_specs="fix.diff:pkg:-f,-p1"
%fetch mmake=unrelated-fetch destination=unsupported destination=unsupported
#MM fixture-commands: $(FETCH)
%build_prog mmake=fixture-commands progname=Main files=$(ARCHSRCDIR)/Main usestartup=no ldflags="-nostdlib -no-pie" targetdir=$(AROSDIR)/C
]=])
file(WRITE "${_src}/commands/mmakefile.src" "${_manifest}")
set(_output "${_build}/output/AROS/C/Main")
set(_extracted "${_build}/output/Ports/example/pkg")
function(run)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Command failed (${_result}): ${ARGN}\n${_out}${_err}")
  endif()
endfunction()
function(pack)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cfz "${_src}/archives/package.tar.gz" pkg
    WORKING_DIRECTORY "${_src}/upstream" COMMAND_ERROR_IS_FATAL ANY)
endfunction()
function(build)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs -j 4
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 AND NOT "${_out}${_err}" MATCHES "native sources prepared; run the build again")
    message(FATAL_ERROR "Fetch/program build failed: ${_out}${_err}")
  endif()
  if(NOT _result EQUAL 0)
    run("${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs -j 4)
  endif()
endfunction()
function(noop)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 OR NOT _out MATCHES "no work to do" OR _out MATCHES "Re-running CMake")
    message(FATAL_ERROR "Expected no-op without regeneration: ${_out}${_err}")
  endif()
endfunction()
function(rejected reason)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  string(REGEX REPLACE "[ \t\r\n]+" " " _diagnostic "${_out}${_err}")
  if(_result EQUAL 0 OR NOT _diagnostic MATCHES "${reason}")
    message(FATAL_ERROR "Expected rejection (${reason}): ${_out}${_err}")
  endif()
endfunction()
pack()
run("${CMAKE_COMMAND}" -G Ninja -S "${_src}" -B "${_build}" "-DAROS_TEST_SOURCE=${_repo}"
  "-DAROS_TEST_INCLUDE_DIR=${_build}/include")
if(EXISTS "${_extracted}/Main.c")
  message(FATAL_ERROR "Fetch ran during configuration")
endif()
build()
if(NOT EXISTS "${_output}")
  message(FATAL_ERROR "Preparation/reconfiguration did not compile the program")
endif()
file(READ "${_extracted}/value.h" _header)
if(NOT _header STREQUAL "#define VALUE 7\n")
  message(FATAL_ERROR "Manifest patch was not applied: ${_header}")
endif()
noop()
foreach(_change IN ITEMS patch archive missing-source missing-header missing-recipe missing-tree)
  file(TIMESTAMP "${_output}" _before "%s")
  run("${CMAKE_COMMAND}" -E sleep 1)
  if(_change STREQUAL patch)
    string(REPLACE "VALUE 7" "VALUE 8" _edited "${_patch}")
    file(WRITE "${_src}/commands/fix.diff" "${_edited}")
  elseif(_change STREQUAL archive)
    file(APPEND "${_src}/upstream/pkg/Main.c" "#include <proto/extra.h>\nint extra = EXTRA_VALUE;\n")
    pack()
  elseif(_change STREQUAL missing-source)
    file(REMOVE "${_extracted}/Main.c")
  elseif(_change STREQUAL missing-header)
    file(REMOVE "${_extracted}/value.h")
  elseif(_change STREQUAL missing-recipe)
    file(REMOVE "${_build}/output/Ports/example/.aros-fetch-recipe")
  else()
    file(REMOVE_RECURSE "${_build}/output/Ports/example")
  endif()
  build()
  file(TIMESTAMP "${_output}" _after "%s")
  if(_before STREQUAL _after)
    message(FATAL_ERROR "Fetch/program ${_change} did not rebuild")
  endif()
  noop()
endforeach()
if(NOT EXISTS "${_build}/include/proto/extra.h")
  message(FATAL_ERROR "New fetched includes did not select their native header producer")
endif()
file(APPEND "${_extracted}/Main.c" "int local_edit = 21;\n")
rejected("Native fetched source changed")
file(REMOVE "${_extracted}/Main.c")
build()
file(WRITE "${_src}/commands/fix.diff" "${_patch}")
string(REPLACE "destination=$(FETCHDIR)" "destination=$(FETCHDIR) unknown=yes" _bad "${_manifest}")
file(WRITE "${_src}/commands/mmakefile.src" "${_bad}")
rejected("Unsupported fetch argument")
file(WRITE "${_src}/commands/mmakefile.src" "${_manifest}")
build()
string(REPLACE "-f,-p1" "--directory=/tmp" _bad "${_manifest}")
file(WRITE "${_src}/commands/mmakefile.src" "${_bad}")
rejected("Unsupported native patch option")
file(WRITE "${_src}/commands/mmakefile.src" "${_manifest}")
build()
file(WRITE "${_src}/commands/fix.diff" "--- ../escape\n+++ ../escape\n@@ -1 +1 @@\n-a\n+b\n")
rejected("Unsafe archive/patch path")
file(WRITE "${_src}/commands/fix.diff" "${_patch}")
build()
file(APPEND "${_src}/commands/mmakefile.src" "\n#MM fixture-fetch: unsupported\nunsupported:\n\t@echo forbidden\n")
rejected("Unsupported static prerequisite recipe")
file(WRITE "${_src}/commands/mmakefile.src" "${_manifest}")
build()
file(MAKE_DIRECTORY "${_src}/new-layer")
file(WRITE "${_src}/new-layer/mmakefile.src" "#MM fixture-fetch: unsupported-global\n")
rejected("Unhandled fetch prerequisites")
file(REMOVE "${_src}/new-layer/mmakefile.src")
build()
string(REGEX REPLACE "%fetch[^\n]*\n" "" _bad "${_manifest}")
file(WRITE "${_src}/commands/mmakefile.src" "${_bad}")
rejected("generated/external source needs a native producer")
file(WRITE "${_src}/commands/mmakefile.src" "${_manifest}")
build()
noop()
file(REMOVE "${_build}/output/Ports/example/.aros-fetch-owner")
rejected("unowned fetch destination")
file(REMOVE_RECURSE "${_build}/output/Ports/example")
build()
noop()
find_package(Python3 3.8 REQUIRED COMPONENTS Interpreter)
run("${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_LIST_DIR}/mmake_fetch_safety.py")

# An upstream alias may carry preparation without being a direct %fetch edge.
string(REPLACE "fixture-commands: $(FETCH)" "fixture-commands: source-alias" _indirect "${_manifest}")
string(APPEND _indirect "\n#MM source-alias: source-next\n")
file(WRITE "${_src}/commands/mmakefile.src" "${_indirect}")
rejected("generated/external source needs a native producer")
file(MAKE_DIRECTORY "${_src}/fetch-edges")
set(_edges "#MM source-alias: source-next\n#MM source-next: fixture-fetch\n")
file(WRITE "${_src}/fetch-edges/mmakefile.src" "${_edges}")
build()
noop()
file(REMOVE_RECURSE "${_build}/output/Ports/example")
build()
noop()
file(APPEND "${_src}/fetch-edges/mmakefile.src" "#MM source-next: source-alias\n")
rejected("dependency cycle")
file(WRITE "${_src}/fetch-edges/mmakefile.src" "${_edges}")
build()
file(APPEND "${_src}/fetch-edges/mmakefile.src" "#MM\nsource-next:\n\t@echo unsupported\n")
rejected("Unsupported static prerequisite recipe")
file(WRITE "${_src}/fetch-edges/mmakefile.src" "${_edges}")
build()

# Fetch traversal must not expand header lists until the initial sources exist.
file(APPEND "${_src}/config-snapshot/bin/linux-x86_64/gen/config/target.cfg"
  "GENINCDIR := $(GENDIR)/include\nAROS_DIR_INCLUDE := include\n")
file(APPEND "${_src}/fetch-edges/mmakefile.src" [=[
#MM source-headers: source-alias
%copy_includes mmake=source-headers includes=value.h dir=$(TARGETDIR)/Ports/example/pkg path=fetched
]=])
string(REPLACE "fixture-commands: source-alias" "fixture-commands: source-headers source-alias"
  _headers "${_indirect}")
file(WRITE "${_src}/commands/mmakefile.src" "${_headers}")
file(REMOVE_RECURSE "${_build}/output/Ports/example")
build()
run("${CMAKE_COMMAND}" -E compare_files "${_extracted}/value.h" "${_build}/include/fetched/value.h")
noop()
string(REPLACE "source-headers source-alias" "source-headers" _headers "${_headers}")
file(WRITE "${_src}/commands/mmakefile.src" "${_headers}")
build()
noop()
file(TIMESTAMP "${_output}" _before "%s")
run("${CMAKE_COMMAND}" -E sleep 1)
string(REPLACE "VALUE 7" "VALUE 11" _edited "${_patch}")
file(WRITE "${_src}/commands/fix.diff" "${_edited}")
build()
file(TIMESTAMP "${_output}" _after "%s")
if(_before STREQUAL _after)
  message(FATAL_ERROR "Indirect fetch edit did not rebuild the program")
endif()
run("${CMAKE_COMMAND}" -E compare_files "${_extracted}/value.h" "${_build}/include/fetched/value.h")
noop()

# Distinct receipts from an augmented alias must authorize all program units.
file(MAKE_DIRECTORY "${_src}/upstream/aux")
file(WRITE "${_src}/upstream/aux/extra.c" "int auxiliary_value(void) { return 3; }\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cfz "${_src}/archives/aux.tar.gz" aux
  WORKING_DIRECTORY "${_src}/upstream" COMMAND_ERROR_IS_FATAL ANY)
file(MAKE_DIRECTORY "${_src}/fetch-more")
file(WRITE "${_src}/fetch-more/mmakefile.src" [=[
#MM source-alias: auxiliary-fetch
%fetch mmake=auxiliary-fetch archive=aux suffixes=tar.gz location=$(SRCDIR)/archives destination=$(TARGETDIR)/Ports/aux
]=])
string(REPLACE "files=$(ARCHSRCDIR)/Main" "files=\"$(ARCHSRCDIR)/Main $(TARGETDIR)/Ports/aux/aux/extra\""
  _multiple "${_headers}")
file(WRITE "${_src}/commands/mmakefile.src" "${_multiple}")
build()
noop()
file(SHA256 "${_output}" _before)
run("${CMAKE_COMMAND}" -E sleep 1)
file(WRITE "${_src}/upstream/aux/extra.c" "int auxiliary_value(void) { return 17; }\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cfz "${_src}/archives/aux.tar.gz" aux
  WORKING_DIRECTORY "${_src}/upstream" COMMAND_ERROR_IS_FATAL ANY)
build()
file(SHA256 "${_output}" _after)
if(_before STREQUAL _after)
  message(FATAL_ERROR "Second indirect archive edit did not rebuild the program")
endif()
noop()
file(REMOVE "${_src}/fetch-edges/mmakefile.src")
rejected("generated/external source needs a native producer")
file(REMOVE "${_src}/fetch-more/mmakefile.src")

# A prerequisite executable must not grant its private source receipt to its
# consumer. Its real build dependencies remain the full registry's concern.
file(WRITE "${_src}/fetch-edges/helper.c" "int _start(void) { return 0; }\n")
file(WRITE "${_src}/fetch-edges/mmakefile.src" [=[
#MM source-headers: helper-program
#MM helper-program: fixture-fetch
%build_prog mmake=helper-program progname=Helper files=helper usestartup=no ldflags="-nostdlib -no-pie" targetdir=$(AROSDIR)/C
]=])
rejected("generated/external source needs a native producer")
file(REMOVE "${_src}/fetch-edges/mmakefile.src")
file(WRITE "${_src}/commands/mmakefile.src" "${_manifest}")
build()
noop()
execute_process(COMMAND "${CMAKE_COMMAND}" "-DTEST_BINARY_DIR=${TEST_BINARY_DIR}/format"
  -P "${CMAKE_CURRENT_LIST_DIR}/mmake_fetch_format.cmake" COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "Native fetch/patch preparation, generated-source programs, rebuilds and no-op checks passed")
