cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass TEST_BINARY_DIR")
endif()
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
string(RANDOM LENGTH 10 ALPHABET abcdef0123456789 _id)
set(_src "${TEST_BINARY_DIR}/${_id}/src")
set(_build "${TEST_BINARY_DIR}/${_id}/build")
file(MAKE_DIRECTORY "${_src}/commands" "${_src}/runtime" "${_src}/include"
  "${_src}/config-snapshot/bin/linux-x86_64/gen/config")
configure_file("${CMAKE_CURRENT_LIST_DIR}/programs/CMakeLists.txt" "${_src}/CMakeLists.txt" COPYONLY)
set(_config "${_src}/config-snapshot/bin/linux-x86_64/gen/config/target.cfg")
set(_config_text [=[
FAMILY := unix
CPPFLAGS = $(USER_CPPFLAGS)
CFLAGS = $(USER_CFLAGS)
LDFLAGS = $(USER_LDFLAGS)
TARGET_ISA_LDFLAGS := -Wl,--defsym=LINK_ORDER=1
NIX_LDFLAGS := -pthread -Wl,--defsym=LINK_ORDER=2
NOSTARTUP_LDFLAGS := -nostartfiles -Wl,--defsym=LINK_ORDER=3
DETACH_LDFLAGS := -Wl,--defsym=LINK_ORDER=4
]=])
file(WRITE "${_config}" "${_config_text}")
file(WRITE "${_src}/support.c" "int support(void) { return 0; }\n")
file(WRITE "${_src}/extra.h" "#define EXTRA_VALUE 1\n")
foreach(_name IN ITEMS First Second)
  file(WRITE "${_src}/commands/${_name}.c" [=[
#ifdef _REENTRANT
#error nix link options leaked into compilation
#endif
int main(void) { return 0; }
]=])
endforeach()
file(WRITE "${_src}/runtime/entry.c" "extern int main(void); volatile int result; void _start(void) { result = main(); }\n")
file(WRITE "${_src}/runtime/unixentry.h" "#define UNIX_VALUE 3\n")
set(_unix_source "#include \"unixentry.h\"\n#if UNIX_MODE != 700\n#error wrong startup compile rule\n#endif\nextern int support(void); int unix_marker(void) { return UNIX_VALUE + support(); }\n")
file(WRITE "${_src}/runtime/unixentry.c" "${_unix_source}")
set(_runtime_manifest [=[
FILES := entry unixentry
runtime-objects: $(addprefix $(AROS_LIB)/,$(addsuffix .o,$(FILES)))
runtime-objects: $(GENDIR)/$(CURDIR)/unix/unixentry.o
$(AROS_LIB)/%.o: $(GENDIR)/$(CURDIR)/%.o
	@$(CP) $< $@
%rule_compile basename=% targetdir=$(GENDIR)/$(CURDIR)
$(AROS_LIB)/%.o: $(GENDIR)/$(CURDIR)/unix/%.o
	@$(CP) $< $@
USER_CPPFLAGS += -DUNIX_MODE=700
%rule_compile basename=% targetdir=$(GENDIR)/$(CURDIR)/unix
USER_CPPFLAGS += -DUNIX_MODE=900
]=])
file(WRITE "${_src}/runtime/mmakefile.src" "${_runtime_manifest}")
# Use a host-supported flag and non-AROS object name to require configuration
# and specs discovery, rather than hard-coded -nix/nixmain.o behavior.
set(_specs "${_src}/compiler.specs")
set(_specs_text "*lib:\n%{pthread:-lfixture}\n\n*libgcc:\n-lgcc\n\n*link_gcc_c_sequence:\n%G %L %G\n\n*startfile:\nentry.o%s %{pthread:unixentry.o%s}\n\n*endfile:\n\n\n")
file(WRITE "${_specs}" "${_specs_text}")
set(_flags "ldflags=\"-specs=${_specs} -no-pie -Wl,-e,main\" targetdir=\$(AROSDIR)/C")
set(_single "%build_prog mmake=fixture-commands progname=First ${_flags}")
set(_batch "%build_progs mmake=fixture-commands files=First Second ${_flags}")
set(_manifest "${_src}/commands/mmakefile.src")
set(_output "${_build}/output/AROS/C/First")
set(_object "${_build}/output/AROS/Development/lib/unixentry.o")
set(_archive "${_build}/output/AROS/Development/lib/libfixture.a")
find_program(_nm NAMES nm REQUIRED)
function(run)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Command failed (${_result}): ${ARGN}\n${_out}${_err}")
  endif()
endfunction()
function(build)
  run("${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs -j 2)
endfunction()
function(noop)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 OR NOT _out MATCHES "no work to do" OR _out MATCHES "Re-running CMake")
    message(FATAL_ERROR "Expected no-op without regeneration: ${_out}${_err}")
  endif()
endfunction()
function(marker output expected)
  execute_process(COMMAND "${_nm}" --defined-only "${output}" RESULT_VARIABLE _result
    OUTPUT_VARIABLE _symbols ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Cannot inspect ${output}: ${_err}")
  endif()
  foreach(_symbol IN ITEMS unix_marker support)
    if((expected AND NOT _symbols MATCHES " ${_symbol}\n") OR
       (NOT expected AND _symbols MATCHES " ${_symbol}\n"))
      message(FATAL_ERROR "Wrong nix input selection for ${output}: ${_symbols}")
    endif()
  endforeach()
endfunction()
function(rejected reason)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  string(REGEX REPLACE "[ \t\r\n]+" " " _diagnostic "${_out}${_err}")
  if(_result EQUAL 0 OR NOT _diagnostic MATCHES "${reason}")
    message(FATAL_ERROR "Expected rejection (${reason}): ${_out}${_err}")
  endif()
endfunction()
file(WRITE "${_manifest}" "${_single} nix=yes\n%build_prog mmake=unselected progname=Unused nix=no\n")
run("${CMAKE_COMMAND}" -G Ninja -S "${_src}" -B "${_build}" "-DAROS_TEST_SOURCE=${_repo}")
build()
marker("${_output}" TRUE)
noop()
string(REPLACE "runtime-objects: $(GENDIR)/$(CURDIR)/unix/unixentry.o\n" ""
  _undeclared_intermediate "${_runtime_manifest}")
file(WRITE "${_src}/runtime/mmakefile.src" "${_undeclared_intermediate}")
rejected("wrong startup compile rule")
file(WRITE "${_src}/runtime/mmakefile.src" "${_runtime_manifest}")
build()
# The earlier generic pattern can see unix/unixentry.c too. The more
# specific compile rule must still win, including its captured flags.
file(MAKE_DIRECTORY "${_src}/runtime/unix")
file(WRITE "${_src}/runtime/unix/unixentry.c" "#error generic compile rule selected\n")
file(WRITE "${_src}/runtime/unixentry.h" "#define UNIX_VALUE 4\n")
build()
marker("${_output}" TRUE)
noop()
file(REMOVE "${_src}/runtime/unix/unixentry.c")
foreach(_change IN ITEMS source header missing-object archive-source missing-archive config)
  file(TIMESTAMP "${_output}" _before "%s")
  file(TIMESTAMP "${_build}/programs/fixture-programs/obj/0.o" _compile_before "%s")
  run("${CMAKE_COMMAND}" -E sleep 1)
  if(_change STREQUAL source)
    file(APPEND "${_src}/runtime/unixentry.c" "int unix_extra = 12;\n")
  elseif(_change STREQUAL header)
    file(WRITE "${_src}/runtime/unixentry.h" "#define UNIX_VALUE 5\n")
  elseif(_change STREQUAL missing-object)
    file(REMOVE "${_object}")
  elseif(_change STREQUAL archive-source)
    file(WRITE "${_src}/support.c" "int support(void) { return 7; }\n")
  elseif(_change STREQUAL missing-archive)
    file(REMOVE "${_archive}")
  else()
    string(REPLACE "-pthread" "-pthread -Wl,--defsym=NIX_CONFIG_EDIT=1" _edited_config "${_config_text}")
    file(WRITE "${_config}" "${_edited_config}")
  endif()
  build()
  file(TIMESTAMP "${_output}" _after "%s")
  file(TIMESTAMP "${_build}/programs/fixture-programs/obj/0.o" _compile_after "%s")
  if(_before STREQUAL _after)
    message(FATAL_ERROR "Nix ${_change} did not relink the program")
  endif()
  if(NOT _change STREQUAL config AND NOT _compile_before STREQUAL _compile_after)
    message(FATAL_ERROR "Nix ${_change} must rebuild/relink without recompiling the program")
  endif()
  marker("${_output}" TRUE)
  noop()
endforeach()
include("${_build}/programs/fixture-programs/program.cmake")
if(NOT "-Wl,--defsym=NIX_CONFIG_EDIT=1" IN_LIST MMAKE_PROGRAM_LINK_OPTIONS)
  message(FATAL_ERROR "Nix configuration edit did not refresh metadata")
endif()
file(WRITE "${_config}" "${_config_text}")
foreach(_kind IN ITEMS single batch)
  file(WRITE "${_manifest}" "${_${_kind}} nix=yes\n")
  build()
  marker("${_output}" TRUE)
  if(_kind STREQUAL batch)
    marker("${_build}/output/AROS/C/Second" TRUE)
  endif()
  noop()
  file(WRITE "${_manifest}" "${_${_kind}} nix=yes usestartup=no detach=yes\n")
  build()
  marker("${_output}" FALSE)
  include("${_build}/programs/fixture-programs/program.cmake")
  set(_expected "-Wl,--defsym=LINK_ORDER=1;-pthread;-Wl,--defsym=LINK_ORDER=2;-nostartfiles;-Wl,--defsym=LINK_ORDER=3;-Wl,--defsym=LINK_ORDER=4")
  if(NOT MMAKE_PROGRAM_LINK_OPTIONS STREQUAL _expected)
    message(FATAL_ERROR "Incorrect upstream link-option ordering: ${MMAKE_PROGRAM_LINK_OPTIONS}")
  endif()
  noop()
  foreach(_option IN ITEMS "nix=no" "")
    file(WRITE "${_manifest}" "${_${_kind}} ${_option}\n")
    build()
    marker("${_output}" FALSE)
    noop()
  endforeach()
endforeach()
foreach(_invalid IN ITEMS maybe 0 "")
  file(WRITE "${_manifest}" "${_single} nix=${_invalid}\n")
  rejected("Invalid nix")
endforeach()
file(WRITE "${_manifest}" "${_single} nix=yes\n")
string(REGEX REPLACE "NIX_LDFLAGS := [^\n]*" "NIX_LDFLAGS :=" _empty_config "${_config_text}")
file(WRITE "${_config}" "${_empty_config}")
rejected("Missing NIX_LDFLAGS")
file(WRITE "${_manifest}" "${_single} nix=no\n")
build()
marker("${_output}" FALSE)
noop()
file(WRITE "${_manifest}" "${_single} nix=yes\n")
file(WRITE "${_config}" "${_config_text}")
build()
file(REMOVE "${_src}/runtime/unixentry.c")
rejected("No supported native compile rule")
file(WRITE "${_src}/runtime/unixentry.c" "${_unix_source}")
build()
string(REPLACE "FILES := entry unixentry" "FILES := entry" _removed "${_runtime_manifest}")
file(WRITE "${_src}/runtime/mmakefile.src" "${_removed}")
rejected("Expected one native SDK object producer")
file(WRITE "${_src}/runtime/mmakefile.src" "${_runtime_manifest}")
string(REPLACE "-lfixture" "-lunowned" _unowned_specs "${_specs_text}")
file(WRITE "${_specs}" "${_unowned_specs}")
rejected("needs a native archive producer for unowned")
file(WRITE "${_specs}" "${_specs_text}")
build()
marker("${_output}" TRUE)
noop()
message(STATUS "Nix single/batch programs, link-only options, specs-selected native inputs, rebuilds and rejection checks passed")
