cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass TEST_BINARY_DIR")
endif()
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
string(RANDOM LENGTH 10 ALPHABET abcdef0123456789 _id)
set(_src "${TEST_BINARY_DIR}/${_id}/src")
set(_build "${TEST_BINARY_DIR}/${_id}/build")
file(MAKE_DIRECTORY "${_src}/commands" "${_src}/runtime" "${_src}/include"
  "${_src}/config-snapshot/bin/linux-x86_64/gen/config")
configure_file("${CMAKE_CURRENT_LIST_DIR}/programs/CMakeLists.txt" "${_src}/CMakeLists.txt" COPYONLY)
set(_config "${_src}/config-snapshot/bin/linux-x86_64/gen/config/target.cfg")
set(_config_text [=[
FAMILY := unix
CPPFLAGS = $(USER_CPPFLAGS)
CFLAGS = $(USER_CFLAGS)
LDFLAGS = $(USER_LDFLAGS)
NOSTARTUP_LDFLAGS := -nostartfiles
DETACH_LDFLAGS := -pthread
]=])
file(WRITE "${_config}" "${_config_text}")
file(WRITE "${_src}/support.c" "int support(void) { return 0; }\n")
file(WRITE "${_src}/extra.h" "#define EXTRA_VALUE 1\n")
file(WRITE "${_src}/commands/First.c" "int main(void) { return 0; }\n")
file(WRITE "${_src}/commands/Second.c" "int main(void) { return 1; }\n")
file(WRITE "${_src}/runtime/entry.c" "extern int main(void); volatile int result; void _start(void) { result = main(); }\n")
file(WRITE "${_src}/runtime/background.h" "#define BACKGROUND_VALUE 3\n")
set(_background_source "#include \"background.h\"\nvolatile int background_marker = BACKGROUND_VALUE;\n")
file(WRITE "${_src}/runtime/background.c" "${_background_source}")
set(_runtime_manifest [=[
FILES := entry background
runtime-objects: $(addprefix $(AROS_LIB)/,$(addsuffix .o,$(FILES)))
$(AROS_LIB)/%.o: $(GENDIR)/$(CURDIR)/%.o
	@$(CP) $< $@
%rule_compile basename=% targetdir=$(GENDIR)/$(CURDIR)
]=])
file(WRITE "${_src}/runtime/mmakefile.src" "${_runtime_manifest}")
# The fixture uses a host-supported switch and a differently named object:
# production must use configuration/specs, not hard-code -detach or detach.o.
set(_specs "${_src}/compiler.specs")
file(WRITE "${_specs}" "*lib:\n-lfixture\n\n*libgcc:\n-lgcc\n\n*link_gcc_c_sequence:\n%G %L %G\n\n*startfile:\nentry.o%s %{pthread:background.o%s}\n\n*endfile:\n\n\n")
set(_flags "ldflags=\"-specs=${_specs} -no-pie\" targetdir=\$(AROSDIR)/C")
set(_single "%build_prog mmake=fixture-commands progname=First ${_flags}")
set(_batch "%build_progs mmake=fixture-commands files=First Second ${_flags}")
set(_manifest "${_src}/commands/mmakefile.src")
set(_output "${_build}/output/AROS/C/First")
set(_object "${_build}/output/AROS/Development/lib/background.o")
find_program(_nm NAMES nm REQUIRED)
function(run)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Command failed (${_result}): ${ARGN}\n${_out}${_err}")
  endif()
endfunction()
function(build)
  run("${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs -j 2)
endfunction()
function(noop)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 OR NOT _out MATCHES "no work to do" OR _out MATCHES "Re-running CMake")
    message(FATAL_ERROR "Expected no-op without regeneration: ${_out}${_err}")
  endif()
endfunction()
function(marker output expected)
  execute_process(COMMAND "${_nm}" --defined-only "${output}" RESULT_VARIABLE _result
    OUTPUT_VARIABLE _symbols ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 OR (expected AND NOT _symbols MATCHES "background_marker")
     OR (NOT expected AND _symbols MATCHES "background_marker"))
    message(FATAL_ERROR "Wrong detached-object selection for ${output}: ${_symbols}${_err}")
  endif()
endfunction()
function(rejected reason)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  string(REGEX REPLACE "[ \t\r\n]+" " " _diagnostic "${_out}${_err}")
  if(_result EQUAL 0 OR NOT _diagnostic MATCHES "${reason}")
    message(FATAL_ERROR "Expected rejection (${reason}): ${_out}${_err}")
  endif()
endfunction()
file(WRITE "${_manifest}" "${_single} detach=yes\n%build_prog mmake=unselected progname=Unused detach=no\n")
run("${CMAKE_COMMAND}" -G Ninja -S "${_src}" -B "${_build}" "-DAROS_TEST_SOURCE=${_repo}")
build()
marker("${_output}" TRUE)
noop()
foreach(_change IN ITEMS source header missing-object)
  file(TIMESTAMP "${_output}" _before "%s")
  file(TIMESTAMP "${_build}/programs/fixture-programs/obj/0.o" _compile_before "%s")
  run("${CMAKE_COMMAND}" -E sleep 1)
  if(_change STREQUAL source)
    file(APPEND "${_src}/runtime/background.c" "int background_extra = 12;\n")
  elseif(_change STREQUAL header)
    file(WRITE "${_src}/runtime/background.h" "#define BACKGROUND_VALUE 5\n")
  else()
    file(REMOVE "${_object}")
  endif()
  build()
  file(TIMESTAMP "${_output}" _after "%s")
  file(TIMESTAMP "${_build}/programs/fixture-programs/obj/0.o" _compile_after "%s")
  if(_before STREQUAL _after OR NOT _compile_before STREQUAL _compile_after)
    message(FATAL_ERROR "Detached startup ${_change} must rebuild/relink without recompiling the program")
  endif()
  marker("${_output}" TRUE)
  noop()
endforeach()
file(WRITE "${_manifest}" "${_batch} detach=yes\n")
build()
marker("${_output}" TRUE)
marker("${_build}/output/AROS/C/Second" TRUE)
noop()
foreach(_option IN ITEMS "detach=no" "")
  file(WRITE "${_manifest}" "${_single} ${_option}\n")
  build()
  marker("${_output}" FALSE)
  noop()
endforeach()
file(WRITE "${_manifest}" "${_single} detach=maybe\n")
rejected("Invalid detach")
file(WRITE "${_manifest}" "${_single} detach=yes\n")
string(REPLACE "-pthread" "" _empty_config "${_config_text}")
file(WRITE "${_config}" "${_empty_config}")
rejected("Missing DETACH_LDFLAGS")
file(WRITE "${_config}" "${_config_text}")
build()
marker("${_output}" TRUE)
file(TIMESTAMP "${_output}" _before "%s")
run("${CMAKE_COMMAND}" -E sleep 1)
string(REPLACE "-pthread" "-pthread -Wl,--defsym=DETACH_CONFIG_EDIT=1" _edited_config "${_config_text}")
file(WRITE "${_config}" "${_edited_config}")
build()
file(TIMESTAMP "${_output}" _after "%s")
if(_before STREQUAL _after)
  message(FATAL_ERROR "Detached linker configuration edit did not relink")
endif()
include("${_build}/programs/fixture-programs/program.cmake")
if(NOT "-Wl,--defsym=DETACH_CONFIG_EDIT=1" IN_LIST MMAKE_PROGRAM_LINK_OPTIONS)
  message(FATAL_ERROR "Detached linker configuration edit did not refresh metadata")
endif()
file(REMOVE "${_src}/runtime/background.c")
rejected("No supported native compile rule")
file(WRITE "${_src}/runtime/background.c" "${_background_source}")
build()
string(REPLACE "FILES := entry background" "FILES := entry" _removed "${_runtime_manifest}")
file(WRITE "${_src}/runtime/mmakefile.src" "${_removed}")
rejected("Expected one native SDK object producer")
file(WRITE "${_src}/runtime/mmakefile.src" "${_runtime_manifest}")
build()
marker("${_output}" TRUE)
noop()
message(STATUS "Detached single/batch programs, specs-selected native objects, rebuilds and rejection checks passed")
