cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass TEST_BINARY_DIR")
endif()
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
string(RANDOM LENGTH 10 ALPHABET abcdef0123456789 _id)
set(_root "${TEST_BINARY_DIR}/${_id}")
set(_src "${_root}/src")
set(_build "${_root}/build")
file(MAKE_DIRECTORY "${_src}/config" "${_src}/package" "${_src}/archives" "${_src}/base" "${_root}/input/pkg")
configure_file("${_repo}/config/make.tmpl" "${_src}/config/make.tmpl" COPYONLY)
file(WRITE "${_src}/base/sentinel" "untouched\n")
file(WRITE "${_src}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.20)
project(FetchFormat NONE)
include("${AROS_TEST_SOURCE}/cmake/AROSModule.cmake")
include("${AROS_TEST_SOURCE}/cmake/AROSProgramTargets.cmake")
set(AROS_TARGET linux-x86_64)
set(AROS_TARGET_FAMILY unix)
set(AROS_NATIVE_OUTPUT_ROOT "${CMAKE_BINARY_DIR}/output")
aros_collect_mmake_manifests(AROS_MMAKE_MANIFESTS)
_aros_register_mmake_fetch(fixture-fetch _fetch)
add_custom_target(fetch DEPENDS "${_fetch}")
]=])
set(_options [=[
PACKAGE := $(PART)
FORMAT ?= tar.gz
BASE := $(SRCDIR)/base
]=])
file(WRITE "${_src}/package/fetch.settings" "${_options}")
file(WRITE "${_src}/package/mmakefile.src" [=[
PART := first
include $(SRCDIR)/package/fetch.settings
PART := too-late
%fetch mmake=ignored mmake=fixture-fetch archive=missing archive=$(PACKAGE) suffixes=zip suffixes=$(FORMAT) location=missing location= archive_origins=$(SRCDIR)/archives base=$(BASE) destination=/not-the-destination destination=$(TARGETDIR)/Ports/nested patches_specs=fix.diff:pkg:-p1
PACKAGE := also-too-late
]=])
file(WRITE "${_src}/package/fix.diff" "--- a/value.h\n+++ b/value.h\n@@ -1 +1 @@\n-old\n+patched\n")
foreach(_name IN ITEMS first second)
  file(WRITE "${_root}/input/pkg/value.h" "old\n")
  file(WRITE "${_root}/input/pkg/marker" "${_name}\n")
  file(WRITE "${_root}/input/pkg/Test Data.txt" "space-containing member\n")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar czf "${_src}/archives/${_name}.tar.gz" pkg
    WORKING_DIRECTORY "${_root}/input" COMMAND_ERROR_IS_FATAL ANY)
endforeach()
function(run)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Fetch format failed: ${ARGN}\n${_out}${_err}")
  endif()
endfunction()
function(build)
  run("${CMAKE_COMMAND}" --build "${_build}" --target fetch)
endfunction()
function(settled expected)
  build()
  build()
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fetch
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 OR NOT _out MATCHES "no work to do" OR _out MATCHES "Re-running CMake")
    message(FATAL_ERROR "Fetch format failed to settle: ${_out}${_err}")
  endif()
  file(READ "${_build}/output/Ports/nested/pkg/marker" _marker)
  file(READ "${_build}/output/Ports/nested/pkg/value.h" _patched)
  file(READ "${_src}/base/sentinel" _sentinel)
  file(READ "${_build}/output/Ports/nested/pkg/Test Data.txt" _spaced)
  file(GLOB _base_contents RELATIVE "${_src}/base" "${_src}/base/*" "${_src}/base/.*")
  if(NOT _marker STREQUAL "${expected}\n" OR NOT _patched STREQUAL "patched\n"
      OR NOT _sentinel STREQUAL "untouched\n" OR NOT _base_contents STREQUAL "sentinel"
      OR NOT _spaced STREQUAL "space-containing member\n")
    message(FATAL_ERROR "Wrong archive, patch directory or writes to legacy base: ${_marker};${_patched};${_base_contents}")
  endif()
endfunction()
function(rejected reason)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fetch
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "${reason}")
    message(FATAL_ERROR "Expected ${reason}: ${_out}${_err}")
  endif()
endfunction()
run("${CMAKE_COMMAND}" -G Ninja -S "${_src}" -B "${_build}" "-DAROS_TEST_SOURCE=${_repo}")
settled(first)
file(REMOVE "${_build}/output/Ports/nested/pkg/Test Data.txt")
settled(first)
string(REPLACE "$(PART)" "second" _edited "${_options}")
file(WRITE "${_src}/package/fetch.settings" "${_edited}")
settled(second)
file(REMOVE_RECURSE "${_build}/output/Ports/nested")
settled(second)
foreach(_unsupported IN ITEMS "target:\n\t@echo forbidden\n" "#MM fixture-fetch: hidden\n"
    "include missing\n" "ifeq (a,a)\nendif\n")
  file(WRITE "${_src}/package/fetch.settings" "${_edited}${_unsupported}")
  rejected("Unsupported options include")
endforeach()
file(REMOVE "${_src}/package/fetch.settings")
rejected("Options include needs an owned source file")
file(WRITE "${_root}/outside.settings" "${_edited}")
file(CREATE_LINK "${_root}/outside.settings" "${_src}/package/fetch.settings" SYMBOLIC)
rejected("Options include needs an owned source file")
file(REMOVE "${_src}/package/fetch.settings")
file(WRITE "${_src}/package/fetch.settings" "${_edited}")
settled(second)

# Other macro translators retain explicit duplicate rejection.
file(WRITE "${_root}/strict.cmake" "include(\"${_repo}/cmake/AROSModule.cmake\")\ninclude(\"${_repo}/cmake/AROSProgramTargets.cmake\")\nset(AROS_TARGET linux-x86_64)\n_aros_mmake_macro_arguments(\"key=first key=last\" _args)\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -P "${_root}/strict.cmake"
  RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "Duplicate rule argument key")
  message(FATAL_ERROR "Unrelated macro duplicate validation changed: ${_out}${_err}")
endif()
message(STATUS "Fetch scalar overrides, separate bookkeeping base, ordered options and no-op checks passed")
