cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass TEST_BINARY_DIR")
endif()
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
string(RANDOM LENGTH 10 ALPHABET abcdef0123456789 _id)
set(_src "${TEST_BINARY_DIR}/${_id}/src")
set(_build "${TEST_BINARY_DIR}/${_id}/build")
file(MAKE_DIRECTORY "${_src}/include" "${_src}/config-snapshot/bin/linux-x86_64/gen/config")
configure_file("${CMAKE_CURRENT_LIST_DIR}/programs/CMakeLists.txt" "${_src}/CMakeLists.txt" COPYONLY)
file(WRITE "${_src}/support.c" "int support(void) { return 0; }\n")
file(WRITE "${_src}/extra.h" "#define EXTRA_VALUE 1\n")
set(_config "${_src}/config-snapshot/bin/linux-x86_64/gen/config/target.cfg")
set(_config_text "FAMILY := unix\nCPPFLAGS = $(USER_CPPFLAGS)\nCFLAGS = $(USER_CFLAGS)\nLDFLAGS = $(USER_LDFLAGS)\nNOSTARTUP_LDFLAGS := -nostartfiles\n")
file(WRITE "${_config}" "${_config_text}CHOICE := first\n")
file(WRITE "${_src}/mmake.config.in" "defaulttarget image\nignoredir cache\n")
# A cyclic aggregate must still discover every program and react to new
# manifests. It is not an executable prerequisite of either program.
file(WRITE "${_src}/mmakefile" "#MM image : outer\n#MM outer : image commands\n")
function(program directory identity name)
  file(MAKE_DIRECTORY "${_src}/${directory}")
  file(WRITE "${_src}/${directory}/${name}.c" "volatile int value; void _start(void) { value = 1; }\n")
  file(WRITE "${_src}/${directory}/mmakefile.src"
    "NAME := ${identity}\n#MM- commands : $(NAME)\nUSER_LDFLAGS := -nostdlib -no-pie\n%build_prog mmake=$(NAME) progname=${name} files=${name} targetdir=$(AROSDIR)/C usestartup=no\n")
endfunction()
program(first commands First)
program(addition extra Extra)
program(cache excluded Excluded)
program(.hidden hidden Hidden)
file(MAKE_DIRECTORY "${_src}/inactive" "${_src}/host")
file(WRITE "${_src}/inactive/mmakefile.src"
  "ifeq ($(AROS_TARGET_CPU),other)\n#MM- commands : inactive\n%build_prog mmake=inactive progname=Missing files=missing\nendif\n")
file(WRITE "${_src}/host/mmakefile.src"
  "#MM- image : host-tool\n%build_prog mmake=host-tool compiler=host files=missing\n")
file(MAKE_DIRECTORY "${_src}/kernel")
file(WRITE "${_src}/kernel/mmakefile.src"
  "#MM- image : kernel-tool\n#MM kernel-tool : commands\n%build_prog mmake=kernel-tool compiler=kernel files=missing\n%build_prog mmake=commands compiler=kernel files=missing\n")
# The root is an aggregate AND a program producer. An addition elsewhere must
# not be hidden by the local program's existence. Avoid a self-edge in metadata.
file(READ "${_src}/first/mmakefile.src" _first)
string(REPLACE "#MM- commands : $(NAME)\n" "" _first "${_first}")
file(WRITE "${_src}/first/mmakefile.src" "${_first}")
function(run)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Command failed (${_result}): ${ARGN}\n${_out}${_err}")
  endif()
endfunction()
function(build)
  run("${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs -j 2)
endfunction()
function(selected expected)
  file(READ "${_build}/programs.txt" _actual)
  string(STRIP "${_actual}" _actual)
  if(NOT _actual STREQUAL expected)
    message(FATAL_ERROR "Expected ${expected}, discovered ${_actual}")
  endif()
endfunction()
function(noop)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 OR NOT _out MATCHES "no work to do" OR _out MATCHES "Re-running CMake")
    message(FATAL_ERROR "Expected no-op without regeneration: ${_out}${_err}")
  endif()
endfunction()
function(rejected reason)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "${reason}")
    message(FATAL_ERROR "Expected ${reason}: ${_out}${_err}")
  endif()
endfunction()
run("${CMAKE_COMMAND}" -G Ninja -S "${_src}" -B "${_build}"
  "-DAROS_TEST_SOURCE=${_repo}" -DAROS_TEST_AUTO_PROGRAMS=ON)
build()
selected("commands;extra")
file(READ "${_build}/program-order.txt" _order)
if(NOT _order MATCHES "aros-programs-extra-native")
  message(FATAL_ERROR "Cross-manifest prerequisites did not reach native compile/link ordering: ${_order}")
endif()
noop()
program(second commands Second)
file(READ "${_src}/second/mmakefile.src" _second)
string(REPLACE "#MM- commands : $(NAME)\n" "" _second "${_second}")
file(WRITE "${_src}/second/mmakefile.src" "${_second}")
build()
file(READ "${_build}/program-order.txt" _order)
string(REGEX MATCHALL "aros-programs-extra-native" _ordered_parts "${_order}")
list(LENGTH _ordered_parts _count)
if(NOT _count EQUAL 2 OR NOT EXISTS "${_build}/output/AROS/C/Second")
  message(FATAL_ERROR "Shared-identity program parts lost their external prerequisites: ${_order}")
endif()
file(REMOVE "${_src}/second/mmakefile.src")
build()
noop()
set(_first_output "${_build}/output/AROS/C/First")
file(SHA256 "${_first_output}" _before)
file(WRITE "${_src}/first/First.c" "volatile int value; void _start(void) { value = 42; }\n")
build()
file(SHA256 "${_first_output}" _after)
if(_before STREQUAL _after)
  message(FATAL_ERROR "Source edit did not rebuild a discovered program")
endif()
file(REMOVE "${_first_output}")
build()
if(NOT EXISTS "${_first_output}")
  message(FATAL_ERROR "Missing discovered program did not recover")
endif()
noop()
program(incoming upstream Upstream)
build()
selected("commands;extra;upstream")
if(NOT EXISTS "${_build}/output/AROS/C/Upstream")
  message(FATAL_ERROR "New top-level manifest did not build its program")
endif()
file(REMOVE "${_src}/incoming/mmakefile.src")
build()
selected("commands;extra")
noop()
file(RENAME "${_src}/addition/mmakefile.src" "${_src}/addition/mmakefile")
build()
selected("commands;extra")
file(READ "${_src}/addition/mmakefile" _extra)
file(WRITE "${_src}/addition/mmakefile.src" "# Preferred empty source manifest\n")
build()
selected("commands")
file(REMOVE "${_src}/addition/mmakefile.src")
build()
selected("commands;extra")
file(WRITE "${_src}/addition/mmakefile" "ifeq ($(CHOICE),second)\n${_extra}endif\n")
build()
selected("commands")
file(WRITE "${_config}" "${_config_text}CHOICE := second\n")
build()
selected("commands;extra")
file(WRITE "${_src}/mmake.config.in" "defaulttarget extra\nignoredir cache\n")
build()
selected("extra")
file(WRITE "${_src}/mmake.config.in" "defaulttarget image\nignoredir cache\n")
# Bare #MM before an ordinary alias is also an exported dependency edge.
file(WRITE "${_src}/mmakefile" "#MM image : outer\n#MM\nouter: commands\n")
build()
selected("commands;extra")
noop()
file(APPEND "${_src}/addition/mmakefile" "#MM- extra : commands\n")
# Unlike the aggregate above, these are mutually dependent native producers.
rejected("Program metadata dependency cycle|inter-target dependency graph")
file(WRITE "${_src}/addition/mmakefile" "${_extra}")
build()
file(APPEND "${_src}/addition/mmakefile"
  "UNKNOWN := $(shell touch ${_src}/must-not-execute)\nifeq ($(UNKNOWN),x)\n#MM extra : unsafe\nendif\n")
rejected("Unresolved rule conditional")
if(EXISTS "${_src}/must-not-execute")
  message(FATAL_ERROR "Discovery executed an arbitrary shell expression")
endif()
run("${CMAKE_COMMAND}" --build "${_build}" --target fixture-support)
file(WRITE "${_src}/addition/mmakefile" "${_extra}")
build()
noop()
file(APPEND "${_src}/addition/mmakefile" "#MM extra : prefix-@unconfigured@-suffix\n")
rejected("prefix-@unconfigured@-suffix")
run("${CMAKE_COMMAND}" --build "${_build}" --target fixture-support)
file(WRITE "${_src}/addition/mmakefile" "${_extra}")
build()
noop()
string(REPLACE "usestartup=no" "usestartup=no usetree=yes" _unsupported "${_extra}")
file(WRITE "${_src}/addition/mmakefile" "${_unsupported}")
rejected("usetree=yes needs native implementation")
file(WRITE "${_src}/addition/mmakefile" "${_extra}")
build()
noop()
message(STATUS "Manifest-root program discovery, additions, conditions, fallback and fail-closed checks passed")
