cmake_minimum_required(VERSION 3.20)
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass TEST_BINARY_DIR")
endif()
string(RANDOM LENGTH 10 ALPHABET abcdef0123456789 _id)
set(_root "${TEST_BINARY_DIR}/${_id}")
set(_src "${_root}/src")
set(_build "${_root}/build")
file(MAKE_DIRECTORY "${_src}/config" "${_src}/package" "${_src}/downloads" "${_src}/archives" "${_root}/archive/pkg")
configure_file("${_repo}/config/make.tmpl" "${_src}/config/make.tmpl" COPYONLY)
file(WRITE "${_src}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.20)
project(TextTransforms NONE)
include("${AROS_TEST_SOURCE}/cmake/AROSModule.cmake")
include("${AROS_TEST_SOURCE}/cmake/AROSProgramTargets.cmake")
include("${AROS_TEST_SOURCE}/cmake/AROSTextTransforms.cmake")
set(AROS_TARGET linux-x86_64)
set(AROS_TARGET_FAMILY unix)
set(AROS_NATIVE_OUTPUT_ROOT "${CMAKE_BINARY_DIR}/output")
set(_AROS_MMAKE_VAR_DEST "${AROS_NATIVE_OUTPUT_ROOT}/sdk")
set(_AROS_MMAKE_VAR_TARGETDIR "${AROS_NATIVE_OUTPUT_ROOT}")
aros_collect_mmake_manifests(AROS_MMAKE_MANIFESTS)
_aros_register_mmake_fetch(fixture-fetch _fetch)
set(_fetches "${_fetch}")
if(TEST_WITHOUT_FETCH)
  set(_fetches)
endif()
aros_add_mmake_transform_target(transforms MANIFEST "${CMAKE_SOURCE_DIR}/package/mmakefile.src"
  MMAKE_NAME fixture-generated FETCH_TARGETS ${_fetches})
]=])
file(WRITE "${_src}/package/options" "VERSION := 1\n")
file(WRITE "${_src}/package/local.in" "local=old\n")
file(WRITE "${_src}/downloads/mmakefile.src" [=[
%fetch mmake=fixture-fetch archive=fixture suffixes=tar.gz archive_origins=$(SRCDIR)/archives destination=$(TARGETDIR)/Ports/pkg
]=])
set(_manifest [=[
include $(SRCDIR)/package/options
#MM
fixture-generated: header-alias $(DEST)/local.txt
header-alias: $(DEST)/result.h
$(DEST)/result.h: $(TARGETDIR)/Ports/pkg/pkg/input.in
	@$(IF) $(TEST) ! -d $(DEST)/setup ; then $(MKDIR) $(DEST)/setup ; else $(NOP) ; fi
	@$(SED) -e 's|@VERSION@|$(VERSION)|g' \
	    -e 's|@PREFIX@|$${prefix}|' $< > $@
$(DEST)/local.txt: local.in
	@$(IF) $(TEST) ! -d $(DEST)/setup ; then $(MKDIR) $(DEST)/setup ; else $(NOP) ; fi
	@$(SED) -e 's/old/new/' $< > $@
VERSION := $(VERSION)-final
unreachable:
	@echo must-not-run
]=])
string(REPLACE "\\t" "\t" _manifest "${_manifest}")
file(WRITE "${_src}/package/mmakefile.src" "${_manifest}")
function(run)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Transform command failed: ${ARGN}\n${_out}${_err}")
  endif()
endfunction()
function(build)
  run("${CMAKE_COMMAND}" --build "${_build}" --target transforms -j 2)
endfunction()
function(noop)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target transforms -j 2
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 OR NOT _out MATCHES "no work to do" OR _out MATCHES "Re-running CMake")
    message(FATAL_ERROR "Transforms did not settle: ${_out}${_err}")
  endif()
endfunction()
function(archive value)
  file(WRITE "${_root}/archive/pkg/input.in" "version=@VERSION@\nprefix=@PREFIX@\nvalue=${value}\n")
  run("${CMAKE_COMMAND}" -E chdir "${_root}/archive" "${CMAKE_COMMAND}" -E tar czf
    "${_src}/archives/fixture.tar.gz" pkg)
endfunction()
function(expect version value)
  file(READ "${_build}/output/sdk/result.h" _result)
  if(NOT _result STREQUAL "version=${version}-final\nprefix=\${prefix}\nvalue=${value}\n")
    message(FATAL_ERROR "Wrong transform contents: ${_result}")
  endif()
endfunction()
function(rejected reason)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target transforms -j 2
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "${reason}")
    message(FATAL_ERROR "Expected ${reason}: ${_out}${_err}")
  endif()
endfunction()
archive(first)
run("${CMAKE_COMMAND}" -G Ninja -S "${_src}" -B "${_build}" "-DAROS_TEST_SOURCE=${_repo}")
rejected("native sources prepared")
build()
expect(1 first)
noop()
file(WRITE "${_src}/package/options" "VERSION := 2\n")
build()
expect(2 first)
noop()
archive(second)
rejected("native sources prepared")
build()
expect(2 second)
file(WRITE "${_src}/package/local.in" "local=old changed\n")
build()
file(READ "${_build}/output/sdk/local.txt" _local)
if(NOT _local STREQUAL "local=new changed\n")
  message(FATAL_ERROR "Static transform input edit was lost")
endif()
file(REMOVE "${_build}/output/sdk/result.h")
build()
expect(2 second)
file(REMOVE_RECURSE "${_build}/output/sdk/setup")
build()
if(NOT IS_DIRECTORY "${_build}/output/sdk/setup")
  message(FATAL_ERROR "Missing shared setup directory was not recovered")
endif()
noop()
set(_good_manifest "${_manifest}")
foreach(_bad IN ITEMS "s/a/b/e" "s/a/b/w evil" "s/a/b/;e evil" "-f evil")
  string(REPLACE "s/old/new/" "${_bad}" _invalid "${_good_manifest}")
  file(WRITE "${_src}/package/mmakefile.src" "${_invalid}")
  rejected("Unsupported text substitution")
endforeach()
string(REPLACE "'s/old/new/'" "\"s/old/new/\"" _invalid "${_good_manifest}")
file(WRITE "${_src}/package/mmakefile.src" "${_invalid}")
rejected("Unsupported text-transform arguments")
string(REPLACE "s/old/new/" "s/[z-a]/new/" _invalid "${_good_manifest}")
file(WRITE "${_src}/package/mmakefile.src" "${_invalid}")
rejected("Text transform failed")
file(READ "${_build}/output/sdk/local.txt" _retained)
if(NOT _retained STREQUAL _local)
  message(FATAL_ERROR "A failed sed invocation published partial output")
endif()
file(WRITE "${_src}/package/mmakefile.src" "${_good_manifest}")
build()
file(WRITE "${_src}/package/mmakefile.src" "${_good_manifest}\n$(DEST)/local.txt: local.in\n\t@$(SED) -e 's/a/b/' $< > $@\n")
rejected("one local producer")
file(WRITE "${_src}/package/mmakefile.src" "${_good_manifest}\nlocal.in:\n\t@echo generated\n")
rejected("cannot adopt a generated input")
string(REPLACE "header-alias: $(DEST)/result.h" "header-alias: fixture-generated" _invalid "${_good_manifest}")
file(WRITE "${_src}/package/mmakefile.src" "${_invalid}")
rejected("Cyclic text-transform")
file(WRITE "${_src}/package/mmakefile.src" "${_good_manifest}")
build()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${_src}" -B "${_build}" -DTEST_WITHOUT_FETCH=ON
  RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "owned static source")
  message(FATAL_ERROR "Unowned fetched transform input was accepted: ${_out}${_err}")
endif()
run("${CMAKE_COMMAND}" -S "${_src}" -B "${_build}" -DTEST_WITHOUT_FETCH=OFF)
build()
noop()
string(REPLACE "$(DEST)/local.txt" "${_root}/escaped.h" _invalid "${_good_manifest}")
file(WRITE "${_src}/package/mmakefile.src" "${_invalid}")
rejected("outside the native build tree")
file(WRITE "${_src}/package/mmakefile.src" "${_good_manifest}")
build()
file(WRITE "${_root}/outside.txt" "untouched\n")
file(REMOVE "${_build}/output/sdk/local.txt")
file(CREATE_LINK "${_root}/outside.txt" "${_build}/output/sdk/local.txt" SYMBOLIC)
file(APPEND "${_src}/package/local.in" "changed\n")
rejected("outside the native build tree")
file(READ "${_root}/outside.txt" _outside)
if(NOT _outside STREQUAL "untouched\n")
  message(FATAL_ERROR "Transform wrote through an output symlink")
endif()
file(REMOVE "${_build}/output/sdk/local.txt")
build()
file(REMOVE "${_src}/package/local.in")
file(CREATE_LINK "${_root}/outside.txt" "${_src}/package/local.in" SYMBOLIC)
file(APPEND "${_root}/outside.txt" "force source rebuild\n")
rejected("owned static source")
file(REMOVE "${_src}/package/local.in")
file(WRITE "${_src}/package/local.in" "local=old\n")
build()
# Replay the scheduled command directly to check build-time receipt validation,
# independently of fetch preparation's configure-time recovery path.
file(GLOB _contexts "${_build}/text-transforms/*.cmake")
foreach(_context IN LISTS _contexts)
  file(READ "${_context}" _contents)
  if(_contents MATCHES "/sdk/result.h")
    set(_header_context "${_context}")
  endif()
endforeach()
if(NOT _header_context)
  message(FATAL_ERROR "Missing generated-header build context")
endif()
file(SHA256 "${_build}/output/sdk/result.h" _before)
file(APPEND "${_build}/output/Ports/pkg/pkg/input.in" "tampered\n")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DCONTEXT_FILE=${_header_context}"
  -P "${_repo}/cmake/build_mmake_transform.cmake"
  RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(_result EQUAL 0)
  message(FATAL_ERROR "Modified fetched input was accepted")
endif()
file(SHA256 "${_build}/output/sdk/result.h" _after)
if(NOT _before STREQUAL _after)
  message(FATAL_ERROR "Failed fetch validation replaced the previous output")
endif()
configure_file("${_root}/archive/pkg/input.in" "${_build}/output/Ports/pkg/pkg/input.in" COPYONLY)
build()
noop()
message(STATUS "Manifest text transforms, fetch ownership, rebuilds, safe recipes and no-op checks passed: ${_root}")
