cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass TEST_BINARY_DIR")
endif()
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
string(RANDOM LENGTH 10 ALPHABET abcdef0123456789 _id)
set(_root "${TEST_BINARY_DIR}/${_id}")
set(_src "${_root}/src")
file(MAKE_DIRECTORY "${_src}")
set(_manifest "${_src}/mmakefile.src")
set(_context "${_root}/context.cmake")
set(_output "${_root}/graph.cmake")
set(_context_text "set(CMAKE_SOURCE_DIR [==[${_src}]==])\nset(AROS_TARGET linux-x86_64)\nset(AROS_TARGET_FAMILY unix)\nset(AROS_LEGACY_BUILD_DIR [==[${_root}/config]==])\nset(PROGRAM_GRAPH_ROOT image)\n")
file(WRITE "${_context}" "${_context_text}set(AROS_MMAKE_MANIFESTS [==[${_manifest}]==])\n")
set(_collector "${_repo}/cmake/collect_program_graph.cmake")
set(_unknown "UNRESOLVED := $(shell touch ${_src}/must-not-execute)\n")
set(_producer "#MM image : selected\n%build_prog mmake=selected progname=Demo\n")
function(run expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DCONTEXT_FILE=${_context}"
    "-DOUTPUT_FILE=${_output}" -P "${_collector}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Unexpected graph error: ${_out}${_err}")
  endif()
  include("${_output}")
  if(NOT PROGRAM_GRAPH_PROGRAMS STREQUAL expected)
    message(FATAL_ERROR "Expected ${expected}, got ${PROGRAM_GRAPH_PROGRAMS}")
  endif()
  if(EXISTS "${_src}/must-not-execute")
    message(FATAL_ERROR "Graph discovery executed a shell expression")
  endif()
endfunction()
function(reject pattern)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DCONTEXT_FILE=${_context}"
    "-DOUTPUT_FILE=${_output}" -P "${_collector}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "${pattern}")
    message(FATAL_ERROR "Expected ${pattern}, got (${_result}): ${_out}${_err}")
  endif()
  if(EXISTS "${_src}/must-not-execute")
    message(FATAL_ERROR "Rejected metadata executed a shell expression")
  endif()
endfunction()
# Unknown flags and recipes do not decide exported identities. Both branches
# remain unknown, not silently interpreted as true/false or empty strings.
set(_flags "${_unknown}ifneq ($(UNRESOLVED),)\nUSER_CPPFLAGS += -DVERSION=$(UNRESOLVED)\nelse\nUSER_CPPFLAGS := -DNO_VERSION\nendif\n")
file(WRITE "${_manifest}" "${_flags}${_producer}")
run(selected)
# Host/kernel declarations remain graph nodes but are not target-OS programs.
# Their outgoing metadata can still discover target-side prerequisites.
file(WRITE "${_manifest}" "#MM image : host-tool\n#MM host-tool : kernel-tool\n#MM kernel-tool : selected\n%build_prog mmake=host-tool compiler=host\n%build_prog mmake=kernel-tool compiler=kernel\n%build_prog mmake=selected compiler=target\n")
run(selected)
foreach(_compiler IN ITEMS typo no 0)
  file(WRITE "${_manifest}" "#MM image : wrong\n%build_prog mmake=wrong compiler=${_compiler}\n")
  reject("Unknown program discovery compiler: ${_compiler}")
endforeach()
file(WRITE "${_manifest}" "ifeq ($(shell touch ${_src}/must-not-execute; echo $$?),0)\nUSER_CFLAGS := -O2\nendif\nifeq (semi;colon,semi;colon)\n${_producer}endif\n")
run(selected)
# Potential matches do not make a file or an inactive declaration exported.
file(WRITE "${_manifest}" "NAME := other\n#MM image : selected\n#MM\nselected : ${_src}/local.c inactive alias\n#MM alias : second\nifeq ($(CPU),other)\n#MM inactive : wrong\nendif\n%build_prog mmake=$(NAME)\n%build_prog mmake=selected\n%build_prog mmake=second\n")
run("second;selected")
include("${_output}")
string(SHA256 _selected_key selected)
if(NOT PROGRAM_GRAPH_DEPENDS_${_selected_key} STREQUAL "alias")
  message(FATAL_ERROR "Local/inactive dependencies became exported edges: ${PROGRAM_GRAPH_DEPENDS_${_selected_key}}")
endif()
file(WRITE "${_manifest}" "${_flags}#MM image : selected\n%build_prog files=$(shell echo mmake=wrong) cppflags=\"$(USER_CPPFLAGS)\" mmake=\"$(addprefix sele,cted)\" compiler=target\n")
run(selected)
# Unknown condition in a known-inactive branch cannot affect the graph.
file(WRITE "${_manifest}" "${_unknown}ifeq ($(CPU),other)\nifneq ($(UNRESOLVED),)\n#MM image : wrong\n%build_prog mmake=wrong\nendif\nelse\n${_producer}endif\n")
run(selected)
file(WRITE "${_manifest}" "${_unknown}ifneq ($(UNRESOLVED),)\n${_producer}endif\n")
reject("Unresolved rule conditional controls metadata")
file(WRITE "${_manifest}" "${_unknown}ifneq ($(UNRESOLVED),)\n#MM\nendif\nimage : selected\n%build_prog mmake=selected\n")
reject("Unresolved rule conditional controls metadata")
file(WRITE "${_manifest}" "#MM\nifeq ($(CPU),other)\nimage : wrong\nelse\nNAME := selected\nimage : $(NAME)\nendif\n%build_prog mmake=selected\n")
run(selected)
file(WRITE "${_manifest}" "${_unknown}#MM image : selected\nifneq ($(UNRESOLVED),)\n%build_prog mmake=selected\nendif\n")
reject("Unresolved rule conditional controls a producer")
foreach(_assignment IN ITEMS "NAME := selected" "NAME = selected" "NAME += selected" "NAME ?= selected")
  file(WRITE "${_manifest}" "${_unknown}ifneq ($(UNRESOLVED),)\n${_assignment}\nelse\nUSER_CFLAGS := unused\nendif\n#MM image : $(NAME)\n%build_prog mmake=selected\n")
  reject("Unresolved program discovery edge")
endforeach()
file(WRITE "${_manifest}" "${_unknown}ifneq ($(UNRESOLVED),)\nNAME := image\nendif\n#MM $(NAME) : selected\n%build_prog mmake=selected\n")
reject("Unresolved program discovery target")
file(WRITE "${_manifest}" "${_unknown}NAME := selected\nifneq ($(UNRESOLVED),)\nNAME ?= wrong\nendif\n#MM image : $(NAME)\n%build_prog mmake=selected\n")
run(selected)
file(WRITE "${_manifest}" "${_unknown}ifneq ($(UNRESOLVED),)\nNAME := wrong\nendif\nNAME := selected\n#MM image : $(NAME)\n%build_prog mmake=selected\n")
run(selected)
# Uncertainty must not disappear through word functions or snapshots.
foreach(_expression IN ITEMS "$(findstring selected,$(NAME))" "$(foreach n,$(NAME),selected)" "$(filter selected,$(NAME))" "$(strip $(NAME))" "$(addprefix prefix,$(NAME))")
  file(WRITE "${_manifest}" "${_unknown}ifneq ($(UNRESOLVED),)\nNAME := selected\nendif\nSNAPSHOT := ${_expression}\nNAME := selected\n#MM image : selected\n%build_prog mmake=$(SNAPSHOT)\n")
  reject("Unresolved program discovery mmake")
  file(WRITE "${_manifest}" "NAME := @unconfigured@\nSNAPSHOT := ${_expression}\nNAME := selected\n#MM image : selected\n%build_prog mmake=$(SNAPSHOT)\n")
  reject("Unresolved program discovery mmake")
endforeach()
file(WRITE "${_manifest}" "${_unknown}ifneq ($(UNRESOLVED),)\nCOMPILER := host\nendif\n#MM image : selected\n%build_prog mmake=selected compiler=$(COMPILER)\n")
reject("Unresolved program discovery compiler")
file(WRITE "${_manifest}" "OPTION := @unconfigured@\n#MM image : selected-$(OPTION)\n%build_prog mmake=selected\n")
reject("Unresolved program discovery edge")
file(WRITE "${_manifest}" "OPTION := @unconfigured@\nifeq ($(OPTION),yes)\n${_producer}endif\n")
reject("Unresolved rule conditional controls metadata")
file(WRITE "${_manifest}" "#MM image : selected\n%build_prog mmake=selected compiler=@unconfigured@\n")
reject("Unresolved program discovery compiler")
file(WRITE "${_manifest}" "${_unknown}ifneq ($(UNRESOLVED),)\ninclude unknown.opts\nendif\n${_producer}")
reject("Unresolved rule conditional controls an include")
foreach(_line IN ITEMS "else" "endif")
  file(WRITE "${_manifest}" "${_line}\n${_producer}")
  reject("Unmatched rule")
endforeach()
file(WRITE "${_manifest}" "#MM image : selected\n%build_prog mmake=\"unterminated\n")
reject("Unbalanced program discovery arguments")
# Aggregate reachability is not an executable DAG. Keep cycles, all outgoing
# producers, and cross-manifest additions, regardless of the entry direction.
function(edges node expected)
  include("${_output}")
  string(SHA256 _key "${node}")
  if(NOT node IN_LIST PROGRAM_GRAPH_NODES OR
     NOT DEFINED PROGRAM_GRAPH_DEPENDS_${_key} OR
     NOT PROGRAM_GRAPH_DEPENDS_${_key} STREQUAL expected)
    message(FATAL_ERROR "Lost discovery edges for ${node}: expected '${expected}', got '${PROGRAM_GRAPH_DEPENDS_${_key}}'")
  endif()
endfunction()
set(_cycle "#MM ancestor : left\n#MM left : leaf right\n#MM right : left selected\n%build_prog mmake=selected\n")
file(WRITE "${_manifest}" "#MM image : ancestor\n${_cycle}")
run(selected)
edges(ancestor left)
edges(left "leaf;right")
edges(right "left;selected")
edges(leaf "")
file(WRITE "${_manifest}" "#MM image : right\n${_cycle}")
run(selected)
edges(left "leaf;right")
edges(right "left;selected")
file(WRITE "${_manifest}" "#MM image : self\n#MM self : self selected\n%build_prog mmake=selected\n")
run(selected)
edges(self "self;selected")
file(WRITE "${_manifest}" "#MM image : ancestor\n${_cycle}")
set(_addition "${_src}/addition/mmakefile.src")
file(MAKE_DIRECTORY "${_src}/addition")
file(WRITE "${_addition}" "#MM left : added\n#MM added : right\n%build_prog mmake=added\n")
foreach(_inventory IN ITEMS "${_manifest};${_addition}" "${_addition};${_manifest}")
  file(WRITE "${_context}" "${_context_text}set(AROS_MMAKE_MANIFESTS [==[${_inventory}]==])\n")
  run("added;selected")
  edges(added right)
  edges(right "left;selected")
  include("${_output}")
  string(SHA256 _key left)
  set(_edges "${PROGRAM_GRAPH_DEPENDS_${_key}}")
  list(SORT _edges)
  if(NOT _edges STREQUAL "added;leaf;right")
    message(FATAL_ERROR "Manifest order lost aggregate edges: ${_edges}")
  endif()
endforeach()
# The unchanged real manifest must be discoverable even though its flag and
# generated-header translation is not thereby implemented.
set(_about "${_repo}/workbench/system/AboutAROS/mmakefile.src")
file(WRITE "${_context}" "${_context_text}set(PROGRAM_GRAPH_ROOT workbench-system-aboutaros)\nset(AROS_MMAKE_MANIFESTS [==[${_about}]==])\n")
run(workbench-system-aboutaros)
# The hosted launcher's unchanged compiler=kernel declaration belongs to the
# host/kernel primitive, not a second target-OS executable producer.
set(_bootstrap "${_repo}/arch/all-hosted/bootstrap/mmakefile.src")
file(WRITE "${_context}" "${_context_text}set(PROGRAM_GRAPH_ROOT kernel-bootstrap-hosted)\nset(AROS_MMAKE_MANIFESTS [==[${_bootstrap}]==])\n")
run("")
# Non-discovery consumers still reject unresolved conditions.
file(WRITE "${_root}/strict.cmake"
  "include([==[${_context}]==])\ninclude([==[${_repo}/cmake/AROSModule.cmake]==])\ninclude([==[${_repo}/cmake/AROSMmakeRules.cmake]==])\n_aros_collect_mmake_rules([==[${_about}]==] _rules)\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -P "${_root}/strict.cmake"
  RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "Unresolved rule conditional")
  message(FATAL_ERROR "Discovery weakened the strict rule reader: ${_out}${_err}")
endif()
message(STATUS "Graph-only condition/argument evaluation and strict-consumer checks passed")
