cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass TEST_BINARY_DIR")
endif()
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
string(RANDOM LENGTH 10 ALPHABET abcdef0123456789 _id)
set(_src "${TEST_BINARY_DIR}/${_id}/src")
set(_build "${TEST_BINARY_DIR}/${_id}/build")
file(MAKE_DIRECTORY "${_src}/commands" "${_src}/sdk/local/nested" "${_src}/upstream/pkg"
  "${_src}/archives" "${_src}/config" "${_src}/config-snapshot/bin/linux-x86_64/gen/config")
configure_file("${CMAKE_CURRENT_LIST_DIR}/programs/CMakeLists.txt" "${_src}/CMakeLists.txt" COPYONLY)
configure_file("${_repo}/config/make.tmpl" "${_src}/config/make.tmpl" COPYONLY)
file(WRITE "${_src}/support.c" "int support(void) { return 0; }\n")
file(WRITE "${_src}/extra.h" "#define EXTRA_VALUE 1\n")
file(WRITE "${_src}/config-snapshot/bin/linux-x86_64/gen/config/target.cfg" [=[
FAMILY := unix
GENINCDIR := $(GENDIR)/include
AROS_DIR_INCLUDE := include
CPPFLAGS = $(USER_CPPFLAGS)
CFLAGS = $(USER_CFLAGS)
LDFLAGS = $(USER_LDFLAGS)
NOSTARTUP_LDFLAGS := -nostartfiles
WILDCARD = $(shell cd $(SRCDIR)/$(CURDIR); for file in $(1); do if [ -f $$file ]; then printf "%s" "$$file "; fi; done)
]=])
file(WRITE "${_src}/commands/Main.c" "#include <fixture/public.h>\nint _start(void) { return VALUE; }\n")
file(WRITE "${_src}/commands/mmakefile.src" [=[
#MM fixture-commands: fixture-includes
%build_prog mmake=fixture-commands progname=Main usestartup=no ldflags="-nostdlib -no-pie" targetdir=$(AROSDIR)/C
]=])
file(WRITE "${_src}/sdk/local/public.h" "#define VALUE 7\n")
file(WRITE "${_src}/sdk/local/not-selected.h" "#error Must not be copied\n")
file(WRITE "${_src}/sdk/local/nested/private.h" "#define PRIVATE 2\n")
file(WRITE "${_src}/sdk/local/host.h" "#define HOST 3\n")
file(WRITE "${_src}/sdk/local/kernel.h" "#define KERNEL 4\n")
file(MAKE_DIRECTORY "${_src}/sdk/local/wild")
file(WRITE "${_src}/sdk/local/wild/a.h" "#define WILD_A 1\n")
set(_manifest [=[
INCLUDE_FILES := public.h
%copy_includes mmake=fixture-includes dir=local path=fixture
INCLUDE_FILES := local/nested/private.h
%copy_includes mmake=fixture-includes path=fixture sdk=private
%copy_includes mmake=fixture-includes dir=local includes=host.h path=host compiler=host
%copy_includes mmake=fixture-includes dir=local includes=kernel.h path=kernel compiler=kernel
INCLUDE_FILES := not-selected.h
ifeq (no,yes)
%copy_includes mmake=fixture-includes includes=missing.h
endif
GLOB_DIR := local/wild
INCLUDE_FILES := $(call WILDCARD, $(GLOB_DIR)/*.h)
%copy_includes mmake=fixture-includes dir=$(GLOB_DIR) path=wild
%copy_includes mmake=fixture-includes includes="$(call WILDCARD, local/missing/*.h)" dir=local/missing path=empty
GLOB_DIR := later
INCLUDE_FILES := absent.h
INCLUDE_FILES = $(call WILDCARD, ../unowned/*.h)
%copy_includes mmake=fixture-includes includes=local/public.h path=explicit
]=])
file(WRITE "${_src}/sdk/mmakefile.src" "${_manifest}")
function(run)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Command failed (${_result}): ${ARGN}\n${_out}${_err}")
  endif()
endfunction()
function(build)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs -j 4
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 AND "${_out}${_err}" MATCHES "native sources prepared; run the build again")
    run("${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs -j 4)
  elseif(NOT _result EQUAL 0)
    message(FATAL_ERROR "Include/program build failed: ${_out}${_err}")
  endif()
endfunction()
function(noop)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 OR NOT _out MATCHES "no work to do" OR _out MATCHES "Re-running CMake")
    message(FATAL_ERROR "Expected no-op without regeneration: ${_out}${_err}")
  endif()
endfunction()
function(rejected reason)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  string(REGEX REPLACE "[ \t\r\n]+" " " _message "${_out}${_err}")
  if(_result EQUAL 0 OR NOT _message MATCHES "${reason}")
    message(FATAL_ERROR "Expected rejection (${reason}): ${_out}${_err}")
  endif()
endfunction()
set(_host "${_build}/output/gen/include")
set(_public "${_build}/include")
set(_private "${_build}/output/gen/buildsdks/private/include")
set(_program "${_build}/output/AROS/C/Main")
run("${CMAKE_COMMAND}" -G Ninja -S "${_src}" -B "${_build}" "-DAROS_TEST_SOURCE=${_repo}"
  "-DAROS_TEST_INCLUDE_DIR=${_public}")
build()
foreach(_path IN ITEMS "${_public}/fixture/public.h" "${_host}/fixture/public.h"
    "${_host}/fixture/local/nested/private.h" "${_private}/fixture/local/nested/private.h"
    "${_host}/host/host.h" "${_host}/kernel/kernel.h")
  if(NOT EXISTS "${_path}")
    message(FATAL_ERROR "Missing declared include: ${_path}")
  endif()
endforeach()
if(EXISTS "${_public}/host/host.h" OR EXISTS "${_public}/kernel/kernel.h"
   OR EXISTS "${_public}/fixture/not-selected.h")
  message(FATAL_ERROR "Staged an undeclared/wrong-role header")
endif()
noop()
run("${CMAKE_COMMAND}" -E compare_files "${_src}/sdk/local/wild/a.h" "${_public}/wild/a.h")
file(WRITE "${_src}/sdk/local/wild/.hidden.h" "hidden\n")
noop()
file(MAKE_DIRECTORY "${_src}/sdk/local/wild/directory.h")
build()
if(EXISTS "${_public}/wild/directory.h" OR EXISTS "${_public}/wild/.hidden.h")
  message(FATAL_ERROR "Wildcard included a directory or shell-hidden header")
endif()
noop()
file(WRITE "${_src}/sdk/local/wild/added.h" "#define ADDED 1\n")
build()
run("${CMAKE_COMMAND}" -E compare_files "${_src}/sdk/local/wild/added.h" "${_public}/wild/added.h")
file(REMOVE "${_src}/sdk/local/wild/added.h")
build()
file(READ "${_build}/build.ninja" _graph)
if(_graph MATCHES "build include/wild/added[.]h:")
  message(FATAL_ERROR "Removed wildcard header still has a native producer")
endif()
noop()
foreach(_change IN ITEMS source missing-public missing-host)
  file(TIMESTAMP "${_program}" _before "%s")
  run("${CMAKE_COMMAND}" -E sleep 1)
  if(_change STREQUAL source)
    file(WRITE "${_src}/sdk/local/public.h" "#define VALUE 8\n")
  elseif(_change STREQUAL missing-public)
    file(REMOVE "${_public}/fixture/public.h")
  else()
    file(REMOVE "${_host}/fixture/public.h")
  endif()
  build()
  file(TIMESTAMP "${_program}" _after "%s")
  if(_before STREQUAL _after)
    message(FATAL_ERROR "Include ${_change} did not rebuild its consumer")
  endif()
  noop()
endforeach()
# Upstream-added producers and metadata edges must augment the same identity.
file(MAKE_DIRECTORY "${_src}/incoming")
file(WRITE "${_src}/incoming/new.h" "#define NEW 1\n")
file(WRITE "${_src}/incoming/mmakefile.src" "%copy_includes mmake=fixture-includes includes=new.h path=new\n")
build()
if(NOT EXISTS "${_public}/new/new.h")
  message(FATAL_ERROR "New top-level include producer was not discovered")
endif()
noop()
# Identical declarations share one copy command rather than duplicate outputs.
file(APPEND "${_src}/sdk/mmakefile.src" "%copy_includes mmake=fixture-includes dir=local includes=public.h path=fixture\n")
build()
noop()
# Fetch the exact declared header, without adopting extracted reference files.
file(WRITE "${_src}/upstream/pkg/public.h" "#define VALUE 12\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cfz "${_src}/archives/pkg.tar.gz" pkg
  WORKING_DIRECTORY "${_src}/upstream" COMMAND_ERROR_IS_FATAL ANY)
set(_fetched [=[
%fetch mmake=fixture-fetch archive=pkg suffixes=tar.gz location=$(SRCDIR)/archives destination=$(TARGETDIR)/Ports/pkg
INCLUDE_FILES := $(call WILDCARD, $(TARGETDIR)/Ports/pkg/pkg/*.h)
%copy_includes mmake=fixture-includes dir=$(TARGETDIR)/Ports/pkg/pkg path=fixture
]=])
file(WRITE "${_src}/sdk/mmakefile.src" "${_fetched}")
file(MAKE_DIRECTORY "${_src}/edges")
file(WRITE "${_src}/edges/mmakefile.src" "#MM fixture-includes: fixture-fetch\n")
build()
file(READ "${_public}/fixture/public.h" _value)
if(NOT _value STREQUAL "#define VALUE 12\n")
  message(FATAL_ERROR "Fetched header was not staged")
endif()
noop()
# An alias must carry fetch ownership, including newly discovered augmentations.
file(WRITE "${_src}/edges/mmakefile.src" "#MM fixture-includes: fetch-alias\n")
rejected("requires an owned (static )?source")
file(MAKE_DIRECTORY "${_src}/fetch-layer")
file(WRITE "${_src}/fetch-layer/mmakefile.src" "#MM fetch-alias: fetch-next\n#MM fetch-next: fixture-fetch\n")
build()
noop()
file(APPEND "${_src}/fetch-layer/mmakefile.src" "#MM fetch-next: fetch-alias\n")
rejected("dependency cycle")
file(WRITE "${_src}/fetch-layer/mmakefile.src" "#MM fetch-alias: fetch-next\n#MM fetch-next: fixture-fetch\n")
# Include producers and their cross-manifest aggregate must retain provenance.
file(WRITE "${_src}/edges/bridge.h" "#define BRIDGE 1\n")
set(_indirect_edges [=[
#MM fixture-includes: bridge-includes fetch-alias
#MM bridge-includes: fetch-alias
%copy_includes mmake=bridge-includes includes=bridge.h path=bridge
]=])
file(WRITE "${_src}/edges/mmakefile.src" "${_indirect_edges}")
file(MAKE_DIRECTORY "${_src}/bridge-part")
file(WRITE "${_src}/bridge-part/other.h" "#define OTHER_BRIDGE 1\n")
file(WRITE "${_src}/bridge-part/mmakefile.src"
  "%copy_includes mmake=bridge-includes includes=other.h path=bridge\n")
build()
run("${CMAKE_COMMAND}" -E compare_files "${_src}/edges/bridge.h" "${_public}/bridge/bridge.h")
run("${CMAKE_COMMAND}" -E compare_files "${_src}/bridge-part/other.h" "${_public}/bridge/other.h")
noop()
# Remove the redundant direct alias: only the intermediate include now owns it.
string(REPLACE "fixture-includes: bridge-includes fetch-alias" "fixture-includes: bridge-includes"
  _indirect_edges "${_indirect_edges}")
file(WRITE "${_src}/edges/mmakefile.src" "${_indirect_edges}")
build()
noop()
# Union two fetches through a shared alias and a multi-part include provider.
file(MAKE_DIRECTORY "${_src}/upstream/aux")
file(WRITE "${_src}/upstream/aux/aux.h" "#define AUX_VALUE 3\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cfz "${_src}/archives/aux.tar.gz" aux
  WORKING_DIRECTORY "${_src}/upstream" COMMAND_ERROR_IS_FATAL ANY)
file(APPEND "${_src}/fetch-layer/mmakefile.src" [=[
#MM fetch-alias: auxiliary-fetch
%fetch mmake=auxiliary-fetch archive=aux suffixes=tar.gz location=$(SRCDIR)/archives destination=$(TARGETDIR)/Ports/aux
]=])
file(APPEND "${_src}/bridge-part/mmakefile.src" [=[
%copy_includes mmake=bridge-includes includes=aux.h dir=$(TARGETDIR)/Ports/aux/aux path=bridge
]=])
build()
run("${CMAKE_COMMAND}" -E compare_files "${_src}/upstream/aux/aux.h" "${_public}/bridge/aux.h")
noop()
# Provenance propagation must not bypass the registry's recipe validation.
file(APPEND "${_src}/fetch-layer/mmakefile.src" "#MM\nfetch-next:\n\t@echo unsupported\n")
rejected("Unsupported|unsupported")
file(READ "${_src}/fetch-layer/mmakefile.src" _layer)
string(REPLACE "#MM\nfetch-next:\n\t@echo unsupported\n" "" _layer "${_layer}")
file(WRITE "${_src}/fetch-layer/mmakefile.src" "${_layer}")
build()
noop()
file(REMOVE "${_build}/output/Ports/pkg/pkg/public.h")
build()
noop()
run("${CMAKE_COMMAND}" -E sleep 1)
file(WRITE "${_src}/upstream/pkg/public.h" "#define VALUE 13\n")
file(WRITE "${_src}/upstream/pkg/new.h" "#define NEW_FETCHED 1\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cfz "${_src}/archives/pkg.tar.gz" pkg
  WORKING_DIRECTORY "${_src}/upstream" COMMAND_ERROR_IS_FATAL ANY)
build()
file(READ "${_public}/fixture/public.h" _value)
if(NOT _value STREQUAL "#define VALUE 13\n")
  message(FATAL_ERROR "Archive edit did not update the staged header")
endif()
noop()
run("${CMAKE_COMMAND}" -E compare_files "${_src}/upstream/pkg/new.h" "${_public}/fixture/new.h")
file(WRITE "${_build}/output/Ports/pkg/pkg/rogue.h" "#define UNOWNED 1\n")
rejected("Native fetched-source inventory changed")
file(REMOVE "${_build}/output/Ports/pkg/pkg/rogue.h")
build()
noop()
file(REMOVE "${_src}/edges/mmakefile.src")
rejected("requires an owned (static )?source")
file(REMOVE "${_src}/fetch-layer/mmakefile.src" "${_src}/bridge-part/mmakefile.src")
file(WRITE "${_src}/sdk/mmakefile.src" "${_manifest}")
build()
foreach(_bad IN ITEMS "path=../escape" "compiler=invalid" "unknown=yes")
  file(WRITE "${_src}/sdk/mmakefile.src" "%copy_includes mmake=fixture-includes includes=local/public.h ${_bad}\n")
  rejected("Unsafe copy_includes|Unsupported copy_includes")
endforeach()
file(WRITE "${_src}/sdk/mmakefile.src" "${_manifest}\nlocal/public.h:\n\t@echo unsupported\n")
rejected("generated source needs a native producer")
file(WRITE "${_src}/sdk/mmakefile.src" "${_manifest}")
file(APPEND "${_src}/incoming/mmakefile.src" "#MM fixture-includes: fixture-includes\n")
rejected("dependency cycle")
file(WRITE "${_src}/incoming/mmakefile.src" "%copy_includes mmake=fixture-includes includes=new.h path=fixture\n")
file(WRITE "${_src}/incoming/public.h" "#define OTHER 1\n")
file(APPEND "${_src}/incoming/mmakefile.src" "%copy_includes mmake=fixture-includes includes=public.h path=fixture\n")
rejected("Conflicting include producer")
file(REMOVE "${_src}/incoming/mmakefile.src")
build()
noop()
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}/${_id}/outside")
file(WRITE "${TEST_BINARY_DIR}/${_id}/outside/public.h" "#define VALUE 99\n")
file(REMOVE "${_src}/sdk/local/public.h")
file(CREATE_LINK "${TEST_BINARY_DIR}/${_id}/outside/public.h" "${_src}/sdk/local/public.h" SYMBOLIC)
rejected("requires an owned static source")
file(REMOVE "${_src}/sdk/local/public.h")
file(WRITE "${_src}/sdk/local/public.h" "#define VALUE 8\n")
build()
# Recheck containment at execution too, not just during graph registration.
file(REMOVE_RECURSE "${_public}/fixture")
file(CREATE_LINK "${TEST_BINARY_DIR}/${_id}/outside" "${_public}/fixture" SYMBOLIC)
run("${CMAKE_COMMAND}" -E sleep 1)
file(WRITE "${_src}/sdk/local/public.h" "#define VALUE 9\n")
rejected("output is outside the native build tree")
file(READ "${TEST_BINARY_DIR}/${_id}/outside/public.h" _value)
if(NOT _value STREQUAL "#define VALUE 99\n")
  message(FATAL_ERROR "Copy escaped the native output directory")
endif()
file(REMOVE "${_public}/fixture")
build()
noop()
# The upstream default identity and a zero-argument macro are valid locally.
file(MAKE_DIRECTORY "${_src}/bare")
file(WRITE "${_src}/bare/bare.h" "#define BARE 1\n")
file(WRITE "${_src}/bare/mmakefile.src" "INCLUDE_FILES := bare.h\n%copy_includes\n")
file(APPEND "${_src}/CMakeLists.txt"
  "\naros_add_mmake_include_target(fixture-local-includes MANIFEST \"${_src}/bare/mmakefile.src\" MMAKE_NAME includes-copy)\n")
run("${CMAKE_COMMAND}" --build "${_build}" --target fixture-local-includes)
foreach(_root IN ITEMS "${_public}" "${_host}")
  run("${CMAKE_COMMAND}" -E compare_files "${_src}/bare/bare.h" "${_root}/bare.h")
endforeach()
file(WRITE "${_src}/edges/mmakefile.src" "#MM fixture-includes\ninclude $(SRCDIR)/edges/rules.opts\n")
file(WRITE "${_src}/edges/rules.opts" "#MM fixture-includes: untranslated\n")
rejected("Unsupported options include")
file(REMOVE "${_src}/edges/mmakefile.src")
build()
noop()
file(WRITE "${_src}/sdk/mmakefile.src"
  "%copy_includes mmake=fixture-includes includes=\"$(call WILDCARD, ${TEST_BINARY_DIR}/${_id}/outside/*.h)\" dir=local path=unsafe\n")
rejected("requires an owned source")
file(WRITE "${_src}/sdk/mmakefile.src"
  "%copy_includes mmake=fixture-includes includes=\"$(call WILDCARD, local/*/*.h)\" dir=local path=unsafe\n")
rejected("requires a literal source directory")
file(WRITE "${_src}/sdk/mmakefile.src" "${_manifest}")
set(_config_file "${_src}/config-snapshot/bin/linux-x86_64/gen/config/target.cfg")
file(READ "${_config_file}" _config)
string(REPLACE "for file in $(1)" "for file in unsupported" _bad_config "${_config}")
file(WRITE "${_config_file}" "${_bad_config}")
rejected("Unsupported static WILDCARD definition")
file(WRITE "${_config_file}" "${_config}")
build()
noop()
message(STATUS "Manifest include snapshots, SDK/host paths, fetch ownership, rebuilds and rejection checks passed")
