cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass TEST_BINARY_DIR")
endif()
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
string(RANDOM LENGTH 10 ALPHABET abcdef0123456789 _id)
set(_root "${TEST_BINARY_DIR}/${_id}")
set(_src "${_root}/src")
set(_build "${_root}/build")
set(_native "${_root}/native @values@.cfg")
set(_snapshot "${_src}/config-snapshot")
file(MAKE_DIRECTORY "${_src}/include" "${_snapshot}/bin/linux-x86_64/gen/config" "${_snapshot}/config")
configure_file("${CMAKE_CURRENT_LIST_DIR}/programs/CMakeLists.txt" "${_src}/CMakeLists.txt" COPYONLY)
file(WRITE "${_src}/support.c" "int support(void) { return 0; }\n")
file(WRITE "${_src}/extra.h" "#define EXTRA_VALUE 1\n")
file(WRITE "${_src}/mmake.config.in" "defaulttarget image\n")
file(WRITE "${_snapshot}/config/make.cfg" "# Snapshot fixture\n")
file(WRITE "${_snapshot}/bin/linux-x86_64/gen/config/target.cfg" [=[
FAMILY := unix
CHOICE := @unconfigured@
NUMBER := 99
CHOICE_FLAGS := -DCHOICE=$(NUMBER)
CPPFLAGS = $(USER_CPPFLAGS)
CFLAGS = $(USER_CFLAGS) $(CHOICE_FLAGS)
LDFLAGS = $(USER_LDFLAGS)
NOSTARTUP_LDFLAGS := -nostartfiles
]=])
file(SHA256 "${_snapshot}/bin/linux-x86_64/gen/config/target.cfg" _original)
file(WRITE "${_src}/mmakefile.src" [=[
#MM image : commands-$(CHOICE)
USER_LDFLAGS := -nostdlib -no-pie
%build_prog mmake=commands-enabled progname=Enabled files=enabled targetdir=$(AROSDIR)/C usestartup=no
%build_prog mmake=commands-disabled progname=Disabled files=disabled targetdir=$(AROSDIR)/C usestartup=no
]=])
foreach(_name IN ITEMS enabled disabled)
  file(WRITE "${_src}/${_name}.c" "volatile int value; void _start(void) { value = CHOICE; }\n")
endforeach()
function(run)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Command failed (${_result}): ${ARGN}\n${_out}${_err}")
  endif()
endfunction()
function(build expected)
  run("${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs -j 2)
  file(READ "${_build}/programs.txt" _actual)
  string(STRIP "${_actual}" _actual)
  if(NOT _actual STREQUAL "commands-${expected}")
    message(FATAL_ERROR "Native config did not select ${expected}: ${_actual}")
  endif()
endfunction()
function(noop)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _result EQUAL 0 OR NOT _out MATCHES "no work to do" OR _out MATCHES "Re-running CMake")
    message(FATAL_ERROR "Expected no-op without regeneration: ${_out}${_err}")
  endif()
endfunction()
function(rejected pattern)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target fixture-programs
    RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "${pattern}")
    message(FATAL_ERROR "Expected ${pattern}: ${_out}${_err}")
  endif()
endfunction()
file(WRITE "${_native}" "# Explicit choices, not manifest defaults\nCHOICE=enabled\nNUMBER=1\nEMPTY=\nKEYS=literal\nLOADED=OFF\n")
file(WRITE "${_root}/read.cmake" "cmake_minimum_required(VERSION 3.20)\ninclude([==[${_repo}/cmake/AROSNativeConfig.cmake]==])\n")
file(APPEND "${_root}/read.cmake" [=[
_aros_native_config_value(EMPTY _value _found)
if(NOT _found OR NOT _value STREQUAL "")
  message(FATAL_ERROR "Explicit empty native config was lost")
endif()
_aros_native_config_value(ABSENT _value _found)
if(_found)
  message(FATAL_ERROR "Missing native config became an explicit value")
endif()
_aros_native_config_value(KEYS _value _found)
if(NOT _found OR NOT _value STREQUAL "literal")
  message(FATAL_ERROR "Native config name collided with reader metadata")
endif()
_aros_native_config_value(LOADED _value _found)
if(NOT _found OR NOT _value STREQUAL "OFF")
  message(FATAL_ERROR "Native config name collided with cache state")
endif()
]=])
run("${CMAKE_COMMAND}" "-DAROS_NATIVE_CONFIG_FILE=${_native}" -P "${_root}/read.cmake")
run("${CMAKE_COMMAND}" -G Ninja -S "${_src}" -B "${_build}"
  "-DAROS_TEST_SOURCE=${_repo}" -DAROS_TEST_AUTO_PROGRAMS=ON "-DAROS_NATIVE_CONFIG_FILE=${_native}")
build(enabled)
noop()
file(SHA256 "${_build}/output/AROS/C/Enabled" _before)
# Switch from the individual-value reader to ordered configuration loading.
file(MAKE_DIRECTORY "${_src}/config")
file(WRITE "${_src}/config/aros.cfg" [=[
include $(TOP)/config/make.cfg
include $(TOP)/bin/$(AROS_TARGET_ARCH)-$(AROS_TARGET_CPU)/gen/config/target.cfg
]=])
file(APPEND "${_src}/mmakefile.src" "\n# Trigger collection with the complete snapshot\n")
build(enabled)
file(SHA256 "${_build}/output/AROS/C/Enabled" _after)
if(NOT _before STREQUAL _after)
  message(FATAL_ERROR "Configure-time and ordered build-time config readers disagree")
endif()
file(WRITE "${_native}" "CHOICE=enabled\nNUMBER=42\nEMPTY=\n")
build(enabled)
file(SHA256 "${_build}/output/AROS/C/Enabled" _after)
if(_before STREQUAL _after)
  message(FATAL_ERROR "Native config edit did not rebuild the program with new flags")
endif()
noop()
file(WRITE "${_native}" "CHOICE=disabled\nNUMBER=42\nEMPTY=\n")
build(disabled)
if(NOT EXISTS "${_build}/output/AROS/C/Disabled")
  message(FATAL_ERROR "Native config edit did not build the newly selected program")
endif()
noop()
file(WRITE "${_native}" "NUMBER=42\n")
rejected("commands-@unconfigured@")
file(WRITE "${_native}" "CHOICE=disabled\nCHOICE=enabled\n")
rejected("Duplicate native configuration value")
file(WRITE "${_native}" "CHOICE=$(shell touch ${_root}/must-not-execute)\n")
rejected("Nonliteral native configuration value")
if(EXISTS "${_root}/must-not-execute")
  message(FATAL_ERROR "Native configuration executed a shell expression")
endif()
foreach(_invalid IN ITEMS "CHOICE=x;y" "CHOICE=@unconfigured@" "CHOICE=x\\y" "include file.cfg")
  file(WRITE "${_native}" "${_invalid}\n")
  rejected("(Nonliteral native configuration value|Expected literal NAME=value)")
endforeach()
file(REMOVE "${_native}")
rejected("existing absolute file")
file(WRITE "${_native}" "CHOICE=disabled\nNUMBER=42\nEMPTY=\n")
build(disabled)
noop()
file(SHA256 "${_snapshot}/bin/linux-x86_64/gen/config/target.cfg" _after)
if(NOT _original STREQUAL _after)
  message(FATAL_ERROR "Native configuration modified the reference snapshot")
endif()
message(STATUS "Native configuration overrides, graph refresh, compilation, rejection and no-op checks passed")
