cmake_minimum_required(VERSION 3.20)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Pass an isolated TEST_BINARY_DIR")
endif()
get_filename_component(_cmake_dir "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef _id)
set(_source "${TEST_BINARY_DIR}/${_id}/source")
set(_build "${TEST_BINARY_DIR}/${_id}/build")
file(MAKE_DIRECTORY "${_source}/producers")
foreach(_file IN ITEMS CMakeLists.txt producers/CMakeLists.txt)
  configure_file("${CMAKE_CURRENT_LIST_DIR}/runtime-module-set/${_file}" "${_source}/${_file}" COPYONLY)
endforeach()
file(WRITE "${_source}/producers/kernel.txt" "kernel input\n")
file(WRITE "${_source}/producers/handler.txt" "handler input\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -G Ninja -S "${_source}" -B "${_build}"
  "-DAROS_RUNTIME_HELPER=${_cmake_dir}/AROSRuntime.cmake" COMMAND_ERROR_IS_FATAL ANY)
function(check_build)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target boot-modules
    COMMAND_ERROR_IS_FATAL ANY)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${_source}/producers/kernel.txt"
    "${_build}/runtime/boot/kernel" COMMAND_ERROR_IS_FATAL ANY)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${_source}/producers/handler.txt"
    "${_build}/runtime/L/differently-named-handler" COMMAND_ERROR_IS_FATAL ANY)
endfunction()
check_build()
file(TIMESTAMP "${_build}/runtime/boot/kernel" _before "%s")
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1 COMMAND_ERROR_IS_FATAL ANY)
check_build()
file(TIMESTAMP "${_build}/runtime/boot/kernel" _after "%s")
if(NOT _before STREQUAL _after)
  message(FATAL_ERROR "Unchanged module set rebuilt its outputs")
endif()
file(APPEND "${_source}/producers/kernel.txt" "updated kernel\n")
check_build()
file(REMOVE "${_build}/runtime/L/differently-named-handler")
check_build()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${_build}" --target incomplete
  RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "Missing native runtime producers: stale")
  message(FATAL_ERROR "An existing unowned file was accepted as native: ${_out}${_err}")
endif()
message(STATUS "Runtime module producer, ordering, rebuild and partial-profile checks passed")
