include_guard(GLOBAL)

function(_aros_scan_manifest_directory directory out_var)
  # Prune before descending, rather than recursively scanning downloaded/build
  # trees and filtering their filenames afterwards. Never follow directory links.
  get_filename_component(_name "${directory}" NAME)
  if(NOT directory STREQUAL _manifest_source_root AND
    (_name MATCHES "^\\." OR _name IN_LIST _manifest_ignored_dirs
     OR IS_SYMLINK "${directory}" OR directory STREQUAL CMAKE_BINARY_DIR
     OR EXISTS "${directory}/CMakeCache.txt" OR EXISTS "${directory}/CMakeFiles"))
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()
  file(GLOB _entries CONFIGURE_DEPENDS LIST_DIRECTORIES TRUE "${directory}/[!.]*")
  set(_manifests)
  foreach(_entry IN LISTS _entries)
    if(IS_DIRECTORY "${_entry}")
      _aros_scan_manifest_directory("${_entry}" _child_manifests)
      list(APPEND _manifests ${_child_manifests})
    elseif(_entry STREQUAL "${directory}/mmakefile.src"
       OR (_entry STREQUAL "${directory}/mmakefile" AND NOT EXISTS "${directory}/mmakefile.src"))
      list(APPEND _manifests "${_entry}")
    endif()
  endforeach()
  set(${out_var} "${_manifests}" PARENT_SCOPE)
endfunction()

function(aros_find_mmake_manifest directory out_var)
  foreach(_name IN ITEMS mmakefile.src mmakefile)
    if(EXISTS "${directory}/${_name}")
      set(${out_var} "${directory}/${_name}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  message(FATAL_ERROR "No source mmake manifest in ${directory}")
endfunction()

# A directory inventory detects additions/removals; configure dependencies also
# detect edits to the files read as metadata. No source-directory allowlist.
function(aros_collect_mmake_manifests out_var)
  cmake_parse_arguments(PARSE_ARGV 1 MANIFEST "" "SOURCE_DIR;IGNORE_FILE" "")
  if(MANIFEST_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "Unexpected manifest discovery arguments: ${MANIFEST_UNPARSED_ARGUMENTS}")
  endif()
  if(NOT MANIFEST_SOURCE_DIR)
    set(MANIFEST_SOURCE_DIR "${CMAKE_SOURCE_DIR}")
  endif()
  get_filename_component(_manifest_source_root "${MANIFEST_SOURCE_DIR}" ABSOLUTE
    BASE_DIR "${CMAKE_SOURCE_DIR}")
  if(NOT IS_DIRECTORY "${_manifest_source_root}")
    message(FATAL_ERROR "Manifest source directory does not exist: ${_manifest_source_root}")
  endif()
  if(NOT MANIFEST_IGNORE_FILE)
    set(MANIFEST_IGNORE_FILE "${_manifest_source_root}/mmake.config.in")
  endif()
  set(_manifest_ignored_dirs)
  if(EXISTS "${MANIFEST_IGNORE_FILE}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${MANIFEST_IGNORE_FILE}")
    file(STRINGS "${MANIFEST_IGNORE_FILE}" _ignore_lines REGEX "^[ \t]*ignoredir[ \t]+")
    foreach(_line IN LISTS _ignore_lines)
      if(_line MATCHES "^[ \t]*ignoredir[ \t]+([^ \t@]+)")
        list(APPEND _manifest_ignored_dirs "${CMAKE_MATCH_1}")
      endif()
    endforeach()
  endif()
  _aros_scan_manifest_directory("${_manifest_source_root}" _manifests)
  list(SORT _manifests)
  if(_manifests)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_manifests})
  endif()
  set(${out_var} "${_manifests}" PARENT_SCOPE)
endfunction()

# The first discovery slice covers the common single, unconditional genmodule
# producer. Source lists, includes and arch overrides remain the module parser's
# responsibility. Do not silently choose a branch or recipe in ambiguous files.
function(aros_discover_genmodule_manifests out_var)
  cmake_parse_arguments(PARSE_ARGV 1 DISCOVER "" "" "MANIFESTS;MODULE_NAMES")
  set(_modules)
  foreach(_manifest IN LISTS DISCOVER_MANIFESTS)
    _aros_read_mmake_logical_lines("${_manifest}" _lines)
    set(_rule_count 0)
    set(_conditional_depth 0)
    set(_conditional_module FALSE)
    foreach(_line IN LISTS _lines)
      if(_line MATCHES "^if(eq|neq|def|ndef)[ \t(]")
        math(EXPR _conditional_depth "${_conditional_depth} + 1")
      elseif(_line STREQUAL "endif")
        math(EXPR _conditional_depth "${_conditional_depth} - 1")
      elseif(_line MATCHES "^%build_module[^ \t]*[ \t]+")
        math(EXPR _rule_count "${_rule_count} + 1")
        if(_conditional_depth GREATER 0)
          set(_conditional_module TRUE)
        endif()
      endif()
    endforeach()
    if(_rule_count EQUAL 0)
      continue()
    endif()
    if(NOT _rule_count EQUAL 1 OR _conditional_module)
      message(FATAL_ERROR "Manifest auto-discovery needs explicit rule selection for ${_manifest}")
    endif()
    get_filename_component(_dir "${_manifest}" DIRECTORY)
    file(RELATIVE_PATH _path "${CMAKE_SOURCE_DIR}" "${_dir}")
    _aros_extract_mmake_build_module_metadata("${_manifest}" "${_path}" _module)
    if(DISCOVER_MODULE_NAMES AND NOT _module_MODULE_NAME IN_LIST DISCOVER_MODULE_NAMES)
      continue()
    endif()
    if(NOT _module_MMAKE_NAME)
      message(FATAL_ERROR "Discovered module has no mmake identity: ${_manifest}")
    endif()
    list(APPEND _modules "${_path}|${_module_MMAKE_NAME}|${_module_MODULE_NAME}|${_module_MODULE_TYPE}")
  endforeach()
  set(${out_var} "${_modules}" PARENT_SCOPE)
endfunction()
