include_guard(GLOBAL)

# Split macro arguments before expansion. Whitespace or key=value text inside
# a Make call is part of its value, not another macro argument. Discovery only
# expands identity fields; source/flag expressions belong to the build parser.
function(_aros_mmake_argument_tokens args prefix)
  set(${prefix}_VALID FALSE PARENT_SCOPE)
  set(_tokens)
  set(_token "")
  set(_quote "")
  set(_depth 0)
  set(_escaped FALSE)
  set(_previous "")
  string(LENGTH "${args}" _length)
  set(_index 0)
  while(_index LESS _length)
    string(SUBSTRING "${args}" ${_index} 1 _char)
    math(EXPR _index "${_index} + 1")
    if(_depth GREATER 0)
      if(_char STREQUAL "(")
        math(EXPR _depth "${_depth} + 1")
      elseif(_char STREQUAL ")")
        math(EXPR _depth "${_depth} - 1")
      endif()
    elseif(_escaped)
      set(_escaped FALSE)
    elseif(_char STREQUAL "\\")
      set(_escaped TRUE)
    elseif(_previous STREQUAL "$" AND _char STREQUAL "(")
      set(_depth 1)
    elseif(NOT _quote STREQUAL "")
      if(_char STREQUAL _quote)
        set(_quote "")
      endif()
    elseif(_char STREQUAL "\"" OR _char STREQUAL "'")
      set(_quote "${_char}")
    elseif(_char MATCHES "[ \t\r\n]")
      if(NOT _token STREQUAL "")
        string(REPLACE ";" "\\;" _token "${_token}")
        list(APPEND _tokens "${_token}")
        set(_token "")
      endif()
      set(_previous "")
      continue()
    endif()
    string(APPEND _token "${_char}")
    set(_previous "${_char}")
  endwhile()
  if(_depth GREATER 0 OR NOT _quote STREQUAL "" OR _escaped)
    set(${prefix}_ERROR "Unbalanced program discovery arguments: ${args}" PARENT_SCOPE)
    return()
  endif()
  if(NOT _token STREQUAL "")
    string(REPLACE ";" "\\;" _token "${_token}")
    list(APPEND _tokens "${_token}")
  endif()
  set(${prefix}_VALID TRUE PARENT_SCOPE)
  set(${prefix}_TOKENS "${_tokens}" PARENT_SCOPE)
endfunction()

function(_aros_mmake_raw_arguments args prefix)
  set(${prefix}_VALID FALSE PARENT_SCOPE)
  _aros_mmake_argument_tokens("${args}" _args)
  if(NOT _args_VALID)
    set(${prefix}_ERROR "${_args_ERROR}" PARENT_SCOPE)
    return()
  endif()
  set(_keys)
  set(_key "")
  foreach(_token IN LISTS _args_TOKENS)
    if(_token MATCHES "^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")
      set(_key "${CMAKE_MATCH_1}")
      set(_value "${CMAKE_MATCH_2}")
      if(_key IN_LIST _keys)
        set(${prefix}_ERROR "Duplicate rule argument ${_key}" PARENT_SCOPE)
        return()
      endif()
      list(APPEND _keys "${_key}")
      set(_value_${_key} "${_value}")
    elseif(_key)
      string(APPEND _value_${_key} " ${_token}")
    else()
      set(${prefix}_ERROR "Program discovery requires literal argument keys: ${args}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  foreach(_key IN LISTS _keys)
    set(${prefix}_${_key} "${_value_${_key}}" PARENT_SCOPE)
  endforeach()
  set(${prefix}_KEYS "${_keys}" PARENT_SCOPE)
  set(${prefix}_VALID TRUE PARENT_SCOPE)
endfunction()

function(_aros_mmake_graph_arguments args prefix)
  _aros_mmake_raw_arguments("${args}" _args)
  if(NOT _args_VALID)
    message(FATAL_ERROR "${_args_ERROR}")
  endif()
  foreach(_key IN ITEMS mmake compiler)
    set(_value "")
    if(_key IN_LIST _args_KEYS)
      _aros_expand_make_tokens("${_args_${_key}}" _expanded)
      if(_expanded MATCHES "\\$|@[^@ \t]+@")
        message(FATAL_ERROR "Unresolved program discovery ${_key}: ${_args_${_key}} -> ${_expanded}")
      endif()
      separate_arguments(_value UNIX_COMMAND "${_expanded}")
      list(LENGTH _value _count)
      if(NOT _count EQUAL 1)
        message(FATAL_ERROR "Expected one program discovery ${_key}: ${_expanded}")
      endif()
    elseif(_key STREQUAL mmake)
      message(FATAL_ERROR "Program discovery requires an mmake identity: ${args}")
    endif()
    set(${prefix}_${_key} "${_value}" PARENT_SCOPE)
  endforeach()
endfunction()
