include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSNativeConfig.cmake")

# Read configuration assignments in include order, without interpreting recipes.
# Recursive values remain expressions; := and += on simple values snapshot now.
function(_aros_read_config_assignments path)
  if(path IN_LIST _config_stack)
    message(FATAL_ERROR "Recursive configuration include: ${_config_stack};${path}")
  endif()
  list(APPEND _config_stack "${path}")
  list(APPEND _config_inputs "${path}")
  # file(STRINGS) splits legacy non-UTF-8 copyright comments into spurious
  # declarations. Read physical lines before joining Make continuations.
  file(READ "${path}" _text)
  string(REPLACE "\r" "" _text "${_text}")
  string(REGEX REPLACE "\\\\\n[ \t]*" " " _text "${_text}")
  string(REPLACE ";" "\\;" _text "${_text}")
  string(REPLACE "\n" ";" _lines "${_text}")
  set(_conditions)
  foreach(_line IN LISTS _lines)
    string(STRIP "${_line}" _line)
    string(REGEX REPLACE "[ \t]+#.*$" "" _line "${_line}")
    if(_line STREQUAL "" OR _line MATCHES "^#")
      continue()
    endif()
    if(ARGV1 STREQUAL PRELUDE AND _line MATCHES "^-?include[ \t]")
      break()
    endif()
    if(_line MATCHES "^ifn?eq[ \t]*\\(.*\\)$")
      _aros_condition_stack_is_active("${_conditions}" _active)
      if(_active)
        _aros_expand_make_tokens("${_line}" _condition)
        if(_condition MATCHES "\\$")
          message(FATAL_ERROR "Unresolved configuration condition in ${path}: ${_line}")
        endif()
        _aros_evaluate_mmake_condition("${_condition}" _active)
      endif()
      list(APPEND _conditions "${_active}")
      continue()
    elseif(_line STREQUAL else)
      if("${_conditions}" STREQUAL "")
        message(FATAL_ERROR "Unmatched configuration else in ${path}")
      endif()
      list(POP_BACK _conditions _active)
      if(_active)
        list(APPEND _conditions FALSE)
      else()
        list(APPEND _conditions TRUE)
      endif()
      continue()
    elseif(_line STREQUAL endif)
      if("${_conditions}" STREQUAL "")
        message(FATAL_ERROR "Unmatched configuration endif in ${path}")
      endif()
      list(POP_BACK _conditions)
      continue()
    endif()
    _aros_condition_stack_is_active("${_conditions}" _active)
    if(NOT _active)
      continue()
    endif()
    if(_line MATCHES "^(-?include)[ \t]+(.*)$")
      set(_mode "${CMAKE_MATCH_1}")
      _aros_expand_make_tokens("${CMAKE_MATCH_2}" _includes)
      separate_arguments(_includes UNIX_COMMAND "${_includes}")
      foreach(_include IN LISTS _includes)
        get_filename_component(_include "${_include}" ABSOLUTE BASE_DIR "${AROS_CONFIG_BUILD_DIR}")
        if(_include MATCHES "[$%*?]")
          message(FATAL_ERROR "Unsupported configuration include: ${_include}")
        endif()
        if(_mode STREQUAL "-include")
          list(APPEND _config_optional_inputs "${_include}")
        endif()
        if(EXISTS "${_include}")
          _aros_read_config_assignments("${_include}")
        elseif(_mode STREQUAL include)
          message(FATAL_ERROR "Missing configuration include: ${_include}")
        endif()
      endforeach()
    elseif(_line MATCHES "^(export[ \t]+)?([A-Za-z0-9_-]+)[ \t]*(\\+=|:=|\\?=|=)[ \t]*(.*)$")
      set(_name "${CMAKE_MATCH_2}")
      set(_mode "${CMAKE_MATCH_3}")
      set(_value "${CMAKE_MATCH_4}")
      if(_name IN_LIST _config_protected OR
         (_mode STREQUAL "?=" AND DEFINED _AROS_MMAKE_VAR_${_name}))
        continue()
      endif()
      if(_value MATCHES "\\$\\(shell[ \t]")
        # Configuration PATH/VPATH shell helpers are not used by this native
        # path. Keep an unexpandable marker so a future consumer fails closed.
        set(_value "$<unsupported-config-shell>")
      endif()
      if(_mode STREQUAL ":=" OR (_mode STREQUAL "+=" AND _config_simple_${_name}))
        _aros_expand_make_tokens("${_value}" _value)
      endif()
      if(_mode STREQUAL "+=" AND DEFINED _AROS_MMAKE_VAR_${_name})
        string(APPEND _AROS_MMAKE_VAR_${_name} " ${_value}")
      else()
        set(_AROS_MMAKE_VAR_${_name} "${_value}")
        set(_config_simple_${_name} FALSE)
        if(_mode STREQUAL ":=")
          set(_config_simple_${_name} TRUE)
        endif()
      endif()
      list(APPEND _config_keys "${_name}")
    elseif(ARGV1 STREQUAL PRELUDE AND _line MATCHES "^[^:]+:[^=]*$")
      continue()
    elseif(_line MATCHES "^[.](SUFFIXES|PHONY)[ \t]*:")
      continue()
    elseif(NOT _line MATCHES "^export[ \t]+[A-Za-z0-9_ \t-]+$")
      message(FATAL_ERROR "Unsupported configuration declaration in ${path}: ${_line}")
    endif()
  endforeach()
  if(NOT "${_conditions}" STREQUAL "")
    message(FATAL_ERROR "Unclosed configuration condition in ${path}")
  endif()
  list(REMOVE_DUPLICATES _config_keys)
  foreach(_key IN LISTS _config_keys)
    set(_AROS_MMAKE_VAR_${_key} "${_AROS_MMAKE_VAR_${_key}}" PARENT_SCOPE)
    set(_config_simple_${_key} "${_config_simple_${_key}}" PARENT_SCOPE)
  endforeach()
  set(_config_keys "${_config_keys}" PARENT_SCOPE)
  set(_config_inputs "${_config_inputs}" PARENT_SCOPE)
  set(_config_optional_inputs "${_config_optional_inputs}" PARENT_SCOPE)
endfunction()

function(_aros_load_program_config)
  # Partial synthetic profiles still use the older individual-value reader.
  # The prepared system snapshot has the upstream configuration entrypoint.
  if(NOT EXISTS "${AROS_SOURCE_DIR}/config/aros.cfg" OR
     NOT EXISTS "${AROS_CONFIG_BUILD_DIR}/config/make.cfg")
    return()
  endif()
  get_cmake_property(_variables VARIABLES)
  set(_overrides)
  foreach(_variable IN LISTS _variables)
    if(_variable MATCHES "^_AROS_MMAKE_VAR_(.+)$")
      set(_key "${CMAKE_MATCH_1}")
      list(APPEND _overrides "${_key}")
      set(_override_${_key} "${${_variable}}")
      unset(${_variable})
    endif()
  endforeach()
  set(_AROS_MMAKE_CONFIG_SNAPSHOT TRUE)
  set(_AROS_MMAKE_VAR_TOP "${AROS_CONFIG_BUILD_DIR}")
  set(_AROS_MMAKE_VAR_SRCDIR "${AROS_SOURCE_DIR}")
  set(_AROS_MMAKE_VAR_AROS_TARGET_ARCH "${AROS_MODULE_CONTEXT_ARCH}")
  set(_AROS_MMAKE_VAR_AROS_TARGET_CPU "${AROS_MODULE_CONTEXT_CPU}")
  set(_config_protected TOP SRCDIR AROS_TARGET_ARCH AROS_TARGET_CPU)
  set(_config_keys "${_config_protected}")
  _aros_native_config(_native)
  foreach(_key IN LISTS _native_KEYS)
    if(_key IN_LIST _config_protected)
      message(FATAL_ERROR "Native configuration cannot override build context ${_key}")
    endif()
    set(_AROS_MMAKE_VAR_${_key} "${_native_VALUE_${_key}}")
    list(APPEND _config_protected "${_key}")
    list(APPEND _config_keys "${_key}")
  endforeach()
  set(_config_inputs ${AROS_NATIVE_CONFIG_FILE})
  set(_config_optional_inputs)
  if(EXISTS "${AROS_CONFIG_BUILD_DIR}/Makefile")
    _aros_read_config_assignments("${AROS_CONFIG_BUILD_DIR}/Makefile" PRELUDE)
  endif()
  _aros_read_config_assignments("${AROS_SOURCE_DIR}/config/aros.cfg")

  # Keep configuration includes rooted in the reference snapshot while reading
  # it, then rebase its derived paths onto the caller's native output roots.
  set(_path_overrides)
  foreach(_key IN LISTS _overrides)
    if(IS_ABSOLUTE "${_AROS_MMAKE_VAR_${_key}}" AND IS_ABSOLUTE "${_override_${_key}}")
      list(APPEND _path_overrides "${_AROS_MMAKE_VAR_${_key}}|${_override_${_key}}")
    endif()
  endforeach()
  list(SORT _path_overrides ORDER DESCENDING)
  foreach(_key IN LISTS _config_keys)
    set(_value "${_AROS_MMAKE_VAR_${_key}}")
    foreach(_pair IN LISTS _path_overrides)
      string(REPLACE "|" ";" _pair "${_pair}")
      list(GET _pair 0 _old)
      list(GET _pair 1 _new)
      string(REPLACE "${_old}" "${_new}" _value "${_value}")
    endforeach()
    set(_AROS_MMAKE_VAR_${_key} "${_value}" PARENT_SCOPE)
  endforeach()
  foreach(_key IN LISTS _overrides)
    set(_AROS_MMAKE_VAR_${_key} "${_override_${_key}}" PARENT_SCOPE)
  endforeach()
  list(REMOVE_DUPLICATES _config_inputs)
  set(MMAKE_PROGRAM_CONFIG_INPUTS "${_config_inputs};${CMAKE_CURRENT_FUNCTION_LIST_FILE}" PARENT_SCOPE)
  set(MMAKE_PROGRAM_CONFIG_OPTIONAL_INPUTS "${_config_optional_inputs}" PARENT_SCOPE)
  set(_AROS_MMAKE_CONFIG_SNAPSHOT TRUE PARENT_SCOPE)
endfunction()
