include_guard(GLOBAL)

function(_aros_static_wildcard_source path kind)
  if(_AROS_WILDCARD_SOURCE_VALIDATOR)
    cmake_language(CALL "${_AROS_WILDCARD_SOURCE_VALIDATOR}" "${path}" "${kind}")
  else()
    _aros_static_owned_source("${path}")
  endif()
endfunction()

# Translate the upstream regular-file-only helper, not arbitrary shell code.
# Absolute patterns require a consumer-specific source ownership validator.
function(_aros_expand_static_wildcard input out_value out_changed)
  set(${out_value} "${input}" PARENT_SCOPE)
  set(${out_changed} FALSE PARENT_SCOPE)
  _aros_extract_make_call("${input}" call _before _body _after)
  if(_body STREQUAL "")
    return()
  endif()
  string(REGEX REPLACE "^call[ \t]+" "" _body "${_body}")
  _aros_split_make_arguments("${_body}" _arguments)
  list(GET _arguments 0 _function)
  string(STRIP "${_function}" _function)
  if(NOT _function STREQUAL "WILDCARD")
    return()
  endif()
  list(LENGTH _arguments _count)
  if(NOT _count EQUAL 2)
    message(FATAL_ERROR "Unsupported static WILDCARD arguments: ${_body}")
  endif()
  list(GET _arguments 1 _patterns)
  _aros_expand_make_tokens("${_patterns}" _patterns)

  set(_AROS_MMAKE_VAR_SRCDIR AROS_WILDCARD_SOURCE)
  set(_AROS_MMAKE_VAR_CURDIR AROS_WILDCARD_DIRECTORY)
  set(_AROS_MMAKE_VAR_1 AROS_WILDCARD_PATTERN)
  if(DEFINED _AROS_MMAKE_VAR_WILDCARD)
    set(_definition "${_AROS_MMAKE_VAR_WILDCARD}")
  else()
    _aros_read_config_value(WILDCARD _definition)
  endif()
  _aros_expand_make_tokens("${_definition}" _definition)
  string(REGEX REPLACE "[ \t]+" " " _definition "${_definition}")
  if(NOT _definition STREQUAL [=[$(shell cd AROS_WILDCARD_SOURCE/AROS_WILDCARD_DIRECTORY; for file in AROS_WILDCARD_PATTERN; do if [ -f $$file ]; then printf "%s" "$$file "; fi; done)]=])
    message(FATAL_ERROR "Unsupported static WILDCARD definition: ${_definition}")
  endif()
  if(AROS_LEGACY_BUILD_DIR)
    # START LEGACY: track the configuration bridge supplying this helper.
    file(GLOB _configs CONFIGURE_DEPENDS
      "${AROS_LEGACY_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/*.cfg"
      "${AROS_LEGACY_BUILD_DIR}/config/*.cfg")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_configs})
    # END LEGACY
  endif()
  if(_patterns MATCHES "[;$%|&<>`\\\\\r\n\"']|\\[|\\]")
    message(FATAL_ERROR "Unsupported static WILDCARD pattern: ${_patterns}")
  endif()
  separate_arguments(_patterns UNIX_COMMAND "${_patterns}")
  set(_result)
  foreach(_pattern IN LISTS _patterns)
    if((IS_ABSOLUTE "${_pattern}" AND NOT _AROS_WILDCARD_SOURCE_VALIDATOR)
       OR _pattern MATCHES "(^|/)\\.\\.(/|$)")
      message(FATAL_ERROR "Static WILDCARD requires a source-relative pattern: ${_pattern}")
    endif()
    get_filename_component(_directory "${_pattern}" DIRECTORY)
    get_filename_component(_name "${_pattern}" NAME)
    if(_directory MATCHES "[*?]" OR _name STREQUAL "")
      message(FATAL_ERROR "Static WILDCARD requires a literal source directory: ${_pattern}")
    endif()
    set(_base "${CMAKE_SOURCE_DIR}/${_AROS_MMAKE_CONTEXT_CURDIR}")
    if(IS_ABSOLUTE "${_pattern}")
      set(_source_directory "${_directory}")
      set(_source_pattern "${_pattern}")
    else()
      set(_source_directory "${_base}/${_directory}")
      set(_source_pattern "${_base}/${_pattern}")
    endif()
    _aros_static_wildcard_source("${_source_directory}" DIRECTORY)
    # Exclude shell-hidden entries from the inventory itself, so adding IDE
    # state does not cause regeneration. A leading '*' may match no bytes.
    set(_globs "${_source_pattern}")
    if(_name MATCHES "^\\*(.*)$")
      set(_suffix "${CMAKE_MATCH_1}")
      set(_globs "${_source_directory}/[!.]*${_suffix}")
      if(NOT _suffix STREQUAL "" AND NOT _suffix MATCHES "^[.*?]")
        list(APPEND _globs "${_source_directory}/${_suffix}")
      elseif(_suffix MATCHES "^[*?]")
        message(FATAL_ERROR "Unsupported static WILDCARD leading glob sequence: ${_pattern}")
      endif()
    elseif(_name MATCHES "^\\?(.*)$")
      set(_globs "${_source_directory}/[!.]${CMAKE_MATCH_1}")
    endif()
    file(GLOB _files CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE ${_globs})
    foreach(_file IN LISTS _files)
      if(NOT EXISTS "${_file}" OR _file MATCHES "[ \t;$%*?\"'\\\\\r\n]|\\[|\\]")
        message(FATAL_ERROR "Unsupported static WILDCARD source: ${_file}")
      endif()
      _aros_static_wildcard_source("${_file}" FILE)
      if(IS_ABSOLUTE "${_pattern}")
        set(_relative "${_file}")
      else()
        file(RELATIVE_PATH _relative "${_base}" "${_file}")
      endif()
      list(APPEND _result "${_relative}")
    endforeach()
  endforeach()
  list(JOIN _result " " _result)
  set(${out_value} "${_before}${_result}${_after}" PARENT_SCOPE)
  set(${out_changed} TRUE PARENT_SCOPE)
endfunction()
