include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSFetchTargets.cmake")

function(_aros_copy_include_defaults out_var)
  file(SHA256 "${CMAKE_SOURCE_DIR}/config/make.tmpl" _hash)
  get_property(_definition GLOBAL PROPERTY "AROS_COPY_INCLUDES_DEFAULT_${_hash}")
  if(NOT _definition)
    _aros_read_mmake_logical_lines("${CMAKE_SOURCE_DIR}/config/make.tmpl" _template)
    set(_count 0)
    foreach(_line IN LISTS _template)
      if(_line MATCHES "^%define copy_includes[ \t]+(.*)$")
        set(_definition "${CMAKE_MATCH_1}")
        math(EXPR _count "${_count} + 1")
      endif()
    endforeach()
    if(NOT _count EQUAL 1)
      message(FATAL_ERROR "Expected one copy_includes definition in config/make.tmpl")
    endif()
    # Cache syntax only: INCLUDE_FILES must expand at each declaration.
    set_property(GLOBAL PROPERTY "AROS_COPY_INCLUDES_DEFAULT_${_hash}" "${_definition}")
  endif()
  set(${out_var} "${_definition}" PARENT_SCOPE)
endfunction()

# Discover identities without expanding filesystem expressions before fetch.
function(_aros_collect_copy_include_identity kind args prefix)
  set(${prefix}_FIELDS "" PARENT_SCOPE)
  if(NOT kind STREQUAL "copy_includes")
    return()
  endif()
  _aros_copy_include_defaults(_definition)
  _aros_mmake_raw_arguments("${args}" _raw)
  _aros_mmake_raw_arguments("${_definition}" _default)
  if(NOT _raw_VALID OR NOT _default_VALID)
    message(FATAL_ERROR "Unsupported copy_includes identity arguments: ${args}")
  endif()
  if(NOT "mmake" IN_LIST _raw_KEYS)
    set(_raw_mmake "${_default_mmake}")
  endif()
  _aros_mmake_macro_arguments("mmake=${_raw_mmake}" _identity)
  if(_identity_mmake MATCHES "[$%;]|@[^@ \t]+@" OR _identity_mmake STREQUAL "")
    message(FATAL_ERROR "Unresolved copy_includes identity: ${_identity_mmake}")
  endif()
  if(_AROS_DISCOVER_ALL_LOCAL_INCLUDES OR _identity_mmake STREQUAL _AROS_SELECTED_INCLUDES)
    set(${prefix}_FIELDS mmake PARENT_SCOPE)
    set(${prefix}_mmake "${_identity_mmake}" PARENT_SCOPE)
  endif()
endfunction()

# Preserve the linklib-local staging scope while replacing the old header glob.
# Named dependencies of each declaration still use the shared native registry.
function(aros_finalize_mmake_linklib_headers)
  set_property(GLOBAL PROPERTY AROS_LINKLIB_HEADERS_SCHEDULED FALSE)
  set(_AROS_MMAKE_VAR_TOP "${CMAKE_BINARY_DIR}")
  set(_AROS_MMAKE_VAR_TARGETDIR "${AROS_NATIVE_OUTPUT_ROOT}")
  set(_AROS_MMAKE_VAR_GENDIR "${AROS_NATIVE_OUTPUT_ROOT}/gen")
  get_property(_libraries GLOBAL PROPERTY AROS_REGISTERED_LINKLIB_TARGETS)
  foreach(_library IN LISTS _libraries)
    get_target_property(_manifest "${_library}" AROS_LINKLIB_HEADER_MANIFEST)
    get_target_property(_finished "${_library}" AROS_LINKLIB_HEADERS_REGISTERED)
    if(NOT _manifest OR _finished)
      continue()
    endif()
    set_property(TARGET "${_library}" PROPERTY AROS_LINKLIB_HEADERS_REGISTERED TRUE)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_manifest}")
    # Match the old stager's local declaration scope, without evaluating
    # unrelated program/module conditions when there are no headers to copy.
    file(STRINGS "${_manifest}" _declarations REGEX "^[ \t]*%copy_includes([ \t]|$)")
    set(_identities)
    if(_declarations)
      set(_AROS_DISCOVER_ALL_LOCAL_INCLUDES TRUE)
      set(_AROS_RULE_MACRO_COLLECTOR _aros_collect_copy_include_identity)
      _aros_collect_mmake_rules("${_manifest}" _rules)
      set(_AROS_DISCOVER_ALL_LOCAL_INCLUDES FALSE)
      foreach(_id IN LISTS _rules_MACROS)
        list(APPEND _identities "${_rules_MACRO_${_id}_mmake}")
      endforeach()
    endif()
    list(REMOVE_DUPLICATES _identities)
    set(_outputs)
    set(_reports)
    set(_python "")
    # A library can own fetched sources without declaring any local headers.
    # Preserve cross-manifest augmentations of the library identity as well.
    get_target_property(_mmake "${_library}" AROS_LINKLIB_MMAKE_NAME)
    _aros_static_manifest_candidates("${_mmake}" _candidates)
    list(APPEND _candidates "${_manifest}")
    list(REMOVE_DUPLICATES _candidates)
    set(_AROS_RULE_MACRO_COLLECTOR _aros_prerequisite_macro_identity)
    set(_edges)
    foreach(_candidate IN LISTS _candidates)
      _aros_program_metadata_prerequisites("${_candidate}" "${_mmake}" "" _part)
      list(APPEND _edges ${_part})
      foreach(_node IN LISTS _part_STATIC_NODES)
        aros_collect_mmake_static_files("${_candidate}" "${_node}" _static STRICT LOCAL_NODE)
      endforeach()
    endforeach()
    list(REMOVE_DUPLICATES _edges)
    set(_fetches)
    foreach(_edge IN LISTS _edges)
      _aros_program_fetch_prerequisites("${_edge}" "${_mmake}" _part)
      list(APPEND _fetches ${_part})
    endforeach()
    list(REMOVE_DUPLICATES _fetches)
    set(_ready TRUE)
    foreach(_fetch IN LISTS _fetches)
      get_target_property(_prepared "${_fetch}" AROS_FETCH_READY)
      get_target_property(_report "${_fetch}" AROS_FETCH_REPORT)
      get_target_property(_python "${_fetch}" AROS_FETCH_PYTHON)
      list(APPEND _reports "${_report}")
      if(NOT _prepared)
        set(_ready FALSE)
      endif()
    endforeach()
    if(_fetches)
      add_dependencies("${_library}" ${_fetches})
      if(NOT _ready)
        set(_prepare "${_library}-prepare-sources")
        add_custom_target("${_prepare}"
          COMMAND "${CMAKE_COMMAND}" -E echo
            "${_library}: native sources prepared; run the build again to configure their consumers"
          COMMAND "${CMAKE_COMMAND}" -E false DEPENDS ${_fetches} VERBATIM)
        set_property(TARGET "${_prepare}" PROPERTY FOLDER "aros/internal/fetch")
        add_dependencies("${_library}" "${_prepare}")
        add_dependencies("${_library}-includes" "${_prepare}")
      endif()
    endif()
    foreach(_identity IN LISTS _identities)
      string(SHA256 _key "${_manifest}|${_identity}")
      set(_target "aros-linklib-headers-${_key}")
      if(NOT TARGET "${_target}")
        aros_add_mmake_include_target("${_target}"
          MANIFEST "${_manifest}" MMAKE_NAME "${_identity}")
      endif()
      add_dependencies("${_library}-includes" "${_target}")
      add_dependencies("${_library}" "${_target}")
      get_target_property(_stamp "${_target}" AROS_MODULE_INTERFACE_STAMP)
      if(_stamp)
        list(APPEND _outputs "${_stamp}")
      endif()
      get_target_property(_fetch_reports "${_target}" AROS_INCLUDE_FETCH_REPORTS)
      if(_fetch_reports)
        list(APPEND _reports ${_fetch_reports})
        get_target_property(_python "${_target}" AROS_INCLUDE_FETCH_PYTHON)
      endif()
    endforeach()
    list(REMOVE_DUPLICATES _reports)
    set(_context "${CMAKE_BINARY_DIR}/linklibs/${_library}-fetch.cmake")
    set(_content "set(LINKLIB_NATIVE_TARGETDIR [==[${AROS_NATIVE_OUTPUT_ROOT}]==])\n")
    string(APPEND _content "set(LINKLIB_FETCH_REPORTS [==[${_reports}]==])\n")
    string(APPEND _content "set(LINKLIB_FETCH_PYTHON [==[${_python}]==])\n")
    file(CONFIGURE OUTPUT "${_context}" CONTENT "@_content@" @ONLY)
    set_target_properties("${_library}" PROPERTIES
      AROS_LINKLIB_FETCH_CONTEXT "${_context}" AROS_LINKLIB_FETCH_REPORTS "${_reports}")
    set_property(TARGET "${_library}" PROPERTY AROS_LINKLIB_HEADER_OUTPUTS "${_outputs}")
  endforeach()
endfunction()

function(_aros_collect_copy_includes kind args prefix)
  set(${prefix}_FIELDS "" PARENT_SCOPE)
  _aros_collect_copy_include_identity("${kind}" "${args}" _selected)
  if(NOT _selected_FIELDS)
    return()
  endif()
  _aros_copy_include_defaults(_definition)
  _aros_mmake_raw_arguments("${args}" _arg)
  _aros_mmake_raw_arguments("${_definition}" _default)
  set(_fields mmake includes path dir compiler sdk)
  foreach(_key IN LISTS _arg_KEYS _default_KEYS)
    if(NOT _key IN_LIST _fields)
      message(FATAL_ERROR "Unsupported copy_includes argument: ${_key}")
    endif()
  endforeach()
  foreach(_key IN LISTS _fields)
    if(NOT _key IN_LIST _arg_KEYS)
      if(NOT _key IN_LIST _default_KEYS OR _default_${_key} STREQUAL "/A")
        message(FATAL_ERROR "Missing copy_includes argument/default: ${_key}")
      endif()
      set(_arg_${_key} "${_default_${_key}}")
    endif()
    # An explicit value must not evaluate an unused filesystem-aware default.
    _aros_mmake_macro_arguments("${_key}=${_arg_${_key}}" _expanded)
    if(_expanded_${_key} MATCHES "[$%;]|@[^@ \t]+@")
      message(FATAL_ERROR "Unresolved copy_includes ${_key}: ${_expanded_${_key}}")
    endif()
    set(${prefix}_${_key} "${_expanded_${_key}}" PARENT_SCOPE)
  endforeach()
  _aros_expand_make_tokens("$(GENINCDIR)" _host_root)
  _aros_expand_make_tokens("$(AROS_DIR_INCLUDE)" _include_directory)
  set(${prefix}_host_root "${_host_root}" PARENT_SCOPE)
  set(${prefix}_include_directory "${_include_directory}" PARENT_SCOPE)
  list(APPEND _fields host_root include_directory)
  set(${prefix}_FIELDS "${_fields}" PARENT_SCOPE)
endfunction()

function(_aros_include_wildcard_source path kind)
  get_filename_component(_path "${path}" ABSOLUTE)
  _aros_catalog_real_path("${_path}" _real)
  if(_path STREQUAL _real)
    if(kind STREQUAL "FILE" AND _path IN_LIST _fetched_sources)
      return()
    elseif(kind STREQUAL "DIRECTORY")
      foreach(_root IN LISTS _fetched_roots)
        file(RELATIVE_PATH _relative "${_root}" "${_path}")
        if(NOT IS_ABSOLUTE "${_relative}" AND NOT _relative MATCHES "^[.][.](/|$)")
          return()
        endif()
      endforeach()
    endif()
  endif()
  _aros_static_owned_source("${_path}")
endfunction()

function(_aros_include_relative path)
  if(IS_ABSOLUTE "${path}" OR path MATCHES "(^|/)[.][.](/|$)|[ \t\r\n;$%*?|\\\\]"
     OR path MATCHES "\\[|\\]")
    message(FATAL_ERROR "Unsafe copy_includes relative path: ${path}")
  endif()
endfunction()

# A local entrypoint supports the shared default identity without pulling in
# every includes-copy declaration in the OS. Global named prerequisites use
# the inventory-wide wrapper below, retaining cross-manifest augmentations.
function(aros_add_mmake_include_target target)
  cmake_parse_arguments(ARG "" "MANIFEST;MMAKE_NAME" "STACK;DEPENDENCY_MANIFESTS" ${ARGN})
  if(NOT ARG_MANIFEST OR NOT ARG_MMAKE_NAME OR ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "aros_add_mmake_include_target requires MANIFEST and MMAKE_NAME")
  endif()
  if(ARG_MMAKE_NAME IN_LIST ARG_STACK)
    message(FATAL_ERROR "Include metadata dependency cycle: ${ARG_STACK};${ARG_MMAKE_NAME}")
  endif()
  set(_AROS_MMAKE_VAR_TOP "${CMAKE_BINARY_DIR}")
  set(_AROS_MMAKE_VAR_TARGETDIR "${AROS_NATIVE_OUTPUT_ROOT}")
  set(_AROS_MMAKE_VAR_GENDIR "${AROS_NATIVE_OUTPUT_ROOT}/gen")
  set(_AROS_SELECTED_INCLUDES "${ARG_MMAKE_NAME}")
  set(_AROS_RULE_OPTION_INCLUDES TRUE)
  set(_AROS_INCLUDE_TRANSFORMS TRUE)
  set(_dependency_manifests "${ARG_MANIFEST}" ${ARG_DEPENDENCY_MANIFESTS})
  list(REMOVE_DUPLICATES _dependency_manifests)
  set(_prerequisites)
  set(_local_manifests)
  set(_local_nodes)
  foreach(_manifest IN LISTS _dependency_manifests)
    set(_AROS_RULE_OPTION_INCLUDES TRUE)
    if(NOT _manifest STREQUAL ARG_MANIFEST)
      _aros_metadata_option_context("${_manifest}" "${ARG_MMAKE_NAME}" _AROS_RULE_OPTION_INCLUDES)
    endif()
    _aros_program_prerequisites("${_manifest}" "${ARG_MMAKE_NAME}" _edges)
    foreach(_node IN LISTS _edges_STATIC_NODES)
      _aros_mmake_is_text_transform("${_manifest}" "${_node}" _transform)
      if(NOT _transform)
        message(FATAL_ERROR "copy_includes needs support for local prerequisite recipes: ${_node}")
      endif()
      list(APPEND _local_manifests "${_manifest}")
      list(APPEND _local_nodes "${_node}")
    endforeach()
    list(APPEND _prerequisites ${_edges})
  endforeach()
  set(_AROS_RULE_OPTION_INCLUDES TRUE)
  list(REMOVE_DUPLICATES _prerequisites)
  file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/include-copies")
  set(_providers)
  set(_reports)
  set(_fetched_sources)
  set(_fetched_roots)
  set(_python "")
  set(_ready TRUE)
  # Collect the complete source closure before registering sibling generators.
  # Do not inherit authorization from a caller's unrelated include consumer.
  set(_fetches)
  foreach(_node IN LISTS _prerequisites)
    _aros_program_fetch_prerequisites("${_node}" "${ARG_STACK};${ARG_MMAKE_NAME}" _part)
    list(APPEND _fetches ${_part})
  endforeach()
  list(REMOVE_DUPLICATES _fetches)
  set(_providers ${_fetches})
  foreach(_fetch IN LISTS _fetches)
    get_target_property(_files "${_fetch}" AROS_FETCH_FILES)
    get_target_property(_report "${_fetch}" AROS_FETCH_REPORT)
    get_target_property(_prepared "${_fetch}" AROS_FETCH_READY)
    get_target_property(_python "${_fetch}" AROS_FETCH_PYTHON)
    get_target_property(_destination "${_fetch}" AROS_FETCH_DESTINATION)
    list(APPEND _reports "${_report}")
    list(APPEND _fetched_sources ${_files})
    list(APPEND _fetched_roots "${_destination}")
    if(NOT _prepared)
      set(_ready FALSE)
    endif()
  endforeach()
  if(NOT _ready)
    add_custom_target("${target}"
      COMMAND "${CMAKE_COMMAND}" -E echo
        "${target}: native sources prepared; run the build again to configure their consumers"
      COMMAND "${CMAKE_COMMAND}" -E false DEPENDS ${_providers} VERBATIM)
    set_target_properties("${target}" PROPERTIES FOLDER "aros/internal/includes"
      AROS_NATIVE_FETCH_TARGETS "${_fetches}")
    return()
  endif()
  foreach(_report IN LISTS _reports)
    execute_process(COMMAND "${_python}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/build_mmake_fetch.py"
      --verify "${_report}" COMMAND_ERROR_IS_FATAL ANY)
  endforeach()
  set(_AROS_PREREQUISITE_FETCH_TARGETS "${_fetches}")
  foreach(_node IN LISTS _prerequisites)
    _aros_register_program_prerequisite("${_node}" "${ARG_STACK};${ARG_MMAKE_NAME}" _provider)
    list(APPEND _providers ${_provider})
  endforeach()
  foreach(_manifest _node IN ZIP_LISTS _local_manifests _local_nodes)
    _aros_register_program_static_node("${_manifest}" "${_node}"
      "${ARG_STACK};${ARG_MMAKE_NAME}" _provider)
    list(APPEND _providers "${_provider}")
  endforeach()
  list(REMOVE_DUPLICATES _providers)
  set(_AROS_RULE_MACRO_COLLECTOR _aros_collect_copy_includes)
  set(_AROS_MMAKE_CALL_EXPANDER _aros_expand_static_wildcard)
  set(_AROS_WILDCARD_SOURCE_VALIDATOR _aros_include_wildcard_source)
  _aros_collect_mmake_rules("${ARG_MANIFEST}" _includes)
  get_filename_component(_source_dir "${ARG_MANIFEST}" DIRECTORY)
  set(_outputs)
  foreach(_id IN LISTS _includes_MACROS)
    foreach(_field IN ITEMS includes path dir compiler sdk host_root include_directory)
      set(_${_field} "${_includes_MACRO_${_id}_${_field}}")
    endforeach()
    if(NOT IS_ABSOLUTE "${_host_root}" OR NOT _include_directory)
      message(FATAL_ERROR "copy_includes requires configured GENINCDIR and AROS_DIR_INCLUDE")
    endif()
    _aros_include_relative("${_include_directory}")
    if(NOT _compiler MATCHES "^(target|host|kernel)$")
      message(FATAL_ERROR "Unsupported copy_includes compiler: ${_compiler}")
    endif()
    if(NOT _sdk MATCHES "^[A-Za-z0-9_+-][A-Za-z0-9_.+-]*$")
      message(FATAL_ERROR "Invalid copy_includes SDK: ${_sdk}")
    endif()
    _aros_include_relative("${_path}")
    set(_roots "${_host_root}")
    if(_compiler STREQUAL "target")
      if(_sdk STREQUAL "public")
        list(APPEND _roots "${AROS_NATIVE_INCLUDE_DIR}")
      else()
        list(APPEND _roots "${AROS_NATIVE_BUILD_SDKS_DIR}/${_sdk}/${_include_directory}")
      endif()
    endif()
    list(REMOVE_DUPLICATES _roots)
    separate_arguments(_headers UNIX_COMMAND "${_includes}")
    foreach(_header IN LISTS _headers)
      if(NOT IS_ABSOLUTE "${_header}" OR _dir STREQUAL "")
        _aros_include_relative("${_header}")
      endif()
      if(_dir STREQUAL "")
        set(_name "${_header}")
        set(_source "${_source_dir}/${_header}")
      else()
        get_filename_component(_name "${_header}" NAME)
        _aros_include_relative("${_name}")
        get_filename_component(_directory "${_dir}" ABSOLUTE BASE_DIR "${_source_dir}")
        set(_source "${_directory}/${_name}")
      endif()
      get_filename_component(_source "${_source}" ABSOLUTE)
      file(REAL_PATH "${_source}" _real_source)
      set(_fetched FALSE)
      if(NOT _source IN_LIST _fetched_sources OR NOT _real_source STREQUAL _source)
        _aros_catalog_static_input("${_source}")
        foreach(_rule IN LISTS _includes_RULES)
          if(_includes_${_rule}_METADATA)
            continue()
          endif()
          foreach(_declared IN LISTS _includes_${_rule}_TARGETS)
            get_filename_component(_declared "${_declared}" ABSOLUTE BASE_DIR "${_source_dir}")
            _aros_mmake_pattern_match("${_declared}" "${_source}" _matches _stem)
            if(_matches)
              message(FATAL_ERROR "copy_includes generated source needs a native producer: ${_source}")
            endif()
          endforeach()
        endforeach()
      else()
        set(_fetched TRUE)
      endif()
      if(NOT EXISTS "${_source}" OR IS_DIRECTORY "${_source}")
        message(FATAL_ERROR "Missing copy_includes source: ${_source}")
      endif()
      foreach(_root IN LISTS _roots)
        get_filename_component(_output "${_root}/${_path}/${_name}" ABSOLUTE)
        _aros_catalog_native_output("${_root}" "${CMAKE_BINARY_DIR}")
        _aros_catalog_native_output("${_output}" "${_root}")
        _aros_catalog_real_path("${_output}" _real_output)
        string(SHA256 _key "${_real_output}")
        get_property(_existing GLOBAL PROPERTY "AROS_INCLUDE_COPY_${_key}")
        set(_identity "${_real_source}|${_reports}")
        if(_existing AND NOT _existing STREQUAL _identity)
          message(FATAL_ERROR "Conflicting include producer for ${_output}")
        elseif(_existing)
          get_property(_existing_path GLOBAL PROPERTY "AROS_INCLUDE_COPY_PATH_${_key}")
          if(NOT _existing_path STREQUAL _output)
            message(FATAL_ERROR "Aliased include outputs are unsupported: ${_existing_path};${_output}")
          endif()
        elseif(NOT _existing)
          _aros_catalog_claim_output("${_real_output}" "${ARG_MMAKE_NAME}")
          set_property(GLOBAL PROPERTY "AROS_INCLUDE_COPY_${_key}" "${_identity}")
          set_property(GLOBAL PROPERTY "AROS_INCLUDE_COPY_PATH_${_key}" "${_output}")
          set(_context "${CMAKE_BINARY_DIR}/include-copies/${_key}.cmake")
          set(_content "")
          foreach(_field IN ITEMS source output real_output root reports python fetched)
            string(APPEND _content "set(COPY_${_field} [==[${_${_field}}]==])\n")
          endforeach()
          string(APPEND _content "set(AROS_LEGACY_BUILD_DIR [==[${AROS_LEGACY_BUILD_DIR}]==])\n")
          string(APPEND _content "set(CMAKE_SOURCE_DIR [==[${CMAKE_SOURCE_DIR}]==])\nset(CMAKE_BINARY_DIR [==[${CMAKE_BINARY_DIR}]==])\n")
          file(CONFIGURE OUTPUT "${_context}" CONTENT "@_content@" @ONLY)
          set(_builder "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/build_mmake_include.cmake")
          add_custom_command(OUTPUT "${_output}"
            COMMAND "${CMAKE_COMMAND}" "-DCONTEXT_FILE=${_context}" -P "${_builder}"
            DEPENDS "${_source}" "${_context}" "${_builder}" ${_reports}
            COMMENT "Staging manifest header ${_output}" VERBATIM)
        endif()
        list(APPEND _outputs "${_output}")
      endforeach()
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES _outputs)
  string(SHA256 _key "${target}")
  set(_stamp "${CMAKE_BINARY_DIR}/include-copies/${_key}.stamp")
  add_custom_command(OUTPUT "${_stamp}" COMMAND "${CMAKE_COMMAND}" -E touch "${_stamp}"
    DEPENDS ${_outputs} "${ARG_MANIFEST}" ${_providers} VERBATIM)
  add_custom_target("${target}" DEPENDS "${_stamp}")
  set_target_properties("${target}" PROPERTIES FOLDER "aros/internal/includes"
    AROS_MODULE_INTERFACE_STAMP "${_stamp}" AROS_INCLUDE_OUTPUTS "${_outputs}"
    AROS_NATIVE_FETCH_TARGETS "${_fetches}"
    AROS_INCLUDE_FETCH_REPORTS "${_reports}" AROS_INCLUDE_FETCH_PYTHON "${_python}")
  file(GLOB _config CONFIGURE_DEPENDS "${AROS_LEGACY_BUILD_DIR}/config/*.cfg"
    "${AROS_LEGACY_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/*.cfg")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ARG_MANIFEST}"
    "${CMAKE_SOURCE_DIR}/config/make.tmpl" ${_dependency_manifests} ${_config} ${AROS_NATIVE_CONFIG_FILE})
endfunction()

function(_aros_register_mmake_includes mmake stack out_var)
  set(_AROS_RULE_OPTION_INCLUDES TRUE)
  set(${out_var} "" PARENT_SCOPE)
  if(mmake IN_LIST stack)
    message(FATAL_ERROR "Include metadata dependency cycle: ${stack};${mmake}")
  endif()
  string(SHA256 _key "${mmake}")
  set(_target "aros-includes-${_key}")
  if(TARGET "${_target}")
    set(${out_var} "${_target}" PARENT_SCOPE)
    return()
  endif()
  _aros_static_manifest_candidates("${mmake}" _candidates)
  set(_AROS_SELECTED_INCLUDES "${mmake}")
  set(_AROS_RULE_MACRO_COLLECTOR _aros_collect_copy_include_identity)
  set(_matches)
  foreach(_manifest IN LISTS _candidates)
    file(STRINGS "${_manifest}" _has_includes REGEX "^[ \t]*%copy_includes([ \t]|$)")
    if(_has_includes)
      _aros_collect_mmake_rules("${_manifest}" _rules)
      if(NOT "${_rules_MACROS}" STREQUAL "")
        list(APPEND _matches "${_manifest}")
      endif()
    endif()
  endforeach()
  if(NOT _matches)
    return()
  endif()
  # Share every candidate's edges across the producers: a fetch requirement
  # may be declared in a different manifest from its header copies.
  set(_parts)
  foreach(_manifest IN LISTS _matches)
    string(SHA256 _part "${_manifest}")
    aros_add_mmake_include_target("${_target}-${_part}"
      MANIFEST "${_manifest}" MMAKE_NAME "${mmake}" STACK ${stack}
      DEPENDENCY_MANIFESTS ${_candidates})
    list(APPEND _parts "${_target}-${_part}")
  endforeach()
  set(_stamps)
  foreach(_part IN LISTS _parts)
    get_target_property(_stamp "${_part}" AROS_MODULE_INTERFACE_STAMP)
    if(_stamp)
      list(APPEND _stamps "${_stamp}")
    endif()
  endforeach()
  set(_stamp "${CMAKE_BINARY_DIR}/include-copies/${_key}.stamp")
  add_custom_command(OUTPUT "${_stamp}" COMMAND "${CMAKE_COMMAND}" -E touch "${_stamp}"
    DEPENDS ${_stamps} ${_parts} VERBATIM)
  add_custom_target("${_target}" DEPENDS "${_stamp}")
  _aros_native_fetch_dependencies(_fetches ${_parts})
  set_target_properties("${_target}" PROPERTIES FOLDER "aros/internal/includes"
    AROS_MODULE_INTERFACE_STAMP "${_stamp}" AROS_NATIVE_FETCH_TARGETS "${_fetches}")
  set(${out_var} "${_target}" PARENT_SCOPE)
endfunction()
