include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSFetchTargets.cmake")

# Classification only: full recipe and input validation happens at registration,
# after the owning graph has discovered and prepared its source producers.
function(_aros_mmake_is_text_transform manifest node out_var)
  set(_AROS_RULE_MACRO_COLLECTOR "")
  set(_AROS_RULE_EXPAND_RECIPES FALSE)
  _aros_collect_mmake_rules("${manifest}" _candidate)
  set(_found FALSE)
  foreach(_id IN LISTS _candidate_RULES)
    if(node IN_LIST _candidate_${_id}_TARGETS AND _candidate_${_id}_RECIPE_COUNT GREATER 0)
      math(EXPR _last "${_candidate_${_id}_RECIPE_COUNT} - 1")
      if(_candidate_${_id}_RECIPE_${_last} MATCHES "^@?\\$\\(SED\\)[ \t]")
        set(_found TRUE)
      endif()
    endif()
  endforeach()
  set(${out_var} "${_found}" PARENT_SCOPE)
endfunction()

function(_aros_transform_substitution expression)
  # Restrict sed to one substitution, never scripts that can execute commands
  # or read/write other files. Escaped delimiters need a later parser extension.
  if(expression MATCHES "[;\\\\\r\n]" OR NOT expression MATCHES "^s([/|])(.*)$")
    message(FATAL_ERROR "Unsupported text substitution: ${expression}")
  endif()
  set(_separator "${CMAKE_MATCH_1}")
  string(REPLACE "${_separator}" ";" _parts "${expression}")
  list(LENGTH _parts _count)
  if(NOT _count EQUAL 4)
    message(FATAL_ERROR "Unsupported text substitution: ${expression}")
  endif()
  list(GET _parts 1 _search)
  list(GET _parts 3 _flags)
  if(_search STREQUAL "" OR NOT _flags MATCHES "^(g)?$")
    message(FATAL_ERROR "Unsupported text substitution: ${expression}")
  endif()
endfunction()

function(_aros_transform_node node trail out_var)
  if(node IN_LIST trail)
    message(FATAL_ERROR "Cyclic text-transform prerequisites: ${trail};${node}")
  endif()
  list(APPEND trail "${node}")
  set(_matches)
  foreach(_id IN LISTS _transform_RULES)
    if(node IN_LIST _transform_${_id}_TARGETS)
      list(APPEND _matches "${_id}")
    endif()
  endforeach()
  list(LENGTH _matches _count)
  if(NOT _count EQUAL 1)
    message(FATAL_ERROR "Text transform needs one local producer for ${node}")
  endif()
  set(_entry "_transform_${_matches}")
  if(${_entry}_RECIPE_COUNT EQUAL 0)
    set(_outputs)
    if(NOT ${_entry}_DEPENDS)
      message(FATAL_ERROR "Text transform has no producer for ${node}")
    endif()
    foreach(_dep IN LISTS ${_entry}_DEPENDS)
      _aros_transform_node("${_dep}" "${trail}" _files)
      list(APPEND _outputs ${_files})
    endforeach()
    set(${out_var} "${_outputs}" PARENT_SCOPE)
    return()
  endif()
  list(LENGTH ${_entry}_TARGETS _targets)
  list(LENGTH ${_entry}_DEPENDS _inputs)
  if(NOT _targets EQUAL 1 OR NOT _inputs EQUAL 1 OR NOT IS_ABSOLUTE "${node}"
      OR node MATCHES "[$%*?;]" OR ${_entry}_RECIPE_COUNT GREATER 2)
    message(FATAL_ERROR "Unsupported text-transform targets/prerequisites: ${node}")
  endif()
  _aros_catalog_native_output("${AROS_NATIVE_OUTPUT_ROOT}" "${CMAKE_BINARY_DIR}")
  _aros_catalog_native_output("${node}" "${AROS_NATIVE_OUTPUT_ROOT}")
  _aros_catalog_real_path("${node}" _real_output)
  get_filename_component(_source "${${_entry}_DEPENDS}" ABSOLUTE BASE_DIR "${_transform_source_dir}")
  file(REAL_PATH "${_source}" _real_source)
  foreach(_id IN LISTS _transform_RULES)
    foreach(_declared IN LISTS _transform_${_id}_TARGETS)
      get_filename_component(_declared "${_declared}" ABSOLUTE BASE_DIR "${_transform_source_dir}")
      _aros_mmake_pattern_match("${_declared}" "${_source}" _match _stem)
      if(_match)
        message(FATAL_ERROR "Text transform cannot adopt a generated input: ${_source}")
      endif()
    endforeach()
  endforeach()
  set(_fetched FALSE)
  if(_source IN_LIST _transform_sources AND _source STREQUAL _real_source)
    set(_fetched TRUE)
  else()
    _aros_catalog_static_input("${_source}")
  endif()
  if(NOT EXISTS "${_source}" OR IS_DIRECTORY "${_source}")
    message(FATAL_ERROR "Missing text-transform source: ${_source}")
  endif()
  set(_directories)
  math(EXPR _last "${${_entry}_RECIPE_COUNT} - 1")
  if(_last GREATER 0)
    set(_directories "${${_entry}_DIRECTORIES}")
    if(NOT _directories)
      message(FATAL_ERROR "Unsupported text-transform setup: ${${_entry}_RECIPE_0}")
    endif()
    foreach(_dir IN LISTS _directories)
      _aros_catalog_native_output("${_dir}" "${AROS_NATIVE_OUTPUT_ROOT}")
    endforeach()
  endif()
  set(_raw "${${_entry}_RECIPE_${_last}}")
  if(NOT _raw MATCHES "^@?\\$\\(SED\\)[ \t]" OR NOT _raw MATCHES "\\$<[ \t]+>[ \t]+\\$@$")
    message(FATAL_ERROR "Unsupported text-transform recipe: ${_raw}")
  endif()
  set(_recipe "${${_entry}_EXPANDED_${_last}}")
  string(REGEX REPLACE "^@" "" _recipe "${_recipe}")
  string(FIND "${_recipe}" "${_transform_VARIABLE_SED} " _start)
  if(NOT _start EQUAL 0 OR _transform_VARIABLE_SED MATCHES "[; \t\r\n]")
    message(FATAL_ERROR "Unsupported text-transform tool: ${_transform_VARIABLE_SED}")
  endif()
  string(LENGTH "${_transform_VARIABLE_SED}" _length)
  string(SUBSTRING "${_recipe}" ${_length} -1 _arguments)
  string(REGEX REPLACE "[ \t]+\\$<[ \t]+>[ \t]+\\$@$" "" _arguments "${_arguments}")
  string(STRIP "${_arguments}" _arguments)
  set(_expressions)
  while(NOT _arguments STREQUAL "")
    if(NOT _arguments MATCHES "^-e[ \t]+'([^']*)'([ \t]+|$)(.*)$")
      message(FATAL_ERROR "Unsupported text-transform arguments: ${_arguments}")
    endif()
    set(_expression "${CMAKE_MATCH_1}")
    set(_arguments "${CMAKE_MATCH_3}")
    # Make's doubled dollars survive a single-quoted shell argument literally.
    string(REPLACE "$$" "@AROS_LITERAL_DOLLAR@" _expression "${_expression}")
    if(_expression MATCHES "\\$")
      message(FATAL_ERROR "Unresolved text-transform expression: ${_expression}")
    endif()
    string(REPLACE "@AROS_LITERAL_DOLLAR@" "$" _expression "${_expression}")
    _aros_transform_substitution("${_expression}")
    list(APPEND _expressions "${_expression}")
  endwhile()
  if(NOT _expressions)
    message(FATAL_ERROR "Text transform has no substitutions: ${node}")
  endif()
  unset(_transform_sed CACHE)
  find_program(_transform_sed NAMES "${_transform_VARIABLE_SED}" REQUIRED)
  set(_tool "${_transform_sed}")
  unset(_transform_sed CACHE)
  string(SHA256 _key "${_real_output}")
  set(_identity "${node}|${_source}|${_expressions}|${_directories}|${_transform_reports}|${_tool}")
  get_property(_existing GLOBAL PROPERTY "AROS_TEXT_TRANSFORM_${_key}")
  if(_existing AND NOT _existing STREQUAL _identity)
    message(FATAL_ERROR "Conflicting text-transform producer: ${node}")
  elseif(NOT _existing)
    _aros_catalog_claim_output("${_real_output}" "${ARG_MMAKE_NAME}")
    set_property(GLOBAL PROPERTY "AROS_TEXT_TRANSFORM_${_key}" "${_identity}")
    set(_context "${CMAKE_BINARY_DIR}/text-transforms/${_key}.cmake")
    set(_content "")
    set(_output "${node}")
    foreach(_field IN ITEMS source output real_output fetched directories tool expressions)
      string(APPEND _content "set(TRANSFORM_${_field} [==[${_${_field}}]==])\n")
    endforeach()
    foreach(_field IN ITEMS reports python)
      string(APPEND _content "set(TRANSFORM_${_field} [==[${_transform_${_field}}]==])\n")
    endforeach()
    foreach(_field IN ITEMS CMAKE_SOURCE_DIR CMAKE_BINARY_DIR AROS_LEGACY_BUILD_DIR AROS_NATIVE_OUTPUT_ROOT)
      string(APPEND _content "set(${_field} [==[${${_field}}]==])\n")
    endforeach()
    file(CONFIGURE OUTPUT "${_context}" CONTENT "@_content@" @ONLY)
    set(_builder "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/build_mmake_transform.cmake")
    set(_directory_stamps)
    foreach(_dir IN LISTS _directories)
      _aros_catalog_real_path("${_dir}" _real_dir)
      string(SHA256 _dir_key "${_real_dir}")
      set(_stamp "${CMAKE_BINARY_DIR}/text-transforms/${_dir_key}.dir.stamp")
      get_property(_dir_registered GLOBAL PROPERTY "AROS_TRANSFORM_DIRECTORY_${_dir_key}")
      if(NOT _dir_registered)
        add_custom_command(OUTPUT "${_stamp}" BYPRODUCTS "${_dir}"
          COMMAND "${CMAKE_COMMAND}" "-DCONTEXT_FILE=${_context}" "-DDIRECTORY_ONLY=${_dir}"
            "-DDIRECTORY_REAL=${_real_dir}" "-DSTAMP_FILE=${_stamp}" -P "${_builder}"
          DEPENDS "${_context}" "${_builder}" VERBATIM)
        set_property(GLOBAL PROPERTY "AROS_TRANSFORM_DIRECTORY_${_dir_key}" TRUE)
      endif()
      list(APPEND _directory_stamps "${_stamp}")
    endforeach()
    add_custom_command(OUTPUT "${node}"
      COMMAND "${CMAKE_COMMAND}" "-DCONTEXT_FILE=${_context}" -P "${_builder}"
      DEPENDS "${_source}" "${_tool}" "${_context}" "${_builder}"
        ${_transform_reports} ${ARG_FETCH_TARGETS} ${_directory_stamps}
      COMMENT "Transforming manifest text ${node}" VERBATIM)
  endif()
  set(${out_var} "${node}" PARENT_SCOPE)
endfunction()

function(aros_add_mmake_transform_target target)
  cmake_parse_arguments(ARG "" "MANIFEST;MMAKE_NAME" "FETCH_TARGETS" ${ARGN})
  if(NOT ARG_MANIFEST OR NOT ARG_MMAKE_NAME OR ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "aros_add_mmake_transform_target requires MANIFEST and MMAKE_NAME")
  endif()
  _aros_expand_make_tokens("$(SED)" _sed_command)
  if(_sed_command STREQUAL "")
    find_program(_aros_sed NAMES sed REQUIRED)
    set(_AROS_MMAKE_VAR_SED "${_aros_sed}")
    unset(_aros_sed CACHE)
  endif()
  set(_transform_reports)
  set(_transform_sources)
  set(_ready TRUE)
  foreach(_fetch IN LISTS ARG_FETCH_TARGETS)
    get_target_property(_prepared "${_fetch}" AROS_FETCH_READY)
    get_target_property(_report "${_fetch}" AROS_FETCH_REPORT)
    get_target_property(_files "${_fetch}" AROS_FETCH_FILES)
    get_target_property(_transform_python "${_fetch}" AROS_FETCH_PYTHON)
    if(NOT _report OR NOT _transform_python)
      message(FATAL_ERROR "Text transform requires a native fetch producer: ${_fetch}")
    endif()
    list(APPEND _transform_reports "${_report}")
    list(APPEND _transform_sources ${_files})
    if(NOT _prepared)
      set(_ready FALSE)
    endif()
  endforeach()
  if(NOT _ready)
    add_custom_target("${target}"
      COMMAND "${CMAKE_COMMAND}" -E echo "${target}: native sources prepared; build again to configure transforms"
      COMMAND "${CMAKE_COMMAND}" -E false DEPENDS ${ARG_FETCH_TARGETS} VERBATIM)
    return()
  endif()
  foreach(_report IN LISTS _transform_reports)
    execute_process(COMMAND "${_transform_python}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/build_mmake_fetch.py"
      --verify "${_report}" COMMAND_ERROR_IS_FATAL ANY)
  endforeach()
  set(_AROS_RULE_OPTION_INCLUDES TRUE)
  set(_AROS_RULE_EXPAND_RECIPES TRUE)
  set(_AROS_RULE_PRESERVE_DOLLARS TRUE)
  set(_AROS_RULE_RECIPE_VARIABLES SED)
  set(_AROS_RULE_MACRO_COLLECTOR "")
  get_filename_component(_transform_source_dir "${ARG_MANIFEST}" DIRECTORY)
  _aros_collect_mmake_rules("${ARG_MANIFEST}" _transform)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ARG_MANIFEST}")
  if(AROS_LEGACY_BUILD_DIR)
    # START LEGACY: track read-only configuration scaffolding until all
    # callers supply native configuration; never execute its recipes.
    file(GLOB _config_inputs CONFIGURE_DEPENDS
      "${AROS_LEGACY_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/*.cfg"
      "${AROS_LEGACY_BUILD_DIR}/config/*.cfg" "${AROS_LEGACY_BUILD_DIR}/Makefile")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_config_inputs})
    # END LEGACY.
  endif()
  _aros_transform_node("${ARG_MMAKE_NAME}" "" _outputs)
  add_custom_target("${target}" DEPENDS ${_outputs})
  set_target_properties("${target}" PROPERTIES FOLDER "aros/internal/codegen"
    AROS_TRANSFORM_OUTPUTS "${_outputs}" AROS_NATIVE_FETCH_TARGETS "${ARG_FETCH_TARGETS}")
endfunction()
