include_guard(GLOBAL)

function(_aros_layering_get_source_root out_var)
  if(DEFINED AROS_SOURCE_DIR AND NOT AROS_SOURCE_DIR STREQUAL "")
    set(${out_var} "${AROS_SOURCE_DIR}" PARENT_SCOPE)
  elseif(DEFINED CMAKE_SOURCE_DIR AND NOT CMAKE_SOURCE_DIR STREQUAL "")
    set(${out_var} "${CMAKE_SOURCE_DIR}" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "AROS source root is not available for layering resolution")
  endif()
endfunction()

function(_aros_layering_get_config_build_dir out_var)
  if(DEFINED AROS_CONFIG_BUILD_DIR AND NOT AROS_CONFIG_BUILD_DIR STREQUAL "")
    set(${out_var} "${AROS_CONFIG_BUILD_DIR}" PARENT_SCOPE)
  elseif(DEFINED AROS_LEGACY_BUILD_DIR AND NOT AROS_LEGACY_BUILD_DIR STREQUAL "")
    set(${out_var} "${AROS_LEGACY_BUILD_DIR}" PARENT_SCOPE)
  elseif(DEFINED AROS_BINARY_DIR AND NOT AROS_BINARY_DIR STREQUAL "")
    set(${out_var} "${AROS_BINARY_DIR}" PARENT_SCOPE)
  elseif(DEFINED CMAKE_BINARY_DIR AND NOT CMAKE_BINARY_DIR STREQUAL "")
    set(${out_var} "${CMAKE_BINARY_DIR}" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "AROS config build root is not available for layering resolution")
  endif()
endfunction()

function(aros_layering_get_target_context out_arch out_cpu out_variant out_family)
  if(NOT DEFINED AROS_TARGET OR AROS_TARGET STREQUAL "")
    message(FATAL_ERROR "AROS_TARGET is required for layering resolution")
  endif()

  string(REPLACE "-" ";" _parts "${AROS_TARGET}")
  list(LENGTH _parts _parts_len)
  if(_parts_len LESS 2)
    message(FATAL_ERROR "AROS_TARGET must be in form <arch>-<cpu>[-<variant>], got: ${AROS_TARGET}")
  endif()

  list(GET _parts 0 _arch)
  list(GET _parts 1 _cpu)
  set(_variant "")
  if(_parts_len GREATER 2)
    list(SUBLIST _parts 2 -1 _variant_parts)
    string(REPLACE ";" "-" _variant "${_variant_parts}")
  endif()

  _aros_layering_get_config_build_dir(_config_build_dir)
  set(_target_cfg "${_config_build_dir}/bin/${AROS_TARGET}/gen/config/target.cfg")
  if(DEFINED AROS_TARGET_FAMILY AND NOT AROS_TARGET_FAMILY STREQUAL "")
    set(_family_line "FAMILY := ${AROS_TARGET_FAMILY}")
  elseif(EXISTS "${_target_cfg}")
    file(STRINGS "${_target_cfg}" _family_line REGEX "^FAMILY[ \t]*:=")
  endif()
  if(_family_line)
    string(REGEX REPLACE "^FAMILY[ \t]*:=[ \t]*" "" _family "${_family_line}")
    string(STRIP "${_family}" _family)
  else()
    set(_family "${_arch}")
  endif()

  set(${out_arch} "${_arch}" PARENT_SCOPE)
  set(${out_cpu} "${_cpu}" PARENT_SCOPE)
  set(${out_variant} "${_variant}" PARENT_SCOPE)
  set(${out_family} "${_family}" PARENT_SCOPE)
endfunction()

function(aros_layering_get_active_alias_layers out_var)
  aros_layering_get_target_context(_arch _cpu _variant _family)

  set(_aliases)
  if(_variant)
    list(APPEND _aliases "${_arch}-${_cpu}-${_variant}")
  endif()
  list(APPEND _aliases "${_arch}-${_cpu}")
  if(_variant)
    list(APPEND _aliases "${_arch}-${_variant}")
  endif()
  list(APPEND _aliases "${_arch}" "${_family}" "${_cpu}")
  list(REMOVE_DUPLICATES _aliases)
  set(${out_var} "${_aliases}" PARENT_SCOPE)
endfunction()

function(aros_layering_get_active_dir_layers out_var)
  aros_layering_get_target_context(_arch _cpu _variant _family)

  set(_layers)
  if(_variant)
    list(APPEND _layers "${_cpu}-${_arch}-${_variant}")
  endif()
  list(APPEND _layers "${_cpu}-${_arch}" "all-${_arch}" "all-${_family}" "${_cpu}-all")
  list(REMOVE_DUPLICATES _layers)
  set(${out_var} "${_layers}" PARENT_SCOPE)
endfunction()

function(aros_layering_read_mmake_logical_lines file_path out_var)
  file(STRINGS "${file_path}" _raw_lines)
  set(_logical_lines)
  set(_current "")

  foreach(_raw_line IN LISTS _raw_lines)
    string(REGEX REPLACE "[\r\n]+$" "" _line "${_raw_line}")
    if(_current STREQUAL "")
      set(_current "${_line}")
    else()
      string(APPEND _current " " "${_line}")
    endif()

    if(_current MATCHES "\\\\[ \t]*$")
      string(REGEX REPLACE "\\\\[ \t]*$" "" _current "${_current}")
      string(STRIP "${_current}" _current)
    else()
      string(STRIP "${_current}" _current)
      if(NOT _current STREQUAL "")
        string(REPLACE ";" "\\;" _current "${_current}")
        list(APPEND _logical_lines "${_current}")
      endif()
      set(_current "")
    endif()
  endforeach()

  if(NOT _current STREQUAL "")
    string(STRIP "${_current}" _current)
    string(REPLACE ";" "\\;" _current "${_current}")
    list(APPEND _logical_lines "${_current}")
  endif()

  set(${out_var} "${_logical_lines}" PARENT_SCOPE)
endfunction()

function(aros_layering_extract_primary_mmake_name mmakefile_src out_var)
  if(NOT EXISTS "${mmakefile_src}")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  aros_layering_read_mmake_logical_lines("${mmakefile_src}" _logical_lines)
  set(_mmake_name "")

  foreach(_line IN LISTS _logical_lines)
    if(_line MATCHES "^%build_module[^ \t]*[ \t]+(.*)$")
      separate_arguments(_tokens NATIVE_COMMAND "${CMAKE_MATCH_1}")
      foreach(_token IN LISTS _tokens)
        if(_token MATCHES "^mmake=(.*)$")
          set(_mmake_name "${CMAKE_MATCH_1}")
          break()
        endif()
      endforeach()
    elseif(_line MATCHES "^%build_archspecific[^ \t]*[ \t]+(.*)$")
      separate_arguments(_tokens NATIVE_COMMAND "${CMAKE_MATCH_1}")
      foreach(_token IN LISTS _tokens)
        if(_token MATCHES "^mainmmake=(.*)$")
          set(_mmake_name "${CMAKE_MATCH_1}")
          break()
        endif()
      endforeach()
    endif()

    if(NOT _mmake_name STREQUAL "")
      break()
    endif()
  endforeach()

  set(${out_var} "${_mmake_name}" PARENT_SCOPE)
endfunction()

function(_aros_layering_normalize_mmake_target_suffix target_name mmake_name out_var)
  if(mmake_name STREQUAL "")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  set(_prefix "${mmake_name}-")
  string(FIND "${target_name}" "${_prefix}" _prefix_pos)
  if(NOT _prefix_pos EQUAL 0)
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  string(LENGTH "${_prefix}" _prefix_len)
  string(SUBSTRING "${target_name}" "${_prefix_len}" -1 _suffix)
  foreach(_known_suffix IN ITEMS "-kobj-quick" "-quick" "-includes" "-linklib" "-kobj")
    if(_suffix MATCHES "${_known_suffix}$")
      string(REGEX REPLACE "${_known_suffix}$" "" _suffix "${_suffix}")
      break()
    endif()
  endforeach()

  set(${out_var} "${_suffix}" PARENT_SCOPE)
endfunction()

function(_aros_layering_get_mmake_layer_id mmakefile_path out_var)
  _aros_layering_get_source_root(_source_root)
  get_filename_component(_module_dir "${mmakefile_path}" DIRECTORY)
  get_filename_component(_layer_dir "${_module_dir}" DIRECTORY)
  file(RELATIVE_PATH _layer_id "${_source_root}/arch" "${_layer_dir}")
  set(${out_var} "${_layer_id}" PARENT_SCOPE)
endfunction()

function(aros_layering_collect_candidate_module_mmakefiles module_dir_name out_var)
  _aros_layering_get_source_root(_source_root)
  file(GLOB _candidate_mmakefiles
    LIST_DIRECTORIES FALSE
    "${_source_root}/arch/*/${module_dir_name}/mmakefile.src"
    "${_source_root}/arch/*/*/${module_dir_name}/mmakefile.src"
  )
  list(SORT _candidate_mmakefiles)
  set(${out_var} "${_candidate_mmakefiles}" PARENT_SCOPE)
endfunction()

function(aros_layering_extract_module_mmake_metadata mmakefile_path mmake_name out_targets out_arches out_edges)
  if(NOT EXISTS "${mmakefile_path}" OR mmake_name STREQUAL "")
    set(${out_targets} "" PARENT_SCOPE)
    set(${out_arches} "" PARENT_SCOPE)
    set(${out_edges} "" PARENT_SCOPE)
    return()
  endif()

  aros_layering_read_mmake_logical_lines("${mmakefile_path}" _logical_lines)
  set(_target_tokens)
  set(_arch_tokens)
  set(_alias_edges)

  foreach(_line IN LISTS _logical_lines)
    if(_line MATCHES "^#MM-?[ \t]+([^ \t:]+)[ \t]*:(.*)$")
      set(_source_target "${CMAKE_MATCH_1}")
      set(_dep_string "${CMAKE_MATCH_2}")
      _aros_layering_normalize_mmake_target_suffix("${_source_target}" "${mmake_name}" _source_suffix)
      if(NOT _source_suffix STREQUAL "")
        list(APPEND _target_tokens "${_source_suffix}")
        string(STRIP "${_dep_string}" _dep_string)
        if(NOT _dep_string STREQUAL "")
          separate_arguments(_dep_tokens NATIVE_COMMAND "${_dep_string}")
          foreach(_dep_token IN LISTS _dep_tokens)
            _aros_layering_normalize_mmake_target_suffix("${_dep_token}" "${mmake_name}" _dep_suffix)
            if(NOT _dep_suffix STREQUAL "")
              list(APPEND _target_tokens "${_dep_suffix}")
              list(APPEND _alias_edges "${_source_suffix}|${_dep_suffix}")
            endif()
          endforeach()
        endif()
      endif()
      continue()
    endif()

    if(_line MATCHES "^%gen_archfamilyrules[ \t]+(.*)$")
      separate_arguments(_arg_tokens NATIVE_COMMAND "${CMAKE_MATCH_1}")
      set(_family_arch "")
      set(_family_alias "")
      set(_family_mmake "")
      foreach(_arg_token IN LISTS _arg_tokens)
        if(_arg_token MATCHES "^arch=([^ \t]+)$")
          set(_family_arch "${CMAKE_MATCH_1}")
        elseif(_arg_token MATCHES "^family=([^ \t]+)$")
          set(_family_alias "${CMAKE_MATCH_1}")
        elseif(_arg_token MATCHES "^mainmmake=([^ \t]+)$")
          set(_family_mmake "${CMAKE_MATCH_1}")
        endif()
      endforeach()
      if(_family_arch AND _family_alias
         AND (_family_mmake STREQUAL "" OR _family_mmake STREQUAL "${mmake_name}"))
        list(APPEND _alias_edges "${_family_arch}|${_family_alias}")
      endif()
      continue()
    endif()

    if(_line MATCHES "^%build_archspecific[^ \t]*[ \t]+(.*)$")
      separate_arguments(_arg_tokens NATIVE_COMMAND "${CMAKE_MATCH_1}")
      foreach(_arg_token IN LISTS _arg_tokens)
        if(_arg_token MATCHES "^arch=([^ \t]+)$")
          list(APPEND _arch_tokens "${CMAKE_MATCH_1}")
        endif()
      endforeach()
    endif()
  endforeach()

  list(REMOVE_DUPLICATES _target_tokens)
  list(REMOVE_DUPLICATES _arch_tokens)
  list(REMOVE_DUPLICATES _alias_edges)
  set(${out_targets} "${_target_tokens}" PARENT_SCOPE)
  set(${out_arches} "${_arch_tokens}" PARENT_SCOPE)
  set(${out_edges} "${_alias_edges}" PARENT_SCOPE)
endfunction()

function(aros_layering_collect_resolved_module_layer_mmakefiles module_dir_name mmake_name out_mmakefiles out_layers out_aliases)
  _aros_layering_get_source_root(_source_root)
  aros_layering_get_active_alias_layers(_reachable_aliases)
  aros_layering_get_active_dir_layers(_active_dir_layers)

  set(_resolved_mmakefiles)
  foreach(_layer IN LISTS _active_dir_layers)
    set(_active_mmakefile "${_source_root}/arch/${_layer}/${module_dir_name}/mmakefile.src")
    if(EXISTS "${_active_mmakefile}")
      list(APPEND _resolved_mmakefiles "${_active_mmakefile}")
    endif()
  endforeach()

  if(NOT mmake_name STREQUAL "")
    aros_layering_collect_candidate_module_mmakefiles("${module_dir_name}" _candidate_mmakefiles)

    set(_changed TRUE)
    while(_changed)
      set(_changed FALSE)
      foreach(_candidate_mmakefile IN LISTS _candidate_mmakefiles)
        aros_layering_extract_module_mmake_metadata(
          "${_candidate_mmakefile}"
          "${mmake_name}"
          _candidate_targets
          _candidate_arches
          _candidate_edges
        )
        foreach(_edge IN LISTS _candidate_edges)
          string(REPLACE "|" ";" _edge_parts "${_edge}")
          list(LENGTH _edge_parts _edge_len)
          if(NOT _edge_len EQUAL 2)
            continue()
          endif()
          list(GET _edge_parts 0 _edge_source)
          list(GET _edge_parts 1 _edge_dest)
          list(FIND _reachable_aliases "${_edge_source}" _source_index)
          list(FIND _reachable_aliases "${_edge_dest}" _dest_index)
          if(NOT _source_index EQUAL -1 AND _dest_index EQUAL -1)
            list(APPEND _reachable_aliases "${_edge_dest}")
            set(_changed TRUE)
          endif()
        endforeach()
      endforeach()
    endwhile()

    foreach(_candidate_mmakefile IN LISTS _candidate_mmakefiles)
      _aros_layering_get_mmake_layer_id("${_candidate_mmakefile}" _candidate_layer)
      list(FIND _active_dir_layers "${_candidate_layer}" _active_layer_index)
      if(NOT _active_layer_index EQUAL -1)
        list(APPEND _resolved_mmakefiles "${_candidate_mmakefile}")
        continue()
      endif()

      aros_layering_extract_module_mmake_metadata(
        "${_candidate_mmakefile}"
        "${mmake_name}"
        _candidate_targets
        _candidate_arches
        _candidate_edges
      )

      set(_include_candidate FALSE)
      foreach(_candidate_token IN LISTS _candidate_targets _candidate_arches)
        list(FIND _reachable_aliases "${_candidate_token}" _token_index)
        if(NOT _token_index EQUAL -1)
          set(_include_candidate TRUE)
          break()
        endif()
      endforeach()

      if(_include_candidate)
        list(APPEND _resolved_mmakefiles "${_candidate_mmakefile}")
      endif()
    endforeach()
  endif()

  list(REMOVE_DUPLICATES _resolved_mmakefiles)

  set(_resolved_layers)
  foreach(_resolved_mmakefile IN LISTS _resolved_mmakefiles)
    _aros_layering_get_mmake_layer_id("${_resolved_mmakefile}" _resolved_layer)
    list(APPEND _resolved_layers "${_resolved_layer}")
  endforeach()
  list(REMOVE_DUPLICATES _resolved_layers)
  list(REMOVE_DUPLICATES _reachable_aliases)

  set(${out_mmakefiles} "${_resolved_mmakefiles}" PARENT_SCOPE)
  set(${out_layers} "${_resolved_layers}" PARENT_SCOPE)
  set(${out_aliases} "${_reachable_aliases}" PARENT_SCOPE)
endfunction()
