include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeObjects.cmake")

function(_aros_collect_icon_macro kind args prefix)
  set(${prefix}_FIELDS "" PARENT_SCOPE)
  if(NOT kind STREQUAL "build_icons")
    return()
  endif()
  _aros_mmake_macro_arguments("${args}" _arg)
  if(NOT _arg_mmake STREQUAL _AROS_SELECTED_ICON_RULE)
    return()
  endif()
  set(_allowed mmake icons fmt dir srcdir image)
  foreach(_key IN LISTS _arg_KEYS)
    if(NOT _key IN_LIST _allowed)
      message(FATAL_ERROR "Unsupported icon argument: ${_key}")
    endif()
  endforeach()
  if(NOT _arg_icons OR NOT _arg_dir)
    message(FATAL_ERROR "build_icons requires icons and dir")
  endif()
  if(NOT DEFINED _arg_srcdir)
    _aros_expand_make_tokens("$(SRCDIR)/$(CURDIR)" _arg_srcdir)
  endif()
  if(NOT DEFINED _arg_fmt)
    set(_arg_fmt png)
  endif()
  foreach(_key IN LISTS _allowed)
    if("${_arg_${_key}}" MATCHES "[$%]")
      message(FATAL_ERROR "Unresolved icon ${_key}: ${_arg_${_key}}")
    endif()
    set(${prefix}_${_key} "${_arg_${_key}}" PARENT_SCOPE)
  endforeach()
  set(${prefix}_FIELDS "${_allowed}" PARENT_SCOPE)
endfunction()

function(_aros_register_program_icons mmake out_target)
  set(${out_target} "" PARENT_SCOPE)
  set(_matches)
  foreach(_manifest IN LISTS AROS_MMAKE_MANIFESTS)
    file(STRINGS "${_manifest}" _rules REGEX "^%build_icons[ \t]")
    if(NOT _rules)
      continue()
    endif()
    _aros_read_mmake_logical_lines("${_manifest}" _lines)
    foreach(_line IN LISTS _lines)
      if(_line MATCHES "^%build_icons[ \t]+.*mmake=\"?([^ \t\"]+)" AND CMAKE_MATCH_1 STREQUAL mmake)
        list(APPEND _matches "${_manifest}")
      endif()
    endforeach()
  endforeach()
  list(LENGTH _matches _count)
  if(_count EQUAL 0)
    return()
  elseif(NOT _count EQUAL 1)
    message(FATAL_ERROR "Ambiguous icon producer for ${mmake}: ${_matches}")
  endif()
  string(SHA256 _key "${mmake}")
  set(_target "aros-icons-${_key}")
  set(${out_target} "${_target}" PARENT_SCOPE)
  if(TARGET "${_target}")
    return()
  endif()
  if(NOT TARGET ilbmtoicon)
    message(FATAL_ERROR "Native icons require the ilbmtoicon host tool")
  endif()
  set(_AROS_MMAKE_VAR_AROSDIR "${AROS_NATIVE_SYSTEM_DIR}")
  set(_AROS_RULE_MACRO_COLLECTOR _aros_collect_icon_macro)
  set(_AROS_SELECTED_ICON_RULE "${mmake}")
  _aros_collect_mmake_rules("${_matches}" _mm)
  list(LENGTH _mm_MACROS _count)
  if(NOT _count EQUAL 1)
    message(FATAL_ERROR "Expected one active icon rule for ${mmake}")
  endif()
  _aros_program_prerequisites("${_matches}" "${mmake}" _prerequisites)
  if(_prerequisites)
    message(FATAL_ERROR "Unhandled icon prerequisites for ${mmake}: ${_prerequisites}")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_matches}")
  separate_arguments(_icons UNIX_COMMAND "${_mm_MACRO_0_icons}")
  set(_outputs)
  foreach(_icon IN LISTS _icons)
    if(NOT _icon MATCHES "^[A-Za-z0-9_+.-]+$" OR _icon MATCHES "^[.]+$")
      message(FATAL_ERROR "Unsupported icon name: ${_icon}")
    endif()
    _aros_static_output_path("${_mm_MACRO_0_dir}/${_icon}.info" _output)
    set(_info "${_mm_MACRO_0_srcdir}/${_icon}.info.src")
    if(_mm_MACRO_0_image)
      set(_image "${_mm_MACRO_0_srcdir}/${_mm_MACRO_0_image}")
    else()
      set(_image "${_mm_MACRO_0_srcdir}/${_icon}.${_mm_MACRO_0_fmt}")
    endif()
    foreach(_input IN ITEMS "${_info}" "${_image}")
      file(REAL_PATH "${_input}" _real)
      file(REAL_PATH "${CMAKE_SOURCE_DIR}" _root)
      file(RELATIVE_PATH _relative "${_root}" "${_real}")
      if(NOT EXISTS "${_input}" OR IS_DIRECTORY "${_input}" OR _relative MATCHES "^\\.\\.(/|$)"
         OR IS_ABSOLUTE "${_relative}")
        message(FATAL_ERROR "Icon requires an owned static source: ${_input}")
      endif()
      foreach(_generated_root IN ITEMS "${CMAKE_BINARY_DIR}" "${AROS_LEGACY_BUILD_DIR}")
        file(REAL_PATH "${_generated_root}" _generated_root)
        file(RELATIVE_PATH _relative "${_generated_root}" "${_real}")
        if(NOT _relative MATCHES "^\\.\\.(/|$)" AND NOT IS_ABSOLUTE "${_relative}")
          message(FATAL_ERROR "Icon requires an owned static source: ${_input}")
        endif()
      endforeach()
    endforeach()
    string(SHA256 _output_key "${_output}")
    get_property(_owner GLOBAL PROPERTY "AROS_ICON_OUTPUT_${_output_key}")
    if(_owner)
      message(FATAL_ERROR "Duplicate icon producer for ${_output}: ${_owner} and ${mmake}")
    endif()
    set_property(GLOBAL PROPERTY "AROS_ICON_OUTPUT_${_output_key}" "${mmake}")
    get_filename_component(_directory "${_output}" DIRECTORY)
    add_custom_command(OUTPUT "${_output}"
      COMMAND "${CMAKE_COMMAND}" -E make_directory "${_directory}"
      COMMAND "$<TARGET_FILE:ilbmtoicon>" "${_info}" "${_image}" "${_output}"
      DEPENDS ilbmtoicon "${_info}" "${_image}" "${_matches}"
      COMMENT "Generating AROS icon ${_output}" VERBATIM)
    list(APPEND _outputs "${_output}")
  endforeach()
  add_custom_target("${_target}" DEPENDS ${_outputs})
  set_target_properties("${_target}" PROPERTIES FOLDER "aros/internal/packaging")
endfunction()
