include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSStaticTargets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeObjects.cmake")

function(_aros_collect_entrypoint kind args prefix)
  set(${prefix}_FIELDS "" PARENT_SCOPE)
  if(NOT kind IN_LIST _AROS_ENTRYPOINT_KINDS)
    return()
  endif()
  _aros_mmake_macro_arguments("${args}" _arg)
  if(NOT _arg_mmake IN_LIST _AROS_ENTRYPOINT_NAMES)
    return()
  endif()
  foreach(_key IN ITEMS compiler libname targetdir libdir)
    if(NOT _key IN_LIST _arg_KEYS)
      set(_arg_${_key} "")
      list(APPEND _arg_KEYS "${_key}")
    endif()
  endforeach()
  set(${prefix}_FIELDS "KIND;KEYS;${_arg_KEYS}" PARENT_SCOPE)
  set(${prefix}_KIND "${kind}" PARENT_SCOPE)
  set(${prefix}_KEYS "${_arg_KEYS}" PARENT_SCOPE)
  foreach(_key IN LISTS _arg_KEYS)
    set(${prefix}_${_key} "${_arg_${_key}}" PARENT_SCOPE)
  endforeach()
endfunction()

# The manifest inventory, not a source-directory map, owns producer identity.
# Names are migration entrypoints; all source/output arguments stay upstream.
function(aros_find_mmake_entrypoint prefix)
  cmake_parse_arguments(ARG "OPTIONAL" "" "NAMES;KINDS" ${ARGN})
  if(NOT ARG_NAMES OR NOT ARG_KINDS OR ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "aros_find_mmake_entrypoint requires NAMES and KINDS")
  endif()
  set(_candidates)
  foreach(_name IN LISTS ARG_NAMES)
    _aros_static_manifest_candidates("${_name}" _matches)
    list(APPEND _candidates ${_matches})
  endforeach()
  list(REMOVE_DUPLICATES _candidates)
  set(_AROS_ENTRYPOINT_NAMES "${ARG_NAMES}")
  set(_AROS_ENTRYPOINT_KINDS "${ARG_KINDS}")
  set(_AROS_RULE_MACRO_COLLECTOR _aros_collect_entrypoint)
  set(_count 0)
  set(_found)
  foreach(_manifest IN LISTS _candidates)
    _aros_collect_mmake_rules("${_manifest}" _entry)
    foreach(_id IN LISTS _entry_MACROS)
      math(EXPR _count "${_count} + 1")
      list(APPEND _found "${_manifest}:${_entry_MACRO_${_id}_mmake}")
      set(${prefix}_MANIFEST "${_manifest}" PARENT_SCOPE)
      get_filename_component(_dir "${_manifest}" DIRECTORY)
      file(RELATIVE_PATH _path "${CMAKE_SOURCE_DIR}" "${_dir}")
      set(${prefix}_MODULE_PATH "${_path}" PARENT_SCOPE)
      foreach(_field IN LISTS _entry_MACRO_${_id}_KEYS ITEMS KIND)
        set(${prefix}_${_field} "${_entry_MACRO_${_id}_${_field}}" PARENT_SCOPE)
      endforeach()
    endforeach()
  endforeach()
  if(_count GREATER 1 OR (_count EQUAL 0 AND NOT ARG_OPTIONAL))
    message(FATAL_ERROR "Expected one native manifest entrypoint for ${ARG_NAMES}, found: ${_found}")
  endif()
  set(${prefix}_FOUND "${_count}" PARENT_SCOPE)
endfunction()
