include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeRules.cmake")

function(_aros_mmake_macro_arguments args prefix)
  string(REPLACE ";" " " _args "${args}")
  _aros_expand_make_tokens("${_args}" _args)
  separate_arguments(_tokens UNIX_COMMAND "${_args}")
  set(_keys)
  set(_key "")
  foreach(_token IN LISTS _tokens)
    if(_token MATCHES "^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")
      set(_key "${CMAKE_MATCH_1}")
      if(_key IN_LIST _keys)
        if(NOT ARGV2 STREQUAL "LAST_WINS")
          message(FATAL_ERROR "Duplicate rule argument ${_key}")
        endif()
      else()
        list(APPEND _keys "${_key}")
      endif()
      set(_value_${_key} "${CMAKE_MATCH_2}")
    elseif(_key)
      string(APPEND _value_${_key} " ${_token}")
    else()
      message(FATAL_ERROR "Unexpected rule argument: ${_token}")
    endif()
  endforeach()
  foreach(_key IN LISTS _keys)
    set(${prefix}_${_key} "${_value_${_key}}" PARENT_SCOPE)
  endforeach()
  set(${prefix}_KEYS "${_keys}" PARENT_SCOPE)
endfunction()

function(_aros_collect_object_macro kind args prefix)
  set(${prefix}_FIELDS "" PARENT_SCOPE)
  if(NOT kind MATCHES "^rule_compile(_cxx|_objc)?$")
    return()
  endif()
  _aros_mmake_macro_arguments("${args}" _arg)
  set(_allowed mmake basename cppflags cflags cxxflags dflags dxxflags incextra targetdir compiler)
  set(_unsupported)
  foreach(_key IN LISTS _arg_KEYS)
    if(NOT _key IN_LIST _allowed)
      list(APPEND _unsupported "${_key}")
    endif()
  endforeach()
  if(NOT _arg_basename)
    message(FATAL_ERROR "rule_compile requires basename")
  endif()
  get_filename_component(_base "${_arg_basename}" NAME)
  if(_arg_targetdir)
    set(_output "${_arg_targetdir}/${_base}.o")
  else()
    set(_output "${_arg_basename}.o")
  endif()
  set(_extension c)
  if(kind STREQUAL "rule_compile_cxx")
    set(_extension cpp)
  elseif(kind STREQUAL "rule_compile_objc")
    set(_extension m)
  endif()
  set(_source "${_arg_basename}.${_extension}")
  set(_flags)
  foreach(_flag IN ITEMS cppflags cflags)
    if(DEFINED _arg_${_flag})
      separate_arguments(_tokens UNIX_COMMAND "${_arg_${_flag}}")
    else()
      string(TOUPPER "${_flag}" _variable)
      _aros_read_config_tokens("${_variable}" _tokens)
    endif()
    list(APPEND _flags ${_tokens})
  endforeach()
  _aros_read_config_tokens(SAFETY_CFLAGS _safety)
  list(APPEND _flags ${_safety})
  list(REMOVE_ITEM _flags -fpermissive)
  if(DEFINED _arg_incextra)
    set(_extra "${_arg_incextra}")
  else()
    _aros_expand_make_tokens("$(TOP)/$(CURDIR)" _extra)
  endif()
  list(APPEND _flags -iquote "${_extra}")
  if(NOT kind STREQUAL "rule_compile" OR (_arg_compiler AND NOT _arg_compiler STREQUAL "target")
     OR _arg_dflags OR _arg_dxxflags)
    list(APPEND _unsupported "${kind}/${_arg_compiler}/${_arg_dflags}/${_arg_dxxflags}")
  endif()
  foreach(_field IN ITEMS output source flags unsupported)
    string(TOUPPER "${_field}" _upper)
    set(${prefix}_${_upper} "${_${_field}}" PARENT_SCOPE)
  endforeach()
  set(${prefix}_FIELDS OUTPUT SOURCE FLAGS UNSUPPORTED PARENT_SCOPE)
endfunction()

function(_aros_mmake_pattern_match pattern path out_match out_stem)
  string(REPLACE "%" ";" _parts "${pattern}")
  list(LENGTH _parts _count)
  set(_match FALSE)
  set(_stem "")
  if(_count EQUAL 1)
    if(pattern STREQUAL path)
      set(_match TRUE)
    endif()
  elseif(_count EQUAL 2)
    list(GET _parts 0 _prefix)
    list(GET _parts 1 _suffix)
    string(LENGTH "${_prefix}" _head)
    string(LENGTH "${_suffix}" _tail)
    string(LENGTH "${path}" _length)
    math(EXPR _size "${_length} - ${_head} - ${_tail}")
    if(_size GREATER 0)
      string(SUBSTRING "${path}" 0 ${_head} _start)
      math(EXPR _end "${_length} - ${_tail}")
      string(SUBSTRING "${path}" ${_end} -1 _finish)
      if(_start STREQUAL _prefix AND _finish STREQUAL _suffix)
        string(SUBSTRING "${path}" ${_head} ${_size} _stem)
        set(_match TRUE)
      endif()
    endif()
  else()
    message(FATAL_ERROR "Unsupported multiple-wildcard rule: ${pattern}")
  endif()
  set(${out_match} "${_match}" PARENT_SCOPE)
  set(${out_stem} "${_stem}" PARENT_SCOPE)
endfunction()

# Translate a declared SDK object through one pattern copy and one compile
# rule. Prefer explicitly declared intermediates before searching implicit
# chains; equal-specificity candidates retain manifest order. Existing .o
# files never satisfy a prerequisite without an owned source/compile rule.
function(aros_collect_mmake_object manifest output prefix)
  set(_AROS_RULE_MACRO_COLLECTOR _aros_collect_object_macro)
  _aros_collect_mmake_rules("${manifest}" _mm)
  set(${prefix}_FOUND FALSE PARENT_SCOPE)
  set(_declared FALSE)
  set(_declared_paths)
  foreach(_id IN LISTS _mm_RULES)
    if(NOT "${_mm_${_id}_TARGETS}" MATCHES "%")
      list(APPEND _declared_paths ${_mm_${_id}_TARGETS} ${_mm_${_id}_DEPENDS})
    endif()
    if(output IN_LIST _mm_${_id}_DEPENDS)
      set(_declared TRUE)
    endif()
  endforeach()
  foreach(_macro IN LISTS _mm_MACROS)
    if(_mm_MACRO_${_macro}_OUTPUT AND NOT _mm_MACRO_${_macro}_OUTPUT MATCHES "%")
      list(APPEND _declared_paths "${_mm_MACRO_${_macro}_OUTPUT}")
    endif()
  endforeach()
  if(NOT _declared)
    return()
  endif()
  set(_patterns)
  set(_declared_rules)
  set(_implicit_rules)
  foreach(_id IN LISTS _mm_RULES)
    foreach(_pattern IN LISTS _mm_${_id}_TARGETS)
      _aros_mmake_pattern_match("${_pattern}" "${output}" _match _stem)
      if(NOT _match)
        continue()
      endif()
      list(LENGTH _mm_${_id}_TARGETS _targets)
      list(LENGTH _mm_${_id}_DEPENDS _depends)
      if(NOT _targets EQUAL 1 OR NOT _depends EQUAL 1 OR NOT _mm_${_id}_RECIPE_COUNT EQUAL 1
         OR NOT _mm_${_id}_RECIPE_0 MATCHES "^@?\\$\\(CP\\)[ \t]+\\$<[ \t]+\\$@$")
        message(FATAL_ERROR "Unsupported SDK object copy rule for ${output} in ${manifest}")
      endif()
      list(APPEND _patterns "${_pattern}")
      string(REPLACE "%" "${_stem}" _intermediate "${_mm_${_id}_DEPENDS}")
      if(_intermediate IN_LIST _declared_paths)
        list(APPEND _declared_rules "${_id}")
      else()
        list(APPEND _implicit_rules "${_id}")
      endif()
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES _patterns)
  list(LENGTH _patterns _count)
  if(_count GREATER 1)
    message(FATAL_ERROR "Unsupported overlapping SDK object patterns for ${output} in ${manifest}")
  endif()
  get_filename_component(_directory "${manifest}" DIRECTORY)
  foreach(_id IN LISTS _declared_rules _implicit_rules)
    list(LENGTH _mm_${_id}_TARGETS _count)
    if(NOT _count EQUAL 1)
      continue()
    endif()
    _aros_mmake_pattern_match("${_mm_${_id}_TARGETS}" "${output}" _match _stem)
    if(NOT _match)
      continue()
    endif()
    list(LENGTH _mm_${_id}_DEPENDS _count)
    if(NOT _count EQUAL 1 OR NOT _mm_${_id}_RECIPE_COUNT EQUAL 1
       OR NOT _mm_${_id}_RECIPE_0 MATCHES "^@?\\$\\(CP\\)[ \t]+\\$<[ \t]+\\$@$")
      message(FATAL_ERROR "Unsupported SDK object copy rule for ${output} in ${manifest}")
    endif()
    string(REPLACE "%" "${_stem}" _intermediate "${_mm_${_id}_DEPENDS}")
    foreach(_constraint IN LISTS _mm_RULES)
      if(_intermediate IN_LIST _mm_${_constraint}_TARGETS)
        message(FATAL_ERROR "Unhandled SDK object compile prerequisites for ${_intermediate} in ${manifest}")
      endif()
    endforeach()
    set(_compile_rules)
    foreach(_macro IN LISTS _mm_MACROS)
      _aros_mmake_pattern_match("${_mm_MACRO_${_macro}_OUTPUT}" "${_intermediate}" _match _source_stem)
      if(NOT _match)
        continue()
      endif()
      # A directory-specific compile pattern beats a generic one even when
      # the latter can reach the same file through a slash-containing stem.
      string(LENGTH "${_source_stem}" _stem_length_${_macro})
      set(_position 0)
      foreach(_candidate IN LISTS _compile_rules)
        if(_stem_length_${_macro} LESS _stem_length_${_candidate})
          break()
        endif()
        math(EXPR _position "${_position} + 1")
      endforeach()
      list(INSERT _compile_rules ${_position} "${_macro}")
    endforeach()
    foreach(_macro IN LISTS _compile_rules)
      _aros_mmake_pattern_match("${_mm_MACRO_${_macro}_OUTPUT}" "${_intermediate}" _match _source_stem)
      string(REPLACE "%" "${_source_stem}" _source "${_mm_MACRO_${_macro}_SOURCE}")
      get_filename_component(_source "${_source}" ABSOLUTE BASE_DIR "${_directory}")
      if(NOT EXISTS "${_source}")
        continue()
      endif()
      file(REAL_PATH "${_source}" _source)
      file(REAL_PATH "${CMAKE_SOURCE_DIR}" _root)
      file(RELATIVE_PATH _relative "${_root}" "${_source}")
      if(_relative MATCHES "^\\.\\.(/|$)" OR IS_ABSOLUTE "${_relative}" OR _source MATCHES "[$%]")
        message(FATAL_ERROR "SDK object requires an owned source: ${_source}")
      endif()
      foreach(_root IN ITEMS "${AROS_BINARY_DIR}" "${AROS_LEGACY_BUILD_DIR}")
        file(RELATIVE_PATH _relative "${_root}" "${_source}")
        if(NOT _relative MATCHES "^\\.\\.(/|$)" AND NOT IS_ABSOLUTE "${_relative}")
          message(FATAL_ERROR "SDK object requires an owned source: ${_source}")
        endif()
      endforeach()
      if(_mm_MACRO_${_macro}_UNSUPPORTED OR "${_mm_MACRO_${_macro}_FLAGS}" MATCHES "[$%]")
        message(FATAL_ERROR "Unsupported SDK object compile rule: ${manifest}: ${_mm_MACRO_${_macro}_UNSUPPORTED}")
      endif()
      set(${prefix}_FOUND TRUE PARENT_SCOPE)
      set(${prefix}_SOURCE "${_source}" PARENT_SCOPE)
      set(${prefix}_FLAGS "${_mm_MACRO_${_macro}_FLAGS}" PARENT_SCOPE)
      set(${prefix}_INTERMEDIATE "${_intermediate}" PARENT_SCOPE)
      return()
    endforeach()
  endforeach()
  message(FATAL_ERROR "No supported native compile rule for declared SDK object ${output} in ${manifest}")
endfunction()
