include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeEntrypoints.cmake")

function(_aros_host_compile_options input_flags out_var)
  set(_flags)
  set(_pending "")
  foreach(_flag IN LISTS input_flags)
    if(NOT _pending STREQUAL "")
      if(_pending STREQUAL "-I" AND _flag STREQUAL AROS_NATIVE_INCLUDE_DIR)
        set(_pending "-idirafter")
      endif()
      # SHELL keeps option/path pairs together during CMake de-duplication.
      string(REPLACE "\\" "\\\\" _path "${_flag}")
      string(REPLACE "\"" "\\\"" _path "${_path}")
      list(APPEND _flags "SHELL:${_pending} \"${_path}\"")
      set(_pending "")
    elseif(_flag MATCHES "^(-I|-isystem|-idirafter|-iquote|-include|-imacros)$")
      set(_pending "${_flag}")
    elseif(_flag STREQUAL "-I${AROS_NATIVE_INCLUDE_DIR}")
      list(APPEND _flags "-idirafter${AROS_NATIVE_INCLUDE_DIR}")
    else()
      list(APPEND _flags "${_flag}")
    endif()
  endforeach()
  if(NOT _pending STREQUAL "")
    message(FATAL_ERROR "Missing argument for ${_pending}")
  endif()
  set(${out_var} "${_flags}" PARENT_SCOPE)
endfunction()

# The root project uses the Linux compiler. Target-OS objects continue to use
# the separate AROS compiler path; never link those archives into host tools.
function(aros_add_mmake_host_target target_name)
  cmake_parse_arguments(ARG "" "MODULE_PATH;MMAKE_NAME;OUTPUT_DIRECTORY" "DEPENDS;HEADER_INTERFACES" ${ARGN})
  if(NOT ARG_MMAKE_NAME OR ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "aros_add_mmake_host_target requires MMAKE_NAME")
  endif()
  set(_AROS_MMAKE_VAR_GENDIR "${AROS_NATIVE_OUTPUT_ROOT}/gen")
  set(_AROS_MMAKE_VAR_GENINCDIR "${AROS_NATIVE_INCLUDE_DIR}")
  set(_AROS_MMAKE_VAR_AROSDIR "${AROS_NATIVE_SYSTEM_DIR}")
  _aros_expand_make_tokens("$(AROS_DIR_BOOTARCH)" _AROS_MMAKE_VAR_AROS_DIR_BOOTARCH)
  _aros_expand_make_tokens("$(AROSARCHDIR)" _AROS_MMAKE_VAR_AROSARCHDIR)
  if(NOT ARG_MODULE_PATH)
    aros_find_mmake_entrypoint(_producer NAMES "${ARG_MMAKE_NAME}" KINDS build_prog build_linklib)
    set(ARG_MODULE_PATH "${_producer_MODULE_PATH}")
  endif()
  aros_find_mmake_manifest("${CMAKE_SOURCE_DIR}/${ARG_MODULE_PATH}" MODULE_MMAKEFILE)
  get_property(_visiting GLOBAL PROPERTY "AROS_HOST_VISITING_${ARG_MMAKE_NAME}")
  if(_visiting)
    message(FATAL_ERROR "Host manifest dependency cycle at ${ARG_MMAKE_NAME}")
  endif()
  set_property(GLOBAL PROPERTY "AROS_HOST_VISITING_${ARG_MMAKE_NAME}" TRUE)

  set(_metadata_dir "${CMAKE_CURRENT_BINARY_DIR}/${target_name}-metadata")
  file(MAKE_DIRECTORY "${_metadata_dir}")
  set(_context "${_metadata_dir}/context.cmake")
  file(WRITE "${_context}" "")
  set(AROS_SOURCE_DIR "${CMAKE_SOURCE_DIR}")
  set(AROS_CONFIG_BUILD_DIR "${AROS_LEGACY_BUILD_DIR}")
  set(MODULE_PATH "${ARG_MODULE_PATH}")
  set(MODULE_MMAKE_NAME "${ARG_MMAKE_NAME}")
  set(_AROS_MMAKE_VAR_GENDIR "${AROS_NATIVE_OUTPUT_ROOT}/gen")
  set(_AROS_MMAKE_VAR_GENINCDIR "${AROS_NATIVE_INCLUDE_DIR}")
  set(_AROS_MMAKE_VAR_AROSDIR "${AROS_NATIVE_SYSTEM_DIR}")
  set(_AROS_MMAKE_VAR_HOST_DEBUG "-g")
  set(_AROS_MMAKE_VAR_KERNEL_INCLUDES "-nostdinc")
  foreach(_dir IN LISTS CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES)
    string(APPEND _AROS_MMAKE_VAR_KERNEL_INCLUDES " -isystem ${_dir}")
  endforeach()
  set(_AROS_MMAKE_VAR_HOST_SYSCALL_CPPFLAGS "${AROS_HOST_SYSCALL_CPPFLAGS}")
  set(_AROS_MMAKE_VAR_CFLAGS_GENERAL_REGS_ONLY "${AROS_HOST_GENERAL_REGS_FLAGS}")
  foreach(_var IN ITEMS AROS_SOURCE_DIR AROS_CONFIG_BUILD_DIR AROS_TARGET AROS_TARGET_FAMILY
      AROS_NATIVE_CONFIG_FILE
      MODULE_PATH MODULE_MMAKE_NAME MODULE_MMAKEFILE _AROS_MMAKE_VAR_GENDIR _AROS_MMAKE_VAR_GENINCDIR
      _AROS_MMAKE_VAR_AROSDIR _AROS_MMAKE_VAR_HOST_DEBUG _AROS_MMAKE_VAR_KERNEL_INCLUDES
      _AROS_MMAKE_VAR_AROS_DIR_BOOTARCH _AROS_MMAKE_VAR_AROSARCHDIR
      _AROS_MMAKE_VAR_HOST_SYSCALL_CPPFLAGS _AROS_MMAKE_VAR_CFLAGS_GENERAL_REGS_ONLY)
    file(APPEND "${_context}" "set(${_var} [==[${${_var}}]==])\n")
  endforeach()
  set(_collector "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/collect_mmake_host_target.cmake")
  execute_process(
    COMMAND "${CMAKE_COMMAND}" "-DCONTEXT_FILE=${_context}"
      "-DOUTPUT_FILE=${_metadata_dir}/target.cmake" -P "${_collector}"
    RESULT_VARIABLE _result
  )
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Failed to collect hosted target ${ARG_MMAKE_NAME}")
  endif()
  include("${_metadata_dir}/target.cmake")
  if(NOT ARG_OUTPUT_DIRECTORY)
    set(ARG_OUTPUT_DIRECTORY "${MMAKE_OUTPUT_DIR}")
  endif()
  if(NOT IS_ABSOLUTE "${ARG_OUTPUT_DIRECTORY}")
    message(FATAL_ERROR "Host target requires an absolute manifest output directory: ${ARG_OUTPUT_DIRECTORY}")
  endif()
  file(RELATIVE_PATH _relative "${AROS_NATIVE_OUTPUT_ROOT}" "${ARG_OUTPUT_DIRECTORY}")
  if(NOT IS_ABSOLUTE "${ARG_OUTPUT_DIRECTORY}" OR _relative MATCHES "^\\.\\.(/|$)"
     OR IS_ABSOLUTE "${_relative}" OR ARG_OUTPUT_DIRECTORY MATCHES "[$;]")
    message(FATAL_ERROR "Host target output is outside the native output tree: ${ARG_OUTPUT_DIRECTORY}")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    ${AROS_NATIVE_CONFIG_FILE}
    ${MMAKE_INPUTS} "${_collector}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/AROSMmakeBuild.cmake"
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/AROSMmakeFunctions.cmake")
  if(AROS_LEGACY_BUILD_DIR)
    file(GLOB _config_inputs CONFIGURE_DEPENDS
      "${AROS_LEGACY_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/*.cfg"
      "${AROS_LEGACY_BUILD_DIR}/config/*.cfg" "${AROS_LEGACY_BUILD_DIR}/Makefile")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_config_inputs})
  endif()

  _aros_collect_mmake_rules("${MODULE_MMAKEFILE}" _rules)
  set(_prerequisites)
  foreach(_id IN LISTS _rules_RULES)
    if(ARG_MMAKE_NAME IN_LIST _rules_${_id}_TARGETS)
      if(_rules_${_id}_RECIPE_COUNT)
        message(FATAL_ERROR "Unsupported host prerequisite recipe for ${ARG_MMAKE_NAME}")
      endif()
      list(APPEND _prerequisites ${_rules_${_id}_DEPENDS})
    endif()
  endforeach()
  set(_host_libraries)
  foreach(_lib IN LISTS MMAKE_USELIBS)
    get_property(_lib_target GLOBAL PROPERTY "AROS_HOST_LINKLIB_${_lib}")
    if(NOT _lib_target)
      foreach(_dependency IN LISTS _prerequisites)
        aros_find_mmake_entrypoint(_lib_producer OPTIONAL NAMES "${_dependency}" KINDS build_linklib)
        if(_lib_producer_FOUND AND _lib_producer_libname STREQUAL _lib
           AND _lib_producer_compiler MATCHES "^(host|kernel)$")
          set(_lib_target "aros-${_lib}-linklib-native")
          aros_add_mmake_host_target("${_lib_target}"
            MMAKE_NAME "${_lib_producer_mmake}" DEPENDS ${ARG_DEPENDS})
          break()
        endif()
      endforeach()
    endif()
    if(NOT _lib_target)
      message(FATAL_ERROR "No declared native host archive producer for ${_lib} (${target_name})")
    endif()
    list(APPEND _host_libraries "${_lib_target}")
  endforeach()
  set(_native_dependencies)
  foreach(_dependency IN LISTS _prerequisites)
    get_property(_provider GLOBAL PROPERTY "AROS_HOST_MMAKE_${_dependency}")
    if(NOT _provider)
      aros_find_mmake_entrypoint(_dep OPTIONAL NAMES "${_dependency}" KINDS build_linklib)
      if(_dep_FOUND)
        _aros_sanitize_property_key("${_dep_libname}" _key)
        get_property(_provider GLOBAL PROPERTY "AROS_REGISTERED_LINKLIB_TARGET_${_key}")
      endif()
    endif()
    if(NOT _provider)
      message(FATAL_ERROR "No native provider for hosted prerequisite ${_dependency}")
    endif()
    list(APPEND _native_dependencies "${_provider}")
  endforeach()
  set(_objects)
  if(MMAKE_BASE_SOURCES)
    list(PREPEND MMAKE_GROUPS base)
    set(MMAKE_SOURCES_base "${MMAKE_BASE_SOURCES}")
    set(MMAKE_FLAGS_base "${MMAKE_BASE_FLAGS}")
  endif()
  foreach(_group IN LISTS MMAKE_GROUPS)
    set(_obj "${target_name}-objects-${_group}")
    add_library("${_obj}" OBJECT EXCLUDE_FROM_ALL ${MMAKE_SOURCES_${_group}})
    set_target_properties("${_obj}" PROPERTIES
      C_STANDARD 99 C_STANDARD_REQUIRED YES C_EXTENSIONS YES
      FOLDER "aros/internal/hosted")
    set(_flags "${MMAKE_FLAGS_${_group}}")
    # Keep the AROS namespaces, but let host libc and GCC built-ins win.
    _aros_host_compile_options("${_flags}" _host_flags)
    target_compile_options("${_obj}" PRIVATE ${AROS_HOST_KERNEL_COMPILE_OPTIONS} ${_host_flags})
    foreach(_source IN LISTS MMAKE_SOURCES_${_group})
      get_filename_component(_dir "${_source}" DIRECTORY)
      target_compile_options("${_obj}" PRIVATE "-iquote${_dir}")
    endforeach()
    if(ARG_DEPENDS)
      add_dependencies("${_obj}" ${ARG_DEPENDS})
    endif()
    if("aros-native-includes" IN_LIST ARG_DEPENDS)
      set_property(SOURCE ${MMAKE_SOURCES_${_group}} TARGET_DIRECTORY "${_obj}"
        APPEND PROPERTY OBJECT_DEPENDS "${AROS_NATIVE_INCLUDES_STAMP}")
    endif()
    if(ARG_HEADER_INTERFACES)
      set_property(TARGET "${_obj}" PROPERTY AROS_HOST_HEADER_INTERFACES "${ARG_HEADER_INTERFACES}")
      set_property(GLOBAL APPEND PROPERTY AROS_HOST_HEADER_CONSUMERS "${_obj}")
    endif()
    list(APPEND _objects "$<TARGET_OBJECTS:${_obj}>")
  endforeach()
  if(MMAKE_KIND STREQUAL "linklib")
    add_library("${target_name}" STATIC EXCLUDE_FROM_ALL ${_objects})
    set_target_properties("${target_name}" PROPERTIES ARCHIVE_OUTPUT_DIRECTORY "${ARG_OUTPUT_DIRECTORY}")
    set_property(GLOBAL PROPERTY "AROS_HOST_LINKLIB_${MMAKE_OUTPUT_NAME}" "${target_name}")
  else()
    add_executable("${target_name}" EXCLUDE_FROM_ALL ${_objects})
    set_target_properties("${target_name}" PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${ARG_OUTPUT_DIRECTORY}")
    target_link_options("${target_name}" PRIVATE ${AROS_HOST_KERNEL_LINK_OPTIONS})
    target_link_libraries("${target_name}" PRIVATE ${_host_libraries})
    # USER_LDFLAGS may contain libraries, which must follow the objects.
    target_link_libraries("${target_name}" PRIVATE ${MMAKE_LINK_FLAGS})
  endif()
  set_target_properties("${target_name}" PROPERTIES
    LINKER_LANGUAGE C OUTPUT_NAME "${MMAKE_OUTPUT_NAME}" FOLDER "aros/hosted"
    AROS_HOST_MANIFEST "${MODULE_MMAKEFILE}")
  if(_native_dependencies)
    add_dependencies("${target_name}" ${_native_dependencies})
  endif()
  set_property(GLOBAL PROPERTY "AROS_HOST_MMAKE_${ARG_MMAKE_NAME}" "${target_name}")
  set_property(GLOBAL PROPERTY "AROS_HOST_VISITING_${ARG_MMAKE_NAME}" FALSE)
endfunction()

function(aros_finalize_host_header_dependencies)
  get_property(_consumers GLOBAL PROPERTY AROS_HOST_HEADER_CONSUMERS)
  foreach(_consumer IN LISTS _consumers)
    get_target_property(_names "${_consumer}" AROS_HOST_HEADER_INTERFACES)
    foreach(_name IN LISTS _names)
      _aros_sanitize_property_key("${_name}" _key)
      get_property(_provider GLOBAL PROPERTY "AROS_MODULE_INTERFACE_TARGET_${_key}")
      if(NOT _provider)
        message(FATAL_ERROR "Hosted target ${_consumer} requires the ${_name} interface producer")
      endif()
      # Follow the interface producer graph without importing target-libc
      # include precedence into sources compiled against the host libc.
      add_dependencies("${_consumer}" "${_provider}")
      get_target_property(_stamp "${_provider}" AROS_MODULE_INTERFACE_STAMP)
      get_target_property(_sources "${_consumer}" SOURCES)
      set_property(SOURCE ${_sources} TARGET_DIRECTORY "${_consumer}"
        APPEND PROPERTY OBJECT_DEPENDS "${_stamp}")
    endforeach()
  endforeach()
endfunction()

if(NOT CMAKE_SCRIPT_MODE_FILE)
  cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" CALL aros_finalize_host_header_dependencies)
endif()
