include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSManifests.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSStaticDirectoryCopies.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSStaticWildcards.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSStaticPatterns.cmake")

function(_aros_rule_condition_state conditions out_var)
  set(_state TRUE)
  foreach(_condition IN LISTS conditions)
    if(_condition STREQUAL "FALSE")
      set(_state FALSE)
      break()
    elseif(_condition STREQUAL "UNKNOWN")
      set(_state UNKNOWN)
    endif()
  endforeach()
  set(${out_var} "${_state}" PARENT_SCOPE)
endfunction()

function(_aros_mmake_directory_recipe recipe out_var)
  string(REGEX REPLACE "[ \t]+" " " _recipe "${recipe}")
  set(_dirs)
  if(_recipe MATCHES "^%mkdirs_q (.*)$")
    _aros_expand_make_tokens("${CMAKE_MATCH_1}" _dirs)
    separate_arguments(_dirs UNIX_COMMAND "${_dirs}")
  elseif(_recipe MATCHES "^@?\\$\\(IF\\) \\$\\(TEST\\) ! -d (.+) ; then \\$\\(MKDIR\\) (.+) ; else \\$\\(NOP\\) ; fi$")
    set(_test "${CMAKE_MATCH_1}")
    set(_mkdir "${CMAKE_MATCH_2}")
    if(_test STREQUAL _mkdir)
      _aros_expand_make_tokens("${_mkdir}" _dir)
      separate_arguments(_dirs UNIX_COMMAND "${_dir}")
      list(LENGTH _dirs _count)
      if(NOT _count EQUAL 1)
        set(_dirs)
      endif()
    endif()
  endif()
  set(${out_var} "${_dirs}" PARENT_SCOPE)
endfunction()

function(_aros_expand_rule_recipe recipe targets out_var)
  foreach(_id IN LISTS _target_variables)
    foreach(_target IN LISTS targets)
      if(_target IN_LIST _target_variable_${_id}_TARGETS)
        set(_AROS_MMAKE_VAR_${_target_variable_${_id}_NAME} "${_target_variable_${_id}_VALUE}")
      endif()
    endforeach()
  endforeach()
  if(_AROS_RULE_PRESERVE_DOLLARS)
    if(recipe MATCHES "@AROS_LITERAL_DOLLAR@")
      message(FATAL_ERROR "Reserved recipe marker in ${recipe}")
    endif()
    string(REPLACE "$$" "@AROS_LITERAL_DOLLAR@" recipe "${recipe}")
  endif()
  _aros_expand_make_tokens("${recipe}" _expanded)
  if(_AROS_RULE_PRESERVE_DOLLARS)
    string(REPLACE "@AROS_LITERAL_DOLLAR@" "$$" _expanded "${_expanded}")
  endif()
  set(${out_var} "${_expanded}" PARENT_SCOPE)
endfunction()

# Read local rule edges separately from build macros. Recipes remain data;
# only explicitly supported patterns may be translated by their consumers.
macro(_aros_rule_assignment)
  # Uses the current rule-reader scope, including variable flavor and condition.
  if(NOT (_mode STREQUAL "?=" AND DEFINED _AROS_MMAKE_VAR_${_name}))
    if(_active STREQUAL "UNKNOWN")
      set(_AROS_MMAKE_VAR_${_name} "$<unresolved-rule-condition:${_name}>")
      set(_simple_${_name} FALSE)
    else()
      if(_mode STREQUAL ":=" OR (_mode STREQUAL "+=" AND _simple_${_name}))
        _aros_expand_make_tokens("${_value}" _value)
      endif()
      if(_mode STREQUAL "+=" AND DEFINED _AROS_MMAKE_VAR_${_name})
        string(APPEND _AROS_MMAKE_VAR_${_name} " ${_value}")
      else()
        set(_AROS_MMAKE_VAR_${_name} "${_value}")
        set(_simple_${_name} FALSE)
        if(_mode STREQUAL ":=")
          set(_simple_${_name} TRUE)
        endif()
      endif()
    endif()
  endif()
endmacro()

function(_aros_collect_mmake_rules manifest prefix)
  _aros_set_make_context_for_file("${manifest}")
  _aros_read_mmake_logical_lines("${manifest}" _lines PRESERVE_RECIPES)
  set(_conditions)
  set(_rules)
  set(_macros)
  set(_includes)
  set(_option_inputs)
  set(_target_variables)
  set(_current "")
  set(_mark_metadata FALSE)
  foreach(_line IN LISTS _lines)
    if(_line MATCHES "^\t" OR
       (NOT _current STREQUAL "" AND _line MATCHES "^%mkdirs_q[ \t]"))
      # genmf emits a tabbed recipe for mkdirs_q even when the macro call
      # itself uses spaces (or no indentation) in mmakefile.src.
      _aros_rule_condition_state("${_conditions}" _active)
      if(NOT _active STREQUAL "TRUE")
        continue()
      endif()
      if(NOT _current STREQUAL "")
        string(STRIP "${_line}" _recipe)
        _aros_mmake_directory_recipe("${_recipe}" _dirs)
        if(_dirs)
          set("${prefix}_${_current}_DIRECTORIES" "${_dirs}" PARENT_SCOPE)
        endif()
        set("${prefix}_${_current}_RECIPE_${_recipe_count}" "${_recipe}" PARENT_SCOPE)
        set(_recipe_${_current}_${_recipe_count} "${_recipe}")
        math(EXPR _recipe_count "${_recipe_count} + 1")
        set(_count_${_current} "${_recipe_count}")
        set("${prefix}_${_current}_RECIPE_COUNT" "${_recipe_count}" PARENT_SCOPE)
      endif()
      continue()
    endif()
    if(_line MATCHES "^ifn?eq[ \t]*\\(.*\\)$")
      _aros_rule_condition_state("${_conditions}" _parent_state)
      if(_parent_state STREQUAL "FALSE")
        list(APPEND _conditions FALSE)
        continue()
      endif()
      # Commas inside nested Make calls are not condition separators.
      string(REGEX MATCH "^(ifn?eq)[ \t]*\\((.*)\\)$" _condition "${_line}")
      set(_operator "${CMAKE_MATCH_1}")
      _aros_split_make_arguments("${CMAKE_MATCH_2}" _arguments)
      list(LENGTH _arguments _count)
      if(NOT _count EQUAL 2)
        message(FATAL_ERROR "Unsupported rule conditional in ${manifest}: ${_line}")
      endif()
      list(GET _arguments 0 _left)
      list(GET _arguments 1 _right)
      _aros_expand_make_tokens("${_left}" _left)
      _aros_expand_make_tokens("${_right}" _right)
      if("${_left}${_right}" MATCHES "\\$|@[^@ \t]+@")
        if(NOT _AROS_RULE_GRAPH_ONLY)
          message(FATAL_ERROR "Unresolved rule conditional in ${manifest}: ${_line}")
        endif()
        set(_active UNKNOWN)
      elseif((_operator STREQUAL "ifeq" AND _left STREQUAL _right)
         OR (_operator STREQUAL "ifneq" AND NOT _left STREQUAL _right))
        set(_active TRUE)
      else()
        set(_active FALSE)
      endif()
      list(APPEND _conditions "${_active}")
      continue()
    elseif(_line STREQUAL "else")
      if("${_conditions}" STREQUAL "")
        message(FATAL_ERROR "Unmatched rule else in ${manifest}")
      endif()
      list(POP_BACK _conditions _active)
      if(_active STREQUAL "UNKNOWN")
        list(APPEND _conditions UNKNOWN)
      elseif(_active)
        list(APPEND _conditions FALSE)
      else()
        list(APPEND _conditions TRUE)
      endif()
      continue()
    elseif(_line STREQUAL "endif")
      if("${_conditions}" STREQUAL "")
        message(FATAL_ERROR "Unmatched rule endif in ${manifest}")
      endif()
      list(POP_BACK _conditions)
      continue()
    elseif(_line MATCHES "^(ifn?def|ifn?eq|else)[ \t]")
      message(FATAL_ERROR "Unsupported rule conditional in ${manifest}: ${_line}")
    endif()
    _aros_rule_condition_state("${_conditions}" _active)
    if(_active STREQUAL "FALSE")
      set(_current "")
      continue()
    endif()
    if(_line MATCHES "^-?include[ \t]+(.*)$")
      if(_active STREQUAL "UNKNOWN")
        message(FATAL_ERROR "Unresolved rule conditional controls an include in ${manifest}: ${_line}")
      endif()
      _aros_expand_make_tokens("${CMAKE_MATCH_1}" _include_paths)
      separate_arguments(_include_paths UNIX_COMMAND "${_include_paths}")
      list(APPEND _includes ${_include_paths})
      if(_AROS_RULE_OPTION_INCLUDES)
        foreach(_option IN LISTS _include_paths)
          if(_option STREQUAL "${CMAKE_SOURCE_DIR}/config/aros.cfg")
            continue()
          endif()
          _aros_read_assignment_options("${_option}" "${CMAKE_SOURCE_DIR}"
            "${CMAKE_BINARY_DIR}" "${AROS_LEGACY_BUILD_DIR}" _option_lines)
          foreach(_option_line IN LISTS _option_lines)
            if(_option_line MATCHES "^[ ]*#MM")
              message(FATAL_ERROR "Unsupported options include metadata in ${_option}: ${_option_line}")
            endif()
            if(_option_line MATCHES "^[ ]*(#|$)")
              continue()
            endif()
            if(NOT _option_line MATCHES "^[ ]*([A-Za-z0-9_-]+)[ \t]*(\\+=|:=|\\?=|=)[ \t]*(.*)$")
              message(FATAL_ERROR "Unsupported options include statement in ${_option}: ${_option_line}")
            endif()
            set(_name "${CMAKE_MATCH_1}")
            set(_mode "${CMAKE_MATCH_2}")
            set(_value "${CMAKE_MATCH_3}")
            _aros_rule_assignment()
          endforeach()
          list(APPEND _option_inputs "${_option}")
          set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_option}")
        endforeach()
      endif()
      set(_current "")
      continue()
    endif()
    if(_AROS_RULE_MACRO_COLLECTOR AND _line MATCHES "^%([A-Za-z0-9_]+)([ \t]+(.*))?$")
      set(_kind "${CMAKE_MATCH_1}")
      set(_args "${CMAKE_MATCH_3}")
      list(LENGTH _macros _id)
      cmake_language(CALL "${_AROS_RULE_MACRO_COLLECTOR}" "${_kind}" "${_args}" _macro)
      if(_macro_FIELDS)
        if(_active STREQUAL "UNKNOWN")
          message(FATAL_ERROR "Unresolved rule conditional controls a producer in ${manifest}: ${_line}")
        endif()
        list(APPEND _macros "${_id}")
        foreach(_field IN LISTS _macro_FIELDS)
          set("${prefix}_MACRO_${_id}_${_field}" "${_macro_${_field}}" PARENT_SCOPE)
        endforeach()
      endif()
      set(_current "")
      continue()
    endif()
    if(_line MATCHES "^([A-Za-z0-9_-]+)[ \t]*(\\+=|:=|\\?=|=)[ \t]*(.*)$")
      set(_name "${CMAKE_MATCH_1}")
      set(_mode "${CMAKE_MATCH_2}")
      set(_value "${CMAKE_MATCH_3}")
      _aros_rule_assignment()
      set(_current "")
      continue()
    endif()
    if(_line STREQUAL "#MM")
      if(_AROS_RULE_GRAPH_ONLY AND _active STREQUAL "UNKNOWN")
        message(FATAL_ERROR "Unresolved rule conditional controls metadata in ${manifest}: ${_line}")
      endif()
      set(_mark_metadata TRUE)
      continue()
    elseif(_line MATCHES "^#MM-?[ \t]+")
      string(REGEX REPLACE "^#MM-?[ \t]+" "" _line "${_line}")
      set(_metadata TRUE)
      if(NOT _line MATCHES ":")
        string(APPEND _line " :")
      endif()
    elseif(_line MATCHES "^#")
      continue()
    else()
      set(_metadata FALSE)
    endif()
    set(_current "")
    if(_AROS_RULE_GRAPH_ONLY)
      if(NOT _metadata AND NOT _mark_metadata)
        continue()
      elseif(_active STREQUAL "UNKNOWN")
        message(FATAL_ERROR "Unresolved rule conditional controls metadata in ${manifest}: ${_line}")
      endif()
    endif()
    if(_AROS_RULE_EXPAND_RECIPES AND NOT _metadata
       AND _line MATCHES "^([^:]+):[ \t]+([A-Za-z0-9_-]+)[ \t]*(:=|=)[ \t]*(.*)$")
      set(_targets "${CMAKE_MATCH_1}")
      set(_name "${CMAKE_MATCH_2}")
      set(_mode "${CMAKE_MATCH_3}")
      set(_value "${CMAKE_MATCH_4}")
      _aros_expand_make_tokens("${_targets}" _targets)
      separate_arguments(_targets UNIX_COMMAND "${_targets}")
      if(_mode STREQUAL ":=")
        _aros_expand_make_tokens("${_value}" _value)
      endif()
      list(LENGTH _target_variables _id)
      list(APPEND _target_variables "${_id}")
      set(_target_variable_${_id}_TARGETS "${_targets}")
      set(_target_variable_${_id}_NAME "${_name}")
      set(_target_variable_${_id}_VALUE "${_value}")
      set("${prefix}_TARGET_VARIABLE_${_id}_TARGETS" "${_targets}" PARENT_SCOPE)
      continue()
    endif()
    if(NOT _line MATCHES "^([^:]+)::?[ \t]*(.*)$")
      continue()
    endif()
    set(_targets "${CMAKE_MATCH_1}")
    set(_deps "${CMAKE_MATCH_2}")
    _aros_expand_make_tokens("${_targets}" _targets)
    _aros_expand_make_tokens("${_deps}" _deps)
    if(_AROS_RULE_GRAPH_ONLY AND _targets MATCHES "\\$|@[^@ \t]+@")
      message(FATAL_ERROR "Unresolved program discovery target in ${manifest}: ${_targets}")
    endif()
    string(REPLACE ";" " " _deps "${_deps}")
    separate_arguments(_targets UNIX_COMMAND "${_targets}")
    separate_arguments(_deps UNIX_COMMAND "${_deps}")
    list(LENGTH _rules _id)
    list(APPEND _rules "${_id}")
    set(_count_${_id} 0)
    set(_targets_${_id} "${_targets}")
    set("${prefix}_${_id}_TARGETS" "${_targets}" PARENT_SCOPE)
    set("${prefix}_${_id}_DEPENDS" "${_deps}" PARENT_SCOPE)
    set("${prefix}_${_id}_RECIPE_COUNT" 0 PARENT_SCOPE)
    set("${prefix}_${_id}_DIRECTORIES" "" PARENT_SCOPE)
    set("${prefix}_${_id}_METADATA" "${_metadata}" PARENT_SCOPE)
    set("${prefix}_${_id}_EXPORTED" FALSE PARENT_SCOPE)
    if(_metadata OR _mark_metadata)
      set("${prefix}_${_id}_EXPORTED" TRUE PARENT_SCOPE)
    endif()
    set(_mark_metadata FALSE)
    if(NOT _metadata)
      set(_current "${_id}")
      set(_recipe_count 0)
    endif()
  endforeach()
  list(LENGTH _conditions _depth)
  if(_depth GREATER 0)
    message(FATAL_ERROR "Unclosed conditional in ${manifest}")
  endif()
  set("${prefix}_RULES" "${_rules}" PARENT_SCOPE)
  set("${prefix}_MACROS" "${_macros}" PARENT_SCOPE)
  set("${prefix}_INCLUDES" "${_includes}" PARENT_SCOPE)
  set("${prefix}_OPTION_INPUTS" "${_option_inputs}" PARENT_SCOPE)
  set("${prefix}_TARGET_VARIABLES" "${_target_variables}" PARENT_SCOPE)
  if(_AROS_RULE_DIRECTORY_COPIES)
    foreach(_id IN LISTS _rules)
      set("${prefix}_${_id}_DIRECTORY_COPY_MATCH" FALSE PARENT_SCOPE)
      if(_count_${_id} EQUAL 1)
        _aros_mmake_directory_copy_recipe("${_recipe_${_id}_0}" _copy)
        foreach(_field IN ITEMS MATCH SOURCE DESTINATION)
          set("${prefix}_${_id}_DIRECTORY_COPY_${_field}" "${_copy_${_field}}" PARENT_SCOPE)
        endforeach()
      endif()
    endforeach()
  endif()
  # Unlike macro arguments, recipe variables are evaluated after the manifest
  # has been read. Consumers opt in to the variables their recipes understand.
  foreach(_variable IN LISTS _AROS_RULE_RECIPE_VARIABLES)
    _aros_expand_make_tokens("$(${_variable})" _value)
    set("${prefix}_VARIABLE_${_variable}" "${_value}" PARENT_SCOPE)
  endforeach()
  if(_AROS_RULE_EXPAND_ECHO OR _AROS_RULE_EXPAND_RECIPES)
    foreach(_id IN LISTS _rules)
      set(_index 0)
      while(_index LESS _count_${_id})
        set(_arguments "")
        if(_recipe_${_id}_${_index} MATCHES "^@?\\$\\(ECHO\\)[ \t]+(.+)$")
          _aros_expand_rule_recipe("${CMAKE_MATCH_1}" "${_targets_${_id}}" _arguments)
        endif()
        set("${prefix}_${_id}_ECHO_${_index}" "${_arguments}" PARENT_SCOPE)
        if(_AROS_RULE_EXPAND_RECIPES)
          _aros_expand_rule_recipe("${_recipe_${_id}_${_index}}" "${_targets_${_id}}" _expanded)
          set("${prefix}_${_id}_EXPANDED_${_index}" "${_expanded}" PARENT_SCOPE)
        endif()
        math(EXPR _index "${_index} + 1")
      endwhile()
    endforeach()
  endif()
endfunction()

function(_aros_static_real_path path out_var)
  if(EXISTS "${path}")
    file(REAL_PATH "${path}" _real)
  elseif(IS_SYMLINK "${path}")
    message(FATAL_ERROR "Static-file destination has a dangling symlink: ${path}")
  else()
    get_filename_component(_parent "${path}" DIRECTORY)
    get_filename_component(_name "${path}" NAME)
    _aros_static_real_path("${_parent}" _parent)
    set(_real "${_parent}/${_name}")
  endif()
  set(${out_var} "${_real}" PARENT_SCOPE)
endfunction()

function(_aros_static_output_path path out_var)
  get_filename_component(_path "${path}" ABSOLUTE)
  file(RELATIVE_PATH _relative "${AROS_NATIVE_SYSTEM_DIR}" "${_path}")
  if(NOT IS_ABSOLUTE "${path}" OR _relative MATCHES "^\\.\\.(/|$)"
     OR IS_ABSOLUTE "${_relative}" OR _relative STREQUAL "" OR path MATCHES "[$%*?]")
    message(FATAL_ERROR "Static-file destination is outside the native runtime tree or unresolved: ${path}")
  endif()
  _aros_static_real_path("${_path}" _real)
  _aros_static_real_path("${AROS_NATIVE_SYSTEM_DIR}" _root)
  file(RELATIVE_PATH _relative "${_root}" "${_real}")
  if(_relative MATCHES "^\\.\\.(/|$)" OR IS_ABSOLUTE "${_relative}")
    message(FATAL_ERROR "Static-file destination escapes the native runtime tree: ${path}")
  endif()
  set(${out_var} "${_path}" PARENT_SCOPE)
endfunction()

# Check ordinary rule edges separately from the registry's global #MM cycles.
function(_aros_check_static_local_cycle node prefix)
  set(_stack ${ARGN})
  if(node IN_LIST _stack)
    message(FATAL_ERROR "Unsupported static local dependency cycle at ${node}")
  endif()
  list(APPEND _stack "${node}")
  foreach(_id IN LISTS ${prefix}_RULES)
    if(NOT ${prefix}_${_id}_METADATA AND node IN_LIST ${prefix}_${_id}_TARGETS)
      foreach(_dep IN LISTS ${prefix}_${_id}_DEPENDS)
        _aros_check_static_local_cycle("${_dep}" "${prefix}" ${_stack})
      endforeach()
    endif()
  endforeach()
endfunction()

# Collect only static-data outputs reachable from the selected manifest
# target. Other build kinds (programs/modules) remain the registry's job.
function(aros_collect_mmake_static_files manifest mmake prefix)
  cmake_parse_arguments(ARG "STRICT;LOCAL_ONLY;LOCAL_NODE" "" "" ${ARGN})
  if(ARG_LOCAL_NODE AND NOT ARG_STRICT)
    message(FATAL_ERROR "Local static nodes require strict validation")
  endif()
  set(_AROS_MMAKE_VAR_AROSDIR "${AROS_NATIVE_SYSTEM_DIR}")
  set(_AROS_RULE_EXPAND_ECHO TRUE)
  set(_AROS_RULE_DIRECTORY_COPIES TRUE)
  set(_AROS_MMAKE_CALL_EXPANDER _aros_expand_static_wildcard)
  _aros_collect_mmake_rules("${manifest}" _mm)
  if(ARG_LOCAL_ONLY)
    # Local make rules and global #MM edges are different graphs. A local
    # migration slice must never register itself as the global aggregate.
    set(_local_rules)
    foreach(_id IN LISTS _mm_RULES)
      if(NOT _mm_${_id}_METADATA)
        list(APPEND _local_rules "${_id}")
      endif()
    endforeach()
    set(_mm_RULES "${_local_rules}")
  endif()
  _aros_expand_static_pattern_rules("${manifest}" "${mmake}" _mm "${ARG_STRICT}")
  set(_reachable "${mmake}")
  set(_changed TRUE)
  while(_changed)
    set(_changed FALSE)
    foreach(_id IN LISTS _mm_RULES)
      # Metadata names are global. Resolve them through the inventory even if
      # this manifest also defines that name; another layer may augment it.
      if(ARG_STRICT AND _mm_${_id}_METADATA)
        continue()
      endif()
      foreach(_name IN LISTS _mm_${_id}_TARGETS)
        if(_name IN_LIST _reachable)
          foreach(_dep IN LISTS _mm_${_id}_DEPENDS)
            if(NOT _dep IN_LIST _reachable)
              list(APPEND _reachable "${_dep}")
              set(_changed TRUE)
            endif()
          endforeach()
        endif()
      endforeach()
    endforeach()
  endwhile()
  get_filename_component(_source_dir "${manifest}" DIRECTORY)
  set(_copies)
  set(_texts)
  set(_directories)
  set(_external)
  set(_exported FALSE)
  set(_local_node FALSE)
  foreach(_id IN LISTS _mm_RULES)
    if(_mm_${_id}_EXPORTED AND mmake IN_LIST _mm_${_id}_TARGETS)
      set(_exported TRUE)
    endif()
    if(NOT _mm_${_id}_METADATA AND mmake IN_LIST _mm_${_id}_TARGETS)
      set(_local_node TRUE)
    endif()
  endforeach()
  set("${prefix}_EXPORTED" "${_exported}" PARENT_SCOPE)
  if(ARG_LOCAL_NODE AND NOT _local_node)
    message(FATAL_ERROR "No local static rule for ${mmake} in ${manifest}")
  endif()
  if(ARG_STRICT AND NOT _exported AND NOT ARG_LOCAL_NODE)
    return()
  endif()
  if(ARG_STRICT)
    _aros_check_static_local_cycle("${mmake}" _mm)
  endif()
  foreach(_id IN LISTS _mm_RULES)
    set(_copy FALSE)
    set(_selected FALSE)
    foreach(_name IN LISTS _mm_${_id}_TARGETS)
      if(_name IN_LIST _reachable)
        set(_selected TRUE)
      endif()
    endforeach()
    if(NOT _selected)
      continue()
    endif()
    if(_mm_${_id}_DIRECTORY_COPY_MATCH)
      list(LENGTH _mm_${_id}_TARGETS _target_count)
      if(NOT _target_count EQUAL 1 OR _mm_${_id}_DEPENDS)
        message(FATAL_ERROR "Unsupported static directory copy targets/prerequisites in ${manifest}")
      endif()
      _aros_collect_static_directory_copy("${manifest}"
        "${_mm_${_id}_DIRECTORY_COPY_SOURCE}" "${_mm_${_id}_DIRECTORY_COPY_DESTINATION}" _batch)
      # Each file copy creates its parent. Do not also claim that directory
      # as an output: an explicit setup rule may already own it.
      set(_index 0)
      foreach(_input IN LISTS _batch_INPUTS)
        # Declared generated files cannot become static inputs merely because
        # an earlier build left them in the source directory.
        foreach(_other IN LISTS _mm_RULES)
          foreach(_target IN LISTS _mm_${_other}_TARGETS)
            get_filename_component(_target "${_target}" ABSOLUTE BASE_DIR "${_source_dir}")
            string(REPLACE "%" "AROSSTATICCOPYSTEM" _pattern "${_target}")
            string(REGEX REPLACE "([^A-Za-z0-9_-])" "\\\\\\1" _pattern "${_pattern}")
            string(REPLACE AROSSTATICCOPYSTEM ".*" _pattern "${_pattern}")
            if(_input MATCHES "^${_pattern}$")
              message(FATAL_ERROR "Static copy cannot adopt a generated prerequisite ${_input}")
            endif()
          endforeach()
        endforeach()
        get_filename_component(_name "${_input}" NAME)
        _aros_static_output_path("${_batch_DESTINATION}/${_name}" _output)
        set(_entry "directory_${_id}_${_index}")
        list(APPEND _copies "${_entry}")
        set("${prefix}_${_entry}_OUTPUT" "${_output}" PARENT_SCOPE)
        set("${prefix}_${_entry}_INPUTS" "${_input}" PARENT_SCOPE)
        set("${prefix}_${_entry}_DIRECTORIES" "" PARENT_SCOPE)
        math(EXPR _index "${_index} + 1")
      endforeach()
      continue()
    endif()
    if(_mm_${_id}_METADATA)
      foreach(_dep IN LISTS _mm_${_id}_DEPENDS)
        set(_local FALSE)
        if(NOT ARG_STRICT)
          foreach(_other IN LISTS _mm_RULES)
            if(_dep IN_LIST _mm_${_other}_TARGETS)
              set(_local TRUE)
            endif()
          endforeach()
        endif()
        if(NOT _local)
          list(APPEND _external "${_dep}")
        endif()
      endforeach()
    endif()
    set(_index 0)
    while(_index LESS _mm_${_id}_RECIPE_COUNT)
      if(_mm_${_id}_RECIPE_${_index} MATCHES "\\$\\(CP\\)")
        set(_copy TRUE)
      endif()
      math(EXPR _index "${_index} + 1")
    endwhile()
    if(NOT _copy)
      if(_mm_${_id}_RECIPE_0 MATCHES "^@?\\$\\(ECHO\\)[ \t]")
        _aros_collect_mmake_text("${manifest}" _mm "${_id}" _content _config_inputs)
        list(APPEND _texts "${_id}")
        set("${prefix}_${_id}_OUTPUT" "${_mm_${_id}_TARGETS}" PARENT_SCOPE)
        set("${prefix}_${_id}_CONTENT" "${_content}" PARENT_SCOPE)
        set("${prefix}_${_id}_INPUTS" "${_config_inputs}" PARENT_SCOPE)
        set("${prefix}_${_id}_DIRECTORIES" "" PARENT_SCOPE)
        continue()
      endif()
      if(ARG_STRICT AND _mm_${_id}_RECIPE_COUNT GREATER 0)
        if(NOT _mm_${_id}_RECIPE_COUNT EQUAL 1 OR
           (NOT _mm_${_id}_DIRECTORIES AND NOT _mm_${_id}_RECIPE_0 MATCHES "^@?\\$\\(NOP\\)$"))
          message(FATAL_ERROR "Unsupported static prerequisite recipe in ${manifest}: ${_mm_${_id}_TARGETS}")
        endif()
        if(_mm_${_id}_DIRECTORIES AND _mm_${_id}_DEPENDS)
          message(FATAL_ERROR "Unsupported prerequisite of directory setup in ${manifest}")
        endif()
        foreach(_dir IN LISTS _mm_${_id}_DIRECTORIES)
          _aros_static_output_path("${_dir}" _dir)
          list(APPEND _directories "${_dir}")
        endforeach()
      endif()
      continue()
    endif()
    list(LENGTH _mm_${_id}_TARGETS _target_count)
    if(NOT _target_count EQUAL 1 OR NOT _mm_${_id}_RECIPE_COUNT EQUAL 1
       OR NOT _mm_${_id}_RECIPE_0 MATCHES "^@?\\$\\(CP\\)[ \t]+\\$[<^][ \t]+\\$@$"
       OR NOT _mm_${_id}_DEPENDS)
      message(FATAL_ERROR "Unsupported static copy recipe in ${manifest}: ${_mm_${_id}_TARGETS}")
    endif()
    _aros_static_output_path("${_mm_${_id}_TARGETS}" _output)
    set(_inputs)
    set(_dirs)
    set(_first TRUE)
    set(_order_only FALSE)
    set(_normal_inputs)
    set(_all_inputs FALSE)
    if(_mm_${_id}_RECIPE_0 MATCHES "\\$\\^")
      set(_all_inputs TRUE)
    endif()
    foreach(_dep IN LISTS _mm_${_id}_DEPENDS)
      if(_dep STREQUAL "|")
        set(_order_only TRUE)
        continue()
      endif()
      set(_helper FALSE)
      foreach(_other IN LISTS _mm_RULES)
        if(ARG_STRICT AND _dep IN_LIST _mm_${_other}_TARGETS
           AND NOT _mm_${_other}_METADATA AND NOT _mm_${_other}_DIRECTORIES)
          message(FATAL_ERROR "Static copy cannot adopt a generated prerequisite ${_dep} in ${manifest}")
        endif()
        if(_dep IN_LIST _mm_${_other}_TARGETS AND _mm_${_other}_RECIPE_COUNT GREATER 0)
          if(_first OR (_all_inputs AND NOT _order_only) OR NOT _mm_${_other}_RECIPE_COUNT EQUAL 1
             OR _mm_${_other}_DEPENDS OR NOT _mm_${_other}_DIRECTORIES)
            message(FATAL_ERROR "Unsupported prerequisite ${_dep} of static copy ${_output}")
          endif()
          # Directory macros use the same variable context as their rule.
          foreach(_dir IN LISTS _mm_${_other}_DIRECTORIES)
            _aros_static_output_path("${_dir}" _dir)
            list(APPEND _dirs "${_dir}")
          endforeach()
          set(_helper TRUE)
        endif()
      endforeach()
      if(NOT _helper)
        get_filename_component(_input "${_dep}" ABSOLUTE BASE_DIR "${_source_dir}")
        if(NOT EXISTS "${_input}" OR IS_DIRECTORY "${_input}" OR _dep MATCHES "[$%*?]")
          message(FATAL_ERROR "Static copy requires an existing source file, got ${_dep} in ${manifest}")
        endif()
        if(ARG_STRICT)
          _aros_static_owned_source("${_input}")
          _aros_static_reject_generated_source("${manifest}" _mm "${_input}")
        endif()
        list(APPEND _inputs "${_input}")
        if(NOT _order_only)
          list(APPEND _normal_inputs "${_input}")
        endif()
      endif()
      set(_first FALSE)
    endforeach()
    list(REMOVE_DUPLICATES _normal_inputs)
    list(LENGTH _normal_inputs _input_count)
    if(_input_count EQUAL 0)
      message(FATAL_ERROR "Static copy needs at least one normal source in ${manifest}")
    endif()
    if(_all_inputs AND NOT _input_count EQUAL 1)
      message(FATAL_ERROR "Static CP $^ copy needs exactly one source in ${manifest}")
    endif()
    list(APPEND _copies "${_id}")
    set("${prefix}_${_id}_OUTPUT" "${_output}" PARENT_SCOPE)
    set("${prefix}_${_id}_INPUTS" "${_inputs}" PARENT_SCOPE)
    set("${prefix}_${_id}_DIRECTORIES" "${_dirs}" PARENT_SCOPE)
  endforeach()
  if(ARG_STRICT)
    foreach(_node IN LISTS _reachable)
      set(_known FALSE)
      foreach(_id IN LISTS _mm_RULES)
        if(_node IN_LIST _mm_${_id}_TARGETS)
          set(_known TRUE)
        endif()
      endforeach()
      if(NOT _known AND IS_ABSOLUTE "${_node}")
        file(RELATIVE_PATH _relative "${AROS_NATIVE_SYSTEM_DIR}" "${_node}")
        if(NOT _relative MATCHES "^\\.\\.(/|$)" AND NOT IS_ABSOLUTE "${_relative}")
          message(FATAL_ERROR "Unhandled static prerequisite without a native producer: ${_node}")
        endif()
      endif()
      if(NOT _known AND NOT _node IN_LIST _external AND NOT _node STREQUAL "|"
         AND NOT EXISTS "${_source_dir}/${_node}" AND NOT (IS_ABSOLUTE "${_node}" AND EXISTS "${_node}"))
        message(FATAL_ERROR "Unhandled static prerequisite ${_node} in ${manifest}")
      endif()
    endforeach()
  endif()
  set("${prefix}_EXPORTED" "${_exported}" PARENT_SCOPE)
  set("${prefix}_EXTERNAL_MMAKE" "${_external}" PARENT_SCOPE)
  set("${prefix}_DIRECTORIES" "${_directories}" PARENT_SCOPE)
  set("${prefix}_COPIES" "${_copies}" PARENT_SCOPE)
  set("${prefix}_TEXTS" "${_texts}" PARENT_SCOPE)
endfunction()

# Recognize data, never execute shell recipes. In particular, echo options,
# escapes, substitutions, append redirection, and extra commands are not text.
function(_aros_collect_mmake_text manifest prefix id out_var out_inputs)
  set(_entry "${prefix}_${id}")
  list(LENGTH ${_entry}_TARGETS _count)
  if(NOT _count EQUAL 1 OR ${_entry}_DEPENDS
     OR ${_entry}_RECIPE_COUNT GREATER 2)
    message(FATAL_ERROR "Unsupported static text rule or prerequisites in ${manifest}")
  endif()
  _aros_static_output_path("${${_entry}_TARGETS}" _output)
  math(EXPR _last "${${_entry}_RECIPE_COUNT} - 1")
  foreach(_index RANGE 0 ${_last})
    string(REPLACE "$@" "${_output}" _arguments "${${_entry}_ECHO_${_index}}")
    if(_index LESS _last)
      if(_arguments STREQUAL "" OR _arguments MATCHES "^[-]" OR _arguments MATCHES "[$`\\\\;|&<>\r\n]")
        message(FATAL_ERROR "Unsupported static text diagnostic in ${manifest}")
      endif()
    else()
      if(NOT _arguments MATCHES "^\"([^\"]*)\"[ \t]+>[ \t]+(\"[^\"]+\"|[^ \t\"]+)$")
        message(FATAL_ERROR "Unsupported static text ECHO recipe in ${manifest}")
      endif()
      set(_content "${CMAKE_MATCH_1}")
      set(_destination "${CMAKE_MATCH_2}")
      if(_content MATCHES "^-" OR _content MATCHES "[$`\\\\;|&<>\r\n]"
         OR _destination MATCHES "[$`\\\\;|&<>\r\n]")
        message(FATAL_ERROR "Unsupported static text expression in ${manifest}")
      endif()
      separate_arguments(_destination UNIX_COMMAND "${_destination}")
      if(NOT _destination STREQUAL _output)
        message(FATAL_ERROR "Static text redirection does not match its declared output in ${manifest}")
      endif()
    endif()
  endforeach()
  foreach(_include IN LISTS ${prefix}_INCLUDES)
    if(NOT _include STREQUAL "${CMAKE_SOURCE_DIR}/config/aros.cfg")
      message(FATAL_ERROR "Static text needs native support for included rules/options: ${_include}")
    endif()
  endforeach()
  set(_inputs)
  if(AROS_LEGACY_BUILD_DIR)
    # START LEGACY: track the configuration assignments used by the shared
    # reader, without executing configure/make or adopting their outputs.
    file(GLOB _inputs CONFIGURE_DEPENDS
      "${AROS_LEGACY_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/*.cfg"
      "${AROS_LEGACY_BUILD_DIR}/config/*.cfg" "${AROS_LEGACY_BUILD_DIR}/Makefile")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_inputs})
    # END LEGACY
  endif()
  set(${out_var} "${_content}\n" PARENT_SCOPE)
  set(${out_inputs} "${_inputs}" PARENT_SCOPE)
endfunction()

function(_aros_add_mmake_static_commands manifest prefix out_var)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")
  set(_outputs)
  set(_prerequisites ${ARGN})
  set(_directories "${${prefix}_DIRECTORIES}")
  if(_directories)
    list(REMOVE_DUPLICATES _directories)
    string(SHA256 _key "${manifest}|${_directories}|${_prerequisites}")
    set(_stamp "${CMAKE_BINARY_DIR}/static-files/${_key}.stamp")
    get_property(_registered GLOBAL PROPERTY "AROS_STATIC_DIRECTORY_${_key}")
    if(NOT _registered)
      add_custom_command(OUTPUT "${_stamp}" BYPRODUCTS ${_directories}
        COMMAND "${CMAKE_COMMAND}" -E make_directory "${CMAKE_BINARY_DIR}/static-files" ${_directories}
        COMMAND "${CMAKE_COMMAND}" -E touch "${_stamp}"
        DEPENDS "${manifest}" ${_prerequisites}
        COMMENT "Creating manifest-defined runtime directories" VERBATIM)
      set_property(GLOBAL PROPERTY "AROS_STATIC_DIRECTORY_${_key}" TRUE)
    endif()
    list(APPEND _outputs "${_stamp}")
    list(APPEND _prerequisites "${_stamp}")
  endif()
  foreach(_id IN LISTS ${prefix}_COPIES ${prefix}_TEXTS)
    set(_entry "${prefix}_${_id}")
    set(_output "${${_entry}_OUTPUT}")
    set(_text FALSE)
    if(_id IN_LIST ${prefix}_TEXTS)
      set(_text TRUE)
    else()
      list(GET ${_entry}_INPUTS 0 _source)
    endif()
    get_filename_component(_dir "${_output}" DIRECTORY)
    string(SHA256 _key "${_output}")
    set(_signature "${manifest}|${${_entry}_INPUTS}|${${_entry}_DIRECTORIES}|${_prerequisites}")
    if(_text)
      string(APPEND _signature "|text:${${_entry}_CONTENT}")
    endif()
    get_property(_producer GLOBAL PROPERTY "AROS_STATIC_FILE_${_key}")
    if(_producer AND NOT _producer STREQUAL _signature)
      message(FATAL_ERROR "Conflicting static-file producers for ${_output}")
    elseif(NOT _producer)
      if(_text)
        set(_source "${CMAKE_BINARY_DIR}/static-files/${_key}.txt")
        file(GENERATE OUTPUT "${_source}" CONTENT "${${_entry}_CONTENT}")
      endif()
      add_custom_command(OUTPUT "${_output}"
        COMMAND "${CMAKE_COMMAND}" -E make_directory "${_dir}" ${${_entry}_DIRECTORIES}
        COMMAND "${CMAKE_COMMAND}" -E copy "${_source}" "${_output}"
        DEPENDS "${_source}" ${${_entry}_INPUTS} "${manifest}" ${_prerequisites}
        COMMENT "Staging ${_source}" VERBATIM)
      set_property(GLOBAL PROPERTY "AROS_STATIC_FILE_${_key}" "${_signature}")
    endif()
    list(APPEND _outputs "${_output}")
  endforeach()
  set(${out_var} "${_outputs}" PARENT_SCOPE)
endfunction()

function(aros_add_mmake_static_files target_name)
  cmake_parse_arguments(ARG "" "MODULE_PATH;MMAKE_NAME" "" ${ARGN})
  if(NOT ARG_MODULE_PATH OR NOT ARG_MMAKE_NAME OR ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "aros_add_mmake_static_files requires MODULE_PATH and MMAKE_NAME")
  endif()
  aros_find_mmake_manifest("${CMAKE_SOURCE_DIR}/${ARG_MODULE_PATH}" _manifest)
  aros_collect_mmake_static_files("${_manifest}" "${ARG_MMAKE_NAME}" _files)
  _aros_add_mmake_static_commands("${_manifest}" _files _outputs)
  add_custom_target("${target_name}" DEPENDS ${_outputs})
  set_target_properties("${target_name}" PROPERTIES FOLDER "aros/internal/packaging")
endfunction()
