include_guard(GLOBAL)

function(_aros_static_pattern_match pattern value out_match out_stem)
  set(${out_match} FALSE PARENT_SCOPE)
  set(${out_stem} "" PARENT_SCOPE)
  if(NOT pattern MATCHES "^([^%]*)%([^%]*)$")
    return()
  endif()
  set(_before "${CMAKE_MATCH_1}")
  set(_after "${CMAKE_MATCH_2}")
  string(REGEX REPLACE "([^A-Za-z0-9_-])" "\\\\\\1" _before "${_before}")
  string(REGEX REPLACE "([^A-Za-z0-9_-])" "\\\\\\1" _after "${_after}")
  if(value MATCHES "^${_before}(.+)${_after}$")
    set(${out_match} TRUE PARENT_SCOPE)
    set(${out_stem} "${CMAKE_MATCH_1}" PARENT_SCOPE)
  endif()
endfunction()

function(_aros_static_reject_generated_source manifest prefix input)
  get_filename_component(_base "${manifest}" DIRECTORY)
  foreach(_id IN LISTS ${prefix}_RULES)
    if(${prefix}_${_id}_METADATA)
      continue()
    endif()
    foreach(_target IN LISTS ${prefix}_${_id}_TARGETS)
      get_filename_component(_target "${_target}" ABSOLUTE BASE_DIR "${_base}")
      _aros_static_pattern_match("${_target}" "${input}" _match _stem)
      if(_match OR _target STREQUAL input)
        message(FATAL_ERROR "Static copy cannot adopt a generated prerequisite ${input} in ${manifest}")
      endif()
    endforeach()
  endforeach()
endfunction()

# Instantiate only reachable, single-source CP patterns. This is not Make's
# implicit-rule search: overlapping producers and generated chains are errors.
function(_aros_expand_static_pattern_rules manifest mmake prefix skip_metadata)
  set(_pending "${mmake}")
  set(_visited)
  get_filename_component(_base "${manifest}" DIRECTORY)
  while(_pending)
    list(POP_FRONT _pending _node)
    if(_node IN_LIST _visited OR _node STREQUAL "|")
      continue()
    endif()
    list(APPEND _visited "${_node}")
    set(_explicit FALSE)
    set(_has_recipe FALSE)
    foreach(_id IN LISTS ${prefix}_RULES)
      if(skip_metadata AND ${prefix}_${_id}_METADATA)
        continue()
      endif()
      if(_node IN_LIST ${prefix}_${_id}_TARGETS)
        set(_explicit TRUE)
        if(${prefix}_${_id}_RECIPE_COUNT GREATER 0)
          set(_has_recipe TRUE)
        endif()
        list(APPEND _pending ${${prefix}_${_id}_DEPENDS})
      endif()
    endforeach()
    if(_has_recipe OR NOT IS_ABSOLUTE "${_node}")
      continue()
    endif()
    set(_matches)
    foreach(_id IN LISTS ${prefix}_RULES)
      if(${prefix}_${_id}_METADATA)
        continue()
      endif()
      foreach(_target IN LISTS ${prefix}_${_id}_TARGETS)
        _aros_static_pattern_match("${_target}" "${_node}" _match _stem)
        if(_match)
          list(APPEND _matches "${_id}")
          set(_selected_stem "${_stem}")
        endif()
      endforeach()
    endforeach()
    list(LENGTH _matches _count)
    if(_count EQUAL 0)
      continue()
    elseif(NOT _count EQUAL 1)
      message(FATAL_ERROR "Ambiguous static pattern producers for ${_node} in ${manifest}")
    endif()
    if(_explicit)
      message(FATAL_ERROR "Unsupported explicit static target relying on an implicit recipe: ${_node}")
    endif()
    list(GET _matches 0 _id)
    set(_entry "${prefix}_${_id}")
    list(LENGTH ${_entry}_TARGETS _targets)
    list(LENGTH ${_entry}_DEPENDS _deps)
    if(NOT _targets EQUAL 1 OR NOT _deps EQUAL 1
       OR NOT ${_entry}_RECIPE_COUNT EQUAL 1
       OR NOT ${_entry}_RECIPE_0 MATCHES "^@?\\$\\(CP\\)[ \t]+\\$[<^][ \t]+\\$@$"
       OR NOT "${${_entry}_DEPENDS}" MATCHES "^[^%]*%[^%]*$")
      message(FATAL_ERROR "Unsupported static copy pattern in ${manifest}: ${${_entry}_TARGETS}")
    endif()
    if(_selected_stem MATCHES "(^|/)\\.\\.(/|$)|[$%*?;|&<>`\r\n]|\\[|\\]")
      message(FATAL_ERROR "Unsafe static copy pattern stem: ${_selected_stem}")
    endif()
    _aros_static_output_path("${_node}" _output)
    string(REPLACE "%" "${_selected_stem}" _source "${${_entry}_DEPENDS}")
    get_filename_component(_source "${_source}" ABSOLUTE BASE_DIR "${_base}")
    _aros_static_owned_source("${_source}")
    _aros_static_reject_generated_source("${manifest}" "${prefix}" "${_source}")
    if(NOT EXISTS "${_source}" OR IS_DIRECTORY "${_source}")
      message(FATAL_ERROR "Static copy pattern requires an existing source file: ${_source}")
    endif()
    list(LENGTH ${prefix}_RULES _index)
    set(_new "pattern_${_index}")
    list(APPEND ${prefix}_RULES "${_new}")
    foreach(_field IN ITEMS TARGETS DEPENDS RECIPE_COUNT RECIPE_0 METADATA EXPORTED DIRECTORIES DIRECTORY_COPY_MATCH)
      set(_value "")
      if(_field STREQUAL TARGETS)
        set(_value "${_output}")
      elseif(_field STREQUAL DEPENDS)
        set(_value "${_source}")
      elseif(_field STREQUAL RECIPE_COUNT)
        set(_value 1)
      elseif(_field STREQUAL RECIPE_0)
        set(_value "${${_entry}_RECIPE_0}")
      endif()
      set(${prefix}_${_new}_${_field} "${_value}")
      set(${prefix}_${_new}_${_field} "${_value}" PARENT_SCOPE)
    endforeach()
  endwhile()
  set(${prefix}_RULES "${${prefix}_RULES}" PARENT_SCOPE)
endfunction()
