include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeEntrypoints.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSCatalogTargets.cmake")

# A bounded ordinary-rule translator for a declared /bin/sh generator whose
# stdout is the output. No recipe is passed to a shell for interpretation.
function(aros_add_mmake_script_output target_name)
  cmake_parse_arguments(ARG "CONFIGURE_PREVIEW" "MMAKE_NAME" "" ${ARGN})
  if(NOT ARG_MMAKE_NAME OR ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "aros_add_mmake_script_output requires MMAKE_NAME")
  endif()
  set(_AROS_MMAKE_VAR_AROSDIR "${AROS_NATIVE_SYSTEM_DIR}")
  set(_AROS_RULE_EXPAND_RECIPES TRUE)
  set(_AROS_RULE_EXPAND_ECHO TRUE)
  _aros_static_manifest_candidates("${ARG_MMAKE_NAME}" _candidates)
  set(_matches)
  foreach(_manifest IN LISTS _candidates)
    _aros_collect_mmake_rules("${_manifest}" _candidate)
    foreach(_id IN LISTS _candidate_RULES)
      if(NOT _candidate_${_id}_METADATA AND _candidate_${_id}_EXPORTED
         AND ARG_MMAKE_NAME IN_LIST _candidate_${_id}_TARGETS)
        list(APPEND _matches "${_manifest}")
      endif()
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES _matches)
  list(LENGTH _matches _count)
  if(NOT _count EQUAL 1)
    message(FATAL_ERROR "Expected one local script-output producer for ${ARG_MMAKE_NAME}: ${_matches}")
  endif()
  set(_manifest "${_matches}")
  get_filename_component(_source_dir "${_manifest}" DIRECTORY)
  _aros_collect_mmake_rules("${_manifest}" _rules)
  foreach(_include IN LISTS _rules_INCLUDES)
    if(NOT _include STREQUAL "${CMAKE_SOURCE_DIR}/config/aros.cfg")
      message(FATAL_ERROR "Script output needs native included-rule support: ${_include}")
    endif()
  endforeach()
  _aros_check_static_local_cycle("${ARG_MMAKE_NAME}" _rules)
  set(_queue "${ARG_MMAKE_NAME}")
  set(_visited)
  set(_inputs)
  set(_directories)
  set(_providers)
  set(_outputs)
  while(_queue)
    list(POP_FRONT _queue _node)
    if(_node IN_LIST _visited OR _node STREQUAL "|")
      continue()
    endif()
    list(APPEND _visited "${_node}")
    set(_known FALSE)
    foreach(_id IN LISTS _rules_RULES)
      if(NOT _node IN_LIST _rules_${_id}_TARGETS)
        continue()
      endif()
      if(_rules_${_id}_METADATA)
        foreach(_dep IN LISTS _rules_${_id}_DEPENDS)
          get_property(_provider GLOBAL PROPERTY "AROS_HOST_MMAKE_${_dep}")
          if(NOT _provider)
            message(FATAL_ERROR "No native provider for script-output prerequisite ${_dep}")
          endif()
          list(APPEND _providers "${_provider}")
        endforeach()
        continue()
      endif()
      set(_known TRUE)
      list(APPEND _queue ${_rules_${_id}_DEPENDS})
      if(NOT _rules_${_id}_RECIPE_COUNT)
        continue()
      endif()
      list(LENGTH _rules_${_id}_TARGETS _count)
      if(NOT _count EQUAL 1 OR _rules_${_id}_RECIPE_COUNT GREATER 2)
        message(FATAL_ERROR "Unsupported script-output rule: ${_node}")
      endif()
      _aros_static_output_path("${_node}" _destination)
      math(EXPR _last "${_rules_${_id}_RECIPE_COUNT} - 1")
      if(_last GREATER 0)
        set(_echo "${_rules_${_id}_ECHO_0}")
        string(REPLACE "$@" "${_destination}" _echo "${_echo}")
        if(NOT _echo MATCHES "^\"[^\"]*\"$" OR _echo MATCHES "[$`\\\\;|&<>\r\n]")
          message(FATAL_ERROR "Unsupported script-output diagnostic: ${_node}")
        endif()
      endif()
      set(_recipe "${_rules_${_id}_EXPANDED_${_last}}")
      if(_recipe MATCHES "^@?mkdir[ \t]+-p[ \t]+\\$@$")
        if(_rules_${_id}_DEPENDS)
          message(FATAL_ERROR "Unsupported script-output directory prerequisites: ${_node}")
        endif()
        list(APPEND _directories "${_destination}")
      elseif(_recipe MATCHES "^@?(.+)[ \t]+>[ \t]*\\$@$")
        set(_command "${CMAKE_MATCH_1}")
        if(_command MATCHES "[$`\\\\;|&<>\r\n]")
          message(FATAL_ERROR "Unsupported script-output command: ${_node}")
        endif()
        separate_arguments(_command UNIX_COMMAND "${_command}")
        list(POP_FRONT _command _script)
        _aros_catalog_static_input("${_script}")
        file(STRINGS "${_script}" _shebang LIMIT_COUNT 1)
        if(NOT _shebang STREQUAL "#!/bin/sh")
          message(FATAL_ERROR "Unsupported script-output interpreter: ${_script}")
        endif()
        list(APPEND _outputs "${_destination}")
        set(_script_args "${_script};${_command}")
      else()
        message(FATAL_ERROR "Unsupported script-output recipe: ${_recipe}")
      endif()
    endforeach()
    if(NOT _known)
      get_filename_component(_input "${_node}" ABSOLUTE BASE_DIR "${_source_dir}")
      _aros_catalog_static_input("${_input}")
      list(APPEND _inputs "${_input}")
    endif()
  endwhile()
  list(LENGTH _outputs _count)
  if(NOT _count EQUAL 1 OR NOT _script IN_LIST _inputs)
    message(FATAL_ERROR "Script output requires one output and a declared generator input")
  endif()
  foreach(_id IN LISTS _rules_TARGET_VARIABLES)
    foreach(_target IN LISTS _rules_TARGET_VARIABLE_${_id}_TARGETS)
      if(_target IN_LIST _visited AND NOT _target IN_LIST _outputs)
        message(FATAL_ERROR "Unsupported inherited script-output target variables: ${_target}")
      endif()
    endforeach()
  endforeach()
  foreach(_arg IN LISTS _command)
    if(IS_ABSOLUTE "${_arg}" AND NOT _arg IN_LIST _inputs)
      message(FATAL_ERROR "Script output has an undeclared input argument: ${_arg}")
    endif()
  endforeach()
  set(_output "${_outputs}")
  set(_config_inputs)
  if(AROS_LEGACY_BUILD_DIR)
    # START LEGACY: configuration values are still imported as metadata.
    file(GLOB _config_inputs CONFIGURE_DEPENDS
      "${AROS_LEGACY_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/*.cfg"
      "${AROS_LEGACY_BUILD_DIR}/config/*.cfg" "${AROS_LEGACY_BUILD_DIR}/Makefile")
    # END LEGACY
  endif()
  _aros_catalog_claim_output("${_output}" "script:${ARG_MMAKE_NAME}")
  find_program(_shell NAMES sh REQUIRED)
  set(_work "${CMAKE_BINARY_DIR}/script-outputs/${target_name}")
  file(MAKE_DIRECTORY "${_work}")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${_manifest}" ${_inputs} ${_config_inputs} "${_shell}")
  set(_setup_COPIES)
  set(_setup_TEXTS)
  set(_setup_DIRECTORIES "${_directories}")
  _aros_add_mmake_static_commands("${_manifest}" _setup _setup_outputs ${_providers})
  aros_add_emit_tool_stdout_file("${target_name}" OUTPUT "${_output}" PROGRAM "${_shell}"
    COMMAND_ARGS ${_script_args} WORKING_DIRECTORY "${_work}"
    DEPENDS "${_manifest}" "${_shell}" ${_inputs} ${_config_inputs} ${_setup_outputs} ${_providers})
  set_target_properties("${target_name}" PROPERTIES FOLDER "aros/hosted"
    AROS_MODULE_OUTPUT "${_output}" AROS_SCRIPT_INPUTS "${_inputs}"
    AROS_SCRIPT_MANIFEST "${_manifest}")
  if(ARG_CONFIGURE_PREVIEW)
    # The private preview lets configure discover consumers of generated data
    # on a clean tree. The packaged file remains a Ninja-owned build output.
    execute_process(COMMAND "${_shell}" ${_script_args} WORKING_DIRECTORY "${_work}"
      OUTPUT_FILE "${_work}/preview.tmp" COMMAND_ERROR_IS_FATAL ANY)
    configure_file("${_work}/preview.tmp" "${_work}/preview" COPYONLY)
    set_target_properties("${target_name}" PROPERTIES AROS_SCRIPT_PREVIEW "${_work}/preview")
  endif()
endfunction()
