include_guard(GLOBAL)

# Shared build-time manifest interpretation for modules and hosted targets.
include("${CMAKE_CURRENT_LIST_DIR}/AROSLayering.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakePrograms.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeFunctions.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSNativeConfig.cmake")

function(_aros_decode_list var_name)
  if(DEFINED ${var_name} AND NOT "${${var_name}}" STREQUAL "")
    string(REPLACE "|" ";" _decoded "${${var_name}}")
    set(${var_name} "${_decoded}" PARENT_SCOPE)
  else()
    set(${var_name} "" PARENT_SCOPE)
  endif()
endfunction()

function(_aros_remove_empty_entries var_name)
  if(NOT DEFINED ${var_name} OR "${${var_name}}" STREQUAL "")
    set(${var_name} "" PARENT_SCOPE)
    return()
  endif()

  set(_filtered_values)
  foreach(_value IN LISTS ${var_name})
    string(STRIP "${_value}" _stripped_value)
    if(NOT _stripped_value STREQUAL "")
      list(APPEND _filtered_values "${_stripped_value}")
    endif()
  endforeach()
  set(${var_name} "${_filtered_values}" PARENT_SCOPE)
endfunction()

function(_aros_remove_token_entries var_name)
  if(NOT DEFINED ${var_name} OR "${${var_name}}" STREQUAL "")
    set(${var_name} "" PARENT_SCOPE)
    return()
  endif()

  set(_filtered_values)
  foreach(_value IN LISTS ${var_name})
    string(STRIP "${_value}" _stripped_value)
    set(_keep_value TRUE)
    foreach(_remove_token IN LISTS ARGN)
      if(_stripped_value STREQUAL "${_remove_token}")
        set(_keep_value FALSE)
        break()
      endif()
    endforeach()
    if(_keep_value)
      list(APPEND _filtered_values "${_stripped_value}")
    endif()
  endforeach()
  set(${var_name} "${_filtered_values}" PARENT_SCOPE)
endfunction()

function(_aros_strip_wrapping_quotes var_name)
  if(NOT DEFINED ${var_name} OR "${${var_name}}" STREQUAL "")
    set(${var_name} "" PARENT_SCOPE)
    return()
  endif()

  set(_normalized_values)
  foreach(_value IN LISTS ${var_name})
    string(STRIP "${_value}" _normalized_value)
    string(REGEX REPLACE "^\"(.*)\"$" "\\1" _normalized_value "${_normalized_value}")
    string(REGEX REPLACE "^\"(.*)$" "\\1" _normalized_value "${_normalized_value}")
    string(REGEX REPLACE "^(.*)\"$" "\\1" _normalized_value "${_normalized_value}")
    string(STRIP "${_normalized_value}" _normalized_value)
    list(APPEND _normalized_values "${_normalized_value}")
  endforeach()
  set(${var_name} "${_normalized_values}" PARENT_SCOPE)
endfunction()

function(_aros_remove_directory_source_markers var_name)
  if(NOT DEFINED ${var_name} OR "${${var_name}}" STREQUAL "")
    set(${var_name} "" PARENT_SCOPE)
    return()
  endif()

  set(_filtered_values)
  foreach(_value IN LISTS ${var_name})
    string(STRIP "${_value}" _stripped_value)
    if(_stripped_value STREQUAL "")
      continue()
    endif()
    if(_stripped_value MATCHES "/$")
      continue()
    endif()
    list(APPEND _filtered_values "${_stripped_value}")
  endforeach()
  set(${var_name} "${_filtered_values}" PARENT_SCOPE)
endfunction()

function(_aros_tokenize_mmake_value input_value out_var)
  if("${input_value}" STREQUAL "")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  separate_arguments(_tokens NATIVE_COMMAND "${input_value}")
  # Shell quoting has already been consumed. Remaining quotes are literal,
  # notably the quotes in -DNAME=\"value\" compiler arguments.
  _aros_remove_empty_entries(_tokens)
  _aros_remove_token_entries(_tokens "\\")
  set(${out_var} "${_tokens}" PARENT_SCOPE)
endfunction()

function(_aros_encode_token_list input_list out_var)
  if("${input_list}" STREQUAL "")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  string(REPLACE ";" "__AROS_TOKEN_LIST_SEP__" _encoded "${input_list}")
  set(${out_var} "${_encoded}" PARENT_SCOPE)
endfunction()

function(_aros_decode_token_list input_value out_var)
  if("${input_value}" STREQUAL "")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  string(REPLACE "__AROS_TOKEN_LIST_SEP__" ";" _decoded "${input_value}")
  set(${out_var} "${_decoded}" PARENT_SCOPE)
endfunction()

function(_aros_remove_flag_pair var_name flag value)
  if(NOT DEFINED ${var_name} OR "${${var_name}}" STREQUAL "")
    set(${var_name} "" PARENT_SCOPE)
    return()
  endif()

  set(_result_values)
  set(_index 0)
  list(LENGTH ${var_name} _value_count)
  while(_index LESS _value_count)
    list(GET ${var_name} ${_index} _item)
    math(EXPR _next_index "${_index} + 1")
    if(_item STREQUAL "${flag}" AND _next_index LESS _value_count)
      list(GET ${var_name} ${_next_index} _next_item)
      if(_next_item STREQUAL "${value}")
        math(EXPR _index "${_index} + 2")
        continue()
      endif()
    endif()
    list(APPEND _result_values "${_item}")
    math(EXPR _index "${_index} + 1")
  endwhile()

  set(${var_name} "${_result_values}" PARENT_SCOPE)
endfunction()

function(_aros_collect_existing_public_linklibs out_var)
  set(_existing_linklibs)
  foreach(_linklib_name IN LISTS ARGN)
    if(_linklib_name STREQUAL "")
      continue()
    endif()

    foreach(_linklib_path IN ITEMS
        "${AROS_NATIVE_PUBLIC_LIB_DIR}/lib${_linklib_name}.a"
        "${AROS_NATIVE_PRIVATE_LIB_DIR}/lib${_linklib_name}.a"
        "${AROS_NATIVE_REL_LIB_DIR}/lib${_linklib_name}.a")
      if(EXISTS "${_linklib_path}")
        list(APPEND _existing_linklibs "${_linklib_name}")
        break()
      endif()
    endforeach()
  endforeach()

  list(REMOVE_DUPLICATES _existing_linklibs)
  set(${out_var} "${_existing_linklibs}" PARENT_SCOPE)
endfunction()

function(_aros_debug_var var_name)
  if(NOT DEFINED AROS_GENMODULE_DEBUG OR NOT AROS_GENMODULE_DEBUG)
    return()
  endif()

  if(DEFINED ${var_name})
    string(REPLACE ";" "\n  " _formatted "${${var_name}}")
    message(STATUS "${var_name}:\n  ${_formatted}")
  else()
    message(STATUS "${var_name}: <undefined>")
  endif()
endfunction()

function(_aros_unwrap_strip_expression input_value out_var)
  set(_value "${input_value}")
  if(_value MATCHES "^\\$\\(strip[ \t]*(.*)\\)$")
    set(_value "${CMAKE_MATCH_1}")
  endif()
  string(STRIP "${_value}" _value)
  set(${out_var} "${_value}" PARENT_SCOPE)
endfunction()

function(_aros_read_mmake_logical_lines file_path out_var)
  file(STRINGS "${file_path}" _raw_lines)
  set(_logical_lines)
  set(_current "")

  foreach(_raw_line IN LISTS _raw_lines)
    string(REGEX REPLACE "[\r\n]+$" "" _line "${_raw_line}")
    string(STRIP "${_line}" _stripped_line)
    if(NOT "${_current}" STREQUAL "" AND "${_stripped_line}" MATCHES "^#")
      string(STRIP "${_current}" _current)
      string(REGEX REPLACE "([ \t]|;)+#.*$" "" _current "${_current}")
      string(STRIP "${_current}" _current)
      if(NOT "${_current}" STREQUAL "")
        string(REPLACE ";" "\\;" _current "${_current}")
        list(APPEND _logical_lines "${_current}")
      endif()
      set(_current "")
      continue()
    endif()
    if("${_current}" STREQUAL "")
      set(_current "${_line}")
    else()
      string(APPEND _current " " "${_line}")
    endif()

    if("${_current}" MATCHES "\\\\[ \t]*$")
      string(REGEX REPLACE "\\\\[ \t]*$" "" _current "${_current}")
      string(STRIP "${_current}" _current)
    else()
      string(STRIP "${_current}" _current)
      string(REGEX REPLACE "([ \t]|;)+#.*$" "" _current "${_current}")
      string(STRIP "${_current}" _current)
      if(NOT "${_current}" STREQUAL "")
        string(REPLACE ";" "\\;" _current "${_current}")
        list(APPEND _logical_lines "${_current}")
      endif()
      set(_current "")
    endif()
  endforeach()

  if(NOT "${_current}" STREQUAL "")
    string(STRIP "${_current}" _current)
    string(REGEX REPLACE "([ \t]|;)+#.*$" "" _current "${_current}")
    string(STRIP "${_current}" _current)
    string(REPLACE ";" "\\;" _current "${_current}")
    list(APPEND _logical_lines "${_current}")
  endif()

  set(${out_var} "${_logical_lines}" PARENT_SCOPE)
endfunction()

function(_aros_read_config_value variable_name out_var)
  if(_AROS_MMAKE_CONFIG_SNAPSHOT)
    set(${out_var} "${_AROS_MMAKE_VAR_${variable_name}}" PARENT_SCOPE)
    return()
  endif()
  _aros_native_config_value("${variable_name}" _value _found)
  if(_found)
    set(${out_var} "${_value}" PARENT_SCOPE)
    return()
  endif()
  set(_config_files
    "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/target.cfg"
    "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/compiler.cfg"
    "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/build.cfg"
    "${AROS_CONFIG_BUILD_DIR}/config/make.cfg"
  )

  foreach(_config_file IN LISTS _config_files)
    if(NOT EXISTS "${_config_file}")
      continue()
    endif()

    file(STRINGS "${_config_file}" _value_line REGEX "^${variable_name}[ \t]*:?=")
    if(_value_line)
      string(REGEX REPLACE "^${variable_name}[ \t]*:?=[ \t]*" "" _value "${_value_line}")
      _aros_unwrap_strip_expression("${_value}" _value)
      set(${out_var} "${_value}" PARENT_SCOPE)
      return()
    endif()
  endforeach()

  set(${out_var} "" PARENT_SCOPE)
endfunction()

function(_aros_read_config_tokens variable_name out_var)
  _aros_read_config_value("${variable_name}" _value)
  if(_value STREQUAL "")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  _aros_expand_make_tokens("${_value}" _expanded_value)
  _aros_unwrap_strip_expression("${_expanded_value}" _expanded_value)
  if(_expanded_value)
    separate_arguments(_tokens NATIVE_COMMAND "${_expanded_value}")
    set(${out_var} "${_tokens}" PARENT_SCOPE)
  else()
    set(${out_var} "" PARENT_SCOPE)
  endif()
endfunction()

function(_aros_find_toolchain_program tool_name out_var)
  set(_candidates
    "${AROS_TOOLCHAIN_DIR}/${AROS_TOOLCHAIN_PREFIX}-${tool_name}"
    "${AROS_TOOLCHAIN_DIR}/bin/${AROS_TOOLCHAIN_PREFIX}-${tool_name}"
  )
  foreach(_candidate IN LISTS _candidates)
    if(EXISTS "${_candidate}")
      set(${out_var} "${_candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${out_var} "" PARENT_SCOPE)
endfunction()

function(_aros_get_active_layers out_var)
  set(_target_cfg "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/target.cfg")
  if(NOT EXISTS "${_target_cfg}")
    message(FATAL_ERROR "Target configuration not found: ${_target_cfg}")
  endif()

  string(REPLACE "-" ";" _parts "${AROS_TARGET}")
  list(GET _parts 0 _arch)
  list(GET _parts 1 _cpu)
  set(_variant "")
  list(LENGTH _parts _parts_len)
  if(_parts_len GREATER 2)
    list(SUBLIST _parts 2 -1 _variant_parts)
    string(REPLACE ";" "-" _variant "${_variant_parts}")
  endif()

  file(STRINGS "${_target_cfg}" _family_line REGEX "^FAMILY[ \t]*:=")
  if(_family_line)
    string(REGEX REPLACE "^FAMILY[ \t]*:=[ \t]*" "" _family "${_family_line}")
    string(STRIP "${_family}" _family)
  else()
    set(_family "${_arch}")
  endif()

  set(_layers)
  if(_variant)
    list(APPEND _layers "${_cpu}-${_arch}-${_variant}")
  endif()
  list(APPEND _layers "${_cpu}-${_arch}" "all-${_arch}" "all-${_family}" "${_cpu}-all")
  list(REMOVE_DUPLICATES _layers)
  set(${out_var} "${_layers}" PARENT_SCOPE)
endfunction()

function(_aros_get_active_alias_layers out_var)
  _aros_get_target_context()

  set(_aliases)
  if(AROS_MODULE_CONTEXT_VARIANT)
    list(APPEND _aliases "${AROS_MODULE_CONTEXT_ARCH}-${AROS_MODULE_CONTEXT_CPU}-${AROS_MODULE_CONTEXT_VARIANT}")
  endif()
  list(APPEND _aliases "${AROS_MODULE_CONTEXT_ARCH}-${AROS_MODULE_CONTEXT_CPU}")
  if(AROS_MODULE_CONTEXT_VARIANT)
    list(APPEND _aliases "${AROS_MODULE_CONTEXT_ARCH}-${AROS_MODULE_CONTEXT_VARIANT}")
  endif()
  list(APPEND _aliases
    "${AROS_MODULE_CONTEXT_ARCH}"
    "${AROS_MODULE_CONTEXT_FAMILY}"
    "${AROS_MODULE_CONTEXT_CPU}"
  )
  list(REMOVE_DUPLICATES _aliases)
  set(${out_var} "${_aliases}" PARENT_SCOPE)
endfunction()

function(_aros_get_target_context)
  string(REPLACE "-" ";" _parts "${AROS_TARGET}")
  list(GET _parts 0 _arch)
  list(GET _parts 1 _cpu)
  set(_variant "")
  list(LENGTH _parts _parts_len)
  if(_parts_len GREATER 2)
    list(SUBLIST _parts 2 -1 _variant_parts)
    string(REPLACE ";" "-" _variant "${_variant_parts}")
  endif()

  set(_target_cfg "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/target.cfg")
  file(STRINGS "${_target_cfg}" _family_line REGEX "^FAMILY[ \t]*:=")
  if(_family_line)
    string(REGEX REPLACE "^FAMILY[ \t]*:=[ \t]*" "" _family "${_family_line}")
    string(STRIP "${_family}" _family)
  else()
    set(_family "${_arch}")
  endif()

  set(AROS_MODULE_CONTEXT_ARCH "${_arch}" PARENT_SCOPE)
  set(AROS_MODULE_CONTEXT_CPU "${_cpu}" PARENT_SCOPE)
  set(AROS_MODULE_CONTEXT_VARIANT "${_variant}" PARENT_SCOPE)
  set(AROS_MODULE_CONTEXT_FAMILY "${_family}" PARENT_SCOPE)
  set(AROS_MODULE_CONTEXT_PLATFORM "${AROS_TARGET}" PARENT_SCOPE)
endfunction()

function(_aros_extract_make_call input_value call_name out_prefix out_body out_suffix)
  string(FIND "${input_value}" "$(${call_name} " _call_start)
  if(_call_start EQUAL -1)
    set(${out_prefix} "${input_value}" PARENT_SCOPE)
    set(${out_body} "" PARENT_SCOPE)
    set(${out_suffix} "" PARENT_SCOPE)
    return()
  endif()

  string(LENGTH "${input_value}" _input_len)
  set(_depth 0)
  set(_call_end -1)
  set(_index "${_call_start}")
  while(_index LESS _input_len)
    math(EXPR _remaining "${_input_len} - ${_index}")
    if(_remaining GREATER 1)
      string(SUBSTRING "${input_value}" ${_index} 2 _pair)
    else()
      set(_pair "")
    endif()

    if(_pair STREQUAL "$(")
      math(EXPR _depth "${_depth} + 1")
      math(EXPR _index "${_index} + 2")
      continue()
    endif()

    string(SUBSTRING "${input_value}" ${_index} 1 _char)
    if(_char STREQUAL ")" AND _depth GREATER 0)
      math(EXPR _depth "${_depth} - 1")
      if(_depth EQUAL 0)
        set(_call_end "${_index}")
        break()
      endif()
    endif()

    math(EXPR _index "${_index} + 1")
  endwhile()

  if(_call_end EQUAL -1)
    message(FATAL_ERROR "Unterminated \$(${call_name} ...) expression: ${input_value}")
  endif()

  if(_call_start GREATER 0)
    string(SUBSTRING "${input_value}" 0 ${_call_start} _prefix)
  else()
    set(_prefix "")
  endif()

  math(EXPR _body_start "${_call_start} + 2")
  math(EXPR _body_len "${_call_end} - ${_body_start}")
  string(SUBSTRING "${input_value}" ${_body_start} ${_body_len} _body)

  math(EXPR _suffix_start "${_call_end} + 1")
  if(_suffix_start LESS _input_len)
    math(EXPR _suffix_len "${_input_len} - ${_suffix_start}")
    string(SUBSTRING "${input_value}" ${_suffix_start} ${_suffix_len} _suffix)
  else()
    set(_suffix "")
  endif()

  set(${out_prefix} "${_prefix}" PARENT_SCOPE)
  set(${out_body} "${_body}" PARENT_SCOPE)
  set(${out_suffix} "${_suffix}" PARENT_SCOPE)
endfunction()

function(_aros_split_make_arguments input_value out_var)
  set(_arguments)
  set(_separator "")
  set(_current "")
  set(_depth 0)
  string(LENGTH "${input_value}" _input_len)
  set(_index 0)

  while(_index LESS _input_len)
    math(EXPR _remaining "${_input_len} - ${_index}")
    if(_remaining GREATER 1)
      string(SUBSTRING "${input_value}" ${_index} 2 _pair)
    else()
      set(_pair "")
    endif()

    if(_pair STREQUAL "$(")
      math(EXPR _depth "${_depth} + 1")
      string(APPEND _current "$(")
      math(EXPR _index "${_index} + 2")
      continue()
    endif()

    string(SUBSTRING "${input_value}" ${_index} 1 _char)
    if(_char STREQUAL ")" AND _depth GREATER 0)
      math(EXPR _depth "${_depth} - 1")
      string(APPEND _current "${_char}")
    elseif(_char STREQUAL "," AND _depth EQUAL 0)
      string(STRIP "${_current}" _current)
      string(APPEND _arguments "${_separator}${_current}")
      set(_separator ";")
      set(_current "")
    else()
      string(APPEND _current "${_char}")
    endif()

    math(EXPR _index "${_index} + 1")
  endwhile()

  string(STRIP "${_current}" _current)
  string(APPEND _arguments "${_separator}${_current}")
  set(${out_var} "${_arguments}" PARENT_SCOPE)
endfunction()

function(_aros_set_make_context_for_file file_path)
  get_filename_component(_file_dir "${file_path}" DIRECTORY)
  if(IS_ABSOLUTE "${_file_dir}")
    file(RELATIVE_PATH _context_curdir "${AROS_SOURCE_DIR}" "${_file_dir}")
  else()
    set(_context_curdir "${_file_dir}")
  endif()

  if(_context_curdir MATCHES "^\\.\\.?(/|$)")
    if(DEFINED MODULE_PATH AND NOT MODULE_PATH STREQUAL "")
      set(_context_curdir "${MODULE_PATH}")
    else()
      set(_context_curdir "")
    endif()
  endif()

  set(_context_maindir "")
  if(ARGC GREATER 1 AND NOT "${ARGV1}" STREQUAL "")
    set(_context_maindir "${ARGV1}")
  elseif(DEFINED MODULE_PATH AND NOT MODULE_PATH STREQUAL "")
    set(_context_maindir "${MODULE_PATH}")
  else()
    set(_context_maindir "${_context_curdir}")
  endif()

  set(_AROS_MMAKE_CONTEXT_CURDIR "${_context_curdir}" PARENT_SCOPE)
  set(_AROS_MMAKE_CONTEXT_MAINDIR "${_context_maindir}" PARENT_SCOPE)
endfunction()

function(_aros_expand_make_tokens input_value out_var)
  _aros_get_target_context()
  set(_expanded "${input_value}")
  set(_make_gendir "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen")
  set(_limit 100)
  while(_limit GREATER 0)
    math(EXPR _limit "${_limit} - 1")
    _aros_expand_make_word_function("${_expanded}" _expanded _expanded_word_function)
    if(_expanded_word_function)
      continue()
    endif()
    _aros_extract_make_call("${_expanded}" "foreach" _foreach_prefix _foreach_body _foreach_suffix)
    if(NOT _foreach_body STREQUAL "")
      string(REGEX REPLACE "^foreach[ \t]+" "" _foreach_arg_string "${_foreach_body}")
      _aros_split_make_arguments("${_foreach_arg_string}" _foreach_args)
      list(LENGTH _foreach_args _foreach_arg_count)
      if(NOT _foreach_arg_count EQUAL 3)
        message(FATAL_ERROR "Unsupported foreach expression in ${MODULE_MMAKEFILE}: ${_foreach_body}")
      endif()

      list(GET _foreach_args 0 _foreach_var)
      list(GET _foreach_args 1 _foreach_list_expr)
      list(GET _foreach_args 2 _foreach_text_expr)
      string(STRIP "${_foreach_var}" _foreach_var)

      _aros_expand_make_tokens("${_foreach_list_expr}" _foreach_list_expanded)
      separate_arguments(_foreach_values NATIVE_COMMAND "${_foreach_list_expanded}")

      set(_foreach_saved_defined FALSE)
      if(DEFINED _AROS_MMAKE_VAR_${_foreach_var})
        set(_foreach_saved_defined TRUE)
        set(_foreach_saved_value "${_AROS_MMAKE_VAR_${_foreach_var}}")
      endif()

      set(_foreach_result "")
      foreach(_foreach_value IN LISTS _foreach_values)
        string(STRIP "${_foreach_value}" _foreach_value)
        if(_foreach_value STREQUAL "")
          continue()
        endif()
        set(_AROS_MMAKE_VAR_${_foreach_var} "${_foreach_value}")
        _aros_expand_make_tokens("${_foreach_text_expr}" _foreach_item)
        string(STRIP "${_foreach_item}" _foreach_item)
        if(_foreach_item STREQUAL "")
          continue()
        endif()
        if(_foreach_result STREQUAL "")
          set(_foreach_result "${_foreach_item}")
        else()
          string(APPEND _foreach_result " " "${_foreach_item}")
        endif()
      endforeach()

      if(_foreach_saved_defined)
        set(_AROS_MMAKE_VAR_${_foreach_var} "${_foreach_saved_value}")
      else()
        unset(_AROS_MMAKE_VAR_${_foreach_var})
      endif()

      set(_expanded "${_foreach_prefix}${_foreach_result}${_foreach_suffix}")
      continue()
    endif()

    _aros_extract_make_call("${_expanded}" "shell" _shell_prefix _shell_body _shell_suffix)
    if(NOT _shell_body STREQUAL "")
      string(REGEX REPLACE "^shell[ \t]+" "" _shell_command "${_shell_body}")
      _aros_expand_make_tokens("${_shell_command}" _shell_command)
      execute_process(
        COMMAND /bin/sh -c "${_shell_command}"
        OUTPUT_VARIABLE _shell_output
        OUTPUT_STRIP_TRAILING_WHITESPACE
      )
      string(REPLACE "\n" " " _shell_output "${_shell_output}")
      set(_expanded "${_shell_prefix}${_shell_output}${_shell_suffix}")
      continue()
    endif()

    string(REGEX MATCH "\\$\\(([A-Za-z0-9_]+)\\)" _match "${_expanded}")
    if(NOT _match)
      break()
    endif()

    set(_var_name "${CMAKE_MATCH_1}")
    if(DEFINED _AROS_MMAKE_VAR_${_var_name})
      set(_replacement "${_AROS_MMAKE_VAR_${_var_name}}")
    elseif(_var_name STREQUAL "ARCH")
      set(_replacement "${AROS_MODULE_CONTEXT_ARCH}")
    elseif(_var_name STREQUAL "CPU")
      set(_replacement "${AROS_MODULE_CONTEXT_CPU}")
    elseif(_var_name STREQUAL "FAMILY")
      set(_replacement "${AROS_MODULE_CONTEXT_FAMILY}")
    elseif(_var_name STREQUAL "AROS_TARGET_ARCH")
      set(_replacement "${AROS_MODULE_CONTEXT_ARCH}")
    elseif(_var_name STREQUAL "AROS_TARGET_CPU")
      set(_replacement "${AROS_MODULE_CONTEXT_CPU}")
    elseif(_var_name STREQUAL "AROS_TARGET_FAMILY")
      set(_replacement "${AROS_MODULE_CONTEXT_FAMILY}")
    elseif(_var_name STREQUAL "AROS_TARGET_PLATFORM")
      set(_replacement "${AROS_MODULE_CONTEXT_PLATFORM}")
    elseif(_var_name STREQUAL "AROS_TARGET_VARIANT")
      set(_replacement "${AROS_MODULE_CONTEXT_VARIANT}")
    elseif(_var_name STREQUAL "TARGET_CPU")
      set(_replacement "${AROS_MODULE_CONTEXT_CPU}")
    elseif(_var_name STREQUAL "SRCDIR")
      set(_replacement "${AROS_SOURCE_DIR}")
    elseif(_var_name STREQUAL "CURDIR")
      if(DEFINED _AROS_MMAKE_CONTEXT_CURDIR AND NOT _AROS_MMAKE_CONTEXT_CURDIR STREQUAL "")
        set(_replacement "${_AROS_MMAKE_CONTEXT_CURDIR}")
      else()
        set(_replacement "${MODULE_PATH}")
      endif()
    elseif(_var_name STREQUAL "MAINDIR")
      if(DEFINED _AROS_MMAKE_CONTEXT_MAINDIR AND NOT _AROS_MMAKE_CONTEXT_MAINDIR STREQUAL "")
        set(_replacement "${_AROS_MMAKE_CONTEXT_MAINDIR}")
      else()
        set(_replacement "${MODULE_PATH}")
      endif()
    elseif(_var_name STREQUAL "GENDIR")
      set(_replacement "${_make_gendir}")
    else()
      _aros_read_config_value("${_var_name}" _replacement)
    endif()
    string(REPLACE "$(${_var_name})" "${_replacement}" _expanded "${_expanded}")
  endwhile()
  set(${out_var} "${_expanded}" PARENT_SCOPE)
endfunction()

function(_aros_collect_make_variable_from_file file_path variable_name out_var)
  if(NOT EXISTS "${file_path}")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  _aros_set_make_context_for_file("${file_path}")
  _aros_read_mmake_logical_lines("${file_path}" _logical_lines)

  set(_values)
  foreach(_line IN LISTS _logical_lines)
    if(_line MATCHES "^[ \t;]*#")
      continue()
    endif()
    if(_line MATCHES "^${variable_name}[ \t]*:?=[ \t]*(.*)$")
      set(_mode "set")
      set(_value "${CMAKE_MATCH_1}")
    elseif(_line MATCHES "^${variable_name}[ \t]*\\+=[ \t]*(.*)$")
      set(_mode "append")
      set(_value "${CMAKE_MATCH_1}")
    else()
      continue()
    endif()

    _aros_expand_make_tokens("${_value}" _expanded_value)
    separate_arguments(_expanded_tokens NATIVE_COMMAND "${_expanded_value}")
    if(_mode STREQUAL "set")
      set(_values ${_expanded_tokens})
    else()
      list(APPEND _values ${_expanded_tokens})
    endif()
  endforeach()

  set(${out_var} "${_values}" PARENT_SCOPE)
endfunction()

function(_aros_collect_layer_makeopts variable_name out_var)
  get_filename_component(_module_dir_name "${MODULE_PATH}" NAME)

  set(_collected_values)
  set(_makeopts_paths)

  if(DEFINED MODULE_RESOLVED_LAYER_MMAKEFILES AND NOT MODULE_RESOLVED_LAYER_MMAKEFILES STREQUAL "")
    foreach(_layer_mmakefile IN LISTS MODULE_RESOLVED_LAYER_MMAKEFILES)
      get_filename_component(_layer_module_dir "${_layer_mmakefile}" DIRECTORY)
      list(APPEND _makeopts_paths "${_layer_module_dir}/make.opts")
    endforeach()
  endif()

  _aros_get_active_layers(_active_layers)
  foreach(_layer IN LISTS _active_layers)
    list(APPEND _makeopts_paths "${AROS_SOURCE_DIR}/arch/${_layer}/${_module_dir_name}/make.opts")
  endforeach()

  list(REMOVE_DUPLICATES _makeopts_paths)
  foreach(_makeopts_path IN LISTS _makeopts_paths)
    _aros_collect_make_variable_from_file("${_makeopts_path}" "${variable_name}" _layer_values)
    list(APPEND _collected_values ${_layer_values})
  endforeach()

  set(${out_var} "${_collected_values}" PARENT_SCOPE)
endfunction()

function(_aros_collect_archincludes maindir modname out_var)
  get_filename_component(_module_dir_name "${maindir}" NAME)

  set(_archinclude_mmakefiles)
  set(_module_mmakefile "${AROS_SOURCE_DIR}/${maindir}/mmakefile.src")
  if(EXISTS "${_module_mmakefile}")
    aros_layering_extract_primary_mmake_name("${_module_mmakefile}" _archinclude_mmake_name)
    if(NOT _archinclude_mmake_name STREQUAL "")
      aros_layering_collect_resolved_module_layer_mmakefiles(
        "${_module_dir_name}"
        "${_archinclude_mmake_name}"
        _archinclude_mmakefiles
        _archinclude_layers
        _archinclude_aliases
      )
    endif()
  endif()

  if(NOT _archinclude_mmakefiles)
    _aros_get_active_layers(_active_layers)
    foreach(_layer IN LISTS _active_layers)
      list(APPEND _archinclude_mmakefiles "${AROS_SOURCE_DIR}/arch/${_layer}/${_module_dir_name}/mmakefile.src")
    endforeach()
  endif()

  set(_archinclude_entries)
  foreach(_mmakefile_path IN LISTS _archinclude_mmakefiles)
    if(NOT EXISTS "${_mmakefile_path}")
      continue()
    endif()

    _aros_set_make_context_for_file("${_mmakefile_path}" "${maindir}")
    _aros_read_mmake_logical_lines("${_mmakefile_path}" _logical_lines)
    foreach(_line IN LISTS _logical_lines)
      if(_line MATCHES "^#")
        continue()
      endif()
      if(NOT _line MATCHES "^%set_archincludes[ \t]+(.*)$")
        continue()
      endif()

      _aros_expand_make_tokens("${CMAKE_MATCH_1}" _expanded_args)
      separate_arguments(_arg_tokens NATIVE_COMMAND "${_expanded_args}")

      set(_entry_modname "")
      set(_entry_maindir "")
      set(_entry_pri "999")
      set(_entry_includes "")
      set(_pending_key "")

      foreach(_arg_token IN LISTS _arg_tokens)
        if(NOT _arg_token MATCHES "^([^=]+)=(.*)$")
          if(NOT _pending_key STREQUAL "")
            set(_pending_var "_entry_${_pending_key}")
            if("${${_pending_var}}" STREQUAL "")
              set(${_pending_var} "${_arg_token}")
            else()
              string(APPEND ${_pending_var} " ${_arg_token}")
            endif()
          endif()
          continue()
        endif()

        set(_arg_key "${CMAKE_MATCH_1}")
        set(_arg_value "${CMAKE_MATCH_2}")
        if(_arg_key STREQUAL "modname")
          set(_pending_key "")
          set(_entry_modname "${_arg_value}")
        elseif(_arg_key STREQUAL "maindir")
          set(_pending_key "")
          set(_entry_maindir "${_arg_value}")
        elseif(_arg_key STREQUAL "pri")
          set(_pending_key "")
          set(_entry_pri "${_arg_value}")
        elseif(_arg_key STREQUAL "includes")
          set(_pending_key "includes")
          set(_entry_includes "${_arg_value}")
        else()
          set(_pending_key "")
        endif()
      endforeach()

      if(NOT _entry_modname STREQUAL "${modname}")
        continue()
      endif()
      if(NOT _entry_maindir STREQUAL "${maindir}")
        continue()
      endif()

      set(_entry_pri_padded "${_entry_pri}")
      string(REGEX REPLACE "^([0-9])$" "00\\1" _entry_pri_padded "${_entry_pri_padded}")
      string(REGEX REPLACE "^([0-9][0-9])$" "0\\1" _entry_pri_padded "${_entry_pri_padded}")
      string(REPLACE ";" "\\;" _entry_includes "${_entry_includes}")
      list(APPEND _archinclude_entries "${_entry_pri_padded}|${_entry_includes}")
    endforeach()
  endforeach()

  list(SORT _archinclude_entries)

  set(_collected_includes)
  foreach(_entry IN LISTS _archinclude_entries)
    string(REGEX REPLACE "^[0-9][0-9][0-9]\\|" "" _entry_includes "${_entry}")
    separate_arguments(_entry_include_tokens NATIVE_COMMAND "${_entry_includes}")
    list(APPEND _collected_includes ${_entry_include_tokens})
  endforeach()

  set(${out_var} "${_collected_includes}" PARENT_SCOPE)
endfunction()

function(_aros_condition_stack_is_active condition_stack out_var)
  set(_active TRUE)
  foreach(_condition IN LISTS condition_stack)
    if(NOT _condition)
      set(_active FALSE)
      break()
    endif()
  endforeach()
  set(${out_var} "${_active}" PARENT_SCOPE)
endfunction()

function(_aros_evaluate_mmake_condition line out_var)
  _aros_evaluate_make_equality("${line}" _active)
  set(${out_var} "${_active}" PARENT_SCOPE)
endfunction()

function(_aros_collect_active_mmake_targets mmake_name active_alias_layers logical_lines out_var)
  set(_active_targets)
  if(NOT mmake_name STREQUAL "")
    list(APPEND _active_targets "${mmake_name}")
    foreach(_alias IN LISTS active_alias_layers)
      list(APPEND _active_targets "${mmake_name}-${_alias}")
    endforeach()
  endif()

  set(_target_edges)
  foreach(_line IN LISTS logical_lines)
    if(NOT _line MATCHES "^#MM-?[ \t]+([^ \t:]+)[ \t]*:(.*)$")
      continue()
    endif()

    set(_source_target "${CMAKE_MATCH_1}")
    set(_dep_string "${CMAKE_MATCH_2}")
    string(STRIP "${_dep_string}" _dep_string)
    if(_dep_string STREQUAL "")
      continue()
    endif()

    separate_arguments(_dep_tokens NATIVE_COMMAND "${_dep_string}")
    foreach(_dep_token IN LISTS _dep_tokens)
      if(_dep_token MATCHES "[$/]")
        continue()
      endif()
      list(APPEND _target_edges "${_source_target}|${_dep_token}")
    endforeach()
  endforeach()

  set(_changed TRUE)
  while(_changed)
    set(_changed FALSE)
    foreach(_edge IN LISTS _target_edges)
      string(REPLACE "|" ";" _edge_parts "${_edge}")
      list(LENGTH _edge_parts _edge_len)
      if(NOT _edge_len EQUAL 2)
        continue()
      endif()
      list(GET _edge_parts 0 _edge_source)
      list(GET _edge_parts 1 _edge_dest)
      list(FIND _active_targets "${_edge_source}" _edge_source_index)
      list(FIND _active_targets "${_edge_dest}" _edge_dest_index)
      if(NOT _edge_source_index EQUAL -1 AND _edge_dest_index EQUAL -1)
        list(APPEND _active_targets "${_edge_dest}")
        set(_changed TRUE)
      endif()
    endforeach()
  endwhile()

  list(REMOVE_DUPLICATES _active_targets)
  set(${out_var} "${_active_targets}" PARENT_SCOPE)
endfunction()

function(_aros_parse_mmake_module file_path)
  _aros_set_make_context_for_file("${file_path}")
  _aros_read_mmake_logical_lines("${file_path}" _logical_lines)
  set(_condition_stack)
  set(_AROS_MMAKE_VAR_RESIDENT_BEGIN "compiler/libinit/libentry")
  set(_AROS_MMAKE_VAR_KICKSTART_BEGIN "compiler/libinit/kickentry")
  if(DEFINED MODULE_RESOLVED_REACHABLE_ALIASES AND NOT MODULE_RESOLVED_REACHABLE_ALIASES STREQUAL "")
    set(_active_alias_layers "${MODULE_RESOLVED_REACHABLE_ALIASES}")
  else()
    _aros_get_active_alias_layers(_active_alias_layers)
  endif()
  if(DEFINED MODULE_MMAKE_NAME AND NOT MODULE_MMAKE_NAME STREQUAL "")
    _aros_collect_active_mmake_targets(
      "${MODULE_MMAKE_NAME}"
      "${_active_alias_layers}"
      "${_logical_lines}"
      _active_mmake_targets
    )
  else()
    set(_active_mmake_targets)
  endif()
  if(DEFINED AROS_GENMODULE_DEBUG AND AROS_GENMODULE_DEBUG)
    message(STATUS "Active mmake targets for ${file_path}: ${_active_mmake_targets}")
  endif()

  # Queue numeric IDs, not line text: mutating CMake lists unescapes the
  # semicolons that the legacy reader preserves inside continued declarations.
  set(_pending_lines)
  set(_line_count 0)
  foreach(_line IN LISTS _logical_lines)
    set(_line_text_${_line_count} "${_line}")
    list(APPEND _pending_lines "${_line_count}")
    math(EXPR _line_count "${_line_count} + 1")
  endforeach()
  set(_include_stack "${file_path}")
  set(_module_mmake_inputs "${file_path}")
  get_filename_component(_manifest_directory "${file_path}" DIRECTORY)
  while(NOT _pending_lines STREQUAL "")
    list(POP_FRONT _pending_lines _line_id)
    set(_line "${_line_text_${_line_id}}")
    if(_line MATCHES "^@AROS_INCLUDE_BEGIN@(.*)$")
      set(_include "${CMAKE_MATCH_1}")
      if(_include IN_LIST _include_stack)
        message(FATAL_ERROR "Recursive mmake options include: ${_include}")
      endif()
      list(APPEND _include_stack "${_include}")
      continue()
    elseif(_line STREQUAL "@AROS_INCLUDE_END@")
      list(POP_BACK _include_stack)
      continue()
    endif()
    if(_line MATCHES "^[ \t;]*#")
      continue()
    endif()

    if(_line MATCHES "^ifn?eq[ \t]*\\(.*\\)$")
      _aros_evaluate_mmake_condition("${_line}" _condition_value)
      list(APPEND _condition_stack "${_condition_value}")
      continue()
    elseif(_line STREQUAL "else")
      list(LENGTH _condition_stack _condition_len)
      if(_condition_len GREATER 0)
        math(EXPR _last_index "${_condition_len} - 1")
        list(GET _condition_stack "${_last_index}" _last_value)
        if(_last_value)
          set(_new_value FALSE)
        else()
          set(_new_value TRUE)
        endif()
        list(REMOVE_AT _condition_stack "${_last_index}")
        list(APPEND _condition_stack "${_new_value}")
      endif()
      continue()
    elseif(_line STREQUAL "endif")
      list(LENGTH _condition_stack _condition_len)
      if(_condition_len GREATER 0)
        math(EXPR _last_index "${_condition_len} - 1")
        list(REMOVE_AT _condition_stack "${_last_index}")
      endif()
      continue()
    endif()

    _aros_condition_stack_is_active("${_condition_stack}" _condition_active)
    if(NOT _condition_active)
      continue()
    endif()

    if(_line MATCHES "^(-?include)[ \t]+(.*)$")
      set(_include_mode "${CMAKE_MATCH_1}")
      _aros_expand_make_tokens("${CMAKE_MATCH_2}" _includes)
      separate_arguments(_includes UNIX_COMMAND "${_includes}")
      list(REVERSE _includes)
      foreach(_include IN LISTS _includes)
        # The generated configuration has its own reader. Option fragments
        # must instead take effect here, before source-selection conditionals.
        if(NOT _include MATCHES "\\.opts$")
          continue()
        endif()
        get_filename_component(_include "${_include}" ABSOLUTE BASE_DIR "${_manifest_directory}")
        if(NOT EXISTS "${_include}")
          if(_include_mode STREQUAL "include")
            message(FATAL_ERROR "Missing mmake options include: ${_include}")
          endif()
          continue()
        endif()
        list(APPEND _module_mmake_inputs "${_include}")
        _aros_read_mmake_logical_lines("${_include}" _include_lines)
        set(_include_ids "${_line_count}")
        set(_line_text_${_line_count} "@AROS_INCLUDE_BEGIN@${_include}")
        math(EXPR _line_count "${_line_count} + 1")
        foreach(_include_line IN LISTS _include_lines)
          set(_line_text_${_line_count} "${_include_line}")
          list(APPEND _include_ids "${_line_count}")
          math(EXPR _line_count "${_line_count} + 1")
        endforeach()
        set(_line_text_${_line_count} "@AROS_INCLUDE_END@")
        list(APPEND _include_ids "${_line_count}")
        math(EXPR _line_count "${_line_count} + 1")
        list(PREPEND _pending_lines ${_include_ids})
      endforeach()
      continue()
    endif()

    if(_line MATCHES "^([A-Za-z0-9_]+)[ \t]*(\\+=|:=|\\?=|=)[ \t]*(.*)$")
      set(_var_name "${CMAKE_MATCH_1}")
      set(_assign_mode "${CMAKE_MATCH_2}")
      set(_raw_value "${CMAKE_MATCH_3}")
      _aros_expand_make_tokens("${_raw_value}" _expanded_value)
      if(_assign_mode STREQUAL "+=" AND DEFINED _AROS_MMAKE_VAR_${_var_name})
        set(_AROS_MMAKE_VAR_${_var_name} "${_AROS_MMAKE_VAR_${_var_name}} ${_expanded_value}")
      elseif(_assign_mode STREQUAL "?=")
        if(NOT DEFINED _AROS_MMAKE_VAR_${_var_name} OR "${_AROS_MMAKE_VAR_${_var_name}}" STREQUAL "")
          set(_AROS_MMAKE_VAR_${_var_name} "${_expanded_value}")
        endif()
      else()
        set(_AROS_MMAKE_VAR_${_var_name} "${_expanded_value}")
      endif()
      continue()
    endif()

    if(_line MATCHES "^%link_kickstart[ \t]+(.*)$")
      _aros_expand_make_tokens("${CMAKE_MATCH_1}" _expanded_args)
      string(REPLACE ";" " " _expanded_args "${_expanded_args}")
      separate_arguments(_arg_tokens NATIVE_COMMAND "${_expanded_args}")
      set(_keys mmake file classes devs handlers hidds libs res startup uselibs ldflags map deps strip packfmt)
      foreach(_key IN LISTS _keys)
        set(_kickstart_${_key} "")
      endforeach()
      _aros_expand_make_tokens("$(LDFLAGS)" _kickstart_ldflags)
      set(_key "")
      foreach(_token IN LISTS _arg_tokens)
        if(_token MATCHES "^([^=]+)=(.*)$")
          set(_key "${CMAKE_MATCH_1}")
          set(_value "${CMAKE_MATCH_2}")
          if(NOT _key IN_LIST _keys)
            message(FATAL_ERROR "Unsupported link_kickstart argument: ${_key}")
          endif()
          set(_kickstart_${_key} "${_value}")
        elseif(_key)
          string(APPEND _kickstart_${_key} " ${_token}")
        else()
          message(FATAL_ERROR "Unexpected link_kickstart token: ${_token}")
        endif()
      endforeach()
      if(NOT _kickstart_mmake STREQUAL MODULE_MMAKE_NAME)
        continue()
      endif()
      set(_module_mmake_kind kickstart)
      foreach(_key IN LISTS _keys)
        _aros_tokenize_mmake_value("${_kickstart_${_key}}" _value)
        set(MODULE_MMAKE_KICKSTART_${_key} "${_value}" PARENT_SCOPE)
      endforeach()
      continue()
    endif()

    if(_line MATCHES "^%get_archincludes[ \t]+(.*)$")
      _aros_expand_make_tokens("${CMAKE_MATCH_1}" _expanded_args)
      separate_arguments(_arg_tokens NATIVE_COMMAND "${_expanded_args}")

      set(_archinclude_modname "")
      set(_archinclude_maindir "")
      set(_archinclude_flag "USER_INCLUDES")
      foreach(_arg_token IN LISTS _arg_tokens)
        if(NOT _arg_token MATCHES "^([^=]+)=(.*)$")
          continue()
        endif()

        set(_arg_key "${CMAKE_MATCH_1}")
        set(_arg_value "${CMAKE_MATCH_2}")
        if(_arg_key STREQUAL "modname")
          set(_archinclude_modname "${_arg_value}")
        elseif(_arg_key STREQUAL "maindir")
          set(_archinclude_maindir "${_arg_value}")
        elseif(_arg_key STREQUAL "includeflag")
          set(_archinclude_flag "${_arg_value}")
        endif()
      endforeach()

      if(_archinclude_modname AND _archinclude_maindir)
        _aros_collect_archincludes("${_archinclude_maindir}" "${_archinclude_modname}" _resolved_archincludes)
        if(_resolved_archincludes)
          if(DEFINED _AROS_MMAKE_VAR_${_archinclude_flag} AND NOT "${_AROS_MMAKE_VAR_${_archinclude_flag}}" STREQUAL "")
            list(JOIN _resolved_archincludes " " _resolved_archincludes_joined)
            set(_AROS_MMAKE_VAR_${_archinclude_flag}
              "${_AROS_MMAKE_VAR_${_archinclude_flag}} ${_resolved_archincludes_joined}"
            )
          else()
            list(JOIN _resolved_archincludes " " _resolved_archincludes_joined)
            set(_AROS_MMAKE_VAR_${_archinclude_flag} "${_resolved_archincludes_joined}")
          endif()
        endif()
      endif()
      continue()
    endif()

    if(_line MATCHES "^%build_(module[^ \t]*|progs?|linklib)[ \t]+(.*)$")
      set(_build_kind "${CMAKE_MATCH_1}")
      _aros_expand_make_tokens("${CMAKE_MATCH_2}" _expanded_args)
      separate_arguments(_arg_tokens NATIVE_COMMAND "${_expanded_args}")
      unset(_build_module_files)
      unset(_build_module_uselibs)
      unset(_build_module_linklibfiles)
      unset(_build_module_linklibobjs)
      unset(_build_module_usesdks)
      set(_build_module_mmake "")
      set(_build_compiler "target")
      set(_build_output_name "")
      set(_build_output_dir "")
      set(_pending_list_key "")
      foreach(_arg_token IN LISTS _arg_tokens)
        if(NOT _arg_token MATCHES "^([^=]+)=(.*)$")
          if(NOT _pending_list_key STREQUAL "")
            set(_pending_value_var "_build_module_${_pending_list_key}")
            if("${${_pending_value_var}}" STREQUAL "")
              set(${_pending_value_var} "${_arg_token}")
            else()
              string(APPEND ${_pending_value_var} " ${_arg_token}")
            endif()
          endif()
          continue()
        endif()
        set(_arg_key "${CMAKE_MATCH_1}")
        set(_arg_value "${CMAKE_MATCH_2}")

        if(_arg_key STREQUAL "files"
           OR _arg_key STREQUAL "uselibs"
           OR _arg_key STREQUAL "linklibfiles"
           OR _arg_key STREQUAL "linklibobjs"
           OR _arg_key STREQUAL "usesdks")
          set(_pending_list_key "${_arg_key}")
          set("_build_module_${_arg_key}" "${_arg_value}")
        elseif(_arg_key STREQUAL "version")
          set(_pending_list_key "")
          set(_module_mmake_version "${_arg_value}")
        elseif(_arg_key STREQUAL "modsuffix")
          set(_pending_list_key "")
          set(_module_mmake_modsuffix "${_arg_value}")
        elseif(_arg_key STREQUAL "mmake")
          set(_pending_list_key "")
          set(_build_module_mmake "${_arg_value}")
        elseif(_arg_key STREQUAL "compiler")
          set(_pending_list_key "")
          set(_build_compiler "${_arg_value}")
        elseif(_arg_key STREQUAL "progname" OR _arg_key STREQUAL "libname")
          set(_pending_list_key "")
          set(_build_output_name "${_arg_value}")
        elseif(_arg_key STREQUAL "targetdir" OR _arg_key STREQUAL "libdir")
          set(_pending_list_key "")
          set(_build_output_dir "${_arg_value}")
        else()
          set(_pending_list_key "")
        endif()
      endforeach()
      if(DEFINED MODULE_MMAKE_NAME
         AND NOT MODULE_MMAKE_NAME STREQUAL ""
         AND NOT _build_module_mmake STREQUAL "${MODULE_MMAKE_NAME}")
        continue()
      endif()
      if(MODULE_COLLECT_PROGRAM AND _build_kind MATCHES "^progs?$")
        if(_program_rule_found)
          message(FATAL_ERROR "Multiple active program rules for ${MODULE_MMAKE_NAME} in ${file_path}")
        endif()
        set(_program_rule_found TRUE)
        _aros_collect_program_options("${_build_kind}" "${_expanded_args}" _program)
        foreach(_field IN LISTS _program_FIELDS)
          set(MMAKE_PROGRAM_${_field} "${_program_${_field}}" PARENT_SCOPE)
        endforeach()
        set(MMAKE_PROGRAM_FIELDS "${_program_FIELDS}" PARENT_SCOPE)
      endif()
      if(_build_kind STREQUAL "prog" AND NOT _build_module_files)
        set(_build_module_files "${_build_output_name}")
      endif()
      # Capture flags at this rule, including empty values. Later rules in the
      # same manifest may use a different ABI or preprocessor configuration.
      foreach(_flag IN ITEMS cppflags includes ldflags cflags aflags)
        set(_module_mmake_user_${_flag} "")
      endforeach()
      set(_module_mmake_optimization_cflags "")
      if(DEFINED _build_module_files)
        set(_module_mmake_kind "${_build_kind}")
        set(_module_mmake_compiler "${_build_compiler}")
        set(_module_mmake_output_name "${_build_output_name}")
        set(_module_mmake_output_dir "${_build_output_dir}")
        separate_arguments(_module_mmake_files NATIVE_COMMAND "${_build_module_files}")
        _aros_strip_wrapping_quotes(_module_mmake_files)
        _aros_remove_empty_entries(_module_mmake_files)
        _aros_remove_token_entries(_module_mmake_files "\\")
        _aros_remove_directory_source_markers(_module_mmake_files)
      endif()
      if(DEFINED _build_module_uselibs)
        separate_arguments(_module_mmake_uselibs NATIVE_COMMAND "${_build_module_uselibs}")
        _aros_strip_wrapping_quotes(_module_mmake_uselibs)
        _aros_remove_empty_entries(_module_mmake_uselibs)
        _aros_remove_token_entries(_module_mmake_uselibs "\\")
      endif()
      if(DEFINED _build_module_linklibfiles)
        separate_arguments(_module_mmake_linklibfiles NATIVE_COMMAND "${_build_module_linklibfiles}")
        _aros_strip_wrapping_quotes(_module_mmake_linklibfiles)
        _aros_remove_empty_entries(_module_mmake_linklibfiles)
        _aros_remove_token_entries(_module_mmake_linklibfiles "\\")
      endif()
      if(DEFINED _build_module_linklibobjs)
        separate_arguments(_module_mmake_linklibobjs NATIVE_COMMAND "${_build_module_linklibobjs}")
        _aros_strip_wrapping_quotes(_module_mmake_linklibobjs)
        _aros_remove_empty_entries(_module_mmake_linklibobjs)
        _aros_remove_token_entries(_module_mmake_linklibobjs "\\")
      endif()
      if(DEFINED _build_module_usesdks)
        separate_arguments(_module_mmake_usesdks NATIVE_COMMAND "${_build_module_usesdks}")
        _aros_strip_wrapping_quotes(_module_mmake_usesdks)
        _aros_remove_empty_entries(_module_mmake_usesdks)
        _aros_remove_token_entries(_module_mmake_usesdks "\\")
      endif()
      if(DEFINED _AROS_MMAKE_VAR_USER_CPPFLAGS)
        separate_arguments(_module_mmake_user_cppflags NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_CPPFLAGS}")
        _aros_remove_empty_entries(_module_mmake_user_cppflags)
        _aros_remove_token_entries(_module_mmake_user_cppflags "\\")
      endif()
      if(DEFINED _AROS_MMAKE_VAR_USER_INCLUDES)
        separate_arguments(_module_mmake_user_includes NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_INCLUDES}")
        _aros_remove_empty_entries(_module_mmake_user_includes)
        _aros_remove_token_entries(_module_mmake_user_includes "\\")
      endif()
      if(DEFINED _AROS_MMAKE_VAR_USER_LDFLAGS)
        separate_arguments(_module_mmake_user_ldflags NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_LDFLAGS}")
        _aros_remove_empty_entries(_module_mmake_user_ldflags)
        _aros_remove_token_entries(_module_mmake_user_ldflags "\\")
      endif()
      if(DEFINED _AROS_MMAKE_VAR_USER_CFLAGS)
        separate_arguments(_module_mmake_user_cflags NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_CFLAGS}")
        _aros_remove_empty_entries(_module_mmake_user_cflags)
        _aros_remove_token_entries(_module_mmake_user_cflags "\\")
      endif()
      if(DEFINED _AROS_MMAKE_VAR_USER_AFLAGS)
        separate_arguments(_module_mmake_user_aflags NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_AFLAGS}")
        _aros_remove_empty_entries(_module_mmake_user_aflags)
        _aros_remove_token_entries(_module_mmake_user_aflags "\\")
      endif()
      if(DEFINED _AROS_MMAKE_VAR_OPTIMIZATION_CFLAGS)
        separate_arguments(_module_mmake_optimization_cflags NATIVE_COMMAND "${_AROS_MMAKE_VAR_OPTIMIZATION_CFLAGS}")
        _aros_remove_empty_entries(_module_mmake_optimization_cflags)
        _aros_remove_token_entries(_module_mmake_optimization_cflags "\\")
      endif()
      continue()
    endif()

    if(_line MATCHES "^%build_archspecific[^ \t]*[ \t]+(.*)$")
      _aros_expand_make_tokens("${CMAKE_MATCH_1}" _expanded_args)
      separate_arguments(_arg_tokens NATIVE_COMMAND "${_expanded_args}")

      set(_archspec_arch "")
      set(_archspec_mainmmake "")
      set(_archspec_files)
      set(_archspec_asmfiles)
      set(_archspec_linklibfiles)
      set(_archspec_linklibobjs)
      set(_archspec_usesdks)
      set(_pending_list_key "")

      foreach(_arg_token IN LISTS _arg_tokens)
        if(NOT _arg_token MATCHES "^([^=]+)=(.*)$")
          if(NOT _pending_list_key STREQUAL "")
            set(_pending_value_var "_archspec_${_pending_list_key}")
            if("${${_pending_value_var}}" STREQUAL "")
              set(${_pending_value_var} "${_arg_token}")
            else()
              string(APPEND ${_pending_value_var} " ${_arg_token}")
            endif()
          endif()
          continue()
        endif()
        set(_arg_key "${CMAKE_MATCH_1}")
        set(_arg_value "${CMAKE_MATCH_2}")

        if(_arg_key STREQUAL "arch")
          set(_pending_list_key "")
          set(_archspec_arch "${_arg_value}")
        elseif(_arg_key STREQUAL "mainmmake")
          set(_pending_list_key "")
          set(_archspec_mainmmake "${_arg_value}")
        elseif(_arg_key STREQUAL "files")
          set(_pending_list_key "files")
          set(_archspec_files "${_arg_value}")
        elseif(_arg_key STREQUAL "asmfiles")
          set(_pending_list_key "asmfiles")
          set(_archspec_asmfiles "${_arg_value}")
        elseif(_arg_key STREQUAL "linklibfiles")
          set(_pending_list_key "linklibfiles")
          set(_archspec_linklibfiles "${_arg_value}")
        elseif(_arg_key STREQUAL "linklibobjs")
          set(_pending_list_key "linklibobjs")
          set(_archspec_linklibobjs "${_arg_value}")
        elseif(_arg_key STREQUAL "usesdks")
          set(_pending_list_key "usesdks")
          set(_archspec_usesdks "${_arg_value}")
        else()
          set(_pending_list_key "")
        endif()
      endforeach()

      if(NOT "${_archspec_files}" STREQUAL "")
        separate_arguments(_archspec_files NATIVE_COMMAND "${_archspec_files}")
        _aros_remove_empty_entries(_archspec_files)
        _aros_remove_token_entries(_archspec_files "\\")
        _aros_remove_directory_source_markers(_archspec_files)
      endif()
      if(NOT "${_archspec_asmfiles}" STREQUAL "")
        separate_arguments(_archspec_asmfiles NATIVE_COMMAND "${_archspec_asmfiles}")
        _aros_remove_empty_entries(_archspec_asmfiles)
        _aros_remove_token_entries(_archspec_asmfiles "\\")
        _aros_remove_directory_source_markers(_archspec_asmfiles)
      endif()
      if(NOT "${_archspec_linklibfiles}" STREQUAL "")
        separate_arguments(_archspec_linklibfiles NATIVE_COMMAND "${_archspec_linklibfiles}")
        _aros_strip_wrapping_quotes(_archspec_linklibfiles)
        _aros_remove_empty_entries(_archspec_linklibfiles)
        _aros_remove_token_entries(_archspec_linklibfiles "\\")
      endif()
      if(NOT "${_archspec_linklibobjs}" STREQUAL "")
        separate_arguments(_archspec_linklibobjs NATIVE_COMMAND "${_archspec_linklibobjs}")
        _aros_strip_wrapping_quotes(_archspec_linklibobjs)
        _aros_remove_empty_entries(_archspec_linklibobjs)
        _aros_remove_token_entries(_archspec_linklibobjs "\\")
      endif()
      if(NOT "${_archspec_usesdks}" STREQUAL "")
        separate_arguments(_archspec_usesdks NATIVE_COMMAND "${_archspec_usesdks}")
        _aros_remove_empty_entries(_archspec_usesdks)
        _aros_remove_token_entries(_archspec_usesdks "\\")
      endif()

      set(_archspec_is_active TRUE)
      if(NOT _archspec_mainmmake STREQUAL "")
        list(FIND _active_mmake_targets "${_archspec_mainmmake}" _active_archspec_target_index)
        if(_active_archspec_target_index EQUAL -1)
          set(_archspec_is_active FALSE)
        endif()
      endif()
      if(_archspec_arch)
        list(FIND _active_alias_layers "${_archspec_arch}" _active_archspec_index)
        if(_active_archspec_index EQUAL -1)
          set(_archspec_is_active FALSE)
        endif()
      endif()

      if(_archspec_is_active)
        _aros_tokenize_mmake_value("${_AROS_MMAKE_VAR_USER_CPPFLAGS}" _archspec_user_cppflags)
        _aros_tokenize_mmake_value("${_AROS_MMAKE_VAR_USER_INCLUDES}" _archspec_user_includes)
        _aros_tokenize_mmake_value("${_AROS_MMAKE_VAR_USER_CFLAGS}" _archspec_user_cflags)
        _aros_tokenize_mmake_value("${_AROS_MMAKE_VAR_USER_AFLAGS}" _archspec_user_aflags)
        _aros_tokenize_mmake_value("${_AROS_MMAKE_VAR_OPTIMIZATION_CFLAGS}" _archspec_optimization_cflags)

        list(APPEND _module_mmake_arch_files ${_archspec_files})
        list(APPEND _module_mmake_arch_asmfiles ${_archspec_asmfiles})
        list(APPEND _module_mmake_arch_linklibfiles ${_archspec_linklibfiles})
        list(APPEND _module_mmake_arch_linklibobjs ${_archspec_linklibobjs})
        list(APPEND _module_mmake_arch_usesdks ${_archspec_usesdks})

        set(_archspec_c_compile_args
          ${_archspec_user_cppflags}
          ${_archspec_user_includes}
          ${_archspec_user_cflags}
          ${_archspec_optimization_cflags}
        )
        _aros_remove_empty_entries(_archspec_c_compile_args)
        if(_archspec_c_compile_args)
          _aros_encode_token_list("${_archspec_c_compile_args}" _archspec_c_compile_args_string)
          foreach(_archspec_source IN LISTS _archspec_files)
            list(APPEND _module_mmake_arch_source_flag_specs
              "${_archspec_source}|${_archspec_c_compile_args_string}"
            )
          endforeach()
        endif()

        set(_archspec_asm_compile_args
          ${_archspec_user_cppflags}
          ${_archspec_user_includes}
          ${_archspec_user_aflags}
        )
        _aros_remove_empty_entries(_archspec_asm_compile_args)
        if(_archspec_asm_compile_args)
          _aros_encode_token_list("${_archspec_asm_compile_args}" _archspec_asm_compile_args_string)
          foreach(_archspec_source IN LISTS _archspec_asmfiles)
            list(APPEND _module_mmake_arch_source_flag_specs
              "${_archspec_source}|${_archspec_asm_compile_args_string}"
            )
          endforeach()
        endif()

        if(DEFINED _AROS_MMAKE_VAR_ISA_FLAGS AND NOT "${_AROS_MMAKE_VAR_ISA_FLAGS}" STREQUAL "")
          _aros_tokenize_mmake_value("${_AROS_MMAKE_VAR_ISA_FLAGS}" _archspec_isa_flags)
          _aros_encode_token_list("${_archspec_isa_flags}" _archspec_isa_flags_string)
          foreach(_archspec_source IN LISTS _archspec_files _archspec_asmfiles)
            list(APPEND _module_mmake_arch_source_flag_specs
              "${_archspec_source}|${_archspec_isa_flags_string}"
            )
          endforeach()
        endif()
      endif()
      continue()
    endif()

    if(_line MATCHES "^%rule_assemble_multi[ \t]+(.*)$")
      set(_rule_kind "asm")
      set(_rule_args "${CMAKE_MATCH_1}")
    elseif(_line MATCHES "^%rule_compile_(cxx_multi|objc_multi|multi)[ \t]+(.*)$")
      set(_rule_kind "${CMAKE_MATCH_1}")
      set(_rule_args "${CMAKE_MATCH_2}")
    else()
      unset(_rule_kind)
      unset(_rule_args)
    endif()

    if(DEFINED _rule_kind)
      _aros_expand_make_tokens("${_rule_args}" _expanded_args)
      separate_arguments(_arg_tokens NATIVE_COMMAND "${_expanded_args}")

      set(_rule_mmake "")
      set(_rule_basenames "")
      set(_rule_targetdir "")
      set(_pending_list_key "")
      foreach(_arg_token IN LISTS _arg_tokens)
        if(NOT _arg_token MATCHES "^([^=]+)=(.*)$")
          if(NOT _pending_list_key STREQUAL "")
            set(_pending_value_var "_rule_${_pending_list_key}")
            if("${${_pending_value_var}}" STREQUAL "")
              set(${_pending_value_var} "${_arg_token}")
            else()
              string(APPEND ${_pending_value_var} " ${_arg_token}")
            endif()
          endif()
          continue()
        endif()

        set(_arg_key "${CMAKE_MATCH_1}")
        set(_arg_value "${CMAKE_MATCH_2}")
        if(_arg_key STREQUAL "mmake")
          set(_pending_list_key "")
          set(_rule_mmake "${_arg_value}")
        elseif(_arg_key STREQUAL "basenames")
          set(_pending_list_key "basenames")
          set(_rule_basenames "${_arg_value}")
        elseif(_arg_key STREQUAL "targetdir")
          set(_pending_list_key "")
          set(_rule_targetdir "${_arg_value}")
        else()
          set(_pending_list_key "")
        endif()
      endforeach()

      if(_rule_mmake STREQUAL "" OR _rule_basenames STREQUAL "")
        continue()
      endif()

      list(FIND _active_mmake_targets "${_rule_mmake}" _active_rule_target_index)
      if(_active_rule_target_index EQUAL -1)
        continue()
      endif()

      separate_arguments(_rule_basenames NATIVE_COMMAND "${_rule_basenames}")
      _aros_remove_empty_entries(_rule_basenames)
      _aros_remove_token_entries(_rule_basenames "\\")
      _aros_remove_directory_source_markers(_rule_basenames)
      if(_rule_targetdir MATCHES "(^|/)linklib(/|$)")
        list(APPEND _module_mmake_arch_linklibfiles ${_rule_basenames})
      elseif(_rule_kind STREQUAL "asm")
        list(APPEND _module_mmake_arch_asmfiles ${_rule_basenames})
      else()
        list(APPEND _module_mmake_arch_files ${_rule_basenames})
      endif()

      _aros_tokenize_mmake_value("${_AROS_MMAKE_VAR_USER_CPPFLAGS}" _rule_user_cppflags)
      _aros_tokenize_mmake_value("${_AROS_MMAKE_VAR_USER_INCLUDES}" _rule_user_includes)
      if(_rule_kind STREQUAL "asm")
        _aros_tokenize_mmake_value("${_AROS_MMAKE_VAR_USER_AFLAGS}" _rule_user_compile_flags)
        set(_rule_compile_args
          ${_rule_user_cppflags}
          ${_rule_user_includes}
          ${_rule_user_compile_flags}
        )
      else()
        _aros_tokenize_mmake_value("${_AROS_MMAKE_VAR_USER_CFLAGS}" _rule_user_compile_flags)
        _aros_tokenize_mmake_value("${_AROS_MMAKE_VAR_OPTIMIZATION_CFLAGS}" _rule_optimization_cflags)
        set(_rule_compile_args
          ${_rule_user_cppflags}
          ${_rule_user_includes}
          ${_rule_user_compile_flags}
          ${_rule_optimization_cflags}
        )
      endif()
      _aros_remove_empty_entries(_rule_compile_args)
      if(_rule_compile_args)
        _aros_encode_token_list("${_rule_compile_args}" _rule_compile_args_string)
        foreach(_rule_source IN LISTS _rule_basenames)
          list(APPEND _module_mmake_arch_source_flag_specs
            "${_rule_source}|${_rule_compile_args_string}"
          )
        endforeach()
      endif()

      if(DEFINED _AROS_MMAKE_VAR_ISA_FLAGS AND NOT "${_AROS_MMAKE_VAR_ISA_FLAGS}" STREQUAL "")
        _aros_tokenize_mmake_value("${_AROS_MMAKE_VAR_ISA_FLAGS}" _rule_isa_flags)
        _aros_encode_token_list("${_rule_isa_flags}" _rule_isa_flags_string)
        foreach(_rule_source IN LISTS _rule_basenames)
          list(APPEND _module_mmake_arch_source_flag_specs
            "${_rule_source}|${_rule_isa_flags_string}"
          )
        endforeach()
      endif()
      unset(_rule_kind)
      unset(_rule_args)
    endif()
  endwhile()

  if(NOT DEFINED _module_mmake_user_cppflags AND DEFINED _AROS_MMAKE_VAR_USER_CPPFLAGS)
    separate_arguments(_module_mmake_user_cppflags NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_CPPFLAGS}")
    _aros_remove_empty_entries(_module_mmake_user_cppflags)
    _aros_remove_token_entries(_module_mmake_user_cppflags "\\")
  endif()
  if(NOT DEFINED _module_mmake_user_includes AND DEFINED _AROS_MMAKE_VAR_USER_INCLUDES)
    separate_arguments(_module_mmake_user_includes NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_INCLUDES}")
    _aros_remove_empty_entries(_module_mmake_user_includes)
    _aros_remove_token_entries(_module_mmake_user_includes "\\")
  endif()
  if(NOT DEFINED _module_mmake_user_ldflags AND DEFINED _AROS_MMAKE_VAR_USER_LDFLAGS)
    separate_arguments(_module_mmake_user_ldflags NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_LDFLAGS}")
    _aros_remove_empty_entries(_module_mmake_user_ldflags)
    _aros_remove_token_entries(_module_mmake_user_ldflags "\\")
  endif()
  if(NOT DEFINED _module_mmake_user_cflags AND DEFINED _AROS_MMAKE_VAR_USER_CFLAGS)
    separate_arguments(_module_mmake_user_cflags NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_CFLAGS}")
    _aros_remove_empty_entries(_module_mmake_user_cflags)
    _aros_remove_token_entries(_module_mmake_user_cflags "\\")
  endif()
  if(NOT DEFINED _module_mmake_user_aflags AND DEFINED _AROS_MMAKE_VAR_USER_AFLAGS)
    separate_arguments(_module_mmake_user_aflags NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_AFLAGS}")
    _aros_remove_empty_entries(_module_mmake_user_aflags)
    _aros_remove_token_entries(_module_mmake_user_aflags "\\")
  endif()
  if(NOT DEFINED _module_mmake_optimization_cflags AND DEFINED _AROS_MMAKE_VAR_OPTIMIZATION_CFLAGS)
    separate_arguments(_module_mmake_optimization_cflags NATIVE_COMMAND "${_AROS_MMAKE_VAR_OPTIMIZATION_CFLAGS}")
    _aros_remove_empty_entries(_module_mmake_optimization_cflags)
    _aros_remove_token_entries(_module_mmake_optimization_cflags "\\")
  endif()

  _aros_remove_empty_entries(_module_mmake_arch_files)
  _aros_remove_empty_entries(_module_mmake_arch_asmfiles)
  _aros_remove_empty_entries(_module_mmake_arch_linklibfiles)
  _aros_remove_empty_entries(_module_mmake_arch_linklibobjs)
  _aros_remove_empty_entries(_module_mmake_arch_usesdks)
  list(REMOVE_DUPLICATES _module_mmake_arch_files)
  list(REMOVE_DUPLICATES _module_mmake_arch_asmfiles)
  list(REMOVE_DUPLICATES _module_mmake_arch_linklibfiles)
  list(REMOVE_DUPLICATES _module_mmake_arch_linklibobjs)
  list(REMOVE_DUPLICATES _module_mmake_arch_usesdks)
  list(REMOVE_DUPLICATES _module_mmake_arch_source_flag_specs)
  if(DEFINED _AROS_MMAKE_VAR_RESIDENT_BEGIN AND NOT "${_AROS_MMAKE_VAR_RESIDENT_BEGIN}" STREQUAL "")
    set(_module_mmake_resident_begin "${_AROS_MMAKE_VAR_RESIDENT_BEGIN}")
  else()
    set(_module_mmake_resident_begin "compiler/libinit/libentry")
  endif()

  set(MODULE_MMAKE_PARSED_FILES "${_module_mmake_files}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_KIND "${_module_mmake_kind}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_COMPILER "${_module_mmake_compiler}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_OUTPUT_NAME "${_module_mmake_output_name}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_OUTPUT_DIR "${_module_mmake_output_dir}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_USER_CPPFLAGS "${_module_mmake_user_cppflags}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_USER_INCLUDES "${_module_mmake_user_includes}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_USER_LDFLAGS "${_module_mmake_user_ldflags}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_USER_CFLAGS "${_module_mmake_user_cflags}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_USER_AFLAGS "${_module_mmake_user_aflags}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_OPTIMIZATION_CFLAGS "${_module_mmake_optimization_cflags}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_USELIBS "${_module_mmake_uselibs}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_LINKLIBFILES "${_module_mmake_linklibfiles}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_LINKLIBOBJS "${_module_mmake_linklibobjs}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_USESDKS "${_module_mmake_usesdks}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_ARCH_FILES "${_module_mmake_arch_files}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_ARCH_ASMFILES "${_module_mmake_arch_asmfiles}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_ARCH_LINKLIBFILES "${_module_mmake_arch_linklibfiles}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_ARCH_LINKLIBOBJS "${_module_mmake_arch_linklibobjs}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_ARCH_USESDKS "${_module_mmake_arch_usesdks}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_ARCH_SOURCE_FLAG_SPECS "${_module_mmake_arch_source_flag_specs}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_VERSION "${_module_mmake_version}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_MODSUFFIX "${_module_mmake_modsuffix}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_RESIDENT_BEGIN "${_module_mmake_resident_begin}" PARENT_SCOPE)
  set(MODULE_MMAKE_PARSED_ACTIVE_TARGETS "${_active_mmake_targets}" PARENT_SCOPE)
  list(REMOVE_DUPLICATES _module_mmake_inputs)
  set(MODULE_MMAKE_PARSED_INPUTS "${_module_mmake_inputs}" PARENT_SCOPE)
endfunction()

function(_aros_compiler_builtin_include_dir compiler out_var)
  execute_process(COMMAND "${compiler}" -print-file-name=include
    RESULT_VARIABLE _result OUTPUT_VARIABLE _include_dir
    ERROR_VARIABLE _error OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT _result EQUAL 0 OR NOT IS_ABSOLUTE "${_include_dir}"
     OR NOT IS_DIRECTORY "${_include_dir}")
    message(FATAL_ERROR "Cannot resolve builtin headers for ${compiler}: ${_include_dir} ${_error}")
  endif()
  set(${out_var} "${_include_dir}" PARENT_SCOPE)
endfunction()

function(_aros_module_compile_args use_base_flags out_var)
  if(NOT _module_compiler_include_dir)
    message(FATAL_ERROR "Resolve the selected compiler's builtin headers before module compilation")
  endif()
  set(_common_compile_args
    "--sysroot=${AROS_SYSROOT}"
    # Explicit SDK -isystem paths otherwise precede GCC's implicit builtin
    # directory, selecting fallback float.h/stddef.h instead of compiler headers.
    -isystem "${_module_compiler_include_dir}"
  )
  if(DEFINED AROS_SOURCE_DIR AND NOT AROS_SOURCE_DIR STREQUAL "")
    list(APPEND _common_compile_args
      "-ffile-prefix-map=${AROS_SOURCE_DIR}/="
      "-fmacro-prefix-map=${AROS_SOURCE_DIR}/="
    )
  endif()
  if(DEFINED AROS_BINARY_DIR AND NOT AROS_BINARY_DIR STREQUAL "")
    list(APPEND _common_compile_args
      "-ffile-prefix-map=${AROS_BINARY_DIR}/="
      "-fmacro-prefix-map=${AROS_BINARY_DIR}/="
    )
  endif()
  list(APPEND _common_compile_args ${_module_config_cppflags})
  if(use_base_flags)
    list(APPEND _common_compile_args ${_module_mmake_user_cppflags})
    list(APPEND _common_compile_args ${_module_mmake_user_includes})
  endif()
  list(APPEND _common_compile_args -D__AROS_GIMME_DEPRECATED__)
  list(APPEND _common_compile_args ${_module_target_isa_cflags})
  list(APPEND _common_compile_args ${_module_target_optimization_cflags})
  list(APPEND _common_compile_args ${_module_target_base_cflags})
  list(APPEND _common_compile_args ${_module_isa_cflags})
  if(use_base_flags)
    list(APPEND _common_compile_args ${_module_mmake_user_cflags})
  endif()
  _aros_get_active_layers(_module_compile_layers)
  get_filename_component(_module_dir_name "${MODULE_PATH}" NAME)
  foreach(_module_compile_layer IN LISTS _module_compile_layers)
    set(_module_layer_dir "${AROS_SOURCE_DIR}/arch/${_module_compile_layer}/${_module_dir_name}")
    if(IS_DIRECTORY "${_module_layer_dir}")
      list(APPEND _common_compile_args "-I${_module_layer_dir}")
    endif()
  endforeach()
  foreach(_include_dir IN LISTS MODULE_INCLUDE_DIRS)
    list(APPEND _common_compile_args "-I${_include_dir}")
  endforeach()
  list(APPEND _common_compile_args "-iquote" "${_module_source_dir}")
  list(APPEND _common_compile_args ${_module_layer_includes})
  list(APPEND _common_compile_args ${_module_layer_cppflags})
  foreach(_define IN LISTS MODULE_COMPILE_DEFINITIONS)
    list(APPEND _common_compile_args "-D${_define}")
  endforeach()
  list(APPEND _common_compile_args ${MODULE_COMPILE_OPTIONS})
  if(use_base_flags)
    list(APPEND _common_compile_args ${_module_base_compile_options})
  endif()
  list(APPEND _common_compile_args ${_module_generated_cppflags})
  list(APPEND _common_compile_args ${_module_generated_cflags})
  list(APPEND _common_compile_args "-I${AROS_NATIVE_INCLUDE_DIR}")
  if(NOT _module_generated_include_root STREQUAL "${AROS_NATIVE_INCLUDE_DIR}")
    list(APPEND _common_compile_args "-I${_module_generated_include_root}")
  endif()
  list(APPEND _common_compile_args "-isystem" "${AROS_NATIVE_INCLUDE_DIR}/aros/posixc")
  list(APPEND _common_compile_args "-isystem" "${AROS_NATIVE_INCLUDE_DIR}/aros/stdc")
  list(APPEND _common_compile_args "-I${MODULE_GENERATED_DIR}")
  list(APPEND _common_compile_args "-I${MODULE_GENERATED_DIR}/include")
  list(APPEND _common_compile_args -include "${_module_deflibdefs}")
  list(APPEND _common_compile_args ${_module_target_safety_cflags})
  set(${out_var} "${_common_compile_args}" PARENT_SCOPE)
endfunction()

function(_aros_merge_source_compile_args common_args source_args out_var)
  set(_includes)
  set(_options)
  set(_include_operand FALSE)
  foreach(_arg IN LISTS source_args)
    if(_include_operand)
      list(APPEND _includes "${_arg}")
      set(_include_operand FALSE)
    elseif(_arg MATCHES "^(-I|-isystem|-iquote|-idirafter)$")
      list(APPEND _includes "${_arg}")
      set(_include_operand TRUE)
    elseif(_arg MATCHES "^(-I|-isystem|-iquote|-idirafter).+")
      list(APPEND _includes "${_arg}")
    else()
      list(APPEND _options "${_arg}")
    endif()
  endforeach()
  if(_include_operand)
    message(FATAL_ERROR "Source include option has no operand: ${source_args}")
  endif()
  # Header search uses first-match precedence; other flags (e.g. -O) use last.
  set(_result ${_includes} ${common_args} ${_options})
  set(${out_var} "${_result}" PARENT_SCOPE)
endfunction()

function(_aros_mmake_uses_kernel_includes includes out_var)
  _aros_read_config_tokens(KERNEL_INCLUDES _kernel_includes)
  set(_uses_kernel_includes FALSE)
  if(_kernel_includes)
    string(FIND ";${includes};" ";${_kernel_includes};" _index)
    if(NOT _index EQUAL -1)
      set(_uses_kernel_includes TRUE)
    endif()
  endif()
  set(${out_var} "${_uses_kernel_includes}" PARENT_SCOPE)
endfunction()

function(_aros_prefer_host_headers args out_var)
  _aros_remove_token_entries(args "-I${AROS_NATIVE_INCLUDE_DIR}")
  _aros_remove_flag_pair(args -I "${AROS_NATIVE_INCLUDE_DIR}")
  _aros_remove_flag_pair(args -isystem "${AROS_NATIVE_INCLUDE_DIR}/aros/posixc")
  _aros_remove_flag_pair(args -isystem "${AROS_NATIVE_INCLUDE_DIR}/aros/stdc")
  list(APPEND args -idirafter "${AROS_NATIVE_INCLUDE_DIR}")
  set(${out_var} "${args}" PARENT_SCOPE)
endfunction()

function(_aros_resolve_source_candidate module_dir basename out_var)
  if(IS_ABSOLUTE "${basename}" AND EXISTS "${basename}")
    set(${out_var} "${basename}" PARENT_SCOPE)
    return()
  endif()

  get_filename_component(_input_ext "${basename}" EXT)
  if(IS_ABSOLUTE "${basename}")
    if(_input_ext)
      set(_candidates "${basename}")
    else()
      set(_candidates)
      foreach(_ext IN ITEMS .c .cc .cxx .cpp .S .s)
        list(APPEND _candidates "${basename}${_ext}")
      endforeach()
    endif()
  elseif(_input_ext)
    set(_candidates "${module_dir}/${basename}")
  else()
    set(_candidates)
    foreach(_ext IN ITEMS .c .cc .cxx .cpp .S .s)
      list(APPEND _candidates "${module_dir}/${basename}${_ext}")
    endforeach()
  endif()

  foreach(_candidate IN LISTS _candidates)
    if(EXISTS "${_candidate}")
      set(${out_var} "${_candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()

  set(${out_var} "" PARENT_SCOPE)
endfunction()

function(_aros_resolve_layer_source_candidate module_dir source out_var)
  _aros_resolve_source_candidate("${module_dir}" "${source}" _resolved)
  if(NOT _resolved AND NOT IS_ABSOLUTE "${source}")
    # build_archspecific strips object paths; make.cfg also supplies the
    # manifest's source directory as VPATH after the declared source path.
    get_filename_component(_name "${source}" NAME)
    _aros_resolve_source_candidate("${module_dir}" "${_name}" _resolved)
  endif()
  set(${out_var} "${_resolved}" PARENT_SCOPE)
endfunction()

function(_aros_append_ordered_source_spec specs_var source_path)
  if(NOT source_path)
    return()
  endif()
  get_filename_component(_ordered_source_name "${source_path}" NAME)
  set(_ordered_specs "${${specs_var}}")
  list(APPEND _ordered_specs "${_ordered_source_name}|${source_path}")
  set(${specs_var} "${_ordered_specs}" PARENT_SCOPE)
endfunction()

function(_aros_finalize_ordered_source_specs specs_var out_var)
  set(_ordered_specs "${${specs_var}}")
  if(NOT _ordered_specs)
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  list(REMOVE_DUPLICATES _ordered_specs)
  list(SORT _ordered_specs)

  set(_ordered_sources)
  foreach(_ordered_spec IN LISTS _ordered_specs)
    string(REPLACE "|" ";" _ordered_parts "${_ordered_spec}")
    list(LENGTH _ordered_parts _ordered_len)
    if(_ordered_len LESS 2)
      continue()
    endif()
    list(GET _ordered_parts 1 _ordered_source_path)
    list(APPEND _ordered_sources "${_ordered_source_path}")
  endforeach()

  set(${out_var} "${_ordered_sources}" PARENT_SCOPE)
endfunction()

function(_aros_resolve_module_sources out_var)
  _aros_decode_list(MODULE_BASE_SOURCES)
  _aros_decode_list(MODULE_LAYER_OVERRIDES)
  _aros_decode_list(MODULE_LAYER_ADDITIONS)
  _aros_decode_list(MODULE_LAYER_EXCLUSIONS)
  _aros_decode_list(MODULE_LAYER_MANIFEST_LAYERS)
  if(DEFINED MODULE_RESOLVED_LAYERS AND NOT MODULE_RESOLVED_LAYERS STREQUAL "")
    set(_active_layers "${MODULE_RESOLVED_LAYERS}")
  else()
    _aros_get_active_layers(_active_layers)
  endif()
  get_filename_component(_module_dir_name "${MODULE_PATH}" NAME)

  set(_resolved_arch_source_specs)
  set(_resolved_base_sources)
  set(_base_source_stems)
  foreach(_base_source IN LISTS MODULE_BASE_SOURCES)
    get_filename_component(_base_stem "${_base_source}" NAME_WE)
    list(APPEND _base_source_stems "${_base_stem}")
  endforeach()
  foreach(_base_source IN LISTS MODULE_BASE_SOURCES)
    get_filename_component(_base_stem "${_base_source}" NAME_WE)
    _aros_resolve_source_candidate("${AROS_SOURCE_DIR}/${MODULE_PATH}" "${_base_source}" _resolved)
    if(NOT _resolved)
      message(FATAL_ERROR "Could not resolve base source '${_base_source}' under ${MODULE_PATH}")
    endif()
    set(_resolved_by_manual FALSE)
    foreach(_layer IN LISTS _active_layers)
      foreach(_override IN LISTS MODULE_LAYER_OVERRIDES)
        string(REPLACE ":" ";" _override_parts "${_override}")
        list(LENGTH _override_parts _override_len)
        if(NOT _override_len EQUAL 2)
          message(FATAL_ERROR "Invalid layer override spec: ${_override}")
        endif()
        list(GET _override_parts 0 _override_layer)
        list(GET _override_parts 1 _override_file)
        get_filename_component(_override_stem "${_override_file}" NAME_WE)
        if(_layer STREQUAL _override_layer AND _base_stem STREQUAL _override_stem)
          # build_archspecific replaces objects by basename, even when the
          # base and layer sources live in different relative directories.
          set(_matches "${_base_source_stems}")
          list(LENGTH _matches _base_count)
          list(REMOVE_ITEM _matches "${_base_stem}")
          list(LENGTH _matches _other_count)
          math(EXPR _match_count "${_base_count} - ${_other_count}")
          if(NOT _match_count EQUAL 1)
            message(FATAL_ERROR "Ambiguous base source for layer override ${_override}")
          endif()
          _aros_resolve_layer_source_candidate("${AROS_SOURCE_DIR}/arch/${_layer}/${_module_dir_name}" "${_override_file}" _resolved)
          if(NOT _resolved)
            message(FATAL_ERROR "Could not resolve declared layer override ${_override} for ${MODULE_PATH}")
          endif()
          set(_resolved_by_manual TRUE)
          break()
        endif()
      endforeach()
      if(_resolved_by_manual)
        break()
      endif()
    endforeach()
    if(NOT _resolved_by_manual)
      foreach(_layer IN LISTS _active_layers)
        list(FIND MODULE_LAYER_MANIFEST_LAYERS "${_layer}" _layer_manifest_index)
        if(NOT _layer_manifest_index EQUAL -1)
          continue()
        endif()
        _aros_resolve_source_candidate("${AROS_SOURCE_DIR}/arch/${_layer}/${_module_dir_name}" "${_base_source}" _layer_candidate)
        if(_layer_candidate)
          set(_resolved "${_layer_candidate}")
          break()
        endif()
      endforeach()
    endif()
    set(_resolved_is_layer FALSE)
    string(FIND "${_resolved}" "${AROS_SOURCE_DIR}/arch/" _resolved_arch_index)
    if(_resolved_arch_index EQUAL 0)
      set(_resolved_is_layer TRUE)
      string(FIND "${_resolved}" "${AROS_SOURCE_DIR}/${MODULE_PATH}/" _resolved_module_root_index)
      if(_resolved_module_root_index EQUAL 0)
        set(_resolved_is_layer FALSE)
      endif()
    endif()
    if(_resolved_is_layer)
      _aros_append_ordered_source_spec(_resolved_arch_source_specs "${_resolved}")
    else()
      list(APPEND _resolved_base_sources "${_resolved}")
    endif()
  endforeach()

  foreach(_layer IN LISTS _active_layers)
    list(FIND MODULE_LAYER_MANIFEST_LAYERS "${_layer}" _layer_manifest_index)
    if(NOT _layer_manifest_index EQUAL -1)
      continue()
    endif()
    set(_layer_module_dir "${AROS_SOURCE_DIR}/arch/${_layer}/${_module_dir_name}")
    if(NOT IS_DIRECTORY "${_layer_module_dir}")
      continue()
    endif()

    file(GLOB _layer_source_candidates
      RELATIVE "${_layer_module_dir}"
      "${_layer_module_dir}/*.c"
      "${_layer_module_dir}/*.cc"
      "${_layer_module_dir}/*.cxx"
      "${_layer_module_dir}/*.cpp"
      "${_layer_module_dir}/*.S"
      "${_layer_module_dir}/*.s"
    )
    list(SORT _layer_source_candidates)

    foreach(_layer_source IN LISTS _layer_source_candidates)
      get_filename_component(_layer_source_stem "${_layer_source}" NAME_WE)
      list(FIND _base_source_stems "${_layer_source_stem}" _base_match_index)
      if(NOT _base_match_index EQUAL -1)
        continue()
      endif()
      list(FIND MODULE_LAYER_EXCLUSIONS "${_layer}:${_layer_source}" _excluded_layer_source)
      if(NOT _excluded_layer_source EQUAL -1)
        continue()
      endif()
      _aros_append_ordered_source_spec(_resolved_arch_source_specs "${_layer_module_dir}/${_layer_source}")
    endforeach()
  endforeach()

  foreach(_addition IN LISTS MODULE_LAYER_ADDITIONS)
    string(REPLACE ":" ";" _addition_parts "${_addition}")
    list(LENGTH _addition_parts _addition_len)
    if(NOT _addition_len EQUAL 2)
      message(FATAL_ERROR "Invalid layer addition spec: ${_addition}")
    endif()
    list(GET _addition_parts 0 _addition_layer)
    list(GET _addition_parts 1 _addition_file)
    list(FIND _active_layers "${_addition_layer}" _active_addition_index)
    if(_active_addition_index EQUAL -1)
      continue()
    endif()
    _aros_resolve_layer_source_candidate("${AROS_SOURCE_DIR}/arch/${_addition_layer}/${_module_dir_name}" "${_addition_file}" _addition_path)
    if(NOT _addition_path)
      message(FATAL_ERROR "Could not resolve declared layer addition ${_addition} for ${MODULE_PATH}")
    endif()
    _aros_append_ordered_source_spec(_resolved_arch_source_specs "${_addition_path}")
  endforeach()

  _aros_finalize_ordered_source_specs(_resolved_arch_source_specs _resolved_arch_sources)
  list(REMOVE_DUPLICATES _resolved_base_sources)
  set(_resolved_sources ${_resolved_arch_sources} ${_resolved_base_sources})
  set(${out_var} "${_resolved_sources}" PARENT_SCOPE)
endfunction()
