include_guard(GLOBAL)

function(aros_determine_target_context target_name out_arch out_cpu out_variant out_family)
  string(REPLACE "-" ";" _parts "${target_name}")
  list(LENGTH _parts _parts_len)
  if(_parts_len LESS 2)
    message(FATAL_ERROR "AROS target must be in form <arch>-<cpu>[-<variant>], got: ${target_name}")
  endif()

  list(GET _parts 0 _arch)
  list(GET _parts 1 _cpu)

  set(_variant "")
  if(_parts_len GREATER 2)
    list(SUBLIST _parts 2 -1 _variant_parts)
    string(REPLACE ";" "-" _variant "${_variant_parts}")
  endif()

  if(_arch MATCHES "^(linux|freebsd|darwin|dragonfly|netbsd|openbsd|solaris)$")
    set(_family "unix")
  else()
    set(_family "${_arch}")
  endif()

  set(${out_arch} "${_arch}" PARENT_SCOPE)
  set(${out_cpu} "${_cpu}" PARENT_SCOPE)
  set(${out_variant} "${_variant}" PARENT_SCOPE)
  set(${out_family} "${_family}" PARENT_SCOPE)
endfunction()

function(_aros_join_system_include_flags input_dirs out_var)
  set(_flags "-nostdinc")
  foreach(_include_dir IN LISTS input_dirs)
    if(_include_dir STREQUAL "")
      continue()
    endif()
    string(APPEND _flags " -isystem ${_include_dir}")
  endforeach()
  set(${out_var} "${_flags}" PARENT_SCOPE)
endfunction()

function(_aros_find_toolchain_program_path toolchain_dir toolchain_prefix tool_name out_var)
  foreach(_candidate IN ITEMS
      "${toolchain_dir}/bin/${toolchain_prefix}-${tool_name}"
      "${toolchain_dir}/${toolchain_prefix}-${tool_name}")
    if(EXISTS "${_candidate}")
      set(${out_var} "${_candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()

  set(${out_var} "${toolchain_dir}/${toolchain_prefix}-${tool_name}" PARENT_SCOPE)
endfunction()

function(aros_write_bootstrap_config_snapshot)
  set(_options)
  set(_one_value_args
    BUILD_DIR
    TARGET
    TOOLCHAIN_DIR
    HOST_ARCH
    HOST_CPU
    BUILD_TYPE_DEFINE
  )
  cmake_parse_arguments(AROS_BOOTSTRAP "${_options}" "${_one_value_args}" "" ${ARGN})

  if(NOT AROS_BOOTSTRAP_BUILD_DIR
     OR NOT AROS_BOOTSTRAP_TARGET
     OR NOT AROS_BOOTSTRAP_TOOLCHAIN_DIR
     OR NOT AROS_BOOTSTRAP_HOST_ARCH
     OR NOT AROS_BOOTSTRAP_HOST_CPU)
    message(FATAL_ERROR "aros_write_bootstrap_config_snapshot requires BUILD_DIR, TARGET, TOOLCHAIN_DIR, HOST_ARCH, and HOST_CPU")
  endif()

  if(NOT AROS_BOOTSTRAP_BUILD_TYPE_DEFINE)
    set(AROS_BOOTSTRAP_BUILD_TYPE_DEFINE "-DAROS_BUILD_TYPE=AROS_BUILD_TYPE_PERSONAL")
  endif()

  aros_determine_target_context(
    "${AROS_BOOTSTRAP_TARGET}"
    _target_arch
    _target_cpu
    _target_variant
    _target_family
  )

  set(_target_suffix "")
  if(NOT _target_variant STREQUAL "")
    set(_target_suffix "-${_target_variant}")
  endif()

  set(_target_cpu32 "")
  if(_target_cpu STREQUAL "x86_64")
    set(_target_cpu32 "i386")
  endif()

  set(_target_cpu_mode "")
  set(_module_isa_cflags "")
  if(_target_cpu STREQUAL "x86_64")
    set(_module_isa_cflags "-ffixed-r12")
  endif()

  _aros_join_system_include_flags("${CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES}" _kernel_includes)

  set(_toolchain_prefix "${_target_cpu}-aros")
  _aros_find_toolchain_program_path("${AROS_BOOTSTRAP_TOOLCHAIN_DIR}" "${_toolchain_prefix}" "ar" _target_ar_plain)
  _aros_find_toolchain_program_path("${AROS_BOOTSTRAP_TOOLCHAIN_DIR}" "${_toolchain_prefix}" "ranlib" _target_ranlib)

  set(_config_dir "${AROS_BOOTSTRAP_BUILD_DIR}/config")
  set(_target_root "${AROS_BOOTSTRAP_BUILD_DIR}/bin/${AROS_BOOTSTRAP_TARGET}")
  set(_target_gen_dir "${_target_root}/gen")
  set(_target_config_dir "${_target_gen_dir}/config")
  file(MAKE_DIRECTORY "${_config_dir}" "${_target_config_dir}")

  set(_make_cfg_lines
    "# Generated by CMake bootstrap config snapshot."
    "TOP                            := ${AROS_BOOTSTRAP_BUILD_DIR}"
    "AROS_HOST_ARCH                 := ${AROS_BOOTSTRAP_HOST_ARCH}"
    "AROS_HOST_CPU                  := ${AROS_BOOTSTRAP_HOST_CPU}"
    "AROS_TARGET_ARCH               := ${_target_arch}"
    "AROS_TARGET_CPU                := ${_target_cpu}"
    "AROS_TARGET_CPU32              := ${_target_cpu32}"
    "AROS_TARGET_CPU_MODE           := ${_target_cpu_mode}"
    "AROS_TARGET_VARIANT            := ${_target_variant}"
    "AROS_TARGET_SUFFIX             := ${_target_suffix}"
    "HOSTDIR                        := $(TOP)/bin/$(AROS_HOST_ARCH)-$(AROS_HOST_CPU)"
    "TOOLDIR                        := $(HOSTDIR)/tools"
    "HOSTGENDIR                     := $(HOSTDIR)/gen/host"
    "TARGETDIR                      := $(TOP)/bin/$(AROS_TARGET_ARCH)-$(AROS_TARGET_CPU)$(AROS_TARGET_SUFFIX)"
    "GENDIR                         := $(TARGETDIR)/gen"
    "CROSSTOOLSDIR                  := ${AROS_BOOTSTRAP_TOOLCHAIN_DIR}"
    "AROS_DIR_AROS                  := AROS"
    "AROS_DIR_ARCH                  := ${_target_arch}${_target_suffix}"
    "AROS_DIR_BOOT                  := boot"
    "AROS_DIR_BOOTARCH              := $(AROS_DIR_BOOT)/$(AROS_DIR_ARCH)"
    "AROS_DIR_C                     := C"
    "AROS_DIR_CLASSES               := Classes"
    "AROS_DIR_CATALOGS              := Catalogs"
    "AROS_DIR_COMMODITIES           := Commodities"
    "AROS_DIR_DATATYPES             := $(AROS_DIR_CLASSES)/Datatypes"
    "AROS_DIR_GADGETS               := $(AROS_DIR_CLASSES)/Gadgets"
    "AROS_DIR_DEVS                  := Devs"
    "AROS_DIR_DRIVERS               := Drivers"
    "AROS_DIR_ENVARC                := Env-Archive"
    "AROS_DIR_EXPANSION             := Expansion"
    "AROS_DIR_FS                    := L"
    "AROS_DIR_HELP                  := Help"
    "AROS_DIR_LIBRARIES             := Libs"
    "AROS_DIR_LOCALE                := Locale"
    "AROS_DIR_PACKAGES              := Packages"
    "AROS_DIR_PREFS                 := Prefs"
    "AROS_DIR_PRESETS               := Presets"
    "AROS_DIR_PRINTERS              := Printers"
    "AROS_DIR_S                     := S"
    "AROS_DIR_STORAGE               := Storage"
    "AROS_DIR_SYSTEM                := System"
    "AROS_DIR_THEMES                := Themes"
    "AROS_DIR_TOOLS                 := Tools"
    "AROS_DIR_UTILITIES             := Utilities"
    "AROS_DIR_WALLPAPERS            := Wallpapers"
    "AROS_DIR_DEVELOPER             := Development"
    "AROS_DIR_BIN                   := bin"
    "AROS_DIR_SDK                   := SDK"
    "AROS_DIR_FD                    := fd"
    "AROS_DIR_INCLUDE               := include"
    "AROS_DIR_LIB                   := lib"
    "AROS_DIR_CONTRIB               := Extras"
    "AROSDIR                        := $(TARGETDIR)/$(AROS_DIR_AROS)"
    "AROSARCHDIR                    := $(AROSDIR)/$(AROS_DIR_BOOTARCH)"
    "AROS_BOOT                      := $(AROSDIR)/$(AROS_DIR_BOOT)"
    "AROS_C                         := $(AROSDIR)/$(AROS_DIR_C)"
    "AROS_CLASSES                   := $(AROSDIR)/$(AROS_DIR_CLASSES)"
    "AROS_CLASSES_ARCH              := $(AROSARCHDIR)/$(AROS_DIR_CLASSES)"
    "AROS_DATATYPES                 := $(AROSDIR)/$(AROS_DIR_DATATYPES)"
    "AROS_GADGETS                   := $(AROSDIR)/$(AROS_DIR_GADGETS)"
    "AROS_DEVS                      := $(AROSDIR)/$(AROS_DIR_DEVS)"
    "AROS_DEVS_ARCH                 := $(AROSARCHDIR)/$(AROS_DIR_DEVS)"
    "AROS_EXPANSION                 := $(AROSDIR)/$(AROS_DIR_EXPANSION)"
    "AROS_FS                        := $(AROSDIR)/$(AROS_DIR_FS)"
    "AROS_FS_ARCH                   := $(AROSARCHDIR)/$(AROS_DIR_FS)"
    "AROS_RESOURCES                 := $(AROS_DEVS)"
    "AROS_DRIVERS                   := $(AROS_DEVS)/$(AROS_DIR_DRIVERS)"
    "AROS_LIBRARIES                 := $(AROSDIR)/$(AROS_DIR_LIBRARIES)"
    "AROS_LIBRARIES_ARCH            := $(AROSARCHDIR)/$(AROS_DIR_LIBRARIES)"
    "AROS_LOCALE                    := $(AROSDIR)/$(AROS_DIR_LOCALE)"
    "AROS_CATALOGS                  := $(AROS_LOCALE)/$(AROS_DIR_CATALOGS)"
    "AROS_HELP                      := $(AROS_LOCALE)/$(AROS_DIR_HELP)"
    "AROS_PREFS                     := $(AROSDIR)/$(AROS_DIR_PREFS)"
    "AROS_ENVARC                    := $(AROS_PREFS)/$(AROS_DIR_ENVARC)"
    "AROS_PACKAGES                  := $(AROS_ENVARC)/SYS/$(AROS_DIR_PACKAGES)"
    "AROS_PRESETS                   := $(AROS_PREFS)/$(AROS_DIR_PRESETS)"
    "AROS_PRINTERS                  := $(AROS_DEVS)/$(AROS_DIR_PRINTERS)"
    "AROS_S                         := $(AROSDIR)/$(AROS_DIR_S)"
    "AROS_STORAGE                   := $(AROSDIR)/$(AROS_DIR_STORAGE)"
    "AROS_SYSTEM                    := $(AROSDIR)/$(AROS_DIR_SYSTEM)"
    "AROS_WALLPAPERS                := $(AROS_PRESETS)/$(AROS_DIR_WALLPAPERS)"
    "AROS_THEMES                    := $(AROS_PRESETS)/$(AROS_DIR_THEMES)"
    "AROS_IMAGES                    := $(AROS_SYSTEM)/Images"
    "AROS_TOOLS                     := $(AROSDIR)/$(AROS_DIR_TOOLS)"
    "AROS_UTILITIES                 := $(AROSDIR)/$(AROS_DIR_UTILITIES)"
    "AROS_WANDERER                  := $(AROS_SYSTEM)/Wanderer"
    "AROS_CONTRIB                   := $(AROSDIR)/$(AROS_DIR_CONTRIB)"
    "AROS_DEVELOPER                 := $(AROSDIR)/$(AROS_DIR_DEVELOPER)"
    "AROS_ARCH_DEVELOPMENT          := $(AROS_DEVELOPER)/$(AROS_TARGET_CPU)-$(AROS_TARGET_ARCH)$(AROS_TARGET_SUFFIX)-aros"
    "AROS_DEV_ARCH_BINS             := $(AROS_DEVELOPER)/$(AROS_TARGET_CPU)-aros/$(AROS_DIR_BIN)"
    "AROS_DEV_BINS                  := $(AROS_DEVELOPER)/$(AROS_DIR_BIN)"
    "AROS_DEBUG                     := $(AROS_DEVELOPER)/Debug"
    "AROS_FD                        := $(AROS_DEVELOPER)/$(AROS_DIR_FD)"
    "AROS_TESTS                     := $(AROS_DEBUG)/Tests"
    "AROS_ARCH_INCLUDES             := $(AROS_ARCH_DEVELOPMENT)/$(AROS_DIR_INCLUDE)"
    "AROS_INCLUDES                  := $(AROS_DEVELOPER)/$(AROS_DIR_INCLUDE)"
    "AROS_ARCH_LIB                  := $(AROS_ARCH_DEVELOPMENT)/$(AROS_DIR_LIB)"
    "AROS_LIB                       := $(AROS_DEVELOPER)/$(AROS_DIR_LIB)"
    "AROS_BUILD_SDKS                := $(GENDIR)/buildsdks"
    "AROS_PRIVATE_DEVELOPMENT       := $(AROS_BUILD_SDKS)/private"
    "AROS_PRIVATE_INCLUDES          := $(AROS_PRIVATE_DEVELOPMENT)/$(AROS_DIR_INCLUDE)"
    "AROS_PRIVATE_LIB               := $(AROS_PRIVATE_DEVELOPMENT)/$(AROS_DIR_LIB)"
    "AROS_REL_LIB                   := $(AROS_BUILD_SDKS)/rel/$(AROS_DIR_LIB)"
    "AROS_CONFIG_INCLUDES           := $(AROS_BUILD_SDKS)/config/$(AROS_DIR_INCLUDE)"
    "GENINCDIR                      := $(GENDIR)/include"
    "RESIDENT_BEGIN                 := compiler/libinit/libentry"
    "KICKSTART_BEGIN                := compiler/libinit/kickentry"
  )
  string(JOIN "\n" _make_cfg_text ${_make_cfg_lines})
  file(WRITE "${_config_dir}/make.cfg" "${_make_cfg_text}\n")

  set(_target_cfg_lines
    "# Generated by CMake bootstrap config snapshot."
    "FAMILY                        := ${_target_family}"
    "KERNEL_INCLUDES               := ${_kernel_includes}"
    "CONFIG_CPPFLAGS               = $(strip ${AROS_BOOTSTRAP_BUILD_TYPE_DEFINE})"
    "CONFIG_AFLAGS                 = $(strip )"
    "OPTIMIZATION_CFLAGS           = $(strip -O2)"
    "ISA_FLAGS                     = $(strip )"
    "TARGET_ISA_CFLAGS             = $(ISA_FLAGS)"
    "TARGET_ISA_LDFLAGS            = $(ISA_FLAGS)"
    "TARGET_CPPFLAGS               = $(strip $(USER_INCLUDES) $(CONFIG_CPPFLAGS) $(USER_CPPFLAGS))"
    "TARGET_C_LIBS                 = $(strip )"
    "MODULE_ISA_CFLAGS             := $(strip ${_module_isa_cflags})"
    "NOSTARTUP_LDFLAGS             := $(strip -nostartfiles)"
    "NOSTDLIB_LDFLAGS              := $(strip -nostdlib)"
    "NOSTARTUP_OBJECTS             = $(strip )"
    "AR_PLAIN                      = $(strip ${_target_ar_plain})"
    "RANLIB                        = $(strip ${_target_ranlib})"
    "AROS_TARGET_PLATFORM          := ${AROS_BOOTSTRAP_TARGET}"
    "ARCH                          := $(AROS_TARGET_ARCH)"
    "CPU                           := $(AROS_TARGET_CPU)"
    "CPU_MODE                      := $(AROS_TARGET_CPU_MODE)"
  )
  string(JOIN "\n" _target_cfg_text ${_target_cfg_lines})
  file(WRITE "${_target_config_dir}/target.cfg" "${_target_cfg_text}\n")

  file(WRITE "${_target_config_dir}/build.cfg" "# Generated by CMake bootstrap config snapshot.\n")
  file(WRITE "${_target_config_dir}/compiler.cfg" "# Generated by CMake bootstrap config snapshot.\n")
endfunction()
