include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSCatalogTargets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSStaticTargets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeGraphArguments.cmake")

function(_aros_collect_fetch_macro kind args prefix)
  set(${prefix}_FIELDS "" PARENT_SCOPE)
  if(NOT kind STREQUAL "fetch")
    return()
  endif()
  # Broad variable-identity candidates can contain unrelated fetch macros.
  # Select by identity before validating their implementation arguments.
  _aros_mmake_argument_tokens("${args}" _tokens)
  if(NOT _tokens_VALID)
    message(FATAL_ERROR "${_tokens_ERROR}")
  endif()
  set(_identities)
  foreach(_token IN LISTS _tokens_TOKENS)
    if(_token MATCHES "^mmake=(.*)$")
      _aros_expand_make_tokens("${CMAKE_MATCH_1}" _identity)
      separate_arguments(_identity UNIX_COMMAND "${_identity}")
      set(_identities "${_identity}")
    endif()
  endforeach()
  list(LENGTH _identities _count)
  if(NOT _count EQUAL 1 OR _identities MATCHES "[$%]|@[^@ \t]+@")
    message(FATAL_ERROR "Unresolved/ambiguous fetch identity: ${args}")
  endif()
  if(NOT _identities STREQUAL _AROS_SELECTED_FETCH_RULE)
    return()
  endif()
  # genmf overwrites earlier scalar arguments, including destination and mmake.
  _aros_mmake_macro_arguments("${args}" _arg LAST_WINS)
  _aros_read_mmake_logical_lines("${CMAKE_SOURCE_DIR}/config/make.tmpl" _template)
  set(_definitions 0)
  foreach(_line IN LISTS _template)
    if(_line MATCHES "^%define fetch[ \t]+(.*)$")
      _aros_mmake_macro_arguments("${CMAKE_MATCH_1}" _default)
      math(EXPR _definitions "${_definitions} + 1")
    endif()
  endforeach()
  if(NOT _definitions EQUAL 1)
    message(FATAL_ERROR "Expected one fetch definition in config/make.tmpl")
  endif()
  set(_allowed mmake archive archive_origins suffixes location base destination tooldir patches_origins patches_specs)
  foreach(_key IN LISTS _arg_KEYS _default_KEYS)
    if(NOT _key IN_LIST _allowed)
      message(FATAL_ERROR "Unsupported fetch argument: ${_key}")
    endif()
  endforeach()
  foreach(_key IN LISTS _allowed)
    if(NOT _key IN_LIST _arg_KEYS)
      if(_default_${_key} STREQUAL "/A" OR NOT _key IN_LIST _default_KEYS)
        message(FATAL_ERROR "Missing fetch argument/default: ${_key}")
      endif()
      set(_arg_${_key} "${_default_${_key}}")
    endif()
    if("${_arg_${_key}}" MATCHES "[$%;]|@[^@ \t]+@")
      message(FATAL_ERROR "Unresolved fetch ${_key}: ${_arg_${_key}}")
    endif()
    set(${prefix}_${_key} "${_arg_${_key}}" PARENT_SCOPE)
  endforeach()
  set(${prefix}_FIELDS "${_allowed}" PARENT_SCOPE)
endfunction()

function(_aros_fetch_json_string value out)
  string(REPLACE "\\" "\\\\" _value "${value}")
  string(REPLACE "\"" "\\\"" _value "${_value}")
  string(REPLACE "\n" "\\n" _value "${_value}")
  string(REPLACE "\r" "\\r" _value "${_value}")
  string(REPLACE "\t" "\\t" _value "${_value}")
  set(${out} "\"${_value}\"" PARENT_SCOPE)
endfunction()

# Consumers publish their native fetch closure explicitly. Do not infer
# source ownership from arbitrary CMake target dependencies or existing files.
function(_aros_native_fetch_dependencies out_var)
  set(_fetches)
  foreach(_provider IN LISTS ARGN)
    get_target_property(_report "${_provider}" AROS_FETCH_REPORT)
    if(_report)
      list(APPEND _fetches "${_provider}")
    else()
      get_target_property(_inherited "${_provider}" AROS_NATIVE_FETCH_TARGETS)
      if(_inherited)
        list(APPEND _fetches ${_inherited})
      endif()
    endif()
  endforeach()
  list(REMOVE_DUPLICATES _fetches)
  set(${out_var} "${_fetches}" PARENT_SCOPE)
endfunction()

function(_aros_register_mmake_fetch mmake out_target)
  set(${out_target} "" PARENT_SCOPE)
  string(SHA256 _key "${mmake}")
  set(_target "aros-fetch-${_key}")
  if(TARGET "${_target}")
    set(${out_target} "${_target}" PARENT_SCOPE)
    return()
  endif()
  set(_AROS_MMAKE_VAR_TOP "${CMAKE_BINARY_DIR}")
  set(_AROS_MMAKE_VAR_TARGETDIR "${AROS_NATIVE_OUTPUT_ROOT}")
  set(_AROS_SELECTED_FETCH_RULE "${mmake}")
  set(_AROS_RULE_OPTION_INCLUDES TRUE)
  set(_AROS_RULE_MACRO_COLLECTOR _aros_collect_fetch_macro)
  _aros_static_manifest_candidates("${mmake}" _candidates)
  set(_matches)
  foreach(_manifest IN LISTS _candidates)
    file(STRINGS "${_manifest}" _fetch REGEX "^%fetch[ \t]")
    if(NOT _fetch)
      continue()
    endif()
    _aros_collect_mmake_rules("${_manifest}" _rules)
    foreach(_id IN LISTS _rules_MACROS)
      list(APPEND _matches "${_manifest}")
      foreach(_field IN ITEMS mmake archive archive_origins suffixes location base destination tooldir patches_origins patches_specs)
        set(_fetch_${_field} "${_rules_MACRO_${_id}_${_field}}")
      endforeach()
      set(_includes "${_rules_INCLUDES}")
      set(_option_inputs "${_rules_OPTION_INPUTS}")
    endforeach()
  endforeach()
  list(LENGTH _matches _count)
  if(_count EQUAL 0)
    return()
  elseif(NOT _count EQUAL 1)
    message(FATAL_ERROR "Ambiguous native fetch producer for ${mmake}: ${_matches}")
  endif()
  foreach(_include IN LISTS _includes)
    if(NOT _include STREQUAL "${CMAKE_SOURCE_DIR}/config/aros.cfg" AND NOT _include IN_LIST _option_inputs)
      message(FATAL_ERROR "Fetch needs native support for included rules/options: ${_include}")
    endif()
  endforeach()
  # Fetch recipes may not silently replace extra rules attached upstream.
  foreach(_manifest IN LISTS _candidates)
    set(_AROS_RULE_OPTION_INCLUDES FALSE)
    if(_manifest IN_LIST _matches)
      set(_AROS_RULE_OPTION_INCLUDES TRUE)
    endif()
    _aros_program_prerequisites("${_manifest}" "${mmake}" _prerequisites)
    if(_prerequisites OR _prerequisites_STATIC_NODES)
      message(FATAL_ERROR "Unhandled fetch prerequisites for ${mmake}: ${_prerequisites};${_prerequisites_STATIC_NODES}")
    endif()
  endforeach()
  if(NOT _fetch_archive MATCHES "^[A-Za-z0-9_+.-]+$" OR _fetch_archive MATCHES "^[.]+$")
    message(FATAL_ERROR "Unsafe fetch archive name: ${_fetch_archive}")
  endif()
  get_filename_component(_directory "${_matches}" DIRECTORY)
  file(RELATIVE_PATH _module "${CMAKE_SOURCE_DIR}" "${_directory}")
  set(_working "${CMAKE_BINARY_DIR}/${_module}")
  get_filename_component(_destination "${_fetch_destination}" ABSOLUTE BASE_DIR "${_working}")
  _aros_catalog_native_output("${_destination}" "${CMAKE_BINARY_DIR}")
  # fetch.sh extracts/patches in destination; base only stores legacy cache
  # markers and patch copies. Native control files replace that bookkeeping.
  get_property(_destinations GLOBAL PROPERTY AROS_FETCH_DESTINATIONS)
  foreach(_other IN LISTS _destinations)
    foreach(_pair IN ITEMS "${_other}|${_destination}" "${_destination}|${_other}")
      string(REPLACE "|" ";" _pair "${_pair}")
      list(GET _pair 0 _parent)
      list(GET _pair 1 _child)
      file(RELATIVE_PATH _relative "${_parent}" "${_child}")
      if(NOT _relative MATCHES "^\\.\\.(/|$)" AND NOT IS_ABSOLUTE "${_relative}")
        message(FATAL_ERROR "Overlapping native fetch destinations: ${_other};${_destination}")
      endif()
    endforeach()
  endforeach()
  set_property(GLOBAL APPEND PROPERTY AROS_FETCH_DESTINATIONS "${_destination}")
  separate_arguments(_suffixes UNIX_COMMAND "${_fetch_suffixes}")
  if(NOT _suffixes)
    message(FATAL_ERROR "Raw fetch inputs need native implementation: ${mmake}")
  endif()
  foreach(_suffix IN LISTS _suffixes)
    if(NOT _suffix MATCHES "^(tar[.](gz|bz2|xz)|tgz|zip)$")
      message(FATAL_ERROR "Unsupported native fetch suffix: ${_suffix}")
    endif()
  endforeach()
  if(_fetch_location STREQUAL "")
    set(_fetch_location "${_fetch_destination}")
  endif()
  get_filename_component(_location "${_fetch_location}" ABSOLUTE BASE_DIR "${_working}")
  set(_archive_candidates)
  foreach(_suffix IN LISTS _suffixes)
    list(APPEND _archive_candidates "${_location}/${_fetch_archive}.${_suffix}")
  endforeach()
  separate_arguments(_origins UNIX_COMMAND "${_fetch_archive_origins}")
  set(_cache_metadata "${CMAKE_SOURCE_DIR}/scripts/fetch.sh")
  foreach(_suffix IN LISTS _suffixes)
    foreach(_origin IN LISTS _origins)
      if(_origin MATCHES "^cache://(.*)$")
        set(_cache_path "${CMAKE_MATCH_1}")
        file(STRINGS "${_cache_metadata}" _base REGEX "^cache_base=\"[^\"]+\"$")
        list(LENGTH _base _count)
        if(NOT _count EQUAL 1)
          message(FATAL_ERROR "Cannot read upstream cache:// origin from ${_cache_metadata}")
        endif()
        string(REGEX REPLACE "^cache_base=\"([^\"]+)\"$" "\\1" _origin "${_base}")
        if(NOT _cache_path STREQUAL "")
          string(APPEND _origin "/${_cache_path}")
        endif()
      endif()
      if(_origin MATCHES "^[A-Za-z]+://")
        if(NOT _origin MATCHES "^(https?|ftp)://")
          message(FATAL_ERROR "Unsupported native fetch origin: ${_origin}")
        endif()
      else()
        get_filename_component(_origin "${_origin}" ABSOLUTE BASE_DIR "${_working}")
      endif()
      list(APPEND _archive_candidates "${_origin}/${_fetch_archive}.${_suffix}")
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES _archive_candidates)
  set(_builder "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/build_mmake_fetch.py")
  set(_inputs "${_matches}" "${CMAKE_SOURCE_DIR}/config/make.tmpl" "${_builder}" ${_option_inputs})
  if(EXISTS "${_cache_metadata}")
    list(APPEND _inputs "${_cache_metadata}")
  endif()
  set(_local_candidates)
  foreach(_candidate IN LISTS _archive_candidates)
    if(IS_ABSOLUTE "${_candidate}")
      list(APPEND _local_candidates "${_candidate}")
    endif()
  endforeach()
  if(_local_candidates)
    file(GLOB _local_archives CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE ${_local_candidates})
    list(APPEND _inputs ${_local_archives})
  endif()
  separate_arguments(_patch_specs UNIX_COMMAND "${_fetch_patches_specs}")
  separate_arguments(_patch_origins UNIX_COMMAND "${_fetch_patches_origins}")
  set(_patches "[]")
  set(_patch_index 0)
  foreach(_spec IN LISTS _patch_specs)
    if(_spec STREQUAL "::")
      continue()
    endif()
    string(REPLACE ":" ";" _parts "${_spec}")
    list(LENGTH _parts _count)
    if(_count GREATER 3)
      message(FATAL_ERROR "Unsupported patch specification: ${_spec}")
    endif()
    list(GET _parts 0 _name)
    if(NOT _name MATCHES "^[A-Za-z0-9_+.-]+$" OR _name MATCHES "^[.]+$")
      message(FATAL_ERROR "Unsafe patch name: ${_name}")
    endif()
    set(_subdir "")
    set(_options "")
    if(_count GREATER 1)
      list(GET _parts 1 _subdir)
    endif()
    if(_count GREATER 2)
      list(GET _parts 2 _options)
    endif()
    if(IS_ABSOLUTE "${_subdir}" OR _subdir MATCHES "(^|/)[.][.](/|$)|[\\\\;$%]")
      message(FATAL_ERROR "Unsafe patch subdirectory: ${_subdir}")
    endif()
    string(REPLACE "," ";" _options "${_options}")
    foreach(_option IN LISTS _options)
      if(NOT _option MATCHES "^(-f|-p[0-9]+)$")
        message(FATAL_ERROR "Unsupported native patch option: ${_option}")
      endif()
    endforeach()
    set(_patch "")
    foreach(_origin IN LISTS _patch_origins)
      if(_origin MATCHES "://")
        message(FATAL_ERROR "Remote/compressed patches need native implementation: ${_origin}")
      endif()
      get_filename_component(_candidate "${_origin}/${_name}" ABSOLUTE BASE_DIR "${_working}")
      file(GLOB _existing CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE "${_candidate}")
      if(_existing AND _patch STREQUAL "")
        set(_patch "${_candidate}")
      endif()
    endforeach()
    if(_patch STREQUAL "")
      message(FATAL_ERROR "Missing native fetch patch: ${_name}")
    endif()
    _aros_catalog_static_input("${_patch}")
    list(APPEND _inputs "${_patch}")
    set(_entry "{}")
    foreach(_field IN ITEMS patch subdir)
      _aros_fetch_json_string("${_${_field}}" _json)
      string(JSON _entry SET "${_entry}" "${_field}" "${_json}")
    endforeach()
    set(_option_json "[]")
    foreach(_option IN LISTS _options)
      string(JSON _count LENGTH "${_option_json}")
      _aros_fetch_json_string("${_option}" _json)
      string(JSON _option_json SET "${_option_json}" ${_count} "${_json}")
    endforeach()
    string(JSON _entry SET "${_entry}" options "${_option_json}")
    string(JSON _patches SET "${_patches}" ${_patch_index} "${_entry}")
    math(EXPR _patch_index "${_patch_index} + 1")
  endforeach()
  find_package(Python3 3.8 REQUIRED COMPONENTS Interpreter)
  find_program(_patch_tool NAMES patch REQUIRED)
  list(APPEND _inputs "${_patch_tool}" "${Python3_EXECUTABLE}")
  set(_control "${CMAKE_BINARY_DIR}/fetch/${_key}")
  _aros_catalog_native_output("${_control}" "${CMAKE_BINARY_DIR}")
  set(_recipe "${_control}/recipe.json")
  set(_native_root "${CMAKE_BINARY_DIR}")
  set(_legacy_root "${AROS_LEGACY_BUILD_DIR}")
  set(_source_root "${CMAKE_SOURCE_DIR}")
  set(_identity "${mmake}")
  set(_json "{}")
  foreach(_field IN ITEMS identity destination native_root legacy_root source_root control patch_tool)
    _aros_fetch_json_string("${_${_field}}" _value)
    string(JSON _json SET "${_json}" "${_field}" "${_value}")
  endforeach()
  set(_array "[]")
  foreach(_candidate IN LISTS _archive_candidates)
    string(JSON _count LENGTH "${_array}")
    _aros_fetch_json_string("${_candidate}" _value)
    string(JSON _array SET "${_array}" ${_count} "${_value}")
  endforeach()
  string(JSON _json SET "${_json}" archives "${_array}")
  string(JSON _json SET "${_json}" patches "${_patches}")
  set(_fingerprint "${_json}")
  foreach(_input IN LISTS _inputs)
    file(SHA256 "${_input}" _hash)
    string(APPEND _fingerprint "\n${_input}:${_hash}")
  endforeach()
  string(SHA256 _fingerprint "${_fingerprint}")
  set(_report "${_control}/receipt-${_fingerprint}.json")
  _aros_fetch_json_string("${_report}" _value)
  string(JSON _json SET "${_json}" receipt "${_value}")
  file(CONFIGURE OUTPUT "${_recipe}" CONTENT "@_json@" @ONLY)
  file(SHA256 "${_recipe}" _recipe_hash)
  set(_ready FALSE)
  set(_outputs)
  if(EXISTS "${_report}")
    file(READ "${_report}" _receipt)
    string(JSON _hash ERROR_VARIABLE _error GET "${_receipt}" recipe_hash)
    if(NOT _error AND _hash STREQUAL _recipe_hash)
      string(JSON _count LENGTH "${_receipt}" files)
      if(_count GREATER 0)
        math(EXPR _last "${_count} - 1")
        foreach(_index RANGE ${_last})
          string(JSON _path GET "${_receipt}" files ${_index})
          if(IS_ABSOLUTE "${_path}" OR _path MATCHES "(^|/)[.][.]?(/|$)|[;\\\\\n\r$%*?|]"
             OR _path MATCHES "\\[|\\]")
            message(FATAL_ERROR "Unsafe fetch receipt path: ${_path}")
          endif()
          set(_output "${_destination}/${_path}")
          _aros_catalog_native_output("${_output}" "${_destination}")
          _aros_catalog_claim_output("${_output}" "${mmake}")
          list(APPEND _outputs "${_output}")
        endforeach()
      endif()
      set(_ready TRUE)
      foreach(_output IN LISTS _outputs)
        if(NOT EXISTS "${_output}")
          set(_ready FALSE)
        endif()
      endforeach()
      if(EXISTS "${_destination}/.aros-fetch-recipe")
        file(READ "${_destination}/.aros-fetch-recipe" _active_recipe)
      endif()
      if(NOT _active_recipe STREQUAL _recipe_hash)
        set(_ready FALSE)
      endif()
      string(SHA256 _owner_hash "${mmake}\n${_destination}")
      if(EXISTS "${_destination}/.aros-fetch-owner")
        file(READ "${_destination}/.aros-fetch-owner" _active_owner)
      endif()
      if(NOT _active_owner STREQUAL _owner_hash)
        set(_ready FALSE)
      endif()
    endif()
  endif()
  if(EXISTS "${_report}" AND NOT _ready)
    # A restored recipe can name an older receipt while another version owns
    # the destination. Invalidate only our receipt, not the extracted tree.
    file(REMOVE "${_report}")
  endif()
  if(AROS_LEGACY_BUILD_DIR)
    file(GLOB _config CONFIGURE_DEPENDS "${AROS_LEGACY_BUILD_DIR}/config/*.cfg"
      "${AROS_LEGACY_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/*.cfg"
      "${AROS_LEGACY_BUILD_DIR}/Makefile")
  endif()
  set(_markers "${_destination}/.aros-fetch-owner" "${_destination}/.aros-fetch-recipe")
  foreach(_marker IN LISTS _markers)
    _aros_catalog_claim_output("${_marker}" "${mmake}")
  endforeach()
  add_custom_command(OUTPUT "${_report}" BYPRODUCTS ${_outputs} ${_markers}
    COMMAND "${Python3_EXECUTABLE}" "${_builder}" "${_recipe}"
    DEPENDS "${_recipe}" "${_builder}" ${_inputs}
    COMMENT "Fetching and patching native sources for ${mmake}" VERBATIM)
  add_custom_target("${_target}" DEPENDS "${_report}")
  set_target_properties("${_target}" PROPERTIES FOLDER "aros/internal/fetch"
    AROS_FETCH_READY "${_ready}" AROS_FETCH_FILES "${_outputs}" AROS_FETCH_REPORT "${_report}"
    AROS_FETCH_DESTINATION "${_destination}"
    AROS_FETCH_PYTHON "${Python3_EXECUTABLE}")
  # CMake excludes custom outputs from its regeneration dependencies. Observe
  # receipt/output presence instead: preparation finishes before the next
  # ordinary build scans fetched sources in a newly configured consumer graph.
  file(GLOB _prepared CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE "${_report}" ${_outputs} ${_markers})
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    ${_inputs} ${_config} ${AROS_NATIVE_CONFIG_FILE})
  set(${out_target} "${_target}" PARENT_SCOPE)
endfunction()
