include_guard(GLOBAL)

# Called inside the shared parser at the selected rule, before later USER_*
# assignments change its context. This is a bounded C-program translation.
function(_aros_collect_program_options kind args prefix)
  # file(STRINGS) represents continued manifest lines with list separators.
  string(REPLACE ";" " " args "${args}")
  separate_arguments(_tokens NATIVE_COMMAND "${args}")
  set(_keys mmake progname files targetdir objdir srcdir compiler linker
    cppflags cflags dflags ldflags uselibs usehostlibs usesdks usestartup
    detach nix usetree coverageinstr funcinstr lto
    objcfiles cxxfiles asmfiles objs alwayscxxlink cxxflags dxxflags aflags)
  set(_seen)
  set(_key "")
  foreach(_token IN LISTS _tokens)
    if(_token MATCHES "^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")
      set(_key "${CMAKE_MATCH_1}")
      set(_value "${CMAKE_MATCH_2}")
      if(NOT _key IN_LIST _keys)
        message(FATAL_ERROR "Unsupported program argument ${_key} in ${MODULE_MMAKE_NAME}")
      endif()
      if(_key IN_LIST _seen)
        message(FATAL_ERROR "Duplicate program argument ${_key} in ${MODULE_MMAKE_NAME}")
      endif()
      list(APPEND _seen "${_key}")
      set(_arg_${_key} "${_value}")
    elseif(_key)
      string(APPEND _arg_${_key} " ${_token}")
    else()
      message(FATAL_ERROR "Unexpected program argument: ${_token}")
    endif()
  endforeach()
  if(NOT DEFINED _arg_compiler)
    set(_arg_compiler target)
  endif()
  if(NOT _arg_compiler STREQUAL "target" OR (_arg_linker AND NOT _arg_linker STREQUAL "target"))
    message(FATAL_ERROR "Expected target-OS compiler/linker for ${MODULE_MMAKE_NAME}")
  endif()
  foreach(_key IN ITEMS objcfiles cxxfiles asmfiles objs usehostlibs cxxflags dflags dxxflags aflags)
    if(_arg_${_key})
      message(FATAL_ERROR "Program ${MODULE_MMAKE_NAME}: ${_key} needs native implementation")
    endif()
  endforeach()
  if(_AROS_MMAKE_VAR_USER_OBJS)
    message(FATAL_ERROR "Program ${MODULE_MMAKE_NAME}: USER_OBJS needs native implementation")
  endif()
  foreach(_key IN ITEMS usetree alwayscxxlink coverageinstr funcinstr lto)
    if(NOT DEFINED _arg_${_key})
      if(_key MATCHES "^(coverageinstr|funcinstr|lto)$")
        string(TOUPPER "${_key}" _config_key)
        _aros_read_config_tokens("TARGET_${_config_key}" _arg_${_key})
      endif()
    endif()
    if(_arg_${_key} AND NOT _arg_${_key} STREQUAL "no")
      message(FATAL_ERROR "Program ${MODULE_MMAKE_NAME}: ${_key}=${_arg_${_key}} needs native implementation")
    endif()
  endforeach()
  if(NOT DEFINED _arg_nix)
    set(_arg_nix no)
  endif()
  if(NOT _arg_nix MATCHES "^(yes|no)$")
    message(FATAL_ERROR "Invalid nix=${_arg_nix} in ${MODULE_MMAKE_NAME}")
  endif()
  if(NOT DEFINED _arg_detach)
    set(_arg_detach no)
  endif()
  if(NOT _arg_detach MATCHES "^(yes|no)$")
    message(FATAL_ERROR "Invalid detach=${_arg_detach} in ${MODULE_MMAKE_NAME}")
  endif()
  if(NOT DEFINED _arg_usestartup)
    set(_arg_usestartup yes)
  endif()
  if(NOT _arg_usestartup MATCHES "^(yes|no)$")
    message(FATAL_ERROR "Invalid usestartup=${_arg_usestartup} in ${MODULE_MMAKE_NAME}")
  endif()
  if(kind STREQUAL "prog")
    if(NOT _arg_progname)
      message(FATAL_ERROR "Program ${MODULE_MMAKE_NAME} has no progname")
    endif()
    if(NOT _arg_files)
      set(_arg_files "${_arg_progname}")
    endif()
  elseif(NOT _arg_files OR _arg_progname)
    message(FATAL_ERROR "build_progs requires files and does not accept progname")
  endif()
  if(NOT DEFINED _arg_targetdir)
    _aros_expand_make_tokens("$(AROSDIR)/$(CURDIR)" _arg_targetdir)
  endif()
  if(DEFINED _arg_objdir)
    if(NOT IS_ABSOLUTE "${_arg_objdir}" OR
       _arg_objdir MATCHES "[$@%*?;|\\\\ \t\r\n]" OR
       _arg_objdir MATCHES "/[.][.]?(/|$)")
      message(FATAL_ERROR "Program ${MODULE_MMAKE_NAME}: objdir requires a normalized absolute path: ${_arg_objdir}")
    endif()
  endif()
  foreach(_key IN ITEMS files uselibs usesdks)
    _aros_tokenize_mmake_value("${_arg_${_key}}" _${_key})
    _aros_remove_empty_entries(_${_key})
  endforeach()
  if(DEFINED _arg_cppflags)
    _aros_tokenize_mmake_value("${_arg_cppflags}" _cppflags)
  else()
    _aros_read_config_tokens(CPPFLAGS _cppflags)
  endif()
  if(_arg_cflags OR (kind STREQUAL "progs" AND DEFINED _arg_cflags))
    _aros_tokenize_mmake_value("${_arg_cflags}" _cflags)
  else()
    _aros_read_config_tokens(CFLAGS _cflags)
  endif()
  if(kind STREQUAL "prog")
    _aros_tokenize_mmake_value("${_AROS_MMAKE_VAR_USER_INCLUDES}" _includes)
    list(APPEND _cflags ${_includes})
  endif()
  _aros_read_config_tokens(SAFETY_CFLAGS _safety)
  set(_COMPILE_FLAGS ${_cppflags} -D__AROS_GIMME_DEPRECATED__ ${_cflags} ${_safety})
  _aros_read_config_tokens(TARGET_ISA_LDFLAGS _LINK_OPTIONS)
  if(_arg_nix STREQUAL "yes")
    # rule_link_prog(s) adds this before startup/detach options, not to
    # compilation flags. Specs determine its native object/library inputs.
    _aros_read_config_tokens(NIX_LDFLAGS _nix)
    if(NOT _nix)
      message(FATAL_ERROR "Missing NIX_LDFLAGS for ${MODULE_MMAKE_NAME}")
    endif()
    list(APPEND _LINK_OPTIONS ${_nix})
  endif()
  if(_arg_usestartup STREQUAL "no")
    _aros_read_config_tokens(NOSTARTUP_LDFLAGS _nostartup)
    if(NOT _nostartup)
      message(FATAL_ERROR "Missing NOSTARTUP_LDFLAGS for ${MODULE_MMAKE_NAME}")
    endif()
    list(APPEND _LINK_OPTIONS ${_nostartup})
  endif()
  if(_arg_detach STREQUAL "yes")
    # Specs select the actual startup inputs; the program graph discovers
    # their native manifest producers rather than naming detach.o here.
    _aros_read_config_tokens(DETACH_LDFLAGS _detach)
    if(NOT _detach)
      message(FATAL_ERROR "Missing DETACH_LDFLAGS for ${MODULE_MMAKE_NAME}")
    endif()
    list(APPEND _LINK_OPTIONS ${_detach})
  endif()
  if(_arg_ldflags)
    _aros_tokenize_mmake_value("${_arg_ldflags}" _LINK_FLAGS)
  else()
    _aros_read_config_tokens(LDFLAGS _LINK_FLAGS)
    if(kind STREQUAL "prog" AND _arg_usestartup STREQUAL "no")
      _aros_read_config_tokens(NOSTARTUP_OBJECTS _nostartup_objects)
      if(_nostartup_objects)
        message(FATAL_ERROR "NOSTARTUP_OBJECTS needs a native producer: ${_nostartup_objects}")
      endif()
    endif()
  endif()
  _aros_read_config_tokens(TARGET_C_LIBS _ARCH_LIBS)
  _aros_expand_make_tokens("$(DEBUG)" _debug)
  if(_debug STREQUAL "yes")
    message(FATAL_ERROR "Program ${MODULE_MMAKE_NAME}: DEBUG=yes needs native debug sidecar support")
  endif()
  _aros_read_config_tokens(TARGET_STRIP _strip)
  set(_STRIP_FLAGS)
  set(_STRIP FALSE)
  if(_strip)
    list(POP_FRONT _strip _strip_tool)
    if(NOT _strip_tool MATCHES "(^|/|-)strip([.]exe)?$")
      message(FATAL_ERROR "Unsupported TARGET_STRIP for ${MODULE_MMAKE_NAME}: ${_strip_tool}")
    endif()
    set(_STRIP TRUE)
    set(_STRIP_FLAGS "${_strip}")
  endif()
  set(_KIND "${kind}")
  set(_NAME "${_arg_progname}")
  set(_FILES "${_files}")
  set(_USELIBS "${_uselibs}")
  set(_USESDKS "${_usesdks}")
  set(_TARGETDIR "${_arg_targetdir}")
  set(_SRCDIR "${_arg_srcdir}")
  set(_OBJDIR "${_arg_objdir}")
  set(_FIELDS KIND NAME FILES USELIBS USESDKS TARGETDIR SRCDIR OBJDIR COMPILE_FLAGS LINK_OPTIONS LINK_FLAGS ARCH_LIBS STRIP STRIP_FLAGS)
  foreach(_field IN LISTS _FIELDS)
    if("${_${_field}}" MATCHES "\\$|%")
      message(FATAL_ERROR "Unresolved program ${_field} for ${MODULE_MMAKE_NAME}: ${_${_field}}")
    endif()
    set(${prefix}_${_field} "${_${_field}}" PARENT_SCOPE)
  endforeach()
  set(${prefix}_FIELDS "${_FIELDS}" PARENT_SCOPE)
endfunction()
