include_guard(GLOBAL)

# Recognize the flat, optional source-directory copy recipe as data. Neither
# the shell condition nor CP/MKDIR commands are executed from the manifest.
function(_aros_mmake_directory_copy_recipe recipe prefix)
  set(${prefix}_MATCH FALSE PARENT_SCOPE)
  string(REGEX REPLACE "[ \t]+" " " _recipe "${recipe}")
  if(NOT _recipe MATCHES "^@?if \\[ -d ([^;]+) \\] ; then \\$\\(MKDIR\\) ([^;]+) ; \\$\\(CP\\) ([^;]+) ; fi$")
    return()
  endif()
  set(_guard "${CMAKE_MATCH_1}")
  set(_mkdir "${CMAKE_MATCH_2}")
  set(_copy "${CMAKE_MATCH_3}")
  foreach(_part IN ITEMS guard mkdir copy)
    _aros_expand_make_tokens("${_${_part}}" _expanded)
    separate_arguments(_${_part} UNIX_COMMAND "${_expanded}")
  endforeach()
  list(LENGTH _guard _guard_count)
  list(LENGTH _mkdir _mkdir_count)
  list(LENGTH _copy _copy_count)
  if(NOT _guard_count EQUAL 1 OR NOT _mkdir_count EQUAL 1 OR NOT _copy_count EQUAL 2)
    return()
  endif()
  list(GET _copy 0 _source)
  list(GET _copy 1 _destination)
  if(NOT _source STREQUAL "${_guard}/*" OR NOT _destination STREQUAL _mkdir)
    return()
  endif()
  set(${prefix}_MATCH TRUE PARENT_SCOPE)
  set(${prefix}_SOURCE "${_guard}" PARENT_SCOPE)
  set(${prefix}_DESTINATION "${_destination}" PARENT_SCOPE)
endfunction()

function(_aros_static_owned_source path)
  _aros_static_real_path("${path}" _real)
  file(REAL_PATH "${CMAKE_SOURCE_DIR}" _root)
  file(RELATIVE_PATH _relative "${_root}" "${_real}")
  if(_relative MATCHES "^\\.\\.(/|$)" OR IS_ABSOLUTE "${_relative}")
    message(FATAL_ERROR "Static copy requires an owned source: ${path}")
  endif()
  foreach(_generated_root IN ITEMS "${CMAKE_BINARY_DIR}" "${AROS_LEGACY_BUILD_DIR}")
    if(_generated_root STREQUAL "")
      continue()
    endif()
    _aros_static_real_path("${_generated_root}" _generated_root)
    file(RELATIVE_PATH _relative "${_generated_root}" "${_real}")
    if(NOT _relative MATCHES "^\\.\\.(/|$)" AND NOT IS_ABSOLUTE "${_relative}")
      message(FATAL_ERROR "Static copy requires an owned source: ${path}")
    endif()
  endforeach()
endfunction()

function(_aros_collect_static_directory_copy manifest source destination prefix)
  if("${source}${destination}" MATCHES "[$%*?;|&<>`\r\n]|\\[|\\]" OR source STREQUAL "")
    message(FATAL_ERROR "Unsupported static directory copy paths in ${manifest}")
  endif()
  get_filename_component(_base "${manifest}" DIRECTORY)
  get_filename_component(_source "${source}" ABSOLUTE BASE_DIR "${_base}")
  _aros_static_owned_source("${_source}")
  _aros_static_output_path("${destination}" _destination)
  # Track both a currently absent optional directory and its shell '*' inputs.
  # Hidden entries are absent from the inventory, as they are from shell '*'.
  file(GLOB _present CONFIGURE_DEPENDS LIST_DIRECTORIES TRUE "${_source}")
  file(GLOB _inputs CONFIGURE_DEPENDS LIST_DIRECTORIES TRUE "${_source}/[!.]*")
  set(${prefix}_INPUTS "" PARENT_SCOPE)
  set(${prefix}_DESTINATION "${_destination}" PARENT_SCOPE)
  if(NOT IS_DIRECTORY "${_source}")
    return()
  endif()
  if(NOT _inputs)
    message(FATAL_ERROR "Static directory copy has no matching source files: ${_source}")
  endif()
  foreach(_input IN LISTS _inputs)
    if(IS_DIRECTORY "${_input}" OR NOT EXISTS "${_input}" OR _input MATCHES "[;$%*?\r\n]")
      message(FATAL_ERROR "Static directory copy requires immediate source files: ${_input}")
    endif()
    _aros_static_owned_source("${_input}")
  endforeach()
  set(${prefix}_INPUTS "${_inputs}" PARENT_SCOPE)
endfunction()
