include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeRules.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeGraphArguments.cmake")

# This is only a candidate filter. The rule reader evaluates assignments and
# conditions before accepting a producer; inactive declarations are not edges.
function(_aros_static_target_pattern expression out_var)
  set(_pattern "${expression}")
  while(_pattern MATCHES "\\$\\([^()]*\\)")
    string(REGEX REPLACE "\\$\\([^()]*\\)" "AROSMETAVARIABLETOKEN" _pattern "${_pattern}")
  endwhile()
  string(REGEX REPLACE "([^A-Za-z0-9_-])" "\\\\\\1" _pattern "${_pattern}")
  string(REPLACE AROSMETAVARIABLETOKEN ".*" _pattern "${_pattern}")
  set(${out_var} "^${_pattern}$" PARENT_SCOPE)
endfunction()

function(_aros_static_target_candidate expression node out_var)
  if(NOT expression MATCHES "\\$")
    if(expression STREQUAL node)
      set(${out_var} TRUE PARENT_SCOPE)
    else()
      set(${out_var} FALSE PARENT_SCOPE)
    endif()
    return()
  endif()
  _aros_static_target_pattern("${expression}" _pattern)
  if(node MATCHES "${_pattern}")
    set(${out_var} TRUE PARENT_SCOPE)
  else()
    set(${out_var} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(_aros_static_manifest_candidates node out_var)
  set(_matches)
  foreach(_manifest IN LISTS AROS_MMAKE_MANIFESTS)
    file(SHA256 "${_manifest}" _hash)
    get_property(_cached GLOBAL PROPERTY "AROS_MANIFEST_CANDIDATES_${_hash}" SET)
    if(_cached)
      get_property(_all_expressions GLOBAL PROPERTY "AROS_MANIFEST_CANDIDATES_${_hash}")
    else()
      _aros_static_manifest_expressions("${_manifest}" _all_expressions)
      set_property(GLOBAL PROPERTY "AROS_MANIFEST_CANDIDATES_${_hash}" "${_all_expressions}")
    endif()
    foreach(_expression IN LISTS _all_expressions)
      _aros_static_target_candidate("${_expression}" "${node}" _match)
      if(_match)
        list(APPEND _matches "${_manifest}")
        break()
      endif()
    endforeach()
  endforeach()
  set(${out_var} "${_matches}" PARENT_SCOPE)
endfunction()

# Cache only unevaluated identity expressions, never conditional results or
# expanded paths. New configuration contexts must still evaluate the manifest.
function(_aros_static_manifest_expressions _manifest out_var)
  set(_all_expressions)
  _aros_read_mmake_logical_lines("${_manifest}" _lines PRESERVE_RECIPES)
  set(_next FALSE)
  set(_marker_frames)
  foreach(_line IN LISTS _lines)
    set(_expressions)
    if(_line MATCHES "^if(n?eq|n?def)[ \t(]")
      list(LENGTH _marker_frames _depth)
      set(_marker_other_${_depth} "${_next}")
      list(APPEND _marker_frames "${_next}")
      continue()
    elseif(_line STREQUAL "else")
      list(LENGTH _marker_frames _depth)
      if(_depth GREATER 0)
        math(EXPR _depth "${_depth} - 1")
        set(_marker_other_${_depth} "${_next}")
        list(GET _marker_frames -1 _next)
      endif()
      continue()
    elseif(_line STREQUAL "endif")
      list(LENGTH _marker_frames _depth)
      if(_depth GREATER 0)
        list(POP_BACK _marker_frames)
        math(EXPR _depth "${_depth} - 1")
        if(_marker_other_${_depth})
          set(_next TRUE)
        endif()
      endif()
      continue()
    elseif(_line STREQUAL "#MM")
      set(_next TRUE)
      continue()
    elseif(_line MATCHES "^#MM-?[ \t]+([^:]+)")
      set(_expressions "${CMAKE_MATCH_1}")
      set(_next FALSE)
    elseif(_line MATCHES "^([A-Za-z0-9_-]+)[ \t]*(\\+=|:=|\\?=|=)")
      continue()
    elseif(_next AND _line MATCHES "^([^:]+):")
      set(_expressions "${CMAKE_MATCH_1}")
      set(_next FALSE)
    elseif(_line MATCHES "^%[A-Za-z0-9_]+[ \t]+(.*)$")
      if(ARGV2 STREQUAL "METADATA_ONLY")
        continue()
      endif()
      _aros_mmake_raw_arguments("${CMAKE_MATCH_1}" _args)
      if(NOT _args_VALID)
        # Keep undecodable identities as candidates, never silently discard
        # them. The active consumer diagnoses unsupported declarations.
        list(APPEND _all_expressions "$(unknown)")
        continue()
      endif()
      # Macros may also export suffixed names (includes, quick, etc.).
      # Do not mistake an untranslated macro product for an absent layer.
      foreach(_key IN ITEMS mmake mainmmake)
        if(_key IN_LIST _args_KEYS)
          string(REGEX REPLACE "^[\"'](.*)[\"']$" "\\1" _identity "${_args_${_key}}")
          list(APPEND _all_expressions "${_identity}" "${_identity}-$(suffix)")
        endif()
      endforeach()
      continue()
    endif()
    _aros_mmake_argument_tokens("${_expressions}" _words)
    if(_words_VALID)
      foreach(_expression IN LISTS _words_TOKENS)
        string(REGEX REPLACE "^[\"'](.*)[\"']$" "\\1" _expression "${_expression}")
        list(APPEND _all_expressions "${_expression}")
      endforeach()
    else()
      list(APPEND _all_expressions "$(unknown)")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES _all_expressions)
  set(${out_var} "${_all_expressions}" PARENT_SCOPE)
endfunction()

# Broad inventory candidates include macros whose generated identities are not
# known yet. They must not activate unrelated generated/recipe includes.
function(_aros_metadata_option_context manifest node out_var)
  _aros_static_manifest_expressions("${manifest}" _expressions METADATA_ONLY)
  set(_selected FALSE)
  foreach(_expression IN LISTS _expressions)
    _aros_static_target_candidate("${_expression}" "${node}" _match)
    if(_match)
      set(_selected TRUE)
    endif()
  endforeach()
  set(${out_var} "${_selected}" PARENT_SCOPE)
endfunction()

function(_aros_collect_static_macro kind args prefix)
  set(${prefix}_FIELDS "" PARENT_SCOPE)
  if(args MATCHES "(^|[ \t])(mmake|mainmmake)=([^ \t]+)")
    set(_name "${CMAKE_MATCH_3}")
    _aros_expand_make_tokens("${_name}" _name)
    string(REPLACE "\"" "" _name "${_name}")
    string(FIND "${_AROS_STATIC_SELECTED_MMAKE}" "${_name}-" _suffix_at)
    if(_name STREQUAL _AROS_STATIC_SELECTED_MMAKE OR _suffix_at EQUAL 0)
      message(FATAL_ERROR "Static target ${_AROS_STATIC_SELECTED_MMAKE} needs native support for %${kind}")
    endif()
  endif()
endfunction()

function(_aros_register_static_mmake node out_var)
  if(node MATCHES "[$%/ \t]" OR node STREQUAL "")
    message(FATAL_ERROR "Unresolved static metadata prerequisite: ${node}")
  endif()
  string(SHA256 _key "${node}")
  get_property(_visiting GLOBAL PROPERTY "AROS_STATIC_VISITING_${_key}")
  if(_visiting)
    message(FATAL_ERROR "Unsupported static metadata dependency cycle at ${node}")
  endif()
  get_property(_registered GLOBAL PROPERTY "AROS_STATIC_MMAKE_${_key}")
  if(_registered)
    set(${out_var} "${_registered}" PARENT_SCOPE)
    return()
  endif()
  _aros_static_manifest_candidates("${node}" _candidates)
  set(_parts)
  set(_dependencies)
  set(_AROS_RULE_MACRO_COLLECTOR _aros_collect_static_macro)
  set(_AROS_STATIC_SELECTED_MMAKE "${node}")
  foreach(_manifest IN LISTS _candidates)
    list(LENGTH _parts _id)
    aros_collect_mmake_static_files("${_manifest}" "${node}" _part_${_id} STRICT)
    if(_part_${_id}_EXPORTED)
      list(APPEND _parts "${_manifest}")
      list(APPEND _dependencies ${_part_${_id}_EXTERNAL_MMAKE})
    endif()
  endforeach()
  set(${out_var} "" PARENT_SCOPE)
  if(NOT _parts)
    # Like MetaMake, absent metadata edges are optional (not missing files).
    # The inventory makes an upstream-added producer visible on the next build.
    return()
  endif()
  set_property(GLOBAL PROPERTY "AROS_STATIC_VISITING_${_key}" TRUE)
  set(_children)
  list(REMOVE_DUPLICATES _dependencies)
  foreach(_dependency IN LISTS _dependencies)
    _aros_register_static_mmake("${_dependency}" _child)
    if(_child)
      list(APPEND _children "${_child}")
    endif()
  endforeach()
  set(_outputs)
  set(_id 0)
  foreach(_manifest IN LISTS _parts)
    _aros_add_mmake_static_commands("${_manifest}" _part_${_id} _files ${_children})
    list(APPEND _outputs ${_files})
    math(EXPR _id "${_id} + 1")
  endforeach()
  set(_target "aros-static-${_key}")
  add_custom_target("${_target}" DEPENDS ${_outputs} ${_children})
  set_target_properties("${_target}" PROPERTIES FOLDER "aros/internal/packaging"
    AROS_STATIC_OUTPUTS "${_outputs}" AROS_STATIC_MMAKE "${node}")
  set_property(GLOBAL PROPERTY "AROS_STATIC_VISITING_${_key}" FALSE)
  set_property(GLOBAL PROPERTY "AROS_STATIC_MMAKE_${_key}" "${_target}")
  set(${out_var} "${_target}" PARENT_SCOPE)
endfunction()

function(aros_add_mmake_static_target target_name)
  cmake_parse_arguments(ARG "" "MMAKE_NAME" "" ${ARGN})
  if(NOT ARG_MMAKE_NAME OR ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "aros_add_mmake_static_target requires MMAKE_NAME")
  endif()
  _aros_register_static_mmake("${ARG_MMAKE_NAME}" _target)
  if(NOT _target)
    message(FATAL_ERROR "No native static manifest producer for ${ARG_MMAKE_NAME}")
  endif()
  add_custom_target("${target_name}" DEPENDS "${_target}")
  set_target_properties("${target_name}" PROPERTIES FOLDER "aros/packaging")
endfunction()

# An explicitly partial profile: build exported ordinary rules, not MetaMake's
# global aggregate of the same name. All reachable local recipes are checked.
function(aros_add_mmake_local_static_target target_name)
  cmake_parse_arguments(ARG "" "MMAKE_NAME" "" ${ARGN})
  if(NOT ARG_MMAKE_NAME OR ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "aros_add_mmake_local_static_target requires MMAKE_NAME")
  endif()
  _aros_static_manifest_candidates("${ARG_MMAKE_NAME}" _candidates)
  set(_outputs)
  set(_found FALSE)
  set(_AROS_RULE_MACRO_COLLECTOR _aros_collect_static_macro)
  set(_AROS_STATIC_SELECTED_MMAKE "${ARG_MMAKE_NAME}")
  foreach(_manifest IN LISTS _candidates)
    aros_collect_mmake_static_files("${_manifest}" "${ARG_MMAKE_NAME}" _part STRICT LOCAL_ONLY)
    if(_part_EXPORTED)
      set(_found TRUE)
      _aros_add_mmake_static_commands("${_manifest}" _part _files)
      list(APPEND _outputs ${_files})
    endif()
  endforeach()
  if(NOT _found)
    message(FATAL_ERROR "No native local static manifest producer for ${ARG_MMAKE_NAME}")
  endif()
  add_custom_target("${target_name}" DEPENDS ${_outputs})
  set_target_properties("${target_name}" PROPERTIES FOLDER "aros/packaging"
    AROS_STATIC_OUTPUTS "${_outputs}" AROS_STATIC_LOCAL_MMAKE "${ARG_MMAKE_NAME}")
endfunction()
