include_guard(GLOBAL)

# Option fragments are data, not included make recipes. Both configure-time
# discovery and archive compilation use this same bounded input contract.
function(_aros_read_assignment_options path source_root binary_root legacy_root out_var)
  file(REAL_PATH "${path}" _real)
  file(RELATIVE_PATH _relative "${source_root}" "${_real}")
  if(NOT IS_ABSOLUTE "${path}" OR NOT EXISTS "${path}" OR IS_DIRECTORY "${path}"
      OR IS_ABSOLUTE "${_relative}" OR _relative MATCHES "^[.][.](/|$)")
    message(FATAL_ERROR "Options include needs an owned source file: ${path}")
  endif()
  foreach(_root IN ITEMS "${binary_root}" "${legacy_root}")
    if(_root STREQUAL "")
      continue()
    endif()
    file(RELATIVE_PATH _relative "${_root}" "${_real}")
    if(NOT IS_ABSOLUTE "${_relative}" AND NOT _relative MATCHES "^[.][.](/|$)")
      message(FATAL_ERROR "Options include needs an owned source file: ${path}")
    endif()
  endforeach()
  _aros_read_mmake_logical_lines("${path}" _lines PRESERVE_RECIPES)
  foreach(_line IN LISTS _lines)
    if(_line MATCHES "^[ ]*#MM")
      message(FATAL_ERROR "Unsupported options include metadata in ${path}: ${_line}")
    endif()
    if(_line MATCHES "^[ ]*(#|$)")
      continue()
    endif()
    if(NOT _line MATCHES "^[ ]*([A-Za-z0-9_-]+)[ \t]*(\\+=|:=|\\?=|=)[ \t]*(.*)$"
        OR _line MATCHES "\\$\\(shell[ \t]")
      message(FATAL_ERROR "Unsupported options include statement in ${path}: ${_line}")
    endif()
  endforeach()
  set(${out_var} "${_lines}" PARENT_SCOPE)
endfunction()

function(_aros_evaluate_make_equality line out_var)
  if(NOT line MATCHES "^(ifn?eq)[ \t]*\\((.*)\\)$")
    message(FATAL_ERROR "Unsupported mmake conditional: ${line}")
  endif()
  set(_operator "${CMAKE_MATCH_1}")
  _aros_split_make_arguments("${CMAKE_MATCH_2}" _arguments)
  list(LENGTH _arguments _count)
  if(NOT _count EQUAL 2)
    message(FATAL_ERROR "Unsupported mmake conditional: ${line}")
  endif()
  list(GET _arguments 0 _left)
  list(GET _arguments 1 _right)
  _aros_expand_make_tokens("${_left}" _left)
  _aros_expand_make_tokens("${_right}" _right)
  set(_active FALSE)
  if((_operator STREQUAL "ifeq" AND _left STREQUAL _right)
     OR (_operator STREQUAL "ifneq" AND NOT _left STREQUAL _right))
    set(_active TRUE)
  endif()
  set(${out_var} "${_active}" PARENT_SCOPE)
endfunction()

# Both manifest parsers supply token expansion and balanced Make-call parsing.
function(_aros_expand_make_word_function input_value out_value out_changed)
  _aros_extract_make_call("${input_value}" strip _prefix _body _suffix)
  if(NOT _body STREQUAL "")
    string(FIND "${_prefix}" "$(foreach " _foreach_start)
    if(NOT _foreach_start LESS 0)
      # Let the caller bind foreach variables before expanding its body.
      set(${out_value} "${input_value}" PARENT_SCOPE)
      set(${out_changed} FALSE PARENT_SCOPE)
      return()
    endif()
    string(REGEX REPLACE "^strip[ \t]*" "" _words "${_body}")
    _aros_expand_make_tokens("${_words}" _words)
    string(REGEX REPLACE "[ \t\r\n]+" " " _words "${_words}")
    string(STRIP "${_words}" _words)
    set(${out_value} "${_prefix}${_words}${_suffix}" PARENT_SCOPE)
    set(${out_changed} TRUE PARENT_SCOPE)
    return()
  endif()
  foreach(_function IN ITEMS addprefix addsuffix findstring filter filter-out)
    _aros_extract_make_call("${input_value}" "${_function}" _prefix _body _suffix)
    if(_body STREQUAL "")
      continue()
    endif()
    string(REGEX REPLACE "^${_function}[ \t]+" "" _arguments "${_body}")
    _aros_split_make_arguments("${_arguments}" _arguments)
    list(LENGTH _arguments _argument_count)
    if(NOT _argument_count EQUAL 2)
      message(FATAL_ERROR "Unsupported ${_function} expression: ${_body}")
    endif()
    list(GET _arguments 0 _affix)
    list(GET _arguments 1 _words)
    _aros_expand_make_tokens("${_affix}" _affix)
    _aros_expand_make_tokens("${_words}" _words)
    if(_function STREQUAL "findstring")
      if("${_affix}${_words}" MATCHES "\\$|@[^@ \t]+@")
        continue()
      endif()
      string(FIND "${_words}" "${_affix}" _index)
      set(_result "")
      if(NOT _affix STREQUAL "" AND NOT _index LESS 0)
        set(_result "${_affix}")
      endif()
      set(${out_value} "${_prefix}${_result}${_suffix}" PARENT_SCOPE)
      set(${out_changed} TRUE PARENT_SCOPE)
      return()
    endif()
    string(REGEX MATCHALL "[^ \t\r\n;]+" _words "${_words}")
    set(_result)
    if(_function MATCHES "^filter")
      # Discovery also reads unrelated assignments containing unsupported
      # nested functions. Preserve those expressions for strict consumers to
      # reject if they become reachable, rather than filtering literal tokens.
      if("${_affix}${_words}" MATCHES "\\$|@[^@ \t]+@")
        continue()
      endif()
      string(REGEX MATCHALL "[^ \t\r\n;]+" _patterns "${_affix}")
      foreach(_word IN LISTS _words)
        set(_matches FALSE)
        foreach(_pattern IN LISTS _patterns)
          if(_pattern MATCHES "\\\\" OR _pattern MATCHES "%.*%")
            message(FATAL_ERROR "Unsupported filter pattern: ${_pattern}")
          endif()
          string(REGEX REPLACE "([][+.*^$()?|])" "\\\\\\1" _pattern "${_pattern}")
          string(REPLACE "%" ".*" _pattern "${_pattern}")
          if(_word MATCHES "^${_pattern}$")
            set(_matches TRUE)
          endif()
        endforeach()
        if((_matches AND _function STREQUAL "filter")
           OR (NOT _matches AND _function STREQUAL "filter-out"))
          list(APPEND _result "${_word}")
        endif()
      endforeach()
      list(JOIN _result " " _result)
      set(${out_value} "${_prefix}${_result}${_suffix}" PARENT_SCOPE)
      set(${out_changed} TRUE PARENT_SCOPE)
      return()
    endif()
    foreach(_word IN LISTS _words)
      if(_function STREQUAL "addprefix")
        list(APPEND _result "${_affix}${_word}")
      else()
        list(APPEND _result "${_word}${_affix}")
      endif()
    endforeach()
    list(JOIN _result " " _result)
    set(${out_value} "${_prefix}${_result}${_suffix}" PARENT_SCOPE)
    set(${out_changed} TRUE PARENT_SCOPE)
    return()
  endforeach()
  set(${out_value} "${input_value}" PARENT_SCOPE)
  set(${out_changed} FALSE PARENT_SCOPE)
endfunction()
