include_guard(GLOBAL)

function(aros_determine_target_context target_name out_arch out_cpu out_variant out_family)
  string(REPLACE "-" ";" _parts "${target_name}")
  list(LENGTH _parts _parts_len)
  if(_parts_len LESS 2)
    message(FATAL_ERROR "AROS target must be in form <arch>-<cpu>[-<variant>], got: ${target_name}")
  endif()

  list(GET _parts 0 _arch)
  list(GET _parts 1 _cpu)

  set(_variant "")
  if(_parts_len GREATER 2)
    list(SUBLIST _parts 2 -1 _variant_parts)
    string(REPLACE ";" "-" _variant "${_variant_parts}")
  endif()

  if(_arch MATCHES "^(linux|freebsd|darwin|dragonfly|netbsd|openbsd|solaris)$")
    set(_family "unix")
  else()
    set(_family "${_arch}")
  endif()

  set(${out_arch} "${_arch}" PARENT_SCOPE)
  set(${out_cpu} "${_cpu}" PARENT_SCOPE)
  set(${out_variant} "${_variant}" PARENT_SCOPE)
  set(${out_family} "${_family}" PARENT_SCOPE)
endfunction()

function(_aros_join_system_include_flags input_dirs out_var)
  set(_flags "-nostdinc")
  foreach(_include_dir IN LISTS input_dirs)
    if(_include_dir STREQUAL "")
      continue()
    endif()
    string(APPEND _flags " -isystem ${_include_dir}")
  endforeach()
  set(${out_var} "${_flags}" PARENT_SCOPE)
endfunction()

function(_aros_find_toolchain_program_path toolchain_dir toolchain_prefix tool_name out_var)
  foreach(_candidate IN ITEMS
      "${toolchain_dir}/bin/${toolchain_prefix}-${tool_name}"
      "${toolchain_dir}/${toolchain_prefix}-${tool_name}")
    if(EXISTS "${_candidate}")
      set(${out_var} "${_candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()

  set(${out_var} "${toolchain_dir}/${toolchain_prefix}-${tool_name}" PARENT_SCOPE)
endfunction()

function(_aros_compute_bootstrap_isa_flags target_cpu out_isa_flags out_isa_32_flags)
  set(_isa_flags "")
  set(_isa_32_flags "")

  if(target_cpu STREQUAL "x86_64")
    set(_isa_flags "-m64 -mcmodel=large $(CFLAGS_NO_RED_ZONE) $(CFLAGS_NO_MS_BITFIELDS)")
    set(_isa_32_flags "$(strip $(ISA_X86_FLAGS))")
  elseif(target_cpu STREQUAL "i386")
    set(_isa_flags "-m32 -march=i486 $(CFLAGS_NO_MS_BITFIELDS)")
    set(_isa_32_flags "$(strip $(ISA_X86_FLAGS))")
  endif()

  set(${out_isa_flags} "${_isa_flags}" PARENT_SCOPE)
  set(${out_isa_32_flags} "${_isa_32_flags}" PARENT_SCOPE)
endfunction()

function(aros_write_bootstrap_config_snapshot)
  set(_options)
  set(_one_value_args
    BUILD_DIR
    TARGET
    TOOLCHAIN_DIR
    HOST_ARCH
    HOST_CPU
    BUILD_TYPE_DEFINE
  )
  cmake_parse_arguments(AROS_BOOTSTRAP "${_options}" "${_one_value_args}" "" ${ARGN})

  if(NOT AROS_BOOTSTRAP_BUILD_DIR
     OR NOT AROS_BOOTSTRAP_TARGET
     OR NOT AROS_BOOTSTRAP_TOOLCHAIN_DIR
     OR NOT AROS_BOOTSTRAP_HOST_ARCH
     OR NOT AROS_BOOTSTRAP_HOST_CPU)
    message(FATAL_ERROR "aros_write_bootstrap_config_snapshot requires BUILD_DIR, TARGET, TOOLCHAIN_DIR, HOST_ARCH, and HOST_CPU")
  endif()

  if(NOT AROS_BOOTSTRAP_BUILD_TYPE_DEFINE)
    set(AROS_BOOTSTRAP_BUILD_TYPE_DEFINE "-DAROS_BUILD_TYPE=AROS_BUILD_TYPE_PERSONAL")
  endif()

  aros_determine_target_context(
    "${AROS_BOOTSTRAP_TARGET}"
    _target_arch
    _target_cpu
    _target_variant
    _target_family
  )

  set(_target_suffix "")
  if(NOT _target_variant STREQUAL "")
    set(_target_suffix "-${_target_variant}")
  endif()

  set(_target_cpu32 "")
  if(_target_cpu STREQUAL "x86_64")
    set(_target_cpu32 "i386")
  endif()

  set(_target_cpu_mode "")
  set(_module_isa_cflags "")
  if(_target_cpu STREQUAL "x86_64")
    set(_module_isa_cflags "-ffixed-r12")
  endif()
  _aros_compute_bootstrap_isa_flags("${_target_cpu}" _target_isa_flags _target_isa_32_flags)

  _aros_join_system_include_flags("${CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES}" _kernel_includes)

  set(_toolchain_prefix "${_target_cpu}-aros")
  _aros_find_toolchain_program_path("${AROS_BOOTSTRAP_TOOLCHAIN_DIR}" "${_toolchain_prefix}" "ar" _target_ar_plain)
  _aros_find_toolchain_program_path("${AROS_BOOTSTRAP_TOOLCHAIN_DIR}" "${_toolchain_prefix}" "ranlib" _target_ranlib)

  set(_config_dir "${AROS_BOOTSTRAP_BUILD_DIR}/config")
  set(_target_root "${AROS_BOOTSTRAP_BUILD_DIR}/bin/${AROS_BOOTSTRAP_TARGET}")
  set(_target_gen_dir "${_target_root}/gen")
  set(_target_config_dir "${_target_gen_dir}/config")
  file(MAKE_DIRECTORY "${_config_dir}" "${_target_config_dir}")

  set(_make_cfg_lines
    "# Generated by CMake bootstrap config snapshot."
    "TOP                            := ${AROS_BOOTSTRAP_BUILD_DIR}"
    "AROS_HOST_ARCH                 := ${AROS_BOOTSTRAP_HOST_ARCH}"
    "AROS_HOST_CPU                  := ${AROS_BOOTSTRAP_HOST_CPU}"
    "AROS_TARGET_ARCH               := ${_target_arch}"
    "AROS_TARGET_CPU                := ${_target_cpu}"
    "AROS_TARGET_CPU32              := ${_target_cpu32}"
    "AROS_TARGET_CPU_MODE           := ${_target_cpu_mode}"
    "AROS_TARGET_VARIANT            := ${_target_variant}"
    "AROS_TARGET_SUFFIX             := ${_target_suffix}"
    "HOSTDIR                        := $(TOP)/bin/$(AROS_HOST_ARCH)-$(AROS_HOST_CPU)"
    "TOOLDIR                        := $(HOSTDIR)/tools"
    "HOSTGENDIR                     := $(HOSTDIR)/gen/host"
    "TARGETDIR                      := $(TOP)/bin/$(AROS_TARGET_ARCH)-$(AROS_TARGET_CPU)$(AROS_TARGET_SUFFIX)"
    "GENDIR                         := $(TARGETDIR)/gen"
    "CROSSTOOLSDIR                  := ${AROS_BOOTSTRAP_TOOLCHAIN_DIR}"
    "AROS_DIR_AROS                  := AROS"
    "AROS_DIR_ARCH                  := ${_target_arch}${_target_suffix}"
    "AROS_DIR_BOOT                  := boot"
    "AROS_DIR_BOOTARCH              := $(AROS_DIR_BOOT)/$(AROS_DIR_ARCH)"
    "AROS_DIR_C                     := C"
    "AROS_DIR_CLASSES               := Classes"
    "AROS_DIR_CATALOGS              := Catalogs"
    "AROS_DIR_COMMODITIES           := Commodities"
    "AROS_DIR_DATATYPES             := $(AROS_DIR_CLASSES)/Datatypes"
    "AROS_DIR_GADGETS               := $(AROS_DIR_CLASSES)/Gadgets"
    "AROS_DIR_DEVS                  := Devs"
    "AROS_DIR_DRIVERS               := Drivers"
    "AROS_DIR_ENVARC                := Env-Archive"
    "AROS_DIR_EXPANSION             := Expansion"
    "AROS_DIR_FS                    := L"
    "AROS_DIR_HELP                  := Help"
    "AROS_DIR_LIBRARIES             := Libs"
    "AROS_DIR_LOCALE                := Locale"
    "AROS_DIR_PACKAGES              := Packages"
    "AROS_DIR_PREFS                 := Prefs"
    "AROS_DIR_PRESETS               := Presets"
    "AROS_DIR_PRINTERS              := Printers"
    "AROS_DIR_S                     := S"
    "AROS_DIR_STORAGE               := Storage"
    "AROS_DIR_SYSTEM                := System"
    "AROS_DIR_THEMES                := Themes"
    "AROS_DIR_TOOLS                 := Tools"
    "AROS_DIR_UTILITIES             := Utilities"
    "AROS_DIR_WALLPAPERS            := Wallpapers"
    "AROS_DIR_DEVELOPER             := Development"
    "AROS_DIR_BIN                   := bin"
    "AROS_DIR_SDK                   := SDK"
    "AROS_DIR_FD                    := fd"
    "AROS_DIR_INCLUDE               := include"
    "AROS_DIR_LIB                   := lib"
    "AROS_DIR_CONTRIB               := Extras"
    "AROSDIR                        := $(TARGETDIR)/$(AROS_DIR_AROS)"
    "AROSARCHDIR                    := $(AROSDIR)/$(AROS_DIR_BOOTARCH)"
    "AROS_BOOT                      := $(AROSDIR)/$(AROS_DIR_BOOT)"
    "AROS_C                         := $(AROSDIR)/$(AROS_DIR_C)"
    "AROS_CLASSES                   := $(AROSDIR)/$(AROS_DIR_CLASSES)"
    "AROS_CLASSES_ARCH              := $(AROSARCHDIR)/$(AROS_DIR_CLASSES)"
    "AROS_DATATYPES                 := $(AROSDIR)/$(AROS_DIR_DATATYPES)"
    "AROS_GADGETS                   := $(AROSDIR)/$(AROS_DIR_GADGETS)"
    "AROS_DEVS                      := $(AROSDIR)/$(AROS_DIR_DEVS)"
    "AROS_DEVS_ARCH                 := $(AROSARCHDIR)/$(AROS_DIR_DEVS)"
    "AROS_EXPANSION                 := $(AROSDIR)/$(AROS_DIR_EXPANSION)"
    "AROS_FS                        := $(AROSDIR)/$(AROS_DIR_FS)"
    "AROS_FS_ARCH                   := $(AROSARCHDIR)/$(AROS_DIR_FS)"
    "AROS_RESOURCES                 := $(AROS_DEVS)"
    "AROS_DRIVERS                   := $(AROS_DEVS)/$(AROS_DIR_DRIVERS)"
    "AROS_LIBRARIES                 := $(AROSDIR)/$(AROS_DIR_LIBRARIES)"
    "AROS_LIBRARIES_ARCH            := $(AROSARCHDIR)/$(AROS_DIR_LIBRARIES)"
    "AROS_LOCALE                    := $(AROSDIR)/$(AROS_DIR_LOCALE)"
    "AROS_CATALOGS                  := $(AROS_LOCALE)/$(AROS_DIR_CATALOGS)"
    "AROS_HELP                      := $(AROS_LOCALE)/$(AROS_DIR_HELP)"
    "AROS_PREFS                     := $(AROSDIR)/$(AROS_DIR_PREFS)"
    "AROS_ENVARC                    := $(AROS_PREFS)/$(AROS_DIR_ENVARC)"
    "AROS_PACKAGES                  := $(AROS_ENVARC)/SYS/$(AROS_DIR_PACKAGES)"
    "AROS_PRESETS                   := $(AROS_PREFS)/$(AROS_DIR_PRESETS)"
    "AROS_PRINTERS                  := $(AROS_DEVS)/$(AROS_DIR_PRINTERS)"
    "AROS_S                         := $(AROSDIR)/$(AROS_DIR_S)"
    "AROS_STORAGE                   := $(AROSDIR)/$(AROS_DIR_STORAGE)"
    "AROS_SYSTEM                    := $(AROSDIR)/$(AROS_DIR_SYSTEM)"
    "AROS_WALLPAPERS                := $(AROS_PRESETS)/$(AROS_DIR_WALLPAPERS)"
    "AROS_THEMES                    := $(AROS_PRESETS)/$(AROS_DIR_THEMES)"
    "AROS_IMAGES                    := $(AROS_SYSTEM)/Images"
    "AROS_TOOLS                     := $(AROSDIR)/$(AROS_DIR_TOOLS)"
    "AROS_UTILITIES                 := $(AROSDIR)/$(AROS_DIR_UTILITIES)"
    "AROS_WANDERER                  := $(AROS_SYSTEM)/Wanderer"
    "AROS_CONTRIB                   := $(AROSDIR)/$(AROS_DIR_CONTRIB)"
    "AROS_DEVELOPER                 := $(AROSDIR)/$(AROS_DIR_DEVELOPER)"
    "AROS_ARCH_DEVELOPMENT          := $(AROS_DEVELOPER)/$(AROS_TARGET_CPU)-$(AROS_TARGET_ARCH)$(AROS_TARGET_SUFFIX)-aros"
    "AROS_DEV_ARCH_BINS             := $(AROS_DEVELOPER)/$(AROS_TARGET_CPU)-aros/$(AROS_DIR_BIN)"
    "AROS_DEV_BINS                  := $(AROS_DEVELOPER)/$(AROS_DIR_BIN)"
    "AROS_DEBUG                     := $(AROS_DEVELOPER)/Debug"
    "AROS_FD                        := $(AROS_DEVELOPER)/$(AROS_DIR_FD)"
    "AROS_TESTS                     := $(AROS_DEBUG)/Tests"
    "AROS_ARCH_INCLUDES             := $(AROS_ARCH_DEVELOPMENT)/$(AROS_DIR_INCLUDE)"
    "AROS_INCLUDES                  := $(AROS_DEVELOPER)/$(AROS_DIR_INCLUDE)"
    "AROS_ARCH_LIB                  := $(AROS_ARCH_DEVELOPMENT)/$(AROS_DIR_LIB)"
    "AROS_LIB                       := $(AROS_DEVELOPER)/$(AROS_DIR_LIB)"
    "AROS_BUILD_SDKS                := $(GENDIR)/buildsdks"
    "AROS_PRIVATE_DEVELOPMENT       := $(AROS_BUILD_SDKS)/private"
    "AROS_PRIVATE_INCLUDES          := $(AROS_PRIVATE_DEVELOPMENT)/$(AROS_DIR_INCLUDE)"
    "AROS_PRIVATE_LIB               := $(AROS_PRIVATE_DEVELOPMENT)/$(AROS_DIR_LIB)"
    "AROS_REL_LIB                   := $(AROS_BUILD_SDKS)/rel/$(AROS_DIR_LIB)"
    "AROS_CONFIG_INCLUDES           := $(AROS_BUILD_SDKS)/config/$(AROS_DIR_INCLUDE)"
    "GENINCDIR                      := $(GENDIR)/include"
    "RESIDENT_BEGIN                 := compiler/libinit/libentry"
    "KICKSTART_BEGIN                := compiler/libinit/kickentry"
  )
  string(JOIN "\n" _make_cfg_text ${_make_cfg_lines})
  file(WRITE "${_config_dir}/make.cfg" "${_make_cfg_text}\n")

  set(_target_cfg_lines
    "# Generated by CMake bootstrap config snapshot."
    "FAMILY                        := ${_target_family}"
    "KERNEL_ISA_FLAGS              = "
    "KERNEL_ISA_CFLAGS             = $(KERNEL_ISA_FLAGS)"
    "KERNEL_ISA_CXXFLAGS           = $(KERNEL_ISA_FLAGS)"
    "KERNEL_ISA_OBJCFLAGS          = $(KERNEL_ISA_FLAGS)"
    "KERNEL_ISA_AFLAGS             = $(KERNEL_ISA_FLAGS)"
    "KERNEL_ISA_LDFLAGS            = $(KERNEL_ISA_FLAGS)"
    "KERNEL_INCLUDES               := ${_kernel_includes}"
    "CONFIG_CPPFLAGS               = $(strip ${AROS_BOOTSTRAP_BUILD_TYPE_DEFINE})"
    "CONFIG_AFLAGS                 = $(strip )"
    "OPTIMIZATION_CFLAGS           = $(strip -O2)"
    "ISA_X86_FLAGS                 = -m32 -march=i486 $(CFLAGS_NO_MS_BITFIELDS)"
    "ISA_X8664_FLAGS               = -m64 -mcmodel=large $(CFLAGS_NO_RED_ZONE) $(CFLAGS_NO_MS_BITFIELDS)"
    "ISA_FLAGS                     = $(strip ${_target_isa_flags})"
    "ISA_32_FLAGS                  = ${_target_isa_32_flags}"
    "TARGET_ISA_CFLAGS             = $(ISA_FLAGS)"
    "TARGET_ISA_CXXFLAGS           = $(ISA_FLAGS)"
    "TARGET_ISA_OBJCFLAGS          = $(TARGET_ISA_CFLAGS)"
    "TARGET_ISA_AFLAGS             = $(ISA_FLAGS)"
    "TARGET_ISA_LDFLAGS            = $(ISA_FLAGS)"
    "TARGET_ISA_32_CFLAGS          = $(ISA_32_FLAGS)"
    "TARGET_ISA_32_CXXFLAGS        = $(ISA_32_FLAGS)"
    "TARGET_ISA_32_OBJCFLAGS       = $(TARGET_ISA_32_CFLAGS)"
    "TARGET_ISA_32_AFLAGS          = $(ISA_32_FLAGS)"
    "TARGET_ISA_32_LDFLAGS         = $(ISA_32_FLAGS)"
    "SAFETY_CFLAGS                := $(strip )"
    "TARGET_CPPFLAGS               = $(strip $(USER_INCLUDES) $(CONFIG_CPPFLAGS) $(USER_CPPFLAGS))"
    "TARGET_C_LIBS                 = $(strip )"
    "MODULE_ISA_CFLAGS             := $(strip ${_module_isa_cflags})"
    "NOSTARTUP_LDFLAGS             := $(strip -nostartfiles)"
    "NOSTDLIB_LDFLAGS              := $(strip -nostdlib)"
    "NOSTARTUP_OBJECTS             = $(strip )"
    "AR_PLAIN                      = $(strip ${_target_ar_plain})"
    "RANLIB                        = $(strip ${_target_ranlib})"
    "AROS_TARGET_PLATFORM          := ${AROS_BOOTSTRAP_TARGET}"
    "ARCH                          := $(AROS_TARGET_ARCH)"
    "CPU                           := $(AROS_TARGET_CPU)"
    "CPU_MODE                      := $(AROS_TARGET_CPU_MODE)"
  )
  string(JOIN "\n" _target_cfg_text ${_target_cfg_lines})
  file(WRITE "${_target_config_dir}/target.cfg" "${_target_cfg_text}\n")

  file(WRITE "${_target_config_dir}/build.cfg" "# Generated by CMake bootstrap config snapshot.\n")
  set(_compiler_cfg_lines
    "# Generated by CMake bootstrap config snapshot."
    "CFLAGS_C89                              := -std=c89"
    "CFLAGS_GNU89                            := -std=gnu89"
    "CFLAGS_C99                              := -std=c99"
    "CFLAGS_GNU99                            := -std=gnu99"
    "CFLAGS_C11                              := -std=c11"
    "CFLAGS_GNU11                            := -std=gnu11"
    "CFLAGS_C17                              := -std=c17"
    "CFLAGS_GNU17                            := -std=gnu17"
    "CXXFLAGS_CXX98                          := -std=c++98"
    "CXXFLAGS_GNU98                          := -std=gnu++98"
    "CXXFLAGS_CXX03                          := -std=c++03"
    "CXXFLAGS_GNU03                          := -std=gnu++03"
    "CXXFLAGS_CXX11                          := -std=c++11"
    "CXXFLAGS_GNU11                          := -std=gnu++11"
    "CXXFLAGS_CXX14                          := -std=c++14"
    "CXXFLAGS_GNU14                          := -std=gnu++14"
    "CXXFLAGS_CXX17                          := -std=c++17"
    "CXXFLAGS_GNU17                          := -std=gnu++17"
    "CXXFLAGS_CXX20                          := -std=c++20"
    "CXXFLAGS_GNU20                          := -std=gnu++20"
    "CXXFLAGS_CXX23                          :="
    "CXXFLAGS_GNU23                          :="
    "CXXFLAGS_NOSTDLIBXX                     :="
    "CFLAGS_EXCEPTIONS                       := -fexceptions"
    "CFLAGS_NO_EXCEPTIONS                    := -fno-exceptions"
    "CFLAGS_FAST_MATH                        := -ffast-math"
    "CFLAGS_ASSOCIATIVE_MATH                 := -fassociative-math"
    "CFLAGS_NO_MATH_ERRNO                    := -fno-math-errno"
    "CFLAGS_NO_TRAPPING_MATH                 := -fno-trapping-math"
    "CFLAGS_FLOAT_STORE                      := -ffloat-store"
    "CFLAGS_NO_FLOAT_STORE                   := -fno-float-store"
    "CFLAGS_TREE_VECTORIZE                   := -ftree-vectorize"
    "CFLAGS_LTO                              := -flto"
    "CFLAGS_NO_LTO                           := -fno-lto"
    "CFLAGS_WHOLE_PROGRAM                    := -fwhole-program"
    "CFLAGS_LOOP_BLOCK                       := -floop-block"
    "CFLAGS_LOOP_INTERCHANGE                 := -floop-interchange"
    "CFLAGS_LOOP_STRIP_MINE                  := -floop-strip-mine"
    "CFLAGS_PEEL_LOOPS                       := -fpeel-loops"
    "CFLAGS_UNROLL_LOOPS                     := -funroll-loops"
    "CFLAGS_STRICT_ALIASING                  := -fstrict-aliasing"
    "CFLAGS_NO_STRICT_ALIASING               := -fno-strict-aliasing"
    "CFLAGS_INLINE_SMALL_FUNCTIONS           := -finline-small-functions"
    "CFLAGS_NO_INLINE_SMALL_FUNCTIONS        := -fno-inline-small-functions"
    "CFLAGS_IPA_CP                           := -fipa-cp"
    "CFLAGS_NO_IPA_CP                        := -fno-ipa-cp"
    "CFLAGS_OMIT_FP                          := -fomit-frame-pointer"
    "CFLAGS_NO_OMIT_FP                       := -fno-omit-frame-pointer"
    "CFLAGS_ALIGNED_NEW                      := -faligned-new"
    "CFLAGS_NO_ALIGNED_NEW                   := -fno-aligned-new"
    "CFLAGS_COMMON                           := -fcommon"
    "CFLAGS_NO_COMMON                        := -fno-common"
    "CFLAGS_NO_DELETE_NULL_POINTER_CHECKS    := -fno-delete-null-pointer-checks"
    "CFLAGS_PROFILE_ARCS                     := -fprofile-arcs"
    "CFLAGS_NO_PROFILE_ARCS                  := -fno-profile-arcs"
    "CFLAGS_TEST_COVERAGE                    := -ftest-coverage"
    "CFLAGS_NO_TEST_COVERAGE                 := -fno-test-coverage"
    "CFLAGS_INSTR_FUNCTIONS                  := -finstrument-functions"
    "CFLAGS_NO_INSTR_FUNCTIONS               := -fno-instrument-functions"
    "CFLAGS_BUILTIN                          := -fbuiltin"
    "CFLAGS_NO_BUILTIN                       := -fno-builtin"
    "CFLAGS_NO_BUILTIN_FLOOR                 := -fno-builtin-floor"
    "CFLAGS_NO_BUILTIN_VSNPRINTF             := -fno-builtin-vsnprintf"
    "CFLAGS_NO_BUILTIN_FFS                   := -fno-builtin-ffs"
    "CFLAGS_NO_BUILTIN_FFSLL                 := -fno-builtin-ffsll"
    "CFLAGS_NO_BUILTIN_BSWAP32               := -fno-builtin-bswap32"
    "CFLAGS_NO_BUILTIN_BSWAP64               := -fno-builtin-bswap64"
    "CFLAGS_NO_BUILTIN_CLZ                   := -fno-builtin-clz"
    "CFLAGS_NO_BUILTIN_CLZLL                 := -fno-builtin-clzll"
    "CFLAGS_NO_BUILTIN_CTZ                   := -fno-builtin-ctz"
    "CFLAGS_NO_BUILTIN_EXPECT                := -fno-builtin-expect"
    "CFLAGS_NO_BUILTIN_POPCOUNT              := -fno-builtin-popcount"
    "CFLAGS_NO_BUILTIN_POPCOUNTLL            := -fno-builtin-popcountll"
    "CFLAGS_NO_BUILTIN_UNREACHABLE           := -fno-builtin-unreachable"
    "CFLAGS_FREESTANDING                     := -ffreestanding"
    "CFLAGS_NO_FREESTANDING                  := -fno-freestanding"
    "CFLAGS_UNWIND_TABLES                    := -funwind-tables"
    "CFLAGS_NO_UNWIND_TABLES                 := -fno-unwind-tables"
    "CFLAGS_ASYNCHRONOUS_UNWIND_TABLES       := -fasynchronous-unwind-tables"
    "CFLAGS_NO_ASYNCHRONOUS_UNWIND_TABLES    := -fno-asynchronous-unwind-tables"
    "CFLAGS_FUNCTION_SECTIONS                := -ffunction-sections"
    "CFLAGS_DATA_SECTIONS                    := -fdata-sections"
    "CFLAGS_MERGE_CONSTANTS                  := -fmerge-constants"
    "CFLAGS_NO_MERGE_CONSTANTS               := -fno-merge-constants"
    "CFLAGS_MERGE_ALL_CONSTANTS              := -fmerge-all-constants"
    "CFLAGS_NO_MERGE_ALL_CONSTANTS           := -fno-merge-all-constants"
    "CFLAGS_VISIBILITY_HIDDEN                := -fvisibility=hidden"
    "CFLAGS_FILE_PREFIX_MAP                  := -ffile-prefix-map"
    "CFLAGS_PERMISSIVE                       := -fpermissive"
    "CFLAGS_NO_PERMISSIVE                    := -fno-permissive"
    "CFLAGS_RTTI                             := -frtti"
    "CFLAGS_NO_RTTI                          := -fno-rtti"
    "CFLAGS_ISYSTEM                          := -isystem"
    "CFLAGS_ISYSTEM_END                      :="
    "CFLAGS_IQUOTE                           := -iquote"
    "CFLAGS_IQUOTE_END                       :="
    "CFLAGS_RED_ZONE                         := -mred-zone"
    "CFLAGS_NO_RED_ZONE                      := -mno-red-zone"
    "CFLAGS_GENERAL_REGS_ONLY                := -mgeneral-regs-only"
    "CFLAGS_MS_BITFIELDS                     := -mms-bitfields"
    "CFLAGS_NO_MS_BITFIELDS                  := -mno-ms-bitfields"
    "CFLAGS_NO_INTEGRATED_AS                 :="
    "WARN_ERROR                              := -Werror"
    "WARN_ALL                                := -Wall"
    "WARN_RESTRICT                           := -Wrestrict"
    "WARN_UNUSED_COMMAND_LINE_ARGUMENT       :="
    "WARN_UNKNOWN_WARNING_OPTION             :="
    "WARN_UNUSED_BUT_SET_VARIABLE            := -Wunused-but-set-variable"
    "WARN_STRICT_ALIASING                    := -Wstrict-aliasing"
    "WARN_ARRAY_BOUNDS                       := -Warray-bounds"
    "WARN_ENUM_COMPARE                       := -Wenum-compare"
    "WARN_BOOL_COMPARE                       := -Wbool-compare"
    "WARN_SIGN_COMPARE                       := -Wsign-compare"
    "WARN_NONNULL_COMPARE                    := -Wnonnull-compare"
    "WARN_OVERFLOW                           := -Woverflow"
    "WARN_STRICT_OVERFLOW                    := -Wstrict-overflow"
    "WARN_FORMAT_SECURITY                    := -Wformat-security"
    "WARN_MISLEADING_INDENTATION             := -Wmisleading-indentation"
    "WARN_UNUSED                             := -Wunused"
    "WARN_UNUSED_LABEL                       := -Wunused-label"
    "WARN_UNUSED_VALUE                       := -Wunused-value"
    "WARN_UNUSED_VARIABLE                    := -Wunused-variable"
    "WARN_UNUSED_FUNCTION                    := -Wunused-function"
    "WARN_UNUSED_PARAMETER                   := -Wunused-parameter"
    "WARN_IMPLICIT_FUNCTION_DECL             := -Wimplicit-function-declaration"
    "WARN_UNINITIALIZED                      := -Wuninitialized"
    "WARN_MAYBE_UNINITIALIZED                := -Wmaybe-uninitialized"
    "WARN_FORMAT                             := -Wformat"
    "WARN_PARENTHESES                        := -Wparentheses"
    "WARN_CHAR_SUBSCRIPTS                    := -Wchar-subscripts"
    "WARN_ENDIF_LABELS                       := -Wendif-labels"
    "WARN_FORMAT_CONTAINS_NUL                := -Wformat-contains-nul"
    "WARN_IMPLICIT_INT                       := -Wimplicit-int"
    "WARN_AGGRESSIVE_LOOP_OPT                := -Waggressive-loop-optimizations"
    "WARN_CPP                                := -Wcpp"
    "WARN_SWITCH                             := -Wswitch"
    "WARN_DISCARDED_QUALIFIERS               := -Wdiscarded-qualifiers"
    "WARN_SEQUENCE_POINT                     := -Wsequence-point"
    "WARN_UNKNOWN_PRAGMAS                    := -Wunknown-pragmas"
    "WARN_DISCARDED_ARRAY_QUAL               := -Wdiscarded-array-qualifiers"
    "WARN_INT_CONVERSION                     := -Wint-conversion"
    "WARN_INT_TO_POINTER_CAST                := -Wint-to-pointer-cast"
    "WARN_POINTER_TO_INT_CAST                := -Wpointer-to-int-cast"
    "WARN_UNUSED_CONST_VARIABLE              := -Wunused-const-variable"
    "WARN_WRITE_STRINGS                      := -Wwrite-strings"
    "WARN_COMMENT                            := -Wcomment"
    "WARN_INCOMPAT_POINTER_TYPES             := -Wincompatible-pointer-types"
    "WARN_LOGICAL_NOT_PARENTHESES            := -Wlogical-not-parentheses"
    "WARN_STRICT_PROTOTYPES                  := -Wstrict-prototypes"
    "WARN_POINTER_SIGN                       := -Wpointer-sign"
    "WARN_SHIFT_OVERFLOW                     := -Wshift-overflow"
    "WARN_FRAME_ADDRESS                      := -Wframe-address"
    "WARN_DEPRECATED_DECLARATIONS            := -Wdeprecated-declarations"
    "WARN_ATTRIBUTES                         := -Wattributes"
    "WARN_UNUSED_LOCAL_TYPEDEFS              := -Wunused-local-typedefs"
    "WARN_MISSING_BRACES                     := -Wmissing-braces"
    "WARN_CONVERSION_NULL                    := -Wconversion-null"
    "WARN_NARROWING                          := -Wnarrowing"
    "WARN_VOLATILE_REGISTER_VAR              := -Wvolatile-register-var"
    "WARN_SIZEOF_POINTER_MEMACCESS           := -Wsizeof-pointer-memaccess"
    "WARN_RETURN_TYPE                        := -Wreturn-type"
    "WARN_FORMAT_ZERO_LENGTH                 := -Wformat-zero-length"
    "WARN_LTO_TYPE_MISMATCH                  := -Wlto-type-mismatch"
    "WARN_TAUTOLOGICAL_COMPARE               := -Wtautological-compare"
    "WARN_EMPTY_BODY                         := -Wempty-body"
    "WARN_FORMAT_OVERFLOW                    := -Wformat-overflow"
    "WARN_STRINGOP_OVERFLOW                  := -Wstringop-overflow"
    "WARN_FORMAT_TRUNCATION                  := -Wformat-truncation"
    "WARN_STRINGOP_TRUNCATION                := -Wstringop-truncation"
    "WARN_SHIFT_NEGATIVE_VALUE               := -Wshift-negative-value"
    "WARN_MISSING_FIELD_INITIALIZERS         := -Wmissing-field-initializers"
    "WARN_IMPLICIT_FALLTHROUGH               := -Wimplicit-fallthrough"
    "WARN_MISSING_PROTOTYPES                 := -Wmissing-prototypes"
    "WARN_CLASS_MEMACCESS                    := -Wclass-memaccess"
    "WARN_INT_IN_BOOL_CONTEXT                := -Wint-in-bool-context"
    "WARN_IGNORED_OPTIMIZATION_ARGUMENT      :="
    "WARN_BUILTIN_DECLARATION_MISMATCH       := -Wbuiltin-declaration-mismatch"
    "WARN_OLD_STYLE_DEFINITION               := -Wold-style-definition"
    "NOWARN_ERROR                            := -Wno-error"
    "NOWARN_RESTRICT                         := -Wno-restrict"
    "NOWARN_UNUSED_COMMAND_LINE_ARGUMENT     :="
    "NOWARN_UNKNOWN_WARNING_OPTION           :="
    "NOWARN_UNUSED_BUT_SET_VARIABLE          := -Wno-unused-but-set-variable"
    "NOWARN_STRICT_ALIASING                  := -Wno-strict-aliasing"
    "NOWARN_ARRAY_BOUNDS                     := -Wno-array-bounds"
    "NOWARN_ENUM_COMPARE                     := -Wno-enum-compare"
    "NOWARN_BOOL_COMPARE                     := -Wno-bool-compare"
    "NOWARN_SIGN_COMPARE                     := -Wno-sign-compare"
    "NOWARN_NONNULL_COMPARE                  := -Wno-nonnull-compare"
    "NOWARN_OVERFLOW                         := -Wno-overflow"
    "NOWARN_STRICT_OVERFLOW                  := -Wno-strict-overflow"
    "NOWARN_FORMAT_SECURITY                  := -Wno-format-security"
    "NOWARN_MISLEADING_INDENTATION           := -Wno-misleading-indentation"
    "NOWARN_UNUSED                           := -Wno-unused"
    "NOWARN_UNUSED_LABEL                     := -Wno-unused-label"
    "NOWARN_UNUSED_VALUE                     := -Wno-unused-value"
    "NOWARN_UNUSED_VARIABLE                  := -Wno-unused-variable"
    "NOWARN_UNUSED_FUNCTION                  := -Wno-unused-function"
    "NOWARN_UNUSED_PARAMETER                 := -Wno-unused-parameter"
    "NOWARN_IMPLICIT_FUNCTION_DECL           := -Wno-implicit-function-declaration"
    "NOWARN_UNINITIALIZED                    := -Wno-uninitialized"
    "NOWARN_MAYBE_UNINITIALIZED              := -Wno-maybe-uninitialized"
    "NOWARN_FORMAT                           := -Wno-format"
    "NOWARN_PARENTHESES                      := -Wno-parentheses"
    "NOWARN_CHAR_SUBSCRIPTS                  := -Wno-char-subscripts"
    "NOWARN_ENDIF_LABELS                     := -Wno-endif-labels"
    "NOWARN_FORMAT_CONTAINS_NUL              := -Wno-format-contains-nul"
    "NOWARN_IMPLICIT_INT                     := -Wno-implicit-int"
    "NOWARN_AGGRESSIVE_LOOP_OPT              := -Wno-aggressive-loop-optimizations"
    "NOWARN_CPP                              := -Wno-cpp"
    "NOWARN_SWITCH                           := -Wno-switch"
    "NOWARN_DISCARDED_QUALIFIERS             := -Wno-discarded-qualifiers"
    "NOWARN_SEQUENCE_POINT                   := -Wno-sequence-point"
    "NOWARN_UNKNOWN_PRAGMAS                  := -Wno-unknown-pragmas"
    "NOWARN_DISCARDED_ARRAY_QUAL             := -Wno-discarded-array-qualifiers"
    "NOWARN_INT_CONVERSION                   := -Wno-int-conversion"
    "NOWARN_INT_TO_POINTER_CAST              := -Wno-int-to-pointer-cast"
    "NOWARN_POINTER_TO_INT_CAST              := -Wno-pointer-to-int-cast"
    "NOWARN_UNUSED_CONST_VARIABLE            := -Wno-unused-const-variable"
    "NOWARN_WRITE_STRINGS                    := -Wno-write-strings"
    "NOWARN_COMMENT                          := -Wno-comment"
    "NOWARN_INCOMPAT_POINTER_TYPES           := -Wno-incompatible-pointer-types"
    "NOWARN_LOGICAL_NOT_PARENTHESES          := -Wno-logical-not-parentheses"
    "NOWARN_STRICT_PROTOTYPES                := -Wno-strict-prototypes"
    "NOWARN_POINTER_SIGN                     := -Wno-pointer-sign"
    "NOWARN_SHIFT_OVERFLOW                   := -Wno-shift-overflow"
    "NOWARN_FRAME_ADDRESS                    := -Wno-frame-address"
    "NOWARN_DEPRECATED_DECLARATIONS          := -Wno-deprecated-declarations"
    "NOWARN_ATTRIBUTES                       := -Wno-attributes"
    "NOWARN_UNUSED_LOCAL_TYPEDEFS            := -Wno-unused-local-typedefs"
    "NOWARN_MISSING_BRACES                   := -Wno-missing-braces"
    "NOWARN_CONVERSION_NULL                  := -Wno-conversion-null"
    "NOWARN_NARROWING                        := -Wno-narrowing"
    "NOWARN_VOLATILE_REGISTER_VAR            := -Wno-volatile-register-var"
    "NOWARN_SIZEOF_POINTER_MEMACCESS         := -Wno-sizeof-pointer-memaccess"
    "NOWARN_RETURN_TYPE                      := -Wno-return-type"
    "NOWARN_FORMAT_ZERO_LENGTH               := -Wno-format-zero-length"
    "NOWARN_LTO_TYPE_MISMATCH                := -Wno-lto-type-mismatch"
    "NOWARN_TAUTOLOGICAL_COMPARE             := -Wno-tautological-compare"
    "NOWARN_EMPTY_BODY                       := -Wno-empty-body"
    "NOWARN_FORMAT_OVERFLOW                  := -Wno-format-overflow"
    "NOWARN_STRINGOP_OVERFLOW                := -Wno-stringop-overflow"
    "NOWARN_FORMAT_TRUNCATION                := -Wno-format-truncation"
    "NOWARN_STRINGOP_TRUNCATION              := -Wno-stringop-truncation"
    "NOWARN_SHIFT_NEGATIVE_VALUE             := -Wno-shift-negative-value"
    "NOWARN_MISSING_FIELD_INITIALIZERS       := -Wno-missing-field-initializers"
    "NOWARN_IMPLICIT_FALLTHROUGH             := -Wno-implicit-fallthrough"
    "NOWARN_MISSING_PROTOTYPES               := -Wno-missing-prototypes"
    "NOWARN_CLASS_MEMACCESS                  := -Wno-class-memaccess"
    "NOWARN_INT_IN_BOOL_CONTEXT              := -Wno-int-in-bool-context"
    "NOWARN_IGNORED_OPTIMIZATION_ARGUMENT    :="
    "NOWARN_BUILTIN_DECLARATION_MISMATCH     := -Wno-builtin-declaration-mismatch"
    "NOWARN_OLD_STYLE_DEFINITION             := -Wno-old-style-definition"
  )
  string(JOIN "\n" _compiler_cfg_text ${_compiler_cfg_lines})
  file(WRITE "${_target_config_dir}/compiler.cfg" "${_compiler_cfg_text}\n")
endfunction()
