include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeRules.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSIconTargets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSCatalogTargets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSProgramCodegen.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSStaticTargets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSProgramDiscovery.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSFetchTargets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSIncludeTargets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSTextTransforms.cmake")

function(_aros_program_driver_archives compiler output out_libs out_runtime out_specs out_objects)
  # Older GCC validates input existence even with -###. This placeholder is
  # never compiled or linked; using a fixed .o avoids random cc*.o probe names.
  file(CONFIGURE OUTPUT "${output}.o" CONTENT "" @ONLY)
  set(_args "--sysroot=${AROS_NATIVE_DEVELOPER_DIR}" ${MMAKE_PROGRAM_LINK_OPTIONS}
    "-B${AROS_NATIVE_PUBLIC_LIB_DIR}/" "${output}.o" -o "${output}" ${MMAKE_PROGRAM_LINK_FLAGS}
    "-L${AROS_NATIVE_PUBLIC_LIB_DIR}")
  foreach(_sdk IN LISTS MMAKE_PROGRAM_USESDKS)
    list(APPEND _args "-L${AROS_NATIVE_BUILD_SDKS_DIR}/${_sdk}/lib")
  endforeach()
  foreach(_lib IN LISTS MMAKE_PROGRAM_USELIBS)
    list(APPEND _args "-l${_lib}")
  endforeach()
  list(APPEND _args ${MMAKE_PROGRAM_ARCH_LIBS})
  # Let GCC expand conditional specs, without compiling or linking the probe.
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env LC_ALL=C "${compiler}" "-###" ${_args} RESULT_VARIABLE _result
    OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Cannot discover program compiler libraries: ${_stdout}${_stderr}")
  endif()
  string(REPLACE "\n" ";" _lines "${_stdout}${_stderr}")
  set(_link_commands 0)
  set(_libs)
  set(_specs)
  set(_objects)
  foreach(_line IN LISTS _lines)
    if(_line MATCHES "^Reading specs from (.+)$")
      list(APPEND _specs "${CMAKE_MATCH_1}")
    endif()
    if(NOT _line MATCHES "^[ \t]+")
      continue()
    endif()
    separate_arguments(_tokens UNIX_COMMAND "${_line}")
    list(FIND _tokens -o _index)
    if(_index LESS 0)
      continue()
    endif()
    math(EXPR _index "${_index} + 1")
    list(LENGTH _tokens _count)
    if(_index GREATER_EQUAL _count)
      continue()
    endif()
    list(GET _tokens ${_index} _destination)
    if(NOT _destination STREQUAL output)
      continue()
    endif()
    math(EXPR _link_commands "${_link_commands} + 1")
    set(_library_next FALSE)
    foreach(_token IN LISTS _tokens)
      if(_library_next)
        list(APPEND _libs "${_token}")
        set(_library_next FALSE)
      elseif(_token STREQUAL "-l")
        set(_library_next TRUE)
      elseif(_token MATCHES "^-l(.+)$")
        list(APPEND _libs "${CMAKE_MATCH_1}")
      elseif(_token MATCHES "^[^-].*[.]o$" AND NOT _token STREQUAL "${output}.o")
        get_filename_component(_name "${_token}" NAME)
        list(APPEND _objects "${AROS_NATIVE_PUBLIC_LIB_DIR}/${_name}")
      endif()
    endforeach()
  endforeach()
  if(NOT _link_commands EQUAL 1)
    message(FATAL_ERROR "Expected one compiler link command, found ${_link_commands}: ${_stdout}${_stderr}")
  endif()
  set(_runtime)
  if(gcc IN_LIST _libs)
    execute_process(COMMAND "${compiler}" ${_args} -print-libgcc-file-name
      OUTPUT_VARIABLE _runtime OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    if(NOT IS_ABSOLUTE "${_runtime}" OR NOT EXISTS "${_runtime}")
      message(FATAL_ERROR "Missing compiler runtime archive: ${_runtime}")
    endif()
    list(REMOVE_ITEM _libs gcc)
  endif()
  list(REMOVE_DUPLICATES _libs)
  set(${out_libs} "${_libs}" PARENT_SCOPE)
  set(${out_runtime} "${_runtime}" PARENT_SCOPE)
  set(${out_specs} "${_specs}" PARENT_SCOPE)
  set(${out_objects} "${_objects}" PARENT_SCOPE)
endfunction()

function(_aros_program_macro_identity kind args prefix)
  set(${prefix}_FIELDS "" PARENT_SCOPE)
  if(kind MATCHES "^build_progs?$")
    set(_arg_compiler "")
    _aros_mmake_macro_arguments("${args}" _arg)
    set(${prefix}_FIELDS MMAKE COMPILER PARENT_SCOPE)
    set(${prefix}_MMAKE "${_arg_mmake}" PARENT_SCOPE)
    set(${prefix}_COMPILER "${_arg_compiler}" PARENT_SCOPE)
  endif()
endfunction()

function(_aros_prerequisite_macro_identity kind args prefix)
  if(kind STREQUAL "copy_includes")
    set(_AROS_DISCOVER_ALL_LOCAL_INCLUDES TRUE)
    _aros_collect_copy_include_identity("${kind}" "${args}" _include)
    set(${prefix}_FIELDS MMAKE PARENT_SCOPE)
    set(${prefix}_MMAKE "${_include_mmake}" PARENT_SCOPE)
  else()
    _aros_program_macro_identity("${kind}" "${args}" _identity)
    set(${prefix}_FIELDS "${_identity_FIELDS}" PARENT_SCOPE)
    foreach(_field IN LISTS _identity_FIELDS)
      set(${prefix}_${_field} "${_identity_${_field}}" PARENT_SCOPE)
    endforeach()
  endif()
endfunction()

function(_aros_program_local_prerequisites node stack root out_var)
  set(${out_var}_STATIC_NODES "" PARENT_SCOPE)
  if(node STREQUAL "|")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()
  if(node IN_LIST stack)
    message(FATAL_ERROR "Program metadata dependency cycle: ${stack};${node}")
  endif()
  list(APPEND stack "${node}")
  if(NOT node STREQUAL root AND node IN_LIST _local_producers
      AND node MATCHES "^[A-Za-z0-9_.+-]+$")
    set(${out_var} "${node}" PARENT_SCOPE)
    return()
  endif()
  set(_external)
  set(_static_nodes)
  set(_local FALSE)
  # A recipe is a local build node, not a global mmake identity. Leave its
  # complete prerequisite closure to the strict static-data translator.
  foreach(_id IN LISTS _rules_RULES)
    if(node IN_LIST _rules_${_id}_TARGETS AND _rules_${_id}_RECIPE_COUNT GREATER 0)
      set(${out_var} "" PARENT_SCOPE)
      set(${out_var}_STATIC_NODES "${node}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  foreach(_id IN LISTS _rules_RULES)
    if(node IN_LIST _rules_${_id}_TARGETS)
      set(_local TRUE)
      foreach(_dependency IN LISTS _rules_${_id}_DEPENDS)
        _aros_program_local_prerequisites("${_dependency}" "${stack}" "${root}" _leaves)
        list(APPEND _external ${_leaves})
        list(APPEND _static_nodes ${_leaves_STATIC_NODES})
      endforeach()
    endif()
  endforeach()
  if(NOT _local AND NOT node STREQUAL root)
    if(IS_ABSOLUTE "${node}")
      # A supported copy pattern may own this path. Missing producers must
      # fail validation even when an old output already exists.
      list(APPEND _static_nodes "${node}")
    else()
      list(APPEND _external "${node}")
    endif()
  endif()
  list(REMOVE_DUPLICATES _external)
  list(REMOVE_DUPLICATES _static_nodes)
  set(${out_var} "${_external}" PARENT_SCOPE)
  set(${out_var}_STATIC_NODES "${_static_nodes}" PARENT_SCOPE)
endfunction()

function(_aros_program_prerequisites manifest mmake out_var)
  # Include declarations are concrete producers too, not aliases whose
  # prerequisite leaves can replace their own copy commands.
  set(_AROS_RULE_MACRO_COLLECTOR _aros_prerequisite_macro_identity)
  _aros_collect_mmake_rules("${manifest}" _rules)
  set(_local_producers)
  foreach(_id IN LISTS _rules_MACROS)
    list(APPEND _local_producers "${_rules_MACRO_${_id}_MMAKE}")
  endforeach()
  foreach(_id IN LISTS _rules_RULES)
    if(_rules_${_id}_EXPORTED)
      list(APPEND _local_producers ${_rules_${_id}_TARGETS})
    endif()
  endforeach()
  _aros_program_local_prerequisites("${mmake}" "" "${mmake}" _external)
  foreach(_node IN LISTS _external_STATIC_NODES)
    if(_AROS_INCLUDE_TRANSFORMS)
      _aros_mmake_is_text_transform("${manifest}" "${_node}" _transform)
      if(_transform)
        continue()
      endif()
    endif()
    aros_collect_mmake_static_files("${manifest}" "${_node}" _static STRICT LOCAL_NODE)
  endforeach()
  set(${out_var} "${_external}" PARENT_SCOPE)
  set(${out_var}_STATIC_NODES "${_external_STATIC_NODES}" PARENT_SCOPE)
  set(${out_var}_INCLUDES "${_rules_INCLUDES}" PARENT_SCOPE)
endfunction()

function(_aros_find_program_manifests mmake out_var)
  _aros_static_manifest_candidates("${mmake}" _matches)
  set(_active_matches)
  set(_AROS_RULE_MACRO_COLLECTOR _aros_program_macro_identity)
  if(ARGV2 STREQUAL "INCLUDING_LINKLIBS")
    set(_AROS_RULE_MACRO_COLLECTOR _aros_source_consumer_identity)
  endif()
  foreach(_manifest IN LISTS _matches)
    if(ARGV2 STREQUAL "INCLUDING_LINKLIBS")
      file(STRINGS "${_manifest}" _declarations REGEX "^[ \t]*%(build_progs?|build_linklib)([ \t]|$)")
    else()
      file(STRINGS "${_manifest}" _declarations REGEX "^[ \t]*%build_progs?([ \t]|$)")
    endif()
    if(NOT _declarations)
      continue()
    endif()
    _aros_collect_mmake_rules("${_manifest}" _rules)
    set(_count 0)
    foreach(_id IN LISTS _rules_MACROS)
      if(_rules_MACRO_${_id}_MMAKE STREQUAL mmake AND
         NOT _rules_MACRO_${_id}_COMPILER MATCHES "^(host|kernel)$")
        list(APPEND _active_matches "${_manifest}")
        math(EXPR _count "${_count} + 1")
      endif()
    endforeach()
    if(_count GREATER 1)
      message(FATAL_ERROR "Multiple active program rules for ${mmake} in ${_manifest} need separate rule snapshots")
    endif()
  endforeach()
  set(${out_var} "${_active_matches}" PARENT_SCOPE)
endfunction()

function(_aros_source_consumer_identity kind args prefix)
  if(kind STREQUAL "build_linklib")
    _aros_mmake_raw_arguments("${args}" _raw)
    _aros_mmake_macro_arguments("mmake=${_raw_mmake}" _identity)
    set(${prefix}_FIELDS MMAKE COMPILER PARENT_SCOPE)
    set(${prefix}_MMAKE "${_identity_mmake}" PARENT_SCOPE)
    set(${prefix}_COMPILER "target" PARENT_SCOPE)
  else()
    _aros_program_macro_identity("${kind}" "${args}" _identity)
    set(${prefix}_FIELDS "${_identity_FIELDS}" PARENT_SCOPE)
    foreach(_field IN LISTS _identity_FIELDS)
      set(${prefix}_${_field} "${_identity_${_field}}" PARENT_SCOPE)
    endforeach()
  endif()
endfunction()

# Keep exported metadata edges global even when the same manifest also names
# their local dependencies. Another manifest may augment any such identity.
function(_aros_program_metadata_prerequisites manifest node stack out_var)
  if(_AROS_RULE_OPTION_INCLUDES)
    _aros_metadata_option_context("${manifest}" "${node}" _AROS_RULE_OPTION_INCLUDES)
  endif()
  _aros_collect_mmake_rules("${manifest}" _rules)
  set(_local_producers)
  foreach(_id IN LISTS _rules_MACROS)
    list(APPEND _local_producers "${_rules_MACRO_${_id}_MMAKE}")
  endforeach()
  set(_dependencies)
  set(_static_nodes)
  set(_exported FALSE)
  set(_local_root FALSE)
  set(_local_rules)
  foreach(_id IN LISTS _rules_RULES)
    if(_rules_${_id}_EXPORTED)
      list(APPEND _local_producers ${_rules_${_id}_TARGETS})
    endif()
    if(_rules_${_id}_EXPORTED AND node IN_LIST _rules_${_id}_TARGETS)
      set(_exported TRUE)
    endif()
    if(_rules_${_id}_METADATA)
      if(node IN_LIST _rules_${_id}_TARGETS)
        list(APPEND _dependencies ${_rules_${_id}_DEPENDS})
      endif()
    else()
      list(APPEND _local_rules "${_id}")
      if(node IN_LIST _rules_${_id}_TARGETS)
        set(_local_root TRUE)
      endif()
    endif()
  endforeach()
  if(_exported AND _local_root)
    set(_rules_RULES "${_local_rules}")
    _aros_program_local_prerequisites("${node}" "${stack}" "${node}" _part)
    list(APPEND _dependencies ${_part})
    list(APPEND _static_nodes ${_part_STATIC_NODES})
  endif()
  list(REMOVE_DUPLICATES _dependencies)
  set(${out_var} "${_dependencies}" PARENT_SCOPE)
  set(${out_var}_STATIC_NODES "${_static_nodes}" PARENT_SCOPE)
endfunction()

function(_aros_program_shared_prerequisite node out_var)
  # Transitional broad aliases are handled by the existing SDK primitives.
  if(node MATCHES "^(includes|includes-copy|includes-generate-deps|core-linklibs|linklibs)$")
    set(${out_var} TRUE PARENT_SCOPE)
  else()
    set(${out_var} FALSE PARENT_SCOPE)
  endif()
endfunction()

# Discover source preparation without registering programs or expanding header
# lists before their sources exist. The full registry still owns build edges.
function(_aros_program_fetch_prerequisites node stack out_var)
  set(_AROS_RULE_OPTION_INCLUDES TRUE)
  set(${out_var} "" PARENT_SCOPE)
  _aros_program_shared_prerequisite("${node}" _shared)
  if(_shared)
    return()
  endif()
  if(NOT node MATCHES "^[A-Za-z0-9_.+-]+$")
    message(FATAL_ERROR "Unresolved program metadata prerequisite: ${node}")
  endif()
  if(node IN_LIST stack)
    message(FATAL_ERROR "Program fetch metadata dependency cycle: ${stack};${node}")
  endif()
  string(SHA256 _identity "${node}")
  get_property(_provider GLOBAL PROPERTY "AROS_MMAKE_RUNTIME_TARGET_${_identity}")
  _aros_sanitize_property_key("${node}" _key)
  if(NOT _provider)
    get_property(_provider GLOBAL PROPERTY "AROS_MODULE_INTERFACE_TARGET_${_key}")
  endif()
  if(_provider)
    _aros_native_fetch_dependencies(_fetches "${_provider}")
    set(${out_var} "${_fetches}" PARENT_SCOPE)
    return()
  endif()
  _aros_find_program_manifests("${node}" _programs INCLUDING_LINKLIBS)
  if(_programs)
    # Compiled prerequisites prepare their own sources, not this consumer's.
    return()
  endif()
  _aros_register_mmake_fetch("${node}" _fetch)
  if(_fetch)
    set(${out_var} "${_fetch}" PARENT_SCOPE)
    return()
  endif()
  _aros_static_manifest_candidates("${node}" _candidates)
  set(_AROS_RULE_MACRO_COLLECTOR _aros_prerequisite_macro_identity)
  set(_dependencies)
  foreach(_manifest IN LISTS _candidates)
    _aros_program_metadata_prerequisites("${_manifest}" "${node}" "${stack}" _part)
    list(APPEND _dependencies ${_part})
    foreach(_static_node IN LISTS _part_STATIC_NODES)
      _aros_mmake_is_text_transform("${_manifest}" "${_static_node}" _transform)
      if(_transform)
        continue()
      endif()
      aros_collect_mmake_static_files("${_manifest}" "${_static_node}" _static STRICT LOCAL_NODE)
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES _dependencies)
  set(_fetches)
  foreach(_dependency IN LISTS _dependencies)
    _aros_program_fetch_prerequisites("${_dependency}" "${stack};${node}" _part)
    list(APPEND _fetches ${_part})
  endforeach()
  list(REMOVE_DUPLICATES _fetches)
  set(${out_var} "${_fetches}" PARENT_SCOPE)
endfunction()

function(aros_add_mmake_programs target_name)
  cmake_parse_arguments(ARG "" "MMAKE_NAME" "" ${ARGN})
  if(NOT ARG_MMAKE_NAME OR ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "aros_add_mmake_programs requires MMAKE_NAME")
  endif()
  string(SHA256 _key "${ARG_MMAKE_NAME}")
  get_property(_existing GLOBAL PROPERTY "AROS_MMAKE_RUNTIME_TARGET_${_key}")
  if(_existing)
    get_target_property(_program_mmake "${_existing}" AROS_PROGRAM_MMAKE)
    if(NOT _program_mmake STREQUAL ARG_MMAKE_NAME)
      message(FATAL_ERROR "Conflicting native mmake producers for ${ARG_MMAKE_NAME}")
    endif()
    if(NOT target_name STREQUAL _existing)
      add_custom_target("${target_name}" DEPENDS "${_existing}")
    endif()
    return()
  endif()
  _aros_find_program_manifests("${ARG_MMAKE_NAME}" _matches)
  list(LENGTH _matches _count)
  if(_count EQUAL 0)
    message(FATAL_ERROR "No manifest for program entrypoint ${ARG_MMAKE_NAME}")
  elseif(_count EQUAL 1)
    _aros_add_program_manifest("${target_name}" "${ARG_MMAKE_NAME}" "${_matches}")
  else()
    add_custom_target("${target_name}")
    set_target_properties("${target_name}" PROPERTIES FOLDER "aros/programs"
      AROS_PROGRAM_MMAKE "${ARG_MMAKE_NAME}")
    foreach(_manifest IN LISTS _matches)
      file(RELATIVE_PATH _relative "${CMAKE_SOURCE_DIR}" "${_manifest}")
      string(SHA256 _key "${_relative}")
      set(_part "${target_name}-${_key}")
      _aros_add_program_manifest("${_part}" "${ARG_MMAKE_NAME}" "${_manifest}")
      set_property(TARGET "${target_name}" APPEND PROPERTY AROS_PROGRAM_PART_TARGETS "${_part}")
      add_dependencies("${target_name}" "${_part}")
    endforeach()
  endif()
  _aros_register_mmake_runtime_target("${ARG_MMAKE_NAME}" "${target_name}")
endfunction()

function(_aros_program_claim_output output owner)
  _aros_catalog_real_path("${output}" _real)
  set(_paths "${output}" "${_real}")
  list(REMOVE_DUPLICATES _paths)
  foreach(_path IN LISTS _paths)
    string(SHA256 _key "${_path}")
    get_property(_previous GLOBAL PROPERTY "AROS_STATIC_FILE_${_key}")
    if(_previous)
      message(FATAL_ERROR "Duplicate program producer for ${output}: ${_previous} and ${owner}")
    endif()
    set_property(GLOBAL PROPERTY "AROS_STATIC_FILE_${_key}" "program:${owner}")
  endforeach()
endfunction()

function(_aros_add_program_manifest target_name ARG_MMAKE_NAME _matches)
  get_filename_component(_module_dir "${_matches}" DIRECTORY)
  file(RELATIVE_PATH MODULE_PATH "${CMAKE_SOURCE_DIR}" "${_module_dir}")
  set(MODULE_MMAKE_NAME "${ARG_MMAKE_NAME}")
  set(MODULE_MMAKEFILE "${_matches}")
  set(_metadata_dir "${CMAKE_CURRENT_BINARY_DIR}/programs/${target_name}")
  file(MAKE_DIRECTORY "${_metadata_dir}")
  set(AROS_SOURCE_DIR "${CMAKE_SOURCE_DIR}")
  set(AROS_BINARY_DIR "${CMAKE_BINARY_DIR}")
  set(AROS_CONFIG_BUILD_DIR "${AROS_LEGACY_BUILD_DIR}")
  set(AROS_TOOLCHAIN_DIR "${AROS_NATIVE_TOOLCHAIN_INSTALL_DIR}")
  set(AROS_TOOLCHAIN_PREFIX "${AROS_CROSSTOOLS_TARGET_CPU}-aros")
  set(_compiler_candidates
    "${AROS_TOOLCHAIN_DIR}/${AROS_TOOLCHAIN_PREFIX}-gcc"
    "${AROS_TOOLCHAIN_DIR}/bin/${AROS_TOOLCHAIN_PREFIX}-gcc")
  file(GLOB _compilers CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE ${_compiler_candidates})
  if(NOT _compilers)
    # Keep clean-checkout configuration possible before toolchain bootstrap.
    # Its installation is detected by the next ordinary build's glob check.
    add_custom_target("${target_name}"
      COMMAND "${CMAKE_COMMAND}" -E echo
        "${target_name}: build/install the target compiler in ${AROS_TOOLCHAIN_DIR} first, then build again"
      COMMAND "${CMAKE_COMMAND}" -E false VERBATIM)
    set_target_properties("${target_name}" PROPERTIES FOLDER "aros/programs"
      AROS_PROGRAM_MMAKE "${ARG_MMAKE_NAME}")
    return()
  endif()
  foreach(_candidate IN LISTS _compiler_candidates)
    if(_candidate IN_LIST _compilers)
      set(_compiler "${_candidate}")
      break()
    endif()
  endforeach()
  set(_AROS_MMAKE_VAR_AROSDIR "${AROS_NATIVE_SYSTEM_DIR}")
  set(_AROS_MMAKE_VAR_TARGETDIR "${AROS_NATIVE_OUTPUT_ROOT}")
  set(_AROS_MMAKE_VAR_GENDIR "${AROS_NATIVE_OUTPUT_ROOT}/gen")
  set(_AROS_MMAKE_VAR_GENINCDIR "${AROS_NATIVE_INCLUDE_DIR}")
  set(_AROS_MMAKE_VAR_OBJDIR "${_metadata_dir}/obj")
  set(_AROS_MMAKE_VAR_AROS_BUILD_SDKS "${AROS_NATIVE_BUILD_SDKS_DIR}")
  _aros_program_prerequisites("${_matches}" "${ARG_MMAKE_NAME}" _prerequisites)
  set(_fetch_targets)
  set(AROS_PROGRAM_FETCH_SOURCES)
  set(AROS_PROGRAM_FETCH_REPORTS)
  set(AROS_PROGRAM_FETCH_PYTHON "")
  set(_fetch_ready TRUE)
  foreach(_prerequisite IN LISTS _prerequisites)
    _aros_program_fetch_prerequisites("${_prerequisite}" "${ARG_MMAKE_NAME}" _fetches)
    list(APPEND _fetch_targets ${_fetches})
  endforeach()
  list(REMOVE_DUPLICATES _fetch_targets)
  foreach(_fetch IN LISTS _fetch_targets)
    get_target_property(_ready "${_fetch}" AROS_FETCH_READY)
    get_target_property(_sources "${_fetch}" AROS_FETCH_FILES)
    get_target_property(_report "${_fetch}" AROS_FETCH_REPORT)
    get_target_property(AROS_PROGRAM_FETCH_PYTHON "${_fetch}" AROS_FETCH_PYTHON)
    list(APPEND AROS_PROGRAM_FETCH_SOURCES ${_sources})
    list(APPEND AROS_PROGRAM_FETCH_REPORTS "${_report}")
    if(NOT _ready)
      set(_fetch_ready FALSE)
    endif()
  endforeach()
  if(NOT _fetch_ready)
    # Do not configure a partial compile/include graph before sources exist.
    # The receipt inventory activates it on the next ordinary build.
    add_custom_target("${target_name}"
      COMMAND "${CMAKE_COMMAND}" -E echo "${target_name}: native sources prepared; run the build again to configure their consumers"
      COMMAND "${CMAKE_COMMAND}" -E false DEPENDS ${_fetch_targets} VERBATIM)
    set_target_properties("${target_name}" PROPERTIES FOLDER "aros/programs"
      AROS_PROGRAM_MMAKE "${ARG_MMAKE_NAME}")
    return()
  endif()
  set(_context "${_metadata_dir}/context.cmake")
  set(_content "")
  foreach(_var IN ITEMS AROS_SOURCE_DIR AROS_BINARY_DIR AROS_CONFIG_BUILD_DIR AROS_TARGET AROS_TARGET_FAMILY
      AROS_NATIVE_CONFIG_FILE
      MODULE_PATH MODULE_MMAKE_NAME MODULE_MMAKEFILE AROS_TOOLCHAIN_DIR AROS_TOOLCHAIN_PREFIX
      AROS_NATIVE_SYSTEM_DIR AROS_NATIVE_DEVELOPER_DIR AROS_NATIVE_PUBLIC_LIB_DIR
      AROS_NATIVE_INCLUDE_DIR AROS_NATIVE_BUILD_SDKS_DIR
      AROS_PROGRAM_FETCH_SOURCES AROS_PROGRAM_FETCH_REPORTS AROS_PROGRAM_FETCH_PYTHON
      _AROS_MMAKE_VAR_TARGETDIR _AROS_MMAKE_VAR_AROSDIR _AROS_MMAKE_VAR_GENDIR _AROS_MMAKE_VAR_GENINCDIR
      _AROS_MMAKE_VAR_OBJDIR _AROS_MMAKE_VAR_AROS_BUILD_SDKS)
    string(APPEND _content "set(${_var} [==[${${_var}}]==])\n")
  endforeach()
  file(CONFIGURE OUTPUT "${_context}" CONTENT "@_content@" @ONLY)
  set(_metadata "${_metadata_dir}/program.cmake")
  set(_collector "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/collect_mmake_program.cmake")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DCONTEXT_FILE=${_context}"
    "-DOUTPUT_FILE=${_metadata}" -P "${_collector}" COMMAND_ERROR_IS_FATAL ANY)
  include("${_metadata}")
  set(_program_objdir "${_AROS_MMAKE_VAR_OBJDIR}")
  if(NOT MMAKE_PROGRAM_OBJDIR STREQUAL "")
    set(_program_objdir "${MMAKE_PROGRAM_OBJDIR}")
  endif()
  _aros_catalog_native_output("${_program_objdir}" "${CMAKE_BINARY_DIR}")
  if(EXISTS "${_program_objdir}" AND NOT IS_DIRECTORY "${_program_objdir}")
    message(FATAL_ERROR "Program objdir is not a directory: ${_program_objdir}")
  endif()
  if(MMAKE_PROGRAM_CONFIG_OPTIONAL_INPUTS)
    file(GLOB _optional_config CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE ${MMAKE_PROGRAM_CONFIG_OPTIONAL_INPUTS})
  endif()
  aros_collect_program_codegen("${_matches}" _compile_inputs)
  _aros_program_driver_archives("${_compiler}" "${_metadata_dir}/compiler-probe" _driver_libs _runtime _specs _startup)
  set(_startup_targets)
  foreach(_object IN LISTS _startup)
    _aros_register_program_object("${_object}" "${_content}" _producer)
    list(APPEND _startup_targets "${_producer}")
  endforeach()
  string(REPLACE ";" "|" _encoded_startup "${_startup}")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    ${MMAKE_PROGRAM_INPUTS} "${_collector}" "${_compiler}" ${_specs}
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/AROSMmakeBuild.cmake"
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/AROSMmakeFunctions.cmake"
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/AROSMmakePrograms.cmake")
  file(RELATIVE_PATH _relative "${AROS_NATIVE_SYSTEM_DIR}" "${MMAKE_PROGRAM_TARGETDIR}")
  if(NOT IS_ABSOLUTE "${MMAKE_PROGRAM_TARGETDIR}" OR _relative MATCHES "^\\.\\.(/|$)"
     OR IS_ABSOLUTE "${_relative}")
    message(FATAL_ERROR "Program destination outside native runtime tree: ${MMAKE_PROGRAM_TARGETDIR}")
  endif()
  foreach(_sdk IN LISTS MMAKE_PROGRAM_USESDKS)
    if(NOT _sdk MATCHES "^[A-Za-z0-9_.+-]+$" OR _sdk MATCHES "^[.]+$")
      message(FATAL_ERROR "Invalid program SDK name: ${_sdk}")
    endif()
  endforeach()
  add_custom_target("${target_name}")
  if(_fetch_targets)
    add_dependencies("${target_name}" ${_fetch_targets})
  endif()
  set_target_properties("${target_name}" PROPERTIES FOLDER "aros/programs"
    AROS_PROGRAM_MMAKE "${ARG_MMAKE_NAME}")
  set(_builder "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/build_mmake_program.cmake")
  set(_objects)
  set(_index 0)
  foreach(_source IN LISTS MMAKE_PROGRAM_SOURCES)
    if(NOT MMAKE_PROGRAM_OBJDIR STREQUAL "")
      list(GET MMAKE_PROGRAM_NAMES ${_index} _name)
      set(_object "${_program_objdir}/${_name}.o")
      set(_depfile "${_program_objdir}/${_name}.d")
    else()
      set(_object "${_program_objdir}/${_index}.o")
      set(_depfile "${_object}.d")
    endif()
    foreach(_path IN ITEMS "${_object}" "${_depfile}")
      _aros_catalog_native_output("${_path}" "${CMAKE_BINARY_DIR}")
      _aros_program_claim_output("${_path}" "${target_name}")
    endforeach()
    add_custom_command(OUTPUT "${_object}"
      COMMAND "${CMAKE_COMMAND}" "-DCONTEXT_FILE=${_context}" "-DMETADATA_FILE=${_metadata}"
        -DMODE=COMPILE "-DSOURCE_FILE=${_source}" "-DOUTPUT_FILE=${_object}" "-DDEPFILE=${_depfile}" -P "${_builder}"
      DEPFILE "${_depfile}"
      DEPENDS "${_source}" "${_metadata}" "${_context}" "${_builder}"
        ${AROS_PROGRAM_FETCH_REPORTS}
        ${_compile_inputs_${_index}}
        "$<TARGET_PROPERTY:${target_name},AROS_PROGRAM_HEADER_DEPS>"
      COMMENT "Compiling AROS program source ${_source}" VERBATIM)
    list(APPEND _objects "${_object}")
    math(EXPR _index "${_index} + 1")
  endforeach()
  if(MMAKE_PROGRAM_KIND STREQUAL "prog")
    set(_names "${MMAKE_PROGRAM_NAME}")
  else()
    set(_names "${MMAKE_PROGRAM_NAMES}")
  endif()
  set(_index 0)
  set(_outputs)
  set(_program_targets)
  foreach(_name IN LISTS _names)
    if(NOT _name MATCHES "^[A-Za-z0-9_+.-]+$" OR _name MATCHES "^[.]+$")
      message(FATAL_ERROR "Unsupported program output name: ${_name}")
    endif()
    set(_output "${MMAKE_PROGRAM_TARGETDIR}/${_name}")
    string(SHA256 _key "${_output}")
    get_property(_owner GLOBAL PROPERTY "AROS_PROGRAM_OUTPUT_${_key}")
    if(_owner)
      message(FATAL_ERROR "Duplicate program output ${_output}: ${_owner} and ${target_name}")
    endif()
    set_property(GLOBAL PROPERTY "AROS_PROGRAM_OUTPUT_${_key}" "${target_name}")
    _aros_program_claim_output("${_output}" "${target_name}")
    if(MMAKE_PROGRAM_KIND STREQUAL "progs")
      list(GET _objects ${_index} _link_objects)
    else()
      set(_link_objects "${_objects}")
    endif()
    string(REPLACE ";" "|" _encoded_objects "${_link_objects}")
    add_custom_command(OUTPUT "${_output}"
      COMMAND "${CMAKE_COMMAND}" "-DCONTEXT_FILE=${_context}" "-DMETADATA_FILE=${_metadata}"
        -DMODE=LINK "-DOBJECT_FILES=${_encoded_objects}" "-DSTARTUP_OBJECTS=${_encoded_startup}"
        "-DOUTPUT_FILE=${_output}" -P "${_builder}"
      DEPENDS ${_link_objects} ${_startup} "${_metadata}" "${_context}" "${_builder}"
        "$<TARGET_PROPERTY:${target_name},AROS_PROGRAM_LINK_DEPS>"
      COMMENT "Linking AROS program ${_name}" VERBATIM)
    set(_program_target "${target_name}-${_name}")
    add_custom_target("${_program_target}" DEPENDS "${_output}")
    if(_startup_targets)
      add_dependencies("${_program_target}" ${_startup_targets})
    endif()
    set_target_properties("${_program_target}" PROPERTIES FOLDER "aros/programs"
      AROS_MODULE_OUTPUT "${_output}")
    add_dependencies("${target_name}" "${_program_target}")
    list(APPEND _program_targets "${_program_target}")
    list(APPEND _outputs "${_output}")
    math(EXPR _index "${_index} + 1")
  endforeach()
  foreach(_input IN LISTS _compile_inputs_SOURCES)
    get_filename_component(_extension "${_input}" EXT)
    list(APPEND _AROS_INCLUDE_SCAN_EXTRA_EXTENSIONS "${_extension}")
  endforeach()
  _aros_collect_include_virtual_paths_from_files(_source_includes ${MMAKE_PROGRAM_SOURCES} ${_compile_inputs_SOURCES})
  _aros_collect_include_interface_modules_from_files(_source_interfaces ${MMAKE_PROGRAM_SOURCES} ${_compile_inputs_SOURCES})
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${MMAKE_PROGRAM_SOURCES} ${_compile_inputs_SOURCES})
  set_target_properties("${target_name}" PROPERTIES AROS_PROGRAM_OUTPUTS "${_outputs}"
    AROS_PROGRAM_TARGETS "${_program_targets}"
    AROS_PROGRAM_PREREQUISITES "${_prerequisites}"
    AROS_PROGRAM_STATIC_NODES "${_prerequisites_STATIC_NODES}"
    AROS_PROGRAM_CONTEXT "${_context}"
    AROS_PROGRAM_ARCHIVES "${MMAKE_PROGRAM_USELIBS};${_driver_libs}"
    AROS_PROGRAM_COMPILER "${_compiler}"
    AROS_PROGRAM_COMPILER_RUNTIME "${_runtime}"
    AROS_PROGRAM_COMPILER_SPECS "${_specs}"
    AROS_PROGRAM_SOURCE_INTERFACES "${_source_interfaces}"
    AROS_PROGRAM_SOURCE_INCLUDES "${_source_includes}")
  set_property(GLOBAL APPEND PROPERTY AROS_NATIVE_PROGRAM_TARGETS "${target_name}")
endfunction()

function(_aros_register_program_object output context_content out_target)
  string(SHA256 _key "${output}")
  set(_target "aros-sdk-object-${_key}")
  set(${out_target} "${_target}" PARENT_SCOPE)
  if(TARGET "${_target}")
    return()
  endif()
  set(_manifests)
  foreach(_manifest IN LISTS AROS_MMAKE_MANIFESTS)
    file(STRINGS "${_manifest}" _compile REGEX "^%rule_compile[ \t]")
    file(STRINGS "${_manifest}" _copy REGEX "\\$\\(CP\\)[ \t]+\\$<[ \t]+\\$@")
    if(_compile AND _copy)
      list(APPEND _manifests "${_manifest}")
    endif()
  endforeach()
  set(_dir "${CMAKE_BINARY_DIR}/sdk-objects/${_key}")
  set(_context "${_dir}/context.cmake")
  set(_metadata "${_dir}/object.cmake")
  string(APPEND context_content "set(OBJECT_MANIFESTS [==[${_manifests}]==])\nset(SDK_OBJECT_OUTPUT [==[${output}]==])\n")
  file(CONFIGURE OUTPUT "${_context}" CONTENT "@context_content@" @ONLY)
  set(_collector "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/collect_mmake_object.cmake")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DCONTEXT_FILE=${_context}"
    "-DOUTPUT_FILE=${_metadata}" -P "${_collector}" COMMAND_ERROR_IS_FATAL ANY)
  include("${_metadata}")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_manifests}
    "${MMAKE_OBJECT_SOURCE}" "${_collector}"
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/AROSMmakeObjects.cmake"
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/AROSMmakeRules.cmake")
  set(_builder "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/build_mmake_program.cmake")
  set(_object "${_dir}/compiled.o")
  add_custom_command(OUTPUT "${_object}"
    COMMAND "${CMAKE_COMMAND}" "-DCONTEXT_FILE=${_context}" "-DMETADATA_FILE=${_metadata}"
      -DMODE=COMPILE "-DSOURCE_FILE=${MMAKE_OBJECT_SOURCE}" "-DOUTPUT_FILE=${_object}" -P "${_builder}"
    DEPFILE "${_object}.d"
    DEPENDS "${MMAKE_OBJECT_SOURCE}" "${_metadata}" "${_context}" "${_builder}"
      "$<TARGET_PROPERTY:${_target},AROS_PROGRAM_HEADER_DEPS>"
    COMMENT "Compiling SDK object from ${MMAKE_OBJECT_SOURCE}" VERBATIM)
  get_filename_component(_outdir "${output}" DIRECTORY)
  add_custom_command(OUTPUT "${output}"
    COMMAND "${CMAKE_COMMAND}" -E make_directory "${_outdir}"
    COMMAND "${CMAKE_COMMAND}" -E copy "${_object}" "${output}"
    DEPENDS "${_object}" COMMENT "Staging native SDK object ${output}" VERBATIM)
  add_custom_target("${_target}" DEPENDS "${output}")
  _aros_collect_include_virtual_paths_from_files(_includes "${MMAKE_OBJECT_SOURCE}")
  _aros_collect_include_interface_modules_from_files(_interfaces "${MMAKE_OBJECT_SOURCE}")
  # Use the same header-provider finalizer as programs, without library inputs.
  set_target_properties("${_target}" PROPERTIES FOLDER "aros/internal/sdk"
    AROS_PROGRAM_ARCHIVES "" AROS_PROGRAM_COMPILER "${_compiler}"
    AROS_PROGRAM_COMPILER_RUNTIME "" AROS_PROGRAM_COMPILER_SPECS ""
    AROS_PROGRAM_SOURCE_INTERFACES "${_interfaces}" AROS_PROGRAM_SOURCE_INCLUDES "${_includes}"
    AROS_PROGRAM_PREREQUISITES "" AROS_PROGRAM_TARGETS "")
  set_property(GLOBAL APPEND PROPERTY AROS_NATIVE_PROGRAM_TARGETS "${_target}")
endfunction()

function(_aros_program_alias_macro kind args prefix)
  set(${prefix}_FIELDS "" PARENT_SCOPE)
  if(args MATCHES "(^|[ \t])(mmake|mainmmake)=\"?([^ \t\"]+)")
    _aros_expand_make_tokens("${CMAKE_MATCH_3}" _name)
    if(_name STREQUAL _AROS_PROGRAM_ALIAS)
      message(FATAL_ERROR "Program prerequisite ${_AROS_PROGRAM_ALIAS} needs native support for %${kind}")
    endif()
  endif()
  _aros_prerequisite_macro_identity("${kind}" "${args}" _identity)
  set(${prefix}_FIELDS "${_identity_FIELDS}" PARENT_SCOPE)
  foreach(_field IN LISTS _identity_FIELDS)
    set(${prefix}_${_field} "${_identity_${_field}}" PARENT_SCOPE)
  endforeach()
endfunction()

function(_aros_register_program_prerequisite node stack out_var)
  set(${out_var} "" PARENT_SCOPE)
  set(_AROS_MMAKE_VAR_AROSDIR "${AROS_NATIVE_SYSTEM_DIR}")
  if(AROS_NATIVE_OUTPUT_ROOT)
    set(_AROS_MMAKE_VAR_GENDIR "${AROS_NATIVE_OUTPUT_ROOT}/gen")
  endif()
  _aros_program_shared_prerequisite("${node}" _shared)
  if(_shared)
    return()
  endif()
  if(NOT node MATCHES "^[A-Za-z0-9_.+-]+$")
    message(FATAL_ERROR "Unresolved program metadata prerequisite: ${node}")
  endif()
  if(node IN_LIST stack)
    message(FATAL_ERROR "Program metadata dependency cycle: ${stack};${node}")
  endif()
  string(SHA256 _identity "${node}")
  get_property(_provider GLOBAL PROPERTY "AROS_MMAKE_RUNTIME_TARGET_${_identity}")
  _aros_sanitize_property_key("${node}" _key)
  if(NOT _provider)
    get_property(_provider GLOBAL PROPERTY "AROS_MODULE_INTERFACE_TARGET_${_key}")
  endif()
  if(NOT _provider)
    _aros_find_program_manifests("${node}" _manifests)
    if(_manifests)
      set(_provider "aros-programs-${node}-native")
      aros_add_mmake_programs("${_provider}" MMAKE_NAME "${node}")
    endif()
  endif()
  if(NOT _provider)
    _aros_register_mmake_includes("${node}" "${stack}" _provider)
  endif()
  if(NOT _provider)
    _aros_register_program_icons("${node}" _provider)
  endif()
  if(NOT _provider)
    _aros_register_program_catalogs("${node}" _provider)
  endif()
  if(NOT _provider)
    _aros_register_mmake_fetch("${node}" _provider)
  endif()
  if(_provider)
    set(${out_var} "${_provider}" PARENT_SCOPE)
    return()
  endif()
  # Absent metadata aliases are optional in MetaMake. Active aliases may
  # contribute across manifests, but never adopt a legacy target or stale file.
  _aros_static_manifest_candidates("${node}" _candidates)
  set(_AROS_RULE_MACRO_COLLECTOR _aros_program_alias_macro)
  set(_AROS_PROGRAM_ALIAS "${node}")
  set(_dependencies)
  set(_providers)
  set(_next_stack ${stack} "${node}")
  foreach(_manifest IN LISTS _candidates)
    _aros_program_metadata_prerequisites("${_manifest}" "${node}" "${stack}" _part)
    list(APPEND _dependencies ${_part})
    foreach(_static_node IN LISTS _part_STATIC_NODES)
      _aros_register_program_static_node("${_manifest}" "${_static_node}" "${_next_stack}" _provider)
      list(APPEND _providers "${_provider}")
    endforeach()
  endforeach()
  foreach(_dependency IN LISTS _dependencies)
    _aros_register_program_prerequisite("${_dependency}" "${_next_stack}" _provider)
    list(APPEND _providers ${_provider})
  endforeach()
  list(REMOVE_DUPLICATES _providers)
  set(${out_var} "${_providers}" PARENT_SCOPE)
endfunction()

function(_aros_register_program_static_node manifest node stack out_var)
  if(_AROS_INCLUDE_TRANSFORMS)
    _aros_mmake_is_text_transform("${manifest}" "${node}" _transform)
    if(_transform)
      string(SHA256 _key "${manifest}|${node}|${_AROS_PREREQUISITE_FETCH_TARGETS}")
      set(_target "aros-prerequisite-transform-${_key}")
      if(NOT TARGET "${_target}")
        aros_add_mmake_transform_target("${_target}" MANIFEST "${manifest}"
          MMAKE_NAME "${node}" FETCH_TARGETS ${_AROS_PREREQUISITE_FETCH_TARGETS})
      endif()
      set(${out_var} "${_target}" PARENT_SCOPE)
      return()
    endif()
  endif()
  # The local recipe's metadata dependencies are resolved separately; a
  # program macro elsewhere in the same manifest is not a static producer.
  set(_AROS_RULE_MACRO_COLLECTOR _aros_program_macro_identity)
  aros_collect_mmake_static_files("${manifest}" "${node}" _static STRICT LOCAL_NODE)
  set(_children)
  foreach(_dependency IN LISTS _static_EXTERNAL_MMAKE)
    _aros_register_program_prerequisite("${_dependency}" "${stack}" _providers)
    list(APPEND _children ${_providers})
  endforeach()
  list(REMOVE_DUPLICATES _children)
  _aros_add_mmake_static_commands("${manifest}" _static _outputs ${_children})
  string(SHA256 _key "${manifest}|${node}|${_outputs}|${_children}")
  set(_target "aros-program-static-${_key}")
  if(NOT TARGET "${_target}")
    add_custom_target("${_target}" DEPENDS ${_outputs} ${_children})
    set_target_properties("${_target}" PROPERTIES FOLDER "aros/internal/packaging"
      AROS_STATIC_OUTPUTS "${_outputs}")
  endif()
  set(${out_var} "${_target}" PARENT_SCOPE)
endfunction()

function(_aros_program_static_prerequisites target out_var)
  set(${out_var} "" PARENT_SCOPE)
  get_target_property(_nodes "${target}" AROS_PROGRAM_STATIC_NODES)
  if(NOT _nodes)
    return()
  endif()
  get_target_property(_context "${target}" AROS_PROGRAM_CONTEXT)
  include("${_context}")
  set(_providers)
  foreach(_node IN LISTS _nodes)
    _aros_register_program_static_node("${MODULE_MMAKEFILE}" "${_node}" "${MODULE_MMAKE_NAME}" _provider)
    list(APPEND _providers "${_provider}")
  endforeach()
  set(${out_var} "${_providers}" PARENT_SCOPE)
endfunction()

function(aros_finalize_program_dependencies)
  set(_finished)
  get_property(_programs GLOBAL PROPERTY AROS_NATIVE_PROGRAM_TARGETS)
  while(_programs)
    list(POP_FRONT _programs _target)
    if(_target IN_LIST _finished)
      continue()
    endif()
    list(APPEND _finished "${_target}")
    get_target_property(_libs "${_target}" AROS_PROGRAM_ARCHIVES)
    foreach(_lib IN LISTS _libs)
      if(_lib STREQUAL "")
        continue()
      endif()
      _aros_collect_registered_archive_dependencies(_check_files _check_targets "${_lib}")
      if(NOT _check_targets)
        _aros_register_discovered_program_linklib("${_lib}")
        _aros_collect_registered_archive_dependencies(_check_files _check_targets "${_lib}")
        if(NOT _check_targets)
          message(FATAL_ERROR "Program ${_target} needs a native archive producer for ${_lib}")
        endif()
      endif()
    endforeach()
    _aros_collect_registered_archive_dependencies(_files _targets ${_libs})
    get_target_property(_compiler "${_target}" AROS_PROGRAM_COMPILER)
    get_target_property(_runtime "${_target}" AROS_PROGRAM_COMPILER_RUNTIME)
    get_target_property(_specs "${_target}" AROS_PROGRAM_COMPILER_SPECS)
    set(_program_header_deps "${AROS_NATIVE_INCLUDES_STAMP}" "${_compiler}")
    get_target_property(_source_interfaces "${_target}" AROS_PROGRAM_SOURCE_INTERFACES)
    foreach(_module IN LISTS _source_interfaces)
      _aros_sanitize_property_key("${_module}" _key)
      get_property(_provider GLOBAL PROPERTY "AROS_MODULE_NAME_INTERFACE_TARGET_${_key}")
      if(_provider)
        list(APPEND _targets "${_provider}")
      endif()
    endforeach()
    get_target_property(_source_includes "${_target}" AROS_PROGRAM_SOURCE_INCLUDES)
    foreach(_include IN LISTS _source_includes)
      _aros_sanitize_property_key("${_include}" _key)
      get_property(_provider GLOBAL PROPERTY "AROS_STAGED_INCLUDE_TARGET_${_key}")
      if(_provider)
        list(APPEND _targets "${_provider}")
      endif()
    endforeach()
    get_target_property(_prerequisites "${_target}" AROS_PROGRAM_PREREQUISITES)
    foreach(_node IN LISTS _prerequisites)
      _aros_register_program_prerequisite("${_node}" "" _providers)
      list(APPEND _targets ${_providers})
    endforeach()
    _aros_program_static_prerequisites("${_target}" _static_providers)
    list(APPEND _targets ${_static_providers})
    set(_link_deps "${_compiler}" ${_runtime} ${_specs} ${_files})
    foreach(_provider IN LISTS _targets)
      get_target_property(_stamp "${_provider}" AROS_MODULE_INTERFACE_STAMP)
      if(_stamp)
        list(APPEND _program_header_deps "${_stamp}")
        list(APPEND _link_deps "${_stamp}")
      endif()
    endforeach()
    get_target_property(_children "${_target}" AROS_PROGRAM_TARGETS)
    foreach(_dependency IN ITEMS aros-native-includes ${_targets})
      if(TARGET "${_dependency}")
        foreach(_consumer IN ITEMS "${_target}" ${_children})
          add_dependencies("${_consumer}" "${_dependency}")
        endforeach()
      endif()
    endforeach()
    list(REMOVE_DUPLICATES _program_header_deps)
    set_target_properties("${_target}" PROPERTIES
      AROS_PROGRAM_HEADER_DEPS "${_program_header_deps}"
      AROS_PROGRAM_LINK_DEPS "${_link_deps}")
    get_property(_programs GLOBAL PROPERTY AROS_NATIVE_PROGRAM_TARGETS)
    list(REMOVE_ITEM _programs ${_finished})
  endwhile()
  _aros_finalize_registered_linklib_interfaces()
endfunction()

function(_aros_register_discovered_program_linklib library)
  set(_matches)
  foreach(_manifest IN LISTS AROS_MMAKE_MANIFESTS)
    file(STRINGS "${_manifest}" _rules REGEX "^[ \t]*%build_linklib[ \t]")
    if(NOT _rules)
      continue()
    endif()
    _aros_read_mmake_logical_lines("${_manifest}" _lines)
    foreach(_line IN LISTS _lines)
      if(_line MATCHES "^%build_linklib[ \t].*libname=\"?([^ \t\"]+)")
        if(CMAKE_MATCH_1 STREQUAL library)
          list(APPEND _matches "${_manifest}")
        endif()
      endif()
    endforeach()
  endforeach()
  list(LENGTH _matches _count)
  if(_count GREATER 1)
    message(FATAL_ERROR "Ambiguous native linklib producer for ${library}: ${_matches}")
  elseif(_count EQUAL 1)
    get_filename_component(_directory "${_matches}" DIRECTORY)
    file(RELATIVE_PATH _path "${CMAKE_SOURCE_DIR}" "${_directory}")
    _aros_sanitize_property_key("${library}" _key)
    aros_register_mmake_linklib("aros-discovered-linklib-${_key}-native"
      MODULE_PATH "${_path}" LIBNAME "${library}")
  endif()
endfunction()
