include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSCatalogTargets.cmake")

function(_aros_program_codegen_macro kind args prefix)
  set(${prefix}_FIELDS "" PARENT_SCOPE)
  if(NOT kind MATCHES "^build_progs?$")
    return()
  endif()
  _aros_mmake_macro_arguments("${args}" _arg)
  if(NOT _arg_mmake STREQUAL MODULE_MMAKE_NAME)
    return()
  endif()
  # Keep the per-program directory separate from global OBJDIR. In particular,
  # objdir=$(OBJDIR)/test must not be expanded again after rebinding OBJDIR.
  set("_AROS_MMAKE_VAR_${MODULE_MMAKE_NAME}_OBJDIR" "${_program_objdir}" PARENT_SCOPE)
  foreach(_suffix IN ITEMS o d)
    set(_paths)
    foreach(_file IN LISTS MMAKE_PROGRAM_FILES)
      get_filename_component(_name "${_file}" NAME)
      list(APPEND _paths "${_program_objdir}/${_name}.${_suffix}")
    endforeach()
    if(_suffix STREQUAL "o")
      set(_variable OBJS)
    else()
      set(_variable DEPS)
    endif()
    string(JOIN " " _paths ${_paths})
    set("_AROS_MMAKE_VAR_${MODULE_MMAKE_NAME}_${_variable}" "${_paths}" PARENT_SCOPE)
  endforeach()
  set(${prefix}_FIELDS NAME PARENT_SCOPE)
  set(${prefix}_NAME "${_arg_mmake}" PARENT_SCOPE)
endfunction()

function(_aros_program_bison output rule out_var)
  foreach(_include IN LISTS _codegen_INCLUDES)
    get_filename_component(_include "${_include}" ABSOLUTE BASE_DIR "${_codegen_source_dir}")
    # START LEGACY: the standard config facade is already served by the shared
    # generated-configuration reader. Other includes may contain unowned rules.
    if(NOT _include STREQUAL "${CMAKE_SOURCE_DIR}/config/aros.cfg"
       AND NOT _include IN_LIST MMAKE_PROGRAM_INPUTS)
      message(FATAL_ERROR "Program code generation needs included-manifest support: ${_include}")
    elseif(NOT _include MATCHES "[.]cfg$")
      message(FATAL_ERROR "Program code generation needs included-manifest support: ${_include}")
    endif()
    # END LEGACY.
  endforeach()
  set(_output_root "${_AROS_MMAKE_VAR_OBJDIR}")
  _aros_catalog_real_path("${output}" _real_output)
  _aros_catalog_real_path("${_program_objdir}" _real_objdir)
  file(RELATIVE_PATH _relative "${_real_objdir}" "${_real_output}")
  if(NOT _relative MATCHES "^\\.\\.(/|$)" AND NOT IS_ABSOLUTE "${_relative}")
    set(_output_root "${_program_objdir}")
  endif()
  _aros_catalog_native_output("${output}" "${_output_root}")
  set(_deps "${_codegen_${rule}_DEPENDS}")
  list(LENGTH _deps _count)
  if(NOT _count EQUAL 1 OR _deps MATCHES "[$%*?|]")
    message(FATAL_ERROR "Program code generation requires one static grammar: ${output}")
  endif()
  get_filename_component(_source "${_deps}" ABSOLUTE BASE_DIR "${_codegen_source_dir}")
  _aros_catalog_static_input("${_source}")
  foreach(_id IN LISTS _codegen_RULES)
    foreach(_target IN LISTS _codegen_${_id}_TARGETS)
      get_filename_component(_path "${_target}" ABSOLUTE BASE_DIR "${_codegen_source_dir}")
      _aros_mmake_pattern_match("${_path}" "${_source}" _match _stem)
      if(_match)
        message(FATAL_ERROR "Program code generation cannot adopt a generated grammar: ${_source}")
      endif()
    endforeach()
  endforeach()
  set(_bison_count 0)
  set(_echo_count 0)
  math(EXPR _last "${_codegen_${rule}_RECIPE_COUNT} - 1")
  foreach(_index RANGE 0 ${_last})
    set(_recipe "${_codegen_${rule}_RECIPE_${_index}}")
    string(REGEX REPLACE "[ \t]+" " " _recipe "${_recipe}")
    set(_diagnostic "${_recipe}")
    foreach(_token IN ITEMS "$(ECHO)" "$(notdir $@)" "$@" "$<")
      string(REPLACE "${_token}" "input" _diagnostic "${_diagnostic}")
    endforeach()
    if(_recipe MATCHES "^@?\\$\\(BISON\\) -o \\$@ \\$<$")
      math(EXPR _bison_count "${_bison_count} + 1")
      set(_command "${_codegen_VARIABLE_BISON}")
    elseif(_recipe MATCHES "^@?\\$\\(ECHO\\) " AND NOT _diagnostic MATCHES "[$;|&`<>]"
        AND _bison_count EQUAL 0)
      math(EXPR _echo_count "${_echo_count} + 1")
    else()
      message(FATAL_ERROR "Unsupported program code-generation recipe: ${_recipe}")
    endif()
  endforeach()
  if(NOT _bison_count EQUAL 1 OR _echo_count GREATER 1)
    message(FATAL_ERROR "Expected one Bison command for ${output}")
  endif()
  file(READ "${_source}" _grammar)
  # These directives change tools, output languages or sidecar paths. They
  # need explicit producer/dependency modelling before they can be accepted.
  if(_grammar MATCHES "%[ \t]*(defines|header|output|verbose|report|graph|xml|file-prefix|skeleton|language|yacc)([^A-Za-z_-]|$)")
    message(FATAL_ERROR "Unsupported Bison output/tool directive in ${_source}")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_source}")
  if(NOT _command)
    set(_command bison)
  endif()
  separate_arguments(_command UNIX_COMMAND "${_command}")
  list(LENGTH _command _count)
  if(NOT _count EQUAL 1 OR _command MATCHES "[$%;|&`<>]")
    message(FATAL_ERROR "Unsupported BISON command: ${_command}")
  endif()
  unset(_aros_bison CACHE)
  find_program(_aros_bison NAMES "${_command}" REQUIRED)
  set(_tool "${_aros_bison}")
  unset(_aros_bison CACHE)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_tool}")
  execute_process(COMMAND "${_tool}" --print-datadir OUTPUT_VARIABLE _data
    OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
  if(NOT IS_DIRECTORY "${_data}")
    message(FATAL_ERROR "Missing Bison data directory: ${_data}")
  endif()
  file(GLOB_RECURSE _tool_inputs CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE "${_data}/*")
  string(SHA256 _key "${output}")
  set(_identity "${_source}|${_tool}|${_tool_inputs}")
  get_property(_owner GLOBAL PROPERTY "AROS_PROGRAM_CODEGEN_${_key}")
  if(_owner AND NOT _owner STREQUAL _identity)
    message(FATAL_ERROR "Conflicting program code-generation producer for ${output}")
  elseif(NOT _owner)
    _aros_catalog_claim_output("${output}" "${MODULE_MMAKE_NAME}")
    set(_builder "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/build_mmake_bison.cmake")
    add_custom_command(OUTPUT "${output}"
      COMMAND "${CMAKE_COMMAND}" "-DBISON=${_tool}" "-DSOURCE_FILE=${_source}"
        "-DOUTPUT_FILE=${output}" "-DBISON_DATA_DIR=${_data}" -P "${_builder}"
      DEPENDS "${_source}" "${_tool}" ${_tool_inputs} "${_builder}"
      COMMENT "Generating AROS parser ${output}" VERBATIM)
    set_property(GLOBAL PROPERTY "AROS_PROGRAM_CODEGEN_${_key}" "${_identity}")
    set_property(GLOBAL PROPERTY "AROS_PROGRAM_CODEGEN_SOURCE_${_key}" "${_source}")
  endif()
  set(${out_var} "${output}" PARENT_SCOPE)
endfunction()

function(_aros_program_codegen_node node trail out_var)
  if(node IN_LIST trail)
    message(FATAL_ERROR "Cyclic program compile prerequisites: ${trail};${node}")
  endif()
  list(APPEND trail "${node}")
  set(_rules "")
  set(_recipe_rules "")
  foreach(_id IN LISTS _codegen_RULES)
    foreach(_target IN LISTS _codegen_${_id}_TARGETS)
      _aros_mmake_pattern_match("${_target}" "${node}" _match _stem)
      if(NOT _match)
        continue()
      endif()
      if(_target MATCHES "%" OR _codegen_${_id}_METADATA)
        message(FATAL_ERROR "Unsupported program compile prerequisite rule: ${_target}")
      endif()
      list(APPEND _rules "${_id}")
      if(_codegen_${_id}_RECIPE_COUNT GREATER 0)
        list(APPEND _recipe_rules "${_id}")
      endif()
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES _rules)
  list(REMOVE_DUPLICATES _recipe_rules)
  set(_files)
  if(NOT "${_recipe_rules}" STREQUAL "")
    list(LENGTH _rules _count)
    if(NOT _count EQUAL 1 OR NOT IS_ABSOLUTE "${node}" OR node MATCHES "[$%*?]")
      message(FATAL_ERROR "Ambiguous or unsupported program code-generation rules for ${node}")
    endif()
    _aros_program_bison("${node}" "${_recipe_rules}" _files)
  elseif(NOT "${_rules}" STREQUAL "")
    foreach(_id IN LISTS _rules)
      foreach(_dep IN LISTS _codegen_${_id}_DEPENDS)
        if(_dep STREQUAL "|")
          message(FATAL_ERROR "Order-only program compile prerequisites need native support: ${node}")
        endif()
        _aros_program_codegen_node("${_dep}" "${trail}" _inputs)
        list(APPEND _files ${_inputs})
      endforeach()
    endforeach()
    if(NOT _files AND NOT node IN_LIST _codegen_roots)
      message(FATAL_ERROR "Program compile prerequisite has no native producer: ${node}")
    endif()
  elseif(NOT node IN_LIST _codegen_roots)
    get_filename_component(_path "${node}" ABSOLUTE BASE_DIR "${_codegen_source_dir}")
    _aros_catalog_static_input("${_path}")
    list(APPEND _files "${_path}")
  endif()
  list(REMOVE_DUPLICATES _files)
  set(${out_var} "${_files}" PARENT_SCOPE)
endfunction()

function(aros_collect_program_codegen manifest prefix)
  set(_program_objdir "${_AROS_MMAKE_VAR_OBJDIR}")
  if(NOT MMAKE_PROGRAM_OBJDIR STREQUAL "")
    set(_program_objdir "${MMAKE_PROGRAM_OBJDIR}")
  endif()
  set(_AROS_RULE_MACRO_COLLECTOR _aros_program_codegen_macro)
  set(_AROS_RULE_RECIPE_VARIABLES BISON)
  get_filename_component(_codegen_source_dir "${manifest}" DIRECTORY)
  _aros_collect_mmake_rules("${manifest}" _codegen)
  list(LENGTH _codegen_MACROS _count)
  if(NOT _count EQUAL 1)
    message(FATAL_ERROR "Expected one active program code-generation context for ${MODULE_MMAKE_NAME}")
  endif()
  set(_codegen_roots)
  foreach(_file IN LISTS MMAKE_PROGRAM_FILES)
    get_filename_component(_name "${_file}" NAME)
    list(APPEND _codegen_roots "${_program_objdir}/${_name}.o" "${_program_objdir}/${_name}.d")
  endforeach()
  set(_index 0)
  set(_sources)
  foreach(_file IN LISTS MMAKE_PROGRAM_FILES)
    get_filename_component(_name "${_file}" NAME)
    set(_files)
    foreach(_suffix IN ITEMS o d)
      _aros_program_codegen_node("${_program_objdir}/${_name}.${_suffix}" "" _inputs)
      list(APPEND _files ${_inputs})
    endforeach()
    list(REMOVE_DUPLICATES _files)
    foreach(_path IN LISTS _files)
      string(SHA256 _key "${_path}")
      get_property(_source GLOBAL PROPERTY "AROS_PROGRAM_CODEGEN_SOURCE_${_key}")
      if(_source)
        list(APPEND _sources "${_source}")
      else()
        list(APPEND _sources "${_path}")
      endif()
    endforeach()
    set(${prefix}_${_index} "${_files}" PARENT_SCOPE)
    math(EXPR _index "${_index} + 1")
  endforeach()
  list(REMOVE_DUPLICATES _sources)
  set(${prefix}_SOURCES "${_sources}" PARENT_SCOPE)
endfunction()
