include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeObjects.cmake")

function(_aros_collect_catalog_macro kind args prefix)
  set(${prefix}_FIELDS "" PARENT_SCOPE)
  if(NOT kind STREQUAL "build_catalogs")
    return()
  endif()
  _aros_mmake_macro_arguments("${args}" _arg)
  if(NOT _arg_mmake STREQUAL _AROS_SELECTED_CATALOG_RULE)
    return()
  endif()
  # Defaults belong to the upstream macro, not to each migrated consumer.
  _aros_read_mmake_logical_lines("${CMAKE_SOURCE_DIR}/config/make.tmpl" _template)
  set(_definitions 0)
  foreach(_line IN LISTS _template)
    if(_line MATCHES "^%define build_catalogs[ \t]+(.*)$")
      _aros_mmake_macro_arguments("${CMAKE_MATCH_1}" _default)
      math(EXPR _definitions "${_definitions} + 1")
    endif()
  endforeach()
  if(NOT _definitions EQUAL 1)
    message(FATAL_ERROR "Expected one build_catalogs definition in config/make.tmpl")
  endif()
  set(_allowed mmake name subdir catalogs source description dir sourcedescription srcdir)
  foreach(_key IN LISTS _arg_KEYS _default_KEYS)
    if(NOT _key IN_LIST _allowed)
      message(FATAL_ERROR "Unsupported catalog argument: ${_key}")
    endif()
  endforeach()
  foreach(_key IN LISTS _allowed)
    if(NOT _key IN_LIST _arg_KEYS)
      if(_default_${_key} STREQUAL "/A")
        message(FATAL_ERROR "build_catalogs requires ${_key}")
      elseif(NOT _key IN_LIST _default_KEYS)
        message(FATAL_ERROR "Missing build_catalogs default for ${_key}")
      endif()
      set(_arg_${_key} "${_default_${_key}}")
    endif()
    if("${_arg_${_key}}" MATCHES "[$%;]")
      message(FATAL_ERROR "Unresolved catalog ${_key}: ${_arg_${_key}}")
    endif()
    set(${prefix}_${_key} "${_arg_${_key}}" PARENT_SCOPE)
  endforeach()
  set(${prefix}_FIELDS "${_allowed}" PARENT_SCOPE)
endfunction()

function(_aros_catalog_real_path path out_var)
  if(NOT IS_ABSOLUTE "${path}")
    message(FATAL_ERROR "Catalog path must be absolute: ${path}")
  endif()
  if(EXISTS "${path}")
    file(REAL_PATH "${path}" _real)
  elseif(IS_SYMLINK "${path}")
    message(FATAL_ERROR "Catalog path has a dangling symlink: ${path}")
  else()
    # Resolve existing ancestors without asking REAL_PATH to resolve a missing
    # output. This also checks symlinked output directories before generation.
    get_filename_component(_parent "${path}" DIRECTORY)
    get_filename_component(_name "${path}" NAME)
    _aros_catalog_real_path("${_parent}" _parent)
    set(_real "${_parent}/${_name}")
  endif()
  set(${out_var} "${_real}" PARENT_SCOPE)
endfunction()

function(_aros_catalog_static_input path)
  _aros_catalog_real_path("${path}" _real)
  file(REAL_PATH "${CMAKE_SOURCE_DIR}" _root)
  file(RELATIVE_PATH _relative "${_root}" "${_real}")
  if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}" OR _relative MATCHES "^\\.\\.(/|$)"
     OR IS_ABSOLUTE "${_relative}" OR path MATCHES "[$%*?]")
    message(FATAL_ERROR "Catalog requires an owned static source: ${path}")
  endif()
  foreach(_root IN ITEMS "${CMAKE_BINARY_DIR}" "${AROS_LEGACY_BUILD_DIR}")
    if(NOT _root)
      continue()
    endif()
    _aros_catalog_real_path("${_root}" _root)
    file(RELATIVE_PATH _relative "${_root}" "${_real}")
    if(NOT _relative MATCHES "^\\.\\.(/|$)" AND NOT IS_ABSOLUTE "${_relative}")
      message(FATAL_ERROR "Catalog requires an owned static source: ${path}")
    endif()
  endforeach()
endfunction()

function(_aros_catalog_claim_output output mmake)
  # Share static-data ownership so a copy rule cannot compete with FlexCat.
  string(SHA256 _key "${output}")
  get_property(_owner GLOBAL PROPERTY "AROS_STATIC_FILE_${_key}")
  if(_owner)
    message(FATAL_ERROR "Duplicate catalog producer for ${output}: ${_owner} and ${mmake}")
  endif()
  set_property(GLOBAL PROPERTY "AROS_STATIC_FILE_${_key}" "catalog:${mmake}")
endfunction()

function(_aros_catalog_native_output output root)
  _aros_catalog_real_path("${output}" _real)
  _aros_catalog_real_path("${root}" _root)
  file(RELATIVE_PATH _relative "${_root}" "${_real}")
  if(_relative MATCHES "^\\.\\.(/|$)" OR IS_ABSOLUTE "${_relative}" OR _relative STREQUAL "")
    message(FATAL_ERROR "Catalog output is outside the native build tree: ${output}")
  endif()
  if(AROS_LEGACY_BUILD_DIR)
    _aros_catalog_real_path("${AROS_LEGACY_BUILD_DIR}" _legacy)
    file(RELATIVE_PATH _relative "${_legacy}" "${_real}")
    if(NOT _relative MATCHES "^\\.\\.(/|$)" AND NOT IS_ABSOLUTE "${_relative}")
      message(FATAL_ERROR "Catalog output cannot use the legacy build tree: ${output}")
    endif()
  endif()
endfunction()

function(_aros_register_program_catalogs mmake out_target)
  set(${out_target} "" PARENT_SCOPE)
  set(_matches)
  foreach(_manifest IN LISTS AROS_MMAKE_MANIFESTS)
    file(STRINGS "${_manifest}" _rules REGEX "^[ \t]*%build_catalogs[ \t]")
    if(NOT _rules)
      continue()
    endif()
    _aros_read_mmake_logical_lines("${_manifest}" _lines)
    foreach(_line IN LISTS _lines)
      if(_line MATCHES "^%build_catalogs[ \t]+.*mmake=\"?([^ \t\"]+)" AND CMAKE_MATCH_1 STREQUAL mmake)
        list(APPEND _matches "${_manifest}")
      endif()
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES _matches)
  list(LENGTH _matches _count)
  if(_count EQUAL 0)
    return()
  elseif(NOT _count EQUAL 1)
    message(FATAL_ERROR "Ambiguous catalog producer for ${mmake}: ${_matches}")
  endif()
  string(SHA256 _key "${mmake}")
  set(_target "aros-catalogs-${_key}")
  set(${out_target} "${_target}" PARENT_SCOPE)
  if(TARGET "${_target}")
    return()
  endif()
  if(NOT TARGET flexcat)
    message(FATAL_ERROR "Native catalogs require the flexcat host tool")
  endif()
  get_target_property(_sd_dir flexcat AROS_FLEXCAT_SOURCE_DESCRIPTION_DIR)
  if(NOT _sd_dir)
    message(FATAL_ERROR "Native flexcat must publish its source description directory")
  endif()
  set(_AROS_MMAKE_VAR_AROSDIR "${AROS_NATIVE_SYSTEM_DIR}")
  set(_AROS_MMAKE_VAR_TOP "${CMAKE_BINARY_DIR}")
  set(_AROS_MMAKE_VAR_GENDIR "${AROS_NATIVE_OUTPUT_ROOT}/gen")
  set(_AROS_MMAKE_VAR_TOOLDIR "${_sd_dir}")
  set(_AROS_SELECTED_CATALOG_RULE "${mmake}")
  set(_AROS_RULE_MACRO_COLLECTOR _aros_collect_catalog_macro)
  _aros_collect_mmake_rules("${_matches}" _mm)
  list(LENGTH _mm_MACROS _count)
  if(NOT _count EQUAL 1)
    message(FATAL_ERROR "Expected one active catalog rule for ${mmake}")
  endif()
  _aros_program_prerequisites("${_matches}" "${mmake}" _prerequisites)
  if(_prerequisites)
    message(FATAL_ERROR "Unhandled catalog prerequisites for ${mmake}: ${_prerequisites}")
  endif()
  get_filename_component(_directory "${_matches}" DIRECTORY)
  file(RELATIVE_PATH _path "${CMAKE_SOURCE_DIR}" "${_directory}")
  set(_working_dir "${CMAKE_BINARY_DIR}/${_path}")
  get_filename_component(_srcdir "${_mm_MACRO_0_srcdir}" ABSOLUTE BASE_DIR "${_working_dir}")
  set(_description "${_mm_MACRO_0_description}")
  if(_description STREQUAL "")
    file(GLOB _cd CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE "${_srcdir}/*.cd")
    list(LENGTH _cd _count)
    if(NOT _count EQUAL 1)
      message(FATAL_ERROR "Catalog ${mmake} needs exactly one description file: ${_cd}")
    endif()
  else()
    get_filename_component(_cd "${_description}.cd" ABSOLUTE BASE_DIR "${_working_dir}")
  endif()
  _aros_catalog_static_input("${_cd}")
  set(_languages "${_mm_MACRO_0_catalogs}")
  if(_languages STREQUAL "")
    file(GLOB _translations CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE "${_srcdir}/*.ct")
    foreach(_translation IN LISTS _translations)
      get_filename_component(_language "${_translation}" NAME_WLE)
      list(APPEND _languages "${_language}")
    endforeach()
  else()
    separate_arguments(_languages UNIX_COMMAND "${_languages}")
  endif()
  list(REMOVE_DUPLICATES _languages)
  if(NOT _mm_MACRO_0_name MATCHES "^[A-Za-z0-9_+.-]+$" OR _mm_MACRO_0_name MATCHES "^[.]+$")
    message(FATAL_ERROR "Unsupported catalog name: ${_mm_MACRO_0_name}")
  endif()
  set(_inputs "${_cd}")
  set(_outputs)
  set(_builder "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/build_mmake_catalog.cmake")
  foreach(_language IN LISTS _languages)
    if(NOT _language MATCHES "^[A-Za-z0-9_+.-]+$" OR _language MATCHES "^[.]+$")
      message(FATAL_ERROR "Unsupported catalog language: ${_language}")
    endif()
    set(_ct "${_srcdir}/${_language}.ct")
    _aros_catalog_static_input("${_ct}")
    list(APPEND _inputs "${_ct}")
    _aros_static_output_path("${_mm_MACRO_0_dir}/${_language}/${_mm_MACRO_0_subdir}/${_mm_MACRO_0_name}.catalog" _output)
    _aros_catalog_native_output("${_output}" "${AROS_NATIVE_SYSTEM_DIR}")
    _aros_catalog_claim_output("${_output}" "${mmake}")
    add_custom_command(OUTPUT "${_output}"
      COMMAND "${CMAKE_COMMAND}" "-DFLEXCAT=$<TARGET_FILE:flexcat>" "-DCD_FILE=${_cd}"
        "-DCT_FILE=${_ct}" "-DLANGUAGE=${_language}" "-DOUTPUT_FILE=${_output}"
        -P "${_builder}"
      DEPENDS flexcat "${_cd}" "${_ct}" "${_matches}" "${_builder}"
        "${CMAKE_SOURCE_DIR}/config/make.tmpl"
      COMMENT "Generating ${_mm_MACRO_0_name} catalog for ${_language}" VERBATIM)
    list(APPEND _outputs "${_output}")
  endforeach()
  set(_header)
  if(NOT _mm_MACRO_0_source STREQUAL "")
    get_filename_component(_header "${_mm_MACRO_0_source}" ABSOLUTE BASE_DIR "${_working_dir}")
    _aros_catalog_native_output("${_header}" "${CMAKE_BINARY_DIR}")
    get_filename_component(_sd "${_mm_MACRO_0_sourcedescription}.sd" ABSOLUTE BASE_DIR "${_working_dir}")
    _aros_catalog_real_path("${_sd}" _real_sd)
    file(REAL_PATH "${_sd_dir}" _real_sd_dir)
    file(RELATIVE_PATH _relative "${_real_sd_dir}" "${_real_sd}")
    if(_relative MATCHES "^\\.\\.(/|$)" OR IS_ABSOLUTE "${_relative}")
      _aros_catalog_static_input("${_sd}")
    elseif(NOT EXISTS "${_sd}" OR IS_DIRECTORY "${_sd}")
      message(FATAL_ERROR "Missing native FlexCat source description: ${_sd}")
    endif()
    list(APPEND _inputs "${_sd}")
    _aros_catalog_claim_output("${_header}" "${mmake}")
    add_custom_command(OUTPUT "${_header}"
      COMMAND "${CMAKE_COMMAND}" "-DFLEXCAT=$<TARGET_FILE:flexcat>" "-DCD_FILE=${_cd}"
        "-DSD_FILE=${_sd}" "-DOUTPUT_FILE=${_header}" -P "${_builder}"
      DEPENDS flexcat "${_cd}" "${_sd}" "${_matches}" "${_builder}"
        "${CMAKE_SOURCE_DIR}/config/make.tmpl"
      COMMENT "Generating ${_mm_MACRO_0_name} catalog source" VERBATIM)
    list(APPEND _outputs "${_header}")
  endif()
  # A present file with a generating rule is not a static input we own.
  foreach(_id IN LISTS _mm_RULES)
    foreach(_declared IN LISTS _mm_${_id}_TARGETS)
      get_filename_component(_declared "${_declared}" ABSOLUTE BASE_DIR "${_working_dir}")
      foreach(_input IN LISTS _inputs)
        _aros_mmake_pattern_match("${_declared}" "${_input}" _match _stem)
        if(_match)
          message(FATAL_ERROR "Catalog input has an unsupported producer: ${_input}")
        endif()
      endforeach()
    endforeach()
  endforeach()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_matches}"
    "${CMAKE_SOURCE_DIR}/config/make.tmpl")
  add_custom_target("${_target}" DEPENDS ${_outputs})
  set_target_properties("${_target}" PROPERTIES FOLDER "aros/internal/packaging"
    AROS_CATALOG_OUTPUTS "${_outputs}" AROS_CATALOG_HEADER "${_header}")
endfunction()
