include_guard(GLOBAL)

function(_aros_collect_runtime_producers directory out_var)
  get_property(_targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  set(_producers)
  foreach(_target IN LISTS _targets)
    get_target_property(_output "${_target}" AROS_MODULE_OUTPUT)
    if(_output)
      list(APPEND _producers "${_target}")
    endif()
  endforeach()
  get_property(_subdirs DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(_dir IN LISTS _subdirs)
    _aros_collect_runtime_producers("${_dir}" _subproducers)
    list(APPEND _producers ${_subproducers})
  endforeach()
  set(${out_var} "${_producers}" PARENT_SCOPE)
endfunction()

# Call after producer registration. Resolve artifact paths, not guessed target
# names: suffix overrides and architecture-specific destinations matter.
function(aros_add_runtime_module_set target_name)
  cmake_parse_arguments(ARG "" "SYSTEM_DIR" "MODULE_PATHS" ${ARGN})
  if(NOT ARG_SYSTEM_DIR OR NOT ARG_MODULE_PATHS OR ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "aros_add_runtime_module_set requires SYSTEM_DIR and MODULE_PATHS")
  endif()
  _aros_collect_runtime_producers("${CMAKE_SOURCE_DIR}" _producers)
  foreach(_producer IN LISTS _producers)
    get_target_property(_output "${_producer}" AROS_MODULE_OUTPUT)
    get_filename_component(_output "${_output}" ABSOLUTE)
    string(SHA256 _key "${_output}")
    if(DEFINED _producer_${_key})
      message(FATAL_ERROR "Multiple native runtime producers for ${_output}")
    endif()
    set(_producer_${_key} "${_producer}")
  endforeach()
  set(_outputs)
  set(_deps)
  set(_missing)
  foreach(_path IN LISTS ARG_MODULE_PATHS)
    get_filename_component(_output "${_path}" ABSOLUTE BASE_DIR "${ARG_SYSTEM_DIR}")
    file(RELATIVE_PATH _relative "${ARG_SYSTEM_DIR}" "${_output}")
    if(IS_ABSOLUTE "${_path}" OR _relative MATCHES "^\\.\\.(/|$)" OR _path MATCHES "[@$]")
      message(FATAL_ERROR "Invalid runtime module path: ${_path}")
    endif()
    string(SHA256 _key "${_output}")
    if(NOT DEFINED _producer_${_key})
      list(APPEND _missing "${_path}")
    else()
      list(APPEND _deps "${_producer_${_key}}")
    endif()
    list(APPEND _outputs "${_output}")
  endforeach()
  if(_missing)
    # Partial profiles must still configure; an existing stale/legacy file is
    # never a substitute for a producer when this native aggregate is built.
    list(JOIN _missing ", " _missing_text)
    add_custom_target("${target_name}"
      COMMAND "${CMAKE_COMMAND}" -E echo "Missing native runtime producers: ${_missing_text}"
      COMMAND "${CMAKE_COMMAND}" -E false VERBATIM)
  else()
    add_custom_target("${target_name}" DEPENDS ${_outputs} ${_deps})
  endif()
  set_target_properties("${target_name}" PROPERTIES FOLDER "aros/runtime"
    AROS_RUNTIME_MODULE_OUTPUTS "${_outputs}" AROS_RUNTIME_MISSING_MODULES "${_missing}")
endfunction()
