include_guard(GLOBAL)

# Explicit configuration values are data, not Make or CMake code. Parse once
# per interpreter so graph discovery does not reread the file for every lookup.
function(_aros_native_config prefix)
  set(${prefix}_KEYS "" PARENT_SCOPE)
  if(NOT AROS_NATIVE_CONFIG_FILE)
    return()
  endif()
  string(SHA256 _id "${AROS_NATIVE_CONFIG_FILE}")
  set(_property "AROS_NATIVE_CONFIG_${_id}")
  get_property(_loaded GLOBAL PROPERTY "${_property}_LOADED")
  if(NOT _loaded)
    if(NOT IS_ABSOLUTE "${AROS_NATIVE_CONFIG_FILE}" OR
       NOT EXISTS "${AROS_NATIVE_CONFIG_FILE}" OR IS_DIRECTORY "${AROS_NATIVE_CONFIG_FILE}")
      message(FATAL_ERROR "AROS_NATIVE_CONFIG_FILE must name an existing absolute file: ${AROS_NATIVE_CONFIG_FILE}")
    endif()
    if(NOT CMAKE_SCRIPT_MODE_FILE)
      set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${AROS_NATIVE_CONFIG_FILE}")
    endif()
    file(READ "${AROS_NATIVE_CONFIG_FILE}" _text)
    string(REPLACE "\r\n" "\n" _text "${_text}")
    string(REPLACE ";" "\\;" _text "${_text}")
    string(REPLACE "\n" ";" _lines "${_text}")
    set(_keys)
    foreach(_line IN LISTS _lines)
      string(STRIP "${_line}" _line)
      if(_line STREQUAL "" OR _line MATCHES "^#")
        continue()
      endif()
      if(NOT _line MATCHES "^([A-Za-z_][A-Za-z0-9_]*)[ \t]*=[ \t]*(.*)$")
        message(FATAL_ERROR "Expected literal NAME=value in ${AROS_NATIVE_CONFIG_FILE}: ${_line}")
      endif()
      set(_name "${CMAKE_MATCH_1}")
      set(_value "${CMAKE_MATCH_2}")
      if(_name IN_LIST _keys)
        message(FATAL_ERROR "Duplicate native configuration value ${_name} in ${AROS_NATIVE_CONFIG_FILE}")
      endif()
      if(_value MATCHES "[$@#;\\\\\r]")
        message(FATAL_ERROR "Nonliteral native configuration value ${_name} in ${AROS_NATIVE_CONFIG_FILE}")
      endif()
      list(APPEND _keys "${_name}")
      set_property(GLOBAL PROPERTY "${_property}_VALUE_${_name}" "${_value}")
    endforeach()
    set_property(GLOBAL PROPERTY "${_property}_KEYS" "${_keys}")
    set_property(GLOBAL PROPERTY "${_property}_LOADED" TRUE)
  endif()
  get_property(_keys GLOBAL PROPERTY "${_property}_KEYS")
  foreach(_name IN LISTS _keys)
    get_property(_value GLOBAL PROPERTY "${_property}_VALUE_${_name}")
    set(${prefix}_VALUE_${_name} "${_value}" PARENT_SCOPE)
  endforeach()
  set(${prefix}_KEYS "${_keys}" PARENT_SCOPE)
endfunction()

function(_aros_native_config_value name out_value out_found)
  _aros_native_config(_native)
  set(${out_found} FALSE PARENT_SCOPE)
  if(name IN_LIST _native_KEYS)
    set(${out_value} "${_native_VALUE_${name}}" PARENT_SCOPE)
    set(${out_found} TRUE PARENT_SCOPE)
  endif()
endfunction()
