include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/AROSStaticTargets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeObjects.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeGraphArguments.cmake")

function(_aros_program_discovery_macro kind args prefix)
  set(${prefix}_FIELDS "" PARENT_SCOPE)
  if(kind MATCHES "^build_progs?$")
    _aros_mmake_graph_arguments("${args}" _arg)
    if(_arg_compiler STREQUAL "")
      set(_arg_compiler target)
    endif()
    if(NOT _arg_compiler MATCHES "^(target|host|kernel)$")
      message(FATAL_ERROR "Unknown program discovery compiler: ${_arg_compiler}")
    endif()
    set(${prefix}_FIELDS MMAKE COMPILER PARENT_SCOPE)
    set(${prefix}_MMAKE "${_arg_mmake}" PARENT_SCOPE)
    set(${prefix}_COMPILER "${_arg_compiler}" PARENT_SCOPE)
  endif()
endfunction()

# These helpers share only the current traversal's caches. A candidate match
# is not an export: local files and inactive declarations must not become edges.
macro(_aros_program_graph_read manifest out_rules)
  string(SHA256 _graph_read_key "${manifest}")
  set(_graph_read_rules "_parsed_${_graph_read_key}")
  if(NOT DEFINED ${_graph_read_rules}_RULES)
    message(VERBOSE "Reading program metadata: ${manifest}")
    _aros_collect_mmake_rules("${manifest}" "${_graph_read_rules}")
    foreach(_graph_read_id IN LISTS ${_graph_read_rules}_RULES)
      if(${_graph_read_rules}_${_graph_read_id}_EXPORTED)
        foreach(_graph_read_name IN LISTS ${_graph_read_rules}_${_graph_read_id}_TARGETS)
          string(SHA256 _graph_read_export_key "${_graph_read_name}")
          set(_graph_export_${_graph_read_export_key} TRUE)
        endforeach()
      endif()
    endforeach()
    foreach(_graph_read_id IN LISTS ${_graph_read_rules}_MACROS)
      string(SHA256 _graph_read_export_key "${${_graph_read_rules}_MACRO_${_graph_read_id}_MMAKE}")
      set(_graph_export_${_graph_read_export_key} TRUE)
    endforeach()
  endif()
  set(${out_rules} "${_graph_read_rules}")
endmacro()

macro(_aros_program_graph_has_export node out_var)
  string(SHA256 _graph_query_key "${node}")
  if(NOT DEFINED _graph_checked_${_graph_query_key})
    _aros_program_graph_candidates("${node}" _graph_query_candidates)
    foreach(_graph_query_manifest IN LISTS _graph_query_candidates)
      _aros_program_graph_read("${_graph_query_manifest}" _graph_query_rules)
    endforeach()
    set(_graph_checked_${_graph_query_key} TRUE)
  endif()
  set(${out_var} "${_graph_export_${_graph_query_key}}")
endmacro()

# Query the traversal's immutable identity index without rereading manifests
# for every ordinary-rule prerequisite.
function(_aros_program_graph_candidates node out_var)
  string(SHA256 _key "${node}")
  if(DEFINED _graph_candidates_${_key})
    set(${out_var} "${_graph_candidates_${_key}}" PARENT_SCOPE)
    return()
  endif()
  set(_candidates "${_candidates_${_key}}")
  foreach(_pattern_key IN LISTS _variable_patterns)
    if(node MATCHES "${_pattern_${_pattern_key}}")
      list(APPEND _candidates ${_pattern_manifests_${_pattern_key}})
    endif()
  endforeach()
  list(REMOVE_DUPLICATES _candidates)
  set(_graph_candidates_${_key} "${_candidates}" PARENT_SCOPE)
  set(${out_var} "${_candidates}" PARENT_SCOPE)
endfunction()

# This projects program producers from the exported metadata graph. Recipes
# and non-program macros are not executed or declared migrated by discovery.
function(aros_discover_program_graph prefix)
  cmake_parse_arguments(ARG "" "ROOT;CONFIG_FILE" "" ${ARGN})
  if(ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "Unexpected program discovery arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  if(NOT ARG_ROOT)
    if(NOT ARG_CONFIG_FILE)
      set(ARG_CONFIG_FILE "${CMAKE_SOURCE_DIR}/mmake.config.in")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ARG_CONFIG_FILE}")
    file(STRINGS "${ARG_CONFIG_FILE}" _defaults REGEX "^[ \t]*defaulttarget[ \t]+")
    list(LENGTH _defaults _count)
    if(NOT _count EQUAL 1 OR NOT _defaults MATCHES "^[ \t]*defaulttarget[ \t]+([A-Za-z0-9_.+-]+)[ \t]*$")
      message(FATAL_ERROR "Expected one defaulttarget in ${ARG_CONFIG_FILE}")
    endif()
    set(ARG_ROOT "${CMAKE_MATCH_1}")
  endif()

  # Index unevaluated identities once. Variable identities are only a
  # candidate filter; the rule reader still evaluates their active branches.
  set(_variable_patterns)
  foreach(_manifest IN LISTS AROS_MMAKE_MANIFESTS)
    string(SHA256 _file_key "${_manifest}")
    _aros_static_manifest_expressions("${_manifest}" _expressions_${_file_key})
    foreach(_expression IN LISTS _expressions_${_file_key})
      if(_expression MATCHES "\\$")
        _aros_static_target_pattern("${_expression}" _pattern)
        string(SHA256 _pattern_key "${_pattern}")
        set(_pattern_${_pattern_key} "${_pattern}")
        list(APPEND _variable_patterns "${_pattern_key}")
        list(APPEND _pattern_manifests_${_pattern_key} "${_manifest}")
      else()
        string(SHA256 _key "${_expression}")
        list(APPEND _candidates_${_key} "${_manifest}")
      endif()
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES _variable_patterns)
  foreach(_pattern_key IN LISTS _variable_patterns)
    list(REMOVE_DUPLICATES _pattern_manifests_${_pattern_key})
  endforeach()
  set(_AROS_RULE_MACRO_COLLECTOR _aros_program_discovery_macro)
  set(_AROS_RULE_GRAPH_ONLY TRUE)
  set(_queue "${ARG_ROOT}")
  set(_visited)
  set(_programs)
  while(_queue)
    list(POP_FRONT _queue _node)
    if(_node IN_LIST _visited)
      continue()
    endif()
    if(NOT _node MATCHES "^[A-Za-z0-9_.+-]+$")
      message(FATAL_ERROR "Unresolved program discovery edge: ${_node}")
    endif()
    list(APPEND _visited "${_node}")
    message(VERBOSE "Discovering program metadata: ${_node}")
    string(SHA256 _key "${_node}")
    _aros_program_graph_candidates("${_node}" _candidates)
    set(_dependencies)
    foreach(_manifest IN LISTS _candidates)
      _aros_program_graph_read("${_manifest}" _rules)
      foreach(_id IN LISTS ${_rules}_RULES)
        if(${_rules}_${_id}_EXPORTED AND _node IN_LIST ${_rules}_${_id}_TARGETS)
          # Ordinary exported rules may reference global aliases as well as
          # local files. Only exported identities join the discovery graph.
          if(${_rules}_${_id}_METADATA)
            list(APPEND _dependencies ${${_rules}_${_id}_DEPENDS})
          else()
            foreach(_dependency IN LISTS ${_rules}_${_id}_DEPENDS)
              _aros_program_graph_has_export("${_dependency}" _exports)
              if(_exports)
                list(APPEND _dependencies "${_dependency}")
              endif()
            endforeach()
          endif()
        endif()
      endforeach()
      foreach(_id IN LISTS ${_rules}_MACROS)
        if(${_rules}_MACRO_${_id}_MMAKE STREQUAL _node AND
           ${_rules}_MACRO_${_id}_COMPILER STREQUAL "target")
          list(APPEND _programs "${_node}")
        endif()
      endforeach()
    endforeach()
    list(REMOVE_DUPLICATES _dependencies)
    set(_edges_${_key} "${_dependencies}")
    list(APPEND _queue ${_dependencies})
  endwhile()

  # This is reachability, not build ordering. Aggregate metadata may cycle;
  # retain every edge rather than dropping traversal-dependent backedges.
  # Concrete producer/prerequisite registration still validates build cycles.
  list(REMOVE_DUPLICATES _programs)
  list(SORT _programs)
  set(${prefix}_ROOT "${ARG_ROOT}" PARENT_SCOPE)
  set(${prefix}_PROGRAMS "${_programs}" PARENT_SCOPE)
  set(${prefix}_NODES "${_visited}" PARENT_SCOPE)
  foreach(_node IN LISTS _visited)
    string(SHA256 _key "${_node}")
    set(${prefix}_DEPENDS_${_key} "${_edges_${_key}}" PARENT_SCOPE)
  endforeach()
endfunction()

function(_aros_program_graph_prerequisites target_name dependencies)
  get_target_property(_parts "${target_name}" AROS_PROGRAM_PART_TARGETS)
  if(_parts)
    foreach(_part IN LISTS _parts)
      _aros_program_graph_prerequisites("${_part}" "${dependencies}")
    endforeach()
  else()
    get_target_property(_existing "${target_name}" AROS_PROGRAM_PREREQUISITES)
    if(NOT _existing)
      set(_existing)
    endif()
    list(APPEND _existing ${dependencies})
    list(REMOVE_DUPLICATES _existing)
    set_target_properties("${target_name}" PROPERTIES AROS_PROGRAM_PREREQUISITES "${_existing}")
  endif()
endfunction()

function(_aros_program_graph_write path content)
  if(EXISTS "${path}")
    file(READ "${path}" _previous)
    if(_previous STREQUAL content)
      return()
    endif()
  endif()
  # Diagnostics and context values are data, not configure_file templates.
  file(WRITE "${path}" "${content}")
endfunction()

function(aros_add_program_graph target_name)
  cmake_parse_arguments(ARG "" "ROOT" "" ${ARGN})
  if(ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "Unexpected program graph arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  set(_dir "${CMAKE_CURRENT_BINARY_DIR}/program-discovery/${target_name}")
  set(_context "${_dir}/context.cmake")
  set(_metadata "${_dir}/graph.cmake")
  set(_content "")
  foreach(_variable IN ITEMS CMAKE_SOURCE_DIR CMAKE_BINARY_DIR AROS_TARGET AROS_TARGET_FAMILY
      AROS_LEGACY_BUILD_DIR AROS_MMAKE_MANIFESTS AROS_NATIVE_CONFIG_FILE)
    string(APPEND _content "set(${_variable} [==[${${_variable}}]==])\n")
  endforeach()
  string(APPEND _content "set(PROGRAM_GRAPH_ROOT [==[${ARG_ROOT}]==])\n")
  _aros_program_graph_write("${_context}" "${_content}")
  set(_collector "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/collect_program_graph.cmake")
  set(_config_files "${CMAKE_SOURCE_DIR}/mmake.config.in"
    ${AROS_NATIVE_CONFIG_FILE}
    "${AROS_LEGACY_BUILD_DIR}/config/make.cfg"
    "${AROS_LEGACY_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/target.cfg"
    "${AROS_LEGACY_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/compiler.cfg"
    "${AROS_LEGACY_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/build.cfg")
  file(GLOB _existing_config CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE ${_config_files})
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    ${AROS_MMAKE_MANIFESTS} ${_existing_config} "${_collector}"
    "${CMAKE_CURRENT_FUNCTION_LIST_FILE}")
  # Discovery is transactional: an unsupported manifest blocks the aggregate,
  # never a silently truncated list or an adopted output from an older graph.
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DCONTEXT_FILE=${_context}"
    "-DOUTPUT_FILE=${_metadata}" -P "${_collector}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
  if(NOT _result EQUAL 0)
    set(_diagnostic "Program graph discovery failed; no partial aggregate was registered.\n${_stdout}${_stderr}")
    _aros_program_graph_write("${_dir}/failure.txt" "${_diagnostic}")
    message(WARNING "${target_name} is blocked; see ${_dir}/failure.txt")
    add_custom_target("${target_name}"
      COMMAND "${CMAKE_COMMAND}" "-DDIAGNOSTIC_FILE=${_dir}/failure.txt"
        -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/fail_program_graph.cmake" VERBATIM)
  else()
    include("${_metadata}")
    if(NOT PROGRAM_GRAPH_PROGRAMS)
      message(FATAL_ERROR "No target programs reachable from metadata root ${PROGRAM_GRAPH_ROOT}")
    endif()
    add_custom_target("${target_name}")
    foreach(_rule IN LISTS PROGRAM_GRAPH_PROGRAMS)
      set(_target "aros-programs-${_rule}-native")
      aros_add_mmake_programs("${_target}" MMAKE_NAME "${_rule}")
      string(SHA256 _key "${_rule}")
      _aros_program_graph_prerequisites("${_target}" "${PROGRAM_GRAPH_DEPENDS_${_key}}")
      add_dependencies("${target_name}" "${_target}")
    endforeach()
    set_target_properties("${target_name}" PROPERTIES
      AROS_PROGRAM_GRAPH_ROOT "${PROGRAM_GRAPH_ROOT}"
      AROS_PROGRAM_GRAPH_RULES "${PROGRAM_GRAPH_PROGRAMS}")
  endif()
  set_target_properties("${target_name}" PROPERTIES FOLDER "aros/programs")
endfunction()
