cmake_minimum_required(VERSION 3.20)
include("${CONTEXT_FILE}")
include("${METADATA_FILE}")
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeBuild.cmake")
_aros_find_toolchain_program(gcc _cc)
if(NOT _cc)
  message(FATAL_ERROR "Missing target compiler in ${AROS_TOOLCHAIN_DIR}")
endif()
get_filename_component(_outdir "${OUTPUT_FILE}" DIRECTORY)
if(MODE STREQUAL "COMPILE")
  foreach(_report IN LISTS AROS_PROGRAM_FETCH_REPORTS)
    execute_process(COMMAND "${AROS_PROGRAM_FETCH_PYTHON}"
      "${CMAKE_CURRENT_LIST_DIR}/build_mmake_fetch.py" --verify "${_report}"
      COMMAND_ERROR_IS_FATAL ANY)
  endforeach()
  include("${CMAKE_CURRENT_LIST_DIR}/AROSCatalogTargets.cmake")
  set(AROS_LEGACY_BUILD_DIR "${AROS_CONFIG_BUILD_DIR}")
  if(NOT DEPFILE)
    set(DEPFILE "${OUTPUT_FILE}.d")
  endif()
  # Recheck before invoking the compiler: output directories may have become
  # symlinks since configuration. Depfiles are writable compiler outputs too.
  foreach(_path IN ITEMS "${OUTPUT_FILE}" "${DEPFILE}")
    _aros_catalog_native_output("${_path}" "${AROS_BINARY_DIR}")
  endforeach()
  get_filename_component(_depdir "${DEPFILE}" DIRECTORY)
  file(MAKE_DIRECTORY "${_outdir}" "${_depdir}")
  execute_process(COMMAND "${_cc}" -print-file-name=include
    OUTPUT_VARIABLE _builtin OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
  set(_command "${_cc}" "--sysroot=${AROS_NATIVE_DEVELOPER_DIR}"
    ${MMAKE_PROGRAM_COMPILE_FLAGS} -nostdinc -isystem "${_builtin}")
  foreach(_sdk IN LISTS MMAKE_PROGRAM_USESDKS)
    list(APPEND _command "-I${AROS_NATIVE_BUILD_SDKS_DIR}/${_sdk}/include")
  endforeach()
  list(APPEND _command -isystem "${AROS_NATIVE_INCLUDE_DIR}"
    -idirafter "${AROS_NATIVE_INCLUDE_DIR}/aros/posixc"
    -idirafter "${AROS_NATIVE_INCLUDE_DIR}/aros/stdc")
  get_filename_component(_srcdir "${SOURCE_FILE}" DIRECTORY)
  list(APPEND _command -iquote "${_srcdir}" -MD -MF "${DEPFILE}"
    -MT "${OUTPUT_FILE}" -c "${SOURCE_FILE}" -o "${OUTPUT_FILE}")
elseif(MODE STREQUAL "LINK")
  file(MAKE_DIRECTORY "${_outdir}")
  if(NOT MAP_FILE)
    get_filename_component(_metadata_dir "${METADATA_FILE}" DIRECTORY)
    get_filename_component(_name "${OUTPUT_FILE}" NAME)
    set(MAP_FILE "${_metadata_dir}/link/${_name}.map")
  endif()
  get_filename_component(_mapdir "${MAP_FILE}" DIRECTORY)
  file(MAKE_DIRECTORY "${_mapdir}")
  string(REPLACE "|" ";" _objects "${OBJECT_FILES}")
  string(REPLACE "|" ";" _startup "${STARTUP_OBJECTS}")
  foreach(_object IN LISTS _startup)
    if(NOT EXISTS "${_object}")
      message(FATAL_ERROR "Missing native startup object: ${_object}")
    endif()
  endforeach()
  set(_command "${_cc}" "--sysroot=${AROS_NATIVE_DEVELOPER_DIR}"
    "-B${AROS_NATIVE_PUBLIC_LIB_DIR}/" ${MMAKE_PROGRAM_LINK_OPTIONS} ${_objects} -o "${OUTPUT_FILE}"
    "-Wl,-Map,${MAP_FILE}" ${MMAKE_PROGRAM_LINK_FLAGS} "-L${AROS_NATIVE_PUBLIC_LIB_DIR}")
  foreach(_sdk IN LISTS MMAKE_PROGRAM_USESDKS)
    list(APPEND _command "-L${AROS_NATIVE_BUILD_SDKS_DIR}/${_sdk}/lib")
  endforeach()
  foreach(_lib IN LISTS MMAKE_PROGRAM_USELIBS)
    list(APPEND _command "-l${_lib}")
  endforeach()
  list(APPEND _command ${MMAKE_PROGRAM_ARCH_LIBS})
else()
  message(FATAL_ERROR "Unknown program build mode: ${MODE}")
endif()
execute_process(COMMAND ${_command} RESULT_VARIABLE _result COMMAND_ECHO STDOUT)
if(NOT _result EQUAL 0)
  file(REMOVE "${OUTPUT_FILE}")
  message(FATAL_ERROR "Program ${MODE} failed (${_result})")
endif()
if(MODE STREQUAL "LINK")
  execute_process(COMMAND ${_command} -print-libgcc-file-name OUTPUT_VARIABLE _libgcc
    OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
  file(REAL_PATH "${_libgcc}" _libgcc)
  set(_owned_objects)
  foreach(_object IN LISTS _objects _startup)
    file(REAL_PATH "${_object}" _object)
    list(APPEND _owned_objects "${_object}")
  endforeach()
  file(STRINGS "${MAP_FILE}" _object_loads REGEX "^LOAD .*\\.o$")
  foreach(_load IN LISTS _object_loads)
    string(REGEX REPLACE "^LOAD " "" _object "${_load}")
    file(REAL_PATH "${_object}" _object)
    if(NOT _object IN_LIST _owned_objects)
      file(REMOVE "${OUTPUT_FILE}")
      message(FATAL_ERROR "Program linked an unowned startup/object input: ${_object}")
    endif()
  endforeach()
  file(STRINGS "${MAP_FILE}" _loads REGEX "^LOAD .*\\.a$")
  foreach(_load IN LISTS _loads)
    string(REGEX REPLACE "^LOAD " "" _archive "${_load}")
    file(REAL_PATH "${_archive}" _archive)
    if(_archive STREQUAL _libgcc)
      continue()
    endif()
    set(_native FALSE)
    foreach(_root IN ITEMS "${AROS_NATIVE_PUBLIC_LIB_DIR}" "${AROS_NATIVE_BUILD_SDKS_DIR}")
      file(REAL_PATH "${_root}" _root)
      file(RELATIVE_PATH _relative "${_root}" "${_archive}")
      if(NOT _relative MATCHES "^\\.\\.(/|$)" AND NOT IS_ABSOLUTE "${_relative}")
        set(_native TRUE)
        break()
      endif()
    endforeach()
    if(NOT _native)
      file(REMOVE "${OUTPUT_FILE}")
      message(FATAL_ERROR "Program linked an archive outside the native SDK: ${_archive}")
    endif()
  endforeach()
endif()
if(MODE STREQUAL "LINK" AND MMAKE_PROGRAM_STRIP)
  _aros_find_toolchain_program(strip _strip)
  if(NOT _strip)
    file(REMOVE "${OUTPUT_FILE}")
    message(FATAL_ERROR "Missing target strip in ${AROS_TOOLCHAIN_DIR}")
  endif()
  execute_process(COMMAND "${_strip}" ${MMAKE_PROGRAM_STRIP_FLAGS} "${OUTPUT_FILE}"
    RESULT_VARIABLE _result COMMAND_ECHO STDOUT)
  if(NOT _result EQUAL 0)
    file(REMOVE "${OUTPUT_FILE}")
    message(FATAL_ERROR "Program strip failed (${_result})")
  endif()
endif()
