cmake_minimum_required(VERSION 3.20)
include("${CONTEXT_FILE}")
include("${CMAKE_CURRENT_LIST_DIR}/AROSCatalogTargets.cmake")
if(DIRECTORY_ONLY)
  _aros_catalog_native_output("${AROS_NATIVE_OUTPUT_ROOT}" "${CMAKE_BINARY_DIR}")
  _aros_catalog_native_output("${DIRECTORY_ONLY}" "${AROS_NATIVE_OUTPUT_ROOT}")
  _aros_catalog_native_output("${STAMP_FILE}" "${CMAKE_BINARY_DIR}")
  _aros_catalog_real_path("${DIRECTORY_ONLY}" _real)
  if(NOT _real STREQUAL DIRECTORY_REAL)
    message(FATAL_ERROR "Text-transform directory changed through a symlink")
  endif()
  get_filename_component(_stamp_dir "${STAMP_FILE}" DIRECTORY)
  file(MAKE_DIRECTORY "${_stamp_dir}" "${DIRECTORY_ONLY}")
  file(TOUCH "${STAMP_FILE}")
  return()
endif()
set(_owned FALSE)
foreach(_report IN LISTS TRANSFORM_reports)
  execute_process(COMMAND "${TRANSFORM_python}" "${CMAKE_CURRENT_LIST_DIR}/build_mmake_fetch.py"
    --verify "${_report}" COMMAND_ERROR_IS_FATAL ANY)
  file(READ "${_report}" _receipt)
  string(JSON _destination GET "${_receipt}" destination)
  string(JSON _count LENGTH "${_receipt}" files)
  if(_count GREATER 0)
    math(EXPR _last "${_count} - 1")
    foreach(_index RANGE 0 ${_last})
      string(JSON _file GET "${_receipt}" files ${_index})
      if("${_destination}/${_file}" STREQUAL TRANSFORM_source)
        set(_owned TRUE)
      endif()
    endforeach()
  endif()
endforeach()
if(NOT TRANSFORM_fetched)
  _aros_catalog_static_input("${TRANSFORM_source}")
elseif(NOT _owned)
  message(FATAL_ERROR "Text-transform input lost fetch ownership: ${TRANSFORM_source}")
endif()
_aros_catalog_native_output("${AROS_NATIVE_OUTPUT_ROOT}" "${CMAKE_BINARY_DIR}")
_aros_catalog_native_output("${TRANSFORM_output}" "${AROS_NATIVE_OUTPUT_ROOT}")
_aros_catalog_real_path("${TRANSFORM_output}" _real)
if(NOT _real STREQUAL TRANSFORM_real_output)
  message(FATAL_ERROR "Text-transform output changed through a symlink")
endif()
foreach(_dir IN LISTS TRANSFORM_directories)
  _aros_catalog_native_output("${_dir}" "${AROS_NATIVE_OUTPUT_ROOT}")
endforeach()
get_filename_component(_directory "${TRANSFORM_output}" DIRECTORY)
file(MAKE_DIRECTORY "${_directory}" ${TRANSFORM_directories})
set(_arguments)
foreach(_expression IN LISTS TRANSFORM_expressions)
  list(APPEND _arguments -e "${_expression}")
endforeach()
string(RANDOM LENGTH 12 ALPHABET abcdef0123456789 _id)
set(_temporary "${TRANSFORM_output}.${_id}.tmp")
execute_process(COMMAND "${TRANSFORM_tool}" ${_arguments} "${TRANSFORM_source}"
  OUTPUT_FILE "${_temporary}" RESULT_VARIABLE _result ERROR_VARIABLE _error)
if(NOT _result EQUAL 0)
  file(REMOVE "${_temporary}")
  message(FATAL_ERROR "Text transform failed: ${_error}")
endif()
file(RENAME "${_temporary}" "${TRANSFORM_output}")
