cmake_minimum_required(VERSION 3.20)
foreach(_required IN ITEMS FLEXCAT CD_FILE OUTPUT_FILE)
  if(NOT ${_required})
    message(FATAL_ERROR "${_required} is required")
  endif()
endforeach()
get_filename_component(_directory "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${_directory}")
set(_args "${CD_FILE}")
set(_limit 1)
if(CT_FILE)
  # Match build_catalogs in config/make.tmpl, including warning exit status.
  if(LANGUAGE STREQUAL "russian")
    list(PREPEND _args win1251toamiga1251)
  endif()
  list(APPEND _args "${CT_FILE}" "CATALOG=${OUTPUT_FILE}")
  set(_limit 10)
elseif(SD_FILE)
  list(APPEND _args "${OUTPUT_FILE}=${SD_FILE}")
else()
  message(FATAL_ERROR "CT_FILE or SD_FILE is required")
endif()
# Source templates can embed the output filename (%o), so use its final name.
# Removing any old result also detects generators that succeed without writing.
file(REMOVE "${OUTPUT_FILE}")
execute_process(COMMAND "${FLEXCAT}" ${_args} RESULT_VARIABLE _result COMMAND_ECHO STDOUT)
if(NOT _result MATCHES "^[0-9]+$" OR _result GREATER_EQUAL _limit OR NOT EXISTS "${OUTPUT_FILE}")
  file(REMOVE "${OUTPUT_FILE}")
  message(FATAL_ERROR "Catalog generation failed (${_result}): ${OUTPUT_FILE}")
endif()
