cmake_minimum_required(VERSION 3.20)
include("${CONTEXT_FILE}")
include("${CMAKE_CURRENT_LIST_DIR}/AROSCatalogTargets.cmake")
foreach(_report IN LISTS COPY_reports)
  execute_process(COMMAND "${COPY_python}" "${CMAKE_CURRENT_LIST_DIR}/build_mmake_fetch.py"
    --verify "${_report}" COMMAND_ERROR_IS_FATAL ANY)
endforeach()
if(NOT COPY_fetched)
  _aros_catalog_static_input("${COPY_source}")
endif()
_aros_catalog_native_output("${COPY_root}" "${CMAKE_BINARY_DIR}")
_aros_catalog_native_output("${COPY_output}" "${COPY_root}")
_aros_catalog_real_path("${COPY_output}" _real_output)
if(NOT _real_output STREQUAL COPY_real_output)
  message(FATAL_ERROR "Include output changed through a symlink: ${COPY_output}")
endif()
get_filename_component(_directory "${COPY_output}" DIRECTORY)
file(MAKE_DIRECTORY "${_directory}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${COPY_source}" "${COPY_output}"
  COMMAND_ERROR_IS_FATAL ANY)
