if(NOT DEFINED AROS_SOURCE_DIR
   OR NOT DEFINED AROS_BINARY_DIR
   OR NOT DEFINED AROS_CONFIG_BUILD_DIR
   OR NOT DEFINED AROS_TARGET
   OR NOT DEFINED AROS_TOOLCHAIN_DIR
   OR NOT DEFINED AROS_TOOLCHAIN_PREFIX
   OR NOT DEFINED AROS_SYSROOT
   OR NOT DEFINED AROS_NATIVE_INCLUDE_DIR
   OR NOT DEFINED AROS_NATIVE_PUBLIC_LIB_DIR
   OR NOT DEFINED AROS_NATIVE_PRIVATE_LIB_DIR
   OR NOT DEFINED AROS_NATIVE_REL_LIB_DIR
   OR NOT DEFINED AROS_NATIVE_BUILD_SDKS_DIR
   OR NOT DEFINED LINKLIB_PATH
   OR NOT DEFINED LINKLIB_MMAKEFILE
   OR NOT DEFINED LINKLIB_NAME
   OR NOT DEFINED LINKLIB_OUTPUT
   OR NOT DEFINED LINKLIB_OBJ_DIR)
  message(FATAL_ERROR "Missing required generic mmake linklib build parameters")
endif()

function(_aros_remove_empty_entries var_name)
  if(NOT DEFINED ${var_name} OR "${${var_name}}" STREQUAL "")
    set(${var_name} "" PARENT_SCOPE)
    return()
  endif()

  set(_filtered_values)
  foreach(_value IN LISTS ${var_name})
    string(STRIP "${_value}" _stripped_value)
    if(NOT _stripped_value STREQUAL "")
      list(APPEND _filtered_values "${_stripped_value}")
    endif()
  endforeach()
  set(${var_name} "${_filtered_values}" PARENT_SCOPE)
endfunction()

function(_aros_remove_token_entries var_name)
  if(NOT DEFINED ${var_name} OR "${${var_name}}" STREQUAL "")
    set(${var_name} "" PARENT_SCOPE)
    return()
  endif()

  set(_filtered_values)
  foreach(_value IN LISTS ${var_name})
    string(STRIP "${_value}" _stripped_value)
    set(_keep_value TRUE)
    foreach(_remove_token IN LISTS ARGN)
      if(_stripped_value STREQUAL "${_remove_token}")
        set(_keep_value FALSE)
        break()
      endif()
    endforeach()
    if(_keep_value)
      list(APPEND _filtered_values "${_stripped_value}")
    endif()
  endforeach()
  set(${var_name} "${_filtered_values}" PARENT_SCOPE)
endfunction()

function(_aros_unwrap_strip_expression input_value out_var)
  set(_value "${input_value}")
  if(_value MATCHES "^\\$\\(strip[ \t]*(.*)\\)$")
    set(_value "${CMAKE_MATCH_1}")
  endif()
  string(STRIP "${_value}" _value)
  set(${out_var} "${_value}" PARENT_SCOPE)
endfunction()

function(_aros_read_mmake_logical_lines file_path out_var)
  file(STRINGS "${file_path}" _raw_lines)
  set(_logical_lines)
  set(_current "")

  foreach(_raw_line IN LISTS _raw_lines)
    string(REGEX REPLACE "[\r\n]+$" "" _line "${_raw_line}")
    if(_current STREQUAL "")
      set(_current "${_line}")
    else()
      string(APPEND _current " " "${_line}")
    endif()

    if(_current MATCHES "\\\\[ \t]*$")
      string(REGEX REPLACE "\\\\[ \t]*$" "" _current "${_current}")
      string(STRIP "${_current}" _current)
    else()
      string(STRIP "${_current}" _current)
      if(NOT _current STREQUAL "")
        string(REPLACE ";" "\\;" _current "${_current}")
        list(APPEND _logical_lines "${_current}")
      endif()
      set(_current "")
    endif()
  endforeach()

  if(NOT _current STREQUAL "")
    string(STRIP "${_current}" _current)
    string(REPLACE ";" "\\;" _current "${_current}")
    list(APPEND _logical_lines "${_current}")
  endif()

  set(${out_var} "${_logical_lines}" PARENT_SCOPE)
endfunction()

function(_aros_get_target_context)
  string(REPLACE "-" ";" _parts "${AROS_TARGET}")
  list(GET _parts 0 _arch)
  list(GET _parts 1 _cpu)
  set(_variant "")
  list(LENGTH _parts _parts_len)
  if(_parts_len GREATER 2)
    list(SUBLIST _parts 2 -1 _variant_parts)
    string(REPLACE ";" "-" _variant "${_variant_parts}")
  endif()

  set(_target_cfg "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/target.cfg")
  file(STRINGS "${_target_cfg}" _family_line REGEX "^FAMILY[ \t]*:=")
  if(_family_line)
    string(REGEX REPLACE "^FAMILY[ \t]*:=[ \t]*" "" _family "${_family_line}")
    string(STRIP "${_family}" _family)
  else()
    set(_family "${_arch}")
  endif()

  set(AROS_MODULE_CONTEXT_ARCH "${_arch}" PARENT_SCOPE)
  set(AROS_MODULE_CONTEXT_CPU "${_cpu}" PARENT_SCOPE)
  set(AROS_MODULE_CONTEXT_VARIANT "${_variant}" PARENT_SCOPE)
  set(AROS_MODULE_CONTEXT_FAMILY "${_family}" PARENT_SCOPE)
  set(AROS_MODULE_CONTEXT_PLATFORM "${AROS_TARGET}" PARENT_SCOPE)
endfunction()

function(_aros_extract_make_call input_value call_name out_prefix out_body out_suffix)
  string(FIND "${input_value}" "$(${call_name} " _call_start)
  if(_call_start EQUAL -1)
    set(${out_prefix} "${input_value}" PARENT_SCOPE)
    set(${out_body} "" PARENT_SCOPE)
    set(${out_suffix} "" PARENT_SCOPE)
    return()
  endif()

  string(LENGTH "${input_value}" _input_len)
  set(_depth 0)
  set(_call_end -1)
  set(_index "${_call_start}")
  while(_index LESS _input_len)
    math(EXPR _remaining "${_input_len} - ${_index}")
    if(_remaining GREATER 1)
      string(SUBSTRING "${input_value}" ${_index} 2 _pair)
    else()
      set(_pair "")
    endif()

    if(_pair STREQUAL "$(")
      math(EXPR _depth "${_depth} + 1")
      math(EXPR _index "${_index} + 2")
      continue()
    endif()

    string(SUBSTRING "${input_value}" ${_index} 1 _char)
    if(_char STREQUAL ")" AND _depth GREATER 0)
      math(EXPR _depth "${_depth} - 1")
      if(_depth EQUAL 0)
        set(_call_end "${_index}")
        break()
      endif()
    endif()

    math(EXPR _index "${_index} + 1")
  endwhile()

  if(_call_end EQUAL -1)
    message(FATAL_ERROR "Unterminated \$(${call_name} ...) expression: ${input_value}")
  endif()

  if(_call_start GREATER 0)
    string(SUBSTRING "${input_value}" 0 ${_call_start} _prefix)
  else()
    set(_prefix "")
  endif()

  math(EXPR _body_start "${_call_start} + 2")
  math(EXPR _body_len "${_call_end} - ${_body_start}")
  string(SUBSTRING "${input_value}" ${_body_start} ${_body_len} _body)

  math(EXPR _suffix_start "${_call_end} + 1")
  if(_suffix_start LESS _input_len)
    math(EXPR _suffix_len "${_input_len} - ${_suffix_start}")
    string(SUBSTRING "${input_value}" ${_suffix_start} ${_suffix_len} _suffix)
  else()
    set(_suffix "")
  endif()

  set(${out_prefix} "${_prefix}" PARENT_SCOPE)
  set(${out_body} "${_body}" PARENT_SCOPE)
  set(${out_suffix} "${_suffix}" PARENT_SCOPE)
endfunction()

function(_aros_split_make_arguments input_value out_var)
  set(_arguments)
  set(_current "")
  set(_depth 0)
  string(LENGTH "${input_value}" _input_len)
  set(_index 0)

  while(_index LESS _input_len)
    math(EXPR _remaining "${_input_len} - ${_index}")
    if(_remaining GREATER 1)
      string(SUBSTRING "${input_value}" ${_index} 2 _pair)
    else()
      set(_pair "")
    endif()

    if(_pair STREQUAL "$(")
      math(EXPR _depth "${_depth} + 1")
      string(APPEND _current "$(")
      math(EXPR _index "${_index} + 2")
      continue()
    endif()

    string(SUBSTRING "${input_value}" ${_index} 1 _char)
    if(_char STREQUAL ")" AND _depth GREATER 0)
      math(EXPR _depth "${_depth} - 1")
      string(APPEND _current "${_char}")
    elseif(_char STREQUAL "," AND _depth EQUAL 0)
      string(STRIP "${_current}" _current)
      list(APPEND _arguments "${_current}")
      set(_current "")
    else()
      string(APPEND _current "${_char}")
    endif()

    math(EXPR _index "${_index} + 1")
  endwhile()

  string(STRIP "${_current}" _current)
  list(APPEND _arguments "${_current}")
  set(${out_var} "${_arguments}" PARENT_SCOPE)
endfunction()

function(_aros_expand_make_tokens input_value out_var)
  _aros_get_target_context()
  set(_expanded "${input_value}")
  set(_make_gendir "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen")
  set(_limit 100)
  while(_limit GREATER 0)
    math(EXPR _limit "${_limit} - 1")
    _aros_extract_make_call("${_expanded}" "foreach" _foreach_prefix _foreach_body _foreach_suffix)
    if(NOT _foreach_body STREQUAL "")
      string(REGEX REPLACE "^foreach[ \t]+" "" _foreach_arg_string "${_foreach_body}")
      _aros_split_make_arguments("${_foreach_arg_string}" _foreach_args)
      list(LENGTH _foreach_args _foreach_arg_count)
      if(NOT _foreach_arg_count EQUAL 3)
        message(FATAL_ERROR "Unsupported foreach expression in ${LINKLIB_MMAKEFILE}: ${_foreach_body}")
      endif()

      list(GET _foreach_args 0 _foreach_var)
      list(GET _foreach_args 1 _foreach_list_expr)
      list(GET _foreach_args 2 _foreach_text_expr)
      string(STRIP "${_foreach_var}" _foreach_var)

      _aros_expand_make_tokens("${_foreach_list_expr}" _foreach_list_expanded)
      separate_arguments(_foreach_values NATIVE_COMMAND "${_foreach_list_expanded}")

      set(_foreach_saved_defined FALSE)
      if(DEFINED _AROS_MMAKE_VAR_${_foreach_var})
        set(_foreach_saved_defined TRUE)
        set(_foreach_saved_value "${_AROS_MMAKE_VAR_${_foreach_var}}")
      endif()

      set(_foreach_result "")
      foreach(_foreach_value IN LISTS _foreach_values)
        set(_AROS_MMAKE_VAR_${_foreach_var} "${_foreach_value}")
        _aros_expand_make_tokens("${_foreach_text_expr}" _foreach_item)
        string(STRIP "${_foreach_item}" _foreach_item)
        if(_foreach_item STREQUAL "")
          continue()
        endif()
        if(_foreach_result STREQUAL "")
          set(_foreach_result "${_foreach_item}")
        else()
          string(APPEND _foreach_result " " "${_foreach_item}")
        endif()
      endforeach()

      if(_foreach_saved_defined)
        set(_AROS_MMAKE_VAR_${_foreach_var} "${_foreach_saved_value}")
      else()
        unset(_AROS_MMAKE_VAR_${_foreach_var})
      endif()

      set(_expanded "${_foreach_prefix}${_foreach_result}${_foreach_suffix}")
      continue()
    endif()

    _aros_extract_make_call("${_expanded}" "shell" _shell_prefix _shell_body _shell_suffix)
    if(NOT _shell_body STREQUAL "")
      string(REGEX REPLACE "^shell[ \t]+" "" _shell_command "${_shell_body}")
      _aros_expand_make_tokens("${_shell_command}" _shell_command)
      execute_process(
        COMMAND /bin/sh -c "${_shell_command}"
        OUTPUT_VARIABLE _shell_output
        OUTPUT_STRIP_TRAILING_WHITESPACE
      )
      string(REPLACE "\n" " " _shell_output "${_shell_output}")
      set(_expanded "${_shell_prefix}${_shell_output}${_shell_suffix}")
      continue()
    endif()

    string(REGEX MATCH "\\$\\(([A-Za-z0-9_]+)\\)" _match "${_expanded}")
    if(NOT _match)
      break()
    endif()

    set(_var_name "${CMAKE_MATCH_1}")
    if(DEFINED _AROS_MMAKE_VAR_${_var_name})
      set(_replacement "${_AROS_MMAKE_VAR_${_var_name}}")
    elseif(_var_name STREQUAL "ARCH")
      set(_replacement "${AROS_MODULE_CONTEXT_ARCH}")
    elseif(_var_name STREQUAL "CPU")
      set(_replacement "${AROS_MODULE_CONTEXT_CPU}")
    elseif(_var_name STREQUAL "FAMILY")
      set(_replacement "${AROS_MODULE_CONTEXT_FAMILY}")
    elseif(_var_name STREQUAL "AROS_TARGET_ARCH")
      set(_replacement "${AROS_MODULE_CONTEXT_ARCH}")
    elseif(_var_name STREQUAL "AROS_TARGET_CPU")
      set(_replacement "${AROS_MODULE_CONTEXT_CPU}")
    elseif(_var_name STREQUAL "AROS_TARGET_FAMILY")
      set(_replacement "${AROS_MODULE_CONTEXT_FAMILY}")
    elseif(_var_name STREQUAL "AROS_TARGET_PLATFORM")
      set(_replacement "${AROS_MODULE_CONTEXT_PLATFORM}")
    elseif(_var_name STREQUAL "AROS_TARGET_VARIANT")
      set(_replacement "${AROS_MODULE_CONTEXT_VARIANT}")
    elseif(_var_name STREQUAL "TARGET_CPU")
      set(_replacement "${AROS_MODULE_CONTEXT_CPU}")
    elseif(_var_name STREQUAL "SRCDIR")
      set(_replacement "${AROS_SOURCE_DIR}")
    elseif(_var_name STREQUAL "CURDIR")
      set(_replacement "${LINKLIB_PATH}")
    elseif(_var_name STREQUAL "GENDIR")
      set(_replacement "${_make_gendir}")
    else()
      _aros_read_config_value("${_var_name}" _replacement)
    endif()
    string(REPLACE "$(${_var_name})" "${_replacement}" _expanded "${_expanded}")
  endwhile()
  set(${out_var} "${_expanded}" PARENT_SCOPE)
endfunction()

function(_aros_read_config_value variable_name out_var)
  set(_config_files
    "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/target.cfg"
    "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/compiler.cfg"
    "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/build.cfg"
    "${AROS_CONFIG_BUILD_DIR}/config/make.cfg"
  )

  foreach(_config_file IN LISTS _config_files)
    if(NOT EXISTS "${_config_file}")
      continue()
    endif()

    file(STRINGS "${_config_file}" _value_line REGEX "^${variable_name}[ \t]*:?=")
    if(_value_line)
      string(REGEX REPLACE "^${variable_name}[ \t]*:?=[ \t]*" "" _value "${_value_line}")
      _aros_unwrap_strip_expression("${_value}" _value)
      set(${out_var} "${_value}" PARENT_SCOPE)
      return()
    endif()
  endforeach()

  set(${out_var} "" PARENT_SCOPE)
endfunction()

function(_aros_read_config_tokens variable_name out_var)
  _aros_read_config_value("${variable_name}" _value)
  if(_value STREQUAL "")
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()

  _aros_expand_make_tokens("${_value}" _expanded_value)
  _aros_unwrap_strip_expression("${_expanded_value}" _expanded_value)
  if(_expanded_value)
    separate_arguments(_tokens NATIVE_COMMAND "${_expanded_value}")
    set(${out_var} "${_tokens}" PARENT_SCOPE)
  else()
    set(${out_var} "" PARENT_SCOPE)
  endif()
endfunction()

function(_aros_parse_make_argument_tokens input_value out_prefix)
  set(_options)
  set(_one_value_args)
  set(_multi_value_args LIST_KEYS)
  cmake_parse_arguments(AROS_PARSE "${_options}" "${_one_value_args}" "${_multi_value_args}" ${ARGN})

  separate_arguments(_arg_tokens NATIVE_COMMAND "${input_value}")

  set(_seen_keys)
  set(_pending_list_key "")
  foreach(_arg_token IN LISTS _arg_tokens)
    if(NOT _arg_token MATCHES "^([^=]+)=(.*)$")
      if(NOT _pending_list_key STREQUAL "")
        set(_pending_var "_parsed_${_pending_list_key}")
        if("${${_pending_var}}" STREQUAL "")
          set(${_pending_var} "${_arg_token}")
        else()
          string(APPEND ${_pending_var} " ${_arg_token}")
        endif()
      endif()
      continue()
    endif()

    set(_arg_key "${CMAKE_MATCH_1}")
    set(_arg_value "${CMAKE_MATCH_2}")
    set(_parsed_${_arg_key} "${_arg_value}")
    list(APPEND _seen_keys "${_arg_key}")

    list(FIND AROS_PARSE_LIST_KEYS "${_arg_key}" _list_key_index)
    if(_list_key_index EQUAL -1)
      set(_pending_list_key "")
    else()
      set(_pending_list_key "${_arg_key}")
    endif()
  endforeach()

  list(REMOVE_DUPLICATES _seen_keys)
  foreach(_arg_key IN LISTS _seen_keys)
    set(${out_prefix}_${_arg_key} "${_parsed_${_arg_key}}" PARENT_SCOPE)
  endforeach()
  set(${out_prefix}_keys "${_seen_keys}" PARENT_SCOPE)
endfunction()

function(_aros_find_toolchain_program tool_name out_var)
  set(_candidates
    "${AROS_TOOLCHAIN_DIR}/${AROS_TOOLCHAIN_PREFIX}-${tool_name}"
    "${AROS_TOOLCHAIN_DIR}/bin/${AROS_TOOLCHAIN_PREFIX}-${tool_name}"
  )
  foreach(_candidate IN LISTS _candidates)
    if(EXISTS "${_candidate}")
      set(${out_var} "${_candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${out_var} "" PARENT_SCOPE)
endfunction()

function(_aros_parse_mmake_linklib file_path)
  _aros_read_mmake_logical_lines("${file_path}" _logical_lines)
  set(_condition_stack)
  set(_matched FALSE)

  foreach(_line IN LISTS _logical_lines)
    if(_line MATCHES "^#")
      continue()
    endif()

    if(_line MATCHES "^ifn?eq[ \t]*\\(.*\\)$")
      if(_line MATCHES "^ifneq[ \t]*\\((.*),(.*)\\)$")
        set(_left "${CMAKE_MATCH_1}")
        set(_right "${CMAKE_MATCH_2}")
        _aros_expand_make_tokens("${_left}" _left_expanded)
        _aros_expand_make_tokens("${_right}" _right_expanded)
        if(NOT _left_expanded STREQUAL _right_expanded)
          list(APPEND _condition_stack TRUE)
        else()
          list(APPEND _condition_stack FALSE)
        endif()
      elseif(_line MATCHES "^ifeq[ \t]*\\((.*),(.*)\\)$")
        set(_left "${CMAKE_MATCH_1}")
        set(_right "${CMAKE_MATCH_2}")
        _aros_expand_make_tokens("${_left}" _left_expanded)
        _aros_expand_make_tokens("${_right}" _right_expanded)
        if(_left_expanded STREQUAL _right_expanded)
          list(APPEND _condition_stack TRUE)
        else()
          list(APPEND _condition_stack FALSE)
        endif()
      endif()
      continue()
    elseif(_line STREQUAL "else")
      list(LENGTH _condition_stack _condition_len)
      if(_condition_len GREATER 0)
        math(EXPR _last_index "${_condition_len} - 1")
        list(GET _condition_stack "${_last_index}" _last_value)
        if(_last_value)
          set(_new_value FALSE)
        else()
          set(_new_value TRUE)
        endif()
        list(REMOVE_AT _condition_stack "${_last_index}")
        list(APPEND _condition_stack "${_new_value}")
      endif()
      continue()
    elseif(_line STREQUAL "endif")
      list(LENGTH _condition_stack _condition_len)
      if(_condition_len GREATER 0)
        math(EXPR _last_index "${_condition_len} - 1")
        list(REMOVE_AT _condition_stack "${_last_index}")
      endif()
      continue()
    endif()

    set(_condition_active TRUE)
    foreach(_condition_value IN LISTS _condition_stack)
      if(NOT _condition_value)
        set(_condition_active FALSE)
        break()
      endif()
    endforeach()
    if(NOT _condition_active)
      continue()
    endif()

    if(_line MATCHES "^([A-Za-z0-9_]+)[ \t]*(\\+=|:=|\\?=|=)[ \t]*(.*)$")
      set(_var_name "${CMAKE_MATCH_1}")
      set(_assign_mode "${CMAKE_MATCH_2}")
      set(_raw_value "${CMAKE_MATCH_3}")
      _aros_expand_make_tokens("${_raw_value}" _expanded_value)
      if(_assign_mode STREQUAL "+=" AND DEFINED _AROS_MMAKE_VAR_${_var_name})
        set(_AROS_MMAKE_VAR_${_var_name} "${_AROS_MMAKE_VAR_${_var_name}} ${_expanded_value}")
      elseif(_assign_mode STREQUAL "?=")
        if(NOT DEFINED _AROS_MMAKE_VAR_${_var_name} OR "${_AROS_MMAKE_VAR_${_var_name}}" STREQUAL "")
          set(_AROS_MMAKE_VAR_${_var_name} "${_expanded_value}")
        endif()
      else()
        set(_AROS_MMAKE_VAR_${_var_name} "${_expanded_value}")
      endif()
      continue()
    endif()

    if(NOT _line MATCHES "^%build_linklib[^ \t]*[ \t]+(.*)$")
      continue()
    endif()

    _aros_expand_make_tokens("${CMAKE_MATCH_1}" _expanded_args)
    _aros_parse_make_argument_tokens(
      "${_expanded_args}"
      _build_linklib
      LIST_KEYS files asmfiles usesdks cppflags cflags aflags dflags objs
    )

    set(_candidate_mmake "${_build_linklib_mmake}")
    set(_candidate_libname "${_build_linklib_libname}")

    if(DEFINED LINKLIB_MMAKE_NAME AND NOT LINKLIB_MMAKE_NAME STREQUAL "" AND NOT _candidate_mmake STREQUAL "${LINKLIB_MMAKE_NAME}")
      continue()
    endif()
    if(NOT _candidate_libname STREQUAL "${LINKLIB_NAME}")
      continue()
    endif()

    set(_matched TRUE)
    if(DEFINED _build_linklib_files)
      separate_arguments(_linklib_files NATIVE_COMMAND "${_build_linklib_files}")
    endif()
    if(DEFINED _build_linklib_asmfiles)
      separate_arguments(_linklib_asmfiles NATIVE_COMMAND "${_build_linklib_asmfiles}")
    endif()
    if(DEFINED _build_linklib_usesdks)
      separate_arguments(_linklib_usesdks NATIVE_COMMAND "${_build_linklib_usesdks}")
    endif()
    if(DEFINED _build_linklib_cppflags)
      separate_arguments(_linklib_cppflags NATIVE_COMMAND "${_build_linklib_cppflags}")
    endif()
    if(DEFINED _build_linklib_cflags)
      separate_arguments(_linklib_cflags NATIVE_COMMAND "${_build_linklib_cflags}")
    endif()
    if(DEFINED _build_linklib_aflags)
      separate_arguments(_linklib_aflags NATIVE_COMMAND "${_build_linklib_aflags}")
    endif()
    if(DEFINED _build_linklib_dflags)
      separate_arguments(_linklib_dflags NATIVE_COMMAND "${_build_linklib_dflags}")
    endif()
    if(DEFINED _build_linklib_sdk)
      set(_linklib_sdk "${_build_linklib_sdk}")
    endif()
    if(DEFINED _build_linklib_srcdir)
      set(_linklib_srcdir "${_build_linklib_srcdir}")
    endif()
    if(DEFINED _build_linklib_objs)
      separate_arguments(_linklib_extra_objects NATIVE_COMMAND "${_build_linklib_objs}")
    endif()
  endforeach()

  if(NOT _matched)
    message(FATAL_ERROR "Could not parse matching %build_linklib entry from ${file_path}")
  endif()

  if(DEFINED _AROS_MMAKE_VAR_USER_CPPFLAGS)
    separate_arguments(_linklib_user_cppflags NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_CPPFLAGS}")
  endif()
  if(DEFINED _AROS_MMAKE_VAR_USER_INCLUDES)
    separate_arguments(_linklib_user_includes NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_INCLUDES}")
  endif()
  if(DEFINED _AROS_MMAKE_VAR_USER_CFLAGS)
    separate_arguments(_linklib_user_cflags NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_CFLAGS}")
  endif()
  if(DEFINED _AROS_MMAKE_VAR_USER_AFLAGS)
    separate_arguments(_linklib_user_aflags NATIVE_COMMAND "${_AROS_MMAKE_VAR_USER_AFLAGS}")
  endif()

  foreach(_var_name IN ITEMS
    _linklib_files
    _linklib_asmfiles
    _linklib_usesdks
    _linklib_cppflags
    _linklib_cflags
    _linklib_aflags
    _linklib_dflags
    _linklib_extra_objects
    _linklib_user_cppflags
    _linklib_user_includes
    _linklib_user_cflags
    _linklib_user_aflags)
    if(DEFINED ${_var_name})
      _aros_remove_empty_entries(${_var_name})
      _aros_remove_token_entries(${_var_name} "\\")
    endif()
  endforeach()

  set(LINKLIB_PARSED_FILES "${_linklib_files}" PARENT_SCOPE)
  set(LINKLIB_PARSED_ASMFILES "${_linklib_asmfiles}" PARENT_SCOPE)
  set(LINKLIB_PARSED_USESDKS "${_linklib_usesdks}" PARENT_SCOPE)
  set(LINKLIB_PARSED_CPPFLAGS "${_linklib_cppflags}" PARENT_SCOPE)
  set(LINKLIB_PARSED_CFLAGS "${_linklib_cflags}" PARENT_SCOPE)
  set(LINKLIB_PARSED_AFLAGS "${_linklib_aflags}" PARENT_SCOPE)
  set(LINKLIB_PARSED_DFLAGS "${_linklib_dflags}" PARENT_SCOPE)
  set(LINKLIB_PARSED_USER_CPPFLAGS "${_linklib_user_cppflags}" PARENT_SCOPE)
  set(LINKLIB_PARSED_USER_INCLUDES "${_linklib_user_includes}" PARENT_SCOPE)
  set(LINKLIB_PARSED_USER_CFLAGS "${_linklib_user_cflags}" PARENT_SCOPE)
  set(LINKLIB_PARSED_USER_AFLAGS "${_linklib_user_aflags}" PARENT_SCOPE)
  set(LINKLIB_PARSED_EXTRA_OBJECTS "${_linklib_extra_objects}" PARENT_SCOPE)
  set(LINKLIB_PARSED_SDK "${_linklib_sdk}" PARENT_SCOPE)
  set(LINKLIB_PARSED_SRCDIR "${_linklib_srcdir}" PARENT_SCOPE)
endfunction()

function(_aros_resolve_source_candidate module_dir basename out_var)
  if(IS_ABSOLUTE "${basename}" AND EXISTS "${basename}")
    set(${out_var} "${basename}" PARENT_SCOPE)
    return()
  endif()

  get_filename_component(_input_ext "${basename}" EXT)
  if(IS_ABSOLUTE "${basename}")
    if(_input_ext)
      set(_candidates "${basename}")
    else()
      set(_candidates)
      foreach(_ext IN ITEMS .c .cc .cxx .cpp .S .s)
        list(APPEND _candidates "${basename}${_ext}")
      endforeach()
    endif()
  elseif(_input_ext)
    set(_candidates "${module_dir}/${basename}")
  else()
    set(_candidates)
    foreach(_ext IN ITEMS .c .cc .cxx .cpp .S .s)
      list(APPEND _candidates "${module_dir}/${basename}${_ext}")
    endforeach()
  endif()

  foreach(_candidate IN LISTS _candidates)
    if(EXISTS "${_candidate}")
      set(${out_var} "${_candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()

  set(${out_var} "" PARENT_SCOPE)
endfunction()

function(_aros_make_object_base logical_name resolved_source out_var)
  set(_object_input "${logical_name}")
  if(_object_input STREQUAL "")
    set(_object_input "${resolved_source}")
  endif()

  string(REPLACE "\\" "/" _object_input "${_object_input}")
  get_filename_component(_object_dir "${_object_input}" DIRECTORY)
  get_filename_component(_object_stem "${_object_input}" NAME_WE)
  if(_object_stem STREQUAL "")
    get_filename_component(_object_stem "${resolved_source}" NAME_WE)
  endif()

  if(_object_dir STREQUAL "")
    set(_object_base "${_object_stem}")
  else()
    set(_object_base "${_object_dir}/${_object_stem}")
  endif()

  string(REPLACE "../" "__/" _object_base "${_object_base}")
  string(REPLACE "./" "" _object_base "${_object_base}")
  string(REPLACE "/" "_" _object_base "${_object_base}")
  string(REPLACE ":" "_" _object_base "${_object_base}")
  string(REPLACE ".." "__" _object_base "${_object_base}")

  if(_object_base STREQUAL "")
    get_filename_component(_object_base "${resolved_source}" NAME_WE)
  endif()

  set(${out_var} "${_object_base}" PARENT_SCOPE)
endfunction()

_aros_parse_mmake_linklib("${LINKLIB_MMAKEFILE}")
_aros_read_config_tokens("TARGET_CPPFLAGS" _linklib_default_cppflags)
_aros_read_config_tokens("TARGET_ISA_CFLAGS" _linklib_target_isa_cflags)
_aros_read_config_tokens("OPTIMIZATION_CFLAGS" _linklib_optimization_cflags)
_aros_read_config_tokens("CFLAGS_NO_OMIT_FP" _linklib_no_omit_fp_cflags)
_aros_read_config_tokens("AR_PLAIN" _linklib_ar)
_aros_read_config_tokens("RANLIB" _linklib_ranlib)
_aros_find_toolchain_program("gcc" _linklib_cc)
_aros_find_toolchain_program("ar" _linklib_ar_fallback)
_aros_find_toolchain_program("ranlib" _linklib_ranlib_fallback)

set(_linklib_ar_path "")
if(_linklib_ar)
  list(GET _linklib_ar 0 _linklib_ar_path)
endif()
if((NOT _linklib_ar OR "${_linklib_ar_path}" STREQUAL "" OR NOT EXISTS "${_linklib_ar_path}") AND _linklib_ar_fallback)
  set(_linklib_ar "${_linklib_ar_fallback}")
endif()

set(_linklib_ranlib_path "")
if(_linklib_ranlib)
  list(GET _linklib_ranlib 0 _linklib_ranlib_path)
endif()
if((NOT _linklib_ranlib OR "${_linklib_ranlib_path}" STREQUAL "" OR NOT EXISTS "${_linklib_ranlib_path}") AND _linklib_ranlib_fallback)
  set(_linklib_ranlib "${_linklib_ranlib_fallback}")
endif()

if(NOT _linklib_cc)
  message(FATAL_ERROR
    "Target compiler for ${LINKLIB_PATH} is missing under ${AROS_TOOLCHAIN_DIR}. "
    "Expected ${AROS_TOOLCHAIN_PREFIX}-gcc in either the toolchain root or its bin/ directory."
  )
endif()
if(NOT _linklib_ar)
  message(FATAL_ERROR "Target ar was not resolved from target.cfg")
endif()
if(NOT _linklib_ranlib)
  message(FATAL_ERROR "Target ranlib was not resolved from target.cfg")
endif()

if(LINKLIB_PARSED_SRCDIR)
  if(IS_ABSOLUTE "${LINKLIB_PARSED_SRCDIR}")
    set(_linklib_source_dir "${LINKLIB_PARSED_SRCDIR}")
  elseif(IS_DIRECTORY "${AROS_SOURCE_DIR}/${LINKLIB_PARSED_SRCDIR}")
    set(_linklib_source_dir "${AROS_SOURCE_DIR}/${LINKLIB_PARSED_SRCDIR}")
  else()
    set(_linklib_source_dir "${AROS_SOURCE_DIR}/${LINKLIB_PATH}/${LINKLIB_PARSED_SRCDIR}")
  endif()
else()
  set(_linklib_source_dir "${AROS_SOURCE_DIR}/${LINKLIB_PATH}")
endif()

set(_use_posixc_headers TRUE)
set(_use_stdc_headers TRUE)
set(_linklib_contains_stdc FALSE)
set(_linklib_contains_posixc FALSE)
foreach(_linklib_file IN LISTS LINKLIB_PARSED_FILES)
  if(_linklib_file MATCHES "^stdc/")
    set(_linklib_contains_stdc TRUE)
  elseif(_linklib_file MATCHES "^posixc/")
    set(_linklib_contains_posixc TRUE)
  endif()
endforeach()
if(_linklib_contains_stdc AND NOT _linklib_contains_posixc)
  set(_use_posixc_headers FALSE)
elseif(_linklib_contains_posixc AND NOT _linklib_contains_stdc)
  set(_use_stdc_headers FALSE)
endif()

file(MAKE_DIRECTORY "${LINKLIB_OBJ_DIR}")
get_filename_component(_linklib_output_dir "${LINKLIB_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_linklib_output_dir}")

set(_common_compile_args
  "--sysroot=${AROS_SYSROOT}"
)
if(DEFINED AROS_SOURCE_DIR AND NOT AROS_SOURCE_DIR STREQUAL "")
  list(APPEND _common_compile_args
    "-ffile-prefix-map=${AROS_SOURCE_DIR}/="
    "-fmacro-prefix-map=${AROS_SOURCE_DIR}/="
  )
endif()
if(DEFINED AROS_BINARY_DIR AND NOT AROS_BINARY_DIR STREQUAL "")
  list(APPEND _common_compile_args
    "-ffile-prefix-map=${AROS_BINARY_DIR}/="
    "-fmacro-prefix-map=${AROS_BINARY_DIR}/="
  )
endif()
set(_linklib_effective_cppflags ${_linklib_default_cppflags})
if(DEFINED LINKLIB_PARSED_CPPFLAGS AND NOT "${LINKLIB_PARSED_CPPFLAGS}" STREQUAL "")
  set(_linklib_effective_cppflags ${LINKLIB_PARSED_CPPFLAGS})
endif()
set(_linklib_default_cflags
  ${_linklib_target_isa_cflags}
  ${_linklib_optimization_cflags}
  ${_linklib_no_omit_fp_cflags}
  ${LINKLIB_PARSED_USER_CFLAGS}
)
_aros_remove_empty_entries(_linklib_default_cflags)
set(_linklib_effective_cflags ${_linklib_default_cflags})
if(DEFINED LINKLIB_PARSED_CFLAGS AND NOT "${LINKLIB_PARSED_CFLAGS}" STREQUAL "")
  set(_linklib_effective_cflags ${LINKLIB_PARSED_CFLAGS})
endif()

list(APPEND _common_compile_args ${_linklib_effective_cppflags})
if(NOT DEFINED LINKLIB_PARSED_CPPFLAGS OR "${LINKLIB_PARSED_CPPFLAGS}" STREQUAL "")
  list(APPEND _common_compile_args ${LINKLIB_PARSED_USER_CPPFLAGS})
  list(APPEND _common_compile_args ${LINKLIB_PARSED_USER_INCLUDES})
endif()
list(APPEND _common_compile_args -D__AROS_GIMME_DEPRECATED__)
list(APPEND _common_compile_args ${_linklib_effective_cflags})
list(APPEND _common_compile_args "-I${AROS_SOURCE_DIR}/${LINKLIB_PATH}")
list(APPEND _common_compile_args "-idirafter" "${AROS_NATIVE_INCLUDE_DIR}")
if(_use_posixc_headers)
  list(APPEND _common_compile_args "-idirafter" "${AROS_NATIVE_INCLUDE_DIR}/aros/posixc")
endif()
if(_use_stdc_headers)
  list(APPEND _common_compile_args "-idirafter" "${AROS_NATIVE_INCLUDE_DIR}/aros/stdc")
endif()
foreach(_sdk IN LISTS LINKLIB_PARSED_USESDKS)
  list(APPEND _common_compile_args "-I${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen/buildsdks/${_sdk}/include")
  list(APPEND _common_compile_args "-I${AROS_NATIVE_BUILD_SDKS_DIR}/${_sdk}/include")
endforeach()

set(_linklib_objects)
foreach(_linklib_file IN LISTS LINKLIB_PARSED_FILES)
  if(_linklib_file STREQUAL "")
    continue()
  endif()
  _aros_resolve_source_candidate("${_linklib_source_dir}" "${_linklib_file}" _resolved_source)
  if(NOT _resolved_source)
    message(FATAL_ERROR "Could not resolve linklib source '${_linklib_file}' under ${_linklib_source_dir}")
  endif()
  _aros_make_object_base("${_linklib_file}" "${_resolved_source}" _obj_base)
  set(_object "${LINKLIB_OBJ_DIR}/${_obj_base}.o")
  execute_process(
    COMMAND "${_linklib_cc}" ${_common_compile_args} -c "${_resolved_source}" -o "${_object}"
    RESULT_VARIABLE _compile_result
  )
  if(NOT _compile_result EQUAL 0)
    message(FATAL_ERROR "Failed compiling ${_resolved_source}")
  endif()
  list(APPEND _linklib_objects "${_object}")
endforeach()

set(_linklib_asm_compile_args ${_common_compile_args})
list(APPEND _linklib_asm_compile_args ${LINKLIB_PARSED_USER_AFLAGS})
if(DEFINED LINKLIB_PARSED_AFLAGS AND NOT "${LINKLIB_PARSED_AFLAGS}" STREQUAL "")
  list(APPEND _linklib_asm_compile_args ${LINKLIB_PARSED_AFLAGS})
endif()
_aros_remove_empty_entries(_linklib_asm_compile_args)

foreach(_linklib_asmfile IN LISTS LINKLIB_PARSED_ASMFILES)
  if(_linklib_asmfile STREQUAL "")
    continue()
  endif()
  _aros_resolve_source_candidate("${_linklib_source_dir}" "${_linklib_asmfile}" _resolved_asm_source)
  if(NOT _resolved_asm_source)
    message(FATAL_ERROR "Could not resolve linklib asm source '${_linklib_asmfile}' under ${_linklib_source_dir}")
  endif()
  _aros_make_object_base("${_linklib_asmfile}" "${_resolved_asm_source}" _asm_obj_base)
  set(_asm_object "${LINKLIB_OBJ_DIR}/${_asm_obj_base}.o")
  execute_process(
    COMMAND "${_linklib_cc}" -x assembler-with-cpp ${_linklib_asm_compile_args} -c "${_resolved_asm_source}" -o "${_asm_object}"
    RESULT_VARIABLE _asm_compile_result
  )
  if(NOT _asm_compile_result EQUAL 0)
    message(FATAL_ERROR "Failed compiling ${_resolved_asm_source}")
  endif()
  list(APPEND _linklib_objects "${_asm_object}")
endforeach()

list(APPEND _linklib_objects ${LINKLIB_PARSED_EXTRA_OBJECTS})
_aros_remove_empty_entries(_linklib_objects)

if(EXISTS "${LINKLIB_OUTPUT}")
  file(REMOVE "${LINKLIB_OUTPUT}")
endif()

execute_process(
  COMMAND "${_linklib_ar}" cr "${LINKLIB_OUTPUT}" ${_linklib_objects}
  RESULT_VARIABLE _ar_result
)
if(NOT _ar_result EQUAL 0)
  message(FATAL_ERROR "Failed archiving ${LINKLIB_OUTPUT}")
endif()

execute_process(
  COMMAND ${_linklib_ranlib} "${LINKLIB_OUTPUT}"
  RESULT_VARIABLE _ranlib_result
)
if(NOT _ranlib_result EQUAL 0)
  message(FATAL_ERROR "Failed indexing ${LINKLIB_OUTPUT}")
endif()
