cmake_minimum_required(VERSION 3.20)
include("${CONTEXT_FILE}")
set(CMAKE_SOURCE_DIR "${AROS_SOURCE_DIR}")
set(AROS_LEGACY_BUILD_DIR "${AROS_CONFIG_BUILD_DIR}")
include("${CMAKE_CURRENT_LIST_DIR}/AROSModule.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeObjects.cmake")
set(_AROS_MMAKE_VAR_TOP "${AROS_BINARY_DIR}")
set(_AROS_MMAKE_VAR_AROS_LIB "${AROS_NATIVE_PUBLIC_LIB_DIR}")
set(_matches)
foreach(_manifest IN LISTS OBJECT_MANIFESTS)
  aros_collect_mmake_object("${_manifest}" "${SDK_OBJECT_OUTPUT}" _object)
  if(_object_FOUND)
    list(APPEND _matches "${_manifest}")
    set(_source "${_object_SOURCE}")
    set(_flags "${_object_FLAGS}")
    set(_intermediate "${_object_INTERMEDIATE}")
  endif()
endforeach()
list(LENGTH _matches _count)
if(NOT _count EQUAL 1)
  message(FATAL_ERROR "Expected one native SDK object producer for ${SDK_OBJECT_OUTPUT}, found: ${_matches}")
endif()
set(_content "set(MMAKE_OBJECT_SOURCE [==[${_source}]==])\nset(MMAKE_OBJECT_MANIFEST [==[${_matches}]==])\nset(MMAKE_OBJECT_INTERMEDIATE [==[${_intermediate}]==])\nset(MMAKE_PROGRAM_COMPILE_FLAGS [==[${_flags}]==])\n")
file(CONFIGURE OUTPUT "${OUTPUT_FILE}" CONTENT "${_content}" @ONLY)
