cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeBuild.cmake")
include("${CONTEXT_FILE}")
if(NOT MODULE_MMAKEFILE)
  set(MODULE_MMAKEFILE "${AROS_SOURCE_DIR}/${MODULE_PATH}/mmakefile.src")
endif()
_aros_parse_mmake_module("${MODULE_MMAKEFILE}")
if(NOT MODULE_MMAKE_PARSED_KIND STREQUAL "kickstart")
  message(FATAL_ERROR "No link_kickstart rule for ${MODULE_MMAKE_NAME}")
endif()
foreach(_unsupported IN ITEMS map packfmt strip deps)
  if(MODULE_MMAKE_KICKSTART_${_unsupported})
    message(FATAL_ERROR "link_kickstart ${_unsupported} is not implemented yet")
  endif()
endforeach()
if(NOT MODULE_MMAKE_KICKSTART_file OR NOT MODULE_MMAKE_KICKSTART_startup)
  message(FATAL_ERROR "Native link_kickstart currently requires an explicit file and startup object")
endif()
set(KICKSTART_OBJECTS ${MODULE_MMAKE_KICKSTART_startup})
# Keep the order from config/make.tmpl, irrespective of argument order.
foreach(_group IN ITEMS classes handlers libs devs hidds res)
  if(_group STREQUAL "classes")
    set(_suffix class)
  elseif(_group STREQUAL "handlers")
    set(_suffix handler)
  elseif(_group STREQUAL "libs")
    set(_suffix library)
  elseif(_group STREQUAL "devs")
    set(_suffix device)
  elseif(_group STREQUAL "hidds")
    set(_suffix hidd)
  else()
    set(_suffix resource)
  endif()
  foreach(_name IN LISTS MODULE_MMAKE_KICKSTART_${_group})
    list(APPEND KICKSTART_OBJECTS "${_AROS_MMAKE_VAR_KOBJSDIR}/${_name}_${_suffix}.o")
  endforeach()
endforeach()
set(KICKSTART_OUTPUT "${MODULE_MMAKE_KICKSTART_file}")
set(KICKSTART_LIBS ${MODULE_MMAKE_KICKSTART_uselibs} stdc.static)
set(KICKSTART_LINK_OPTIONS ${MODULE_MMAKE_KICKSTART_ldflags})
_aros_read_config_tokens(NOSTARTUP_LDFLAGS _nostartup)
list(APPEND KICKSTART_LINK_OPTIONS ${_nostartup} -noclibs -nosysbase -Wl,-Ur)
file(WRITE "${OUTPUT_FILE}" "# Native link_kickstart metadata.\n")
foreach(_var IN ITEMS KICKSTART_OBJECTS KICKSTART_OUTPUT KICKSTART_LIBS KICKSTART_LINK_OPTIONS)
  file(APPEND "${OUTPUT_FILE}" "set(${_var} [==[${${_var}}]==])\n")
endforeach()
