cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeBuild.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeConfig.cmake")
include("${CONTEXT_FILE}")
_aros_get_target_context()
if(NOT MODULE_MMAKEFILE)
  set(MODULE_MMAKEFILE "${AROS_SOURCE_DIR}/${MODULE_PATH}/mmakefile.src")
endif()
get_filename_component(_module_dir_name "${MODULE_PATH}" NAME)
aros_layering_collect_resolved_module_layer_mmakefiles(
  "${_module_dir_name}" "${MODULE_MMAKE_NAME}"
  MODULE_RESOLVED_LAYER_MMAKEFILES MODULE_RESOLVED_LAYERS MODULE_RESOLVED_REACHABLE_ALIASES)
set(MODULE_COLLECT_PROGRAM TRUE)
_aros_load_program_config()
_aros_parse_mmake_module("${MODULE_MMAKEFILE}")
if(NOT MMAKE_PROGRAM_FIELDS)
  message(FATAL_ERROR "No active target program rule for ${MODULE_MMAKE_NAME} in ${MODULE_MMAKEFILE}")
endif()
set(MODULE_COLLECT_PROGRAM FALSE)
set(_inputs "${MODULE_MMAKE_PARSED_INPUTS};${MMAKE_PROGRAM_CONFIG_INPUTS}")
foreach(_config IN ITEMS ${AROS_NATIVE_CONFIG_FILE} "${AROS_CONFIG_BUILD_DIR}/Makefile" "${AROS_CONFIG_BUILD_DIR}/config/make.cfg"
    "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/target.cfg"
    "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/build.cfg"
    "${AROS_CONFIG_BUILD_DIR}/bin/${AROS_TARGET}/gen/config/compiler.cfg")
  if(EXISTS "${_config}")
    list(APPEND _inputs "${_config}")
  endif()
endforeach()
foreach(_layer IN LISTS MODULE_RESOLVED_LAYER_MMAKEFILES)
  if(_layer STREQUAL MODULE_MMAKEFILE)
    continue()
  endif()
  _aros_parse_mmake_module("${_layer}")
  list(APPEND _inputs ${MODULE_MMAKE_PARSED_INPUTS})
  if(MODULE_MMAKE_PARSED_ARCH_FILES OR MODULE_MMAKE_PARSED_ARCH_ASMFILES)
    message(FATAL_ERROR "Program ${MODULE_MMAKE_NAME}: target-program layer objects need native implementation (${_layer})")
  endif()
endforeach()
if(MMAKE_PROGRAM_SRCDIR)
  get_filename_component(_source_root "${MMAKE_PROGRAM_SRCDIR}" ABSOLUTE
    BASE_DIR "${AROS_SOURCE_DIR}/${MODULE_PATH}")
  set(_source_root "${_source_root}/${MODULE_PATH}")
else()
  set(_source_root "${AROS_SOURCE_DIR}/${MODULE_PATH}")
endif()
set(_sources)
set(_names)
foreach(_file IN LISTS MMAKE_PROGRAM_FILES)
  _aros_resolve_source_candidate("${_source_root}" "${_file}" _source)
  if(NOT _source OR NOT _source MATCHES "[.]c$")
    message(FATAL_ERROR "Program ${MODULE_MMAKE_NAME}: missing or unsupported C source ${_file}")
  endif()
  file(REAL_PATH "${_source}" _real_source)
  if(_real_source IN_LIST AROS_PROGRAM_FETCH_SOURCES AND _source STREQUAL _real_source)
    # Only a registered, completed native fetch receipt can authorize this
    # source. Existing files in either build tree are insufficient by themselves.
    set(_fetched TRUE)
  else()
    set(_fetched FALSE)
  endif()
  file(REAL_PATH "${AROS_SOURCE_DIR}" _real_root)
  file(RELATIVE_PATH _relative "${_real_root}" "${_real_source}")
  if(NOT _fetched AND (_relative MATCHES "^\\.\\.(/|$)" OR IS_ABSOLUTE "${_relative}"))
    message(FATAL_ERROR "Program ${MODULE_MMAKE_NAME}: generated/external source needs a native producer: ${_source}")
  endif()
  foreach(_generated_root IN ITEMS "${AROS_BINARY_DIR}" "${AROS_CONFIG_BUILD_DIR}")
    if(_generated_root)
      file(REAL_PATH "${_generated_root}" _real_generated_root)
      file(RELATIVE_PATH _relative "${_real_generated_root}" "${_real_source}")
      if(NOT _relative MATCHES "^\\.\\.(/|$)" AND NOT IS_ABSOLUTE "${_relative}"
         AND (NOT _fetched OR _generated_root STREQUAL AROS_CONFIG_BUILD_DIR))
        message(FATAL_ERROR "Program ${MODULE_MMAKE_NAME}: generated/external source needs a native producer: ${_source}")
      endif()
    endif()
  endforeach()
  get_filename_component(_name "${_file}" NAME)
  if(_name IN_LIST _names)
    message(FATAL_ERROR "Program ${MODULE_MMAKE_NAME}: duplicate object/output basename ${_name}")
  endif()
  list(APPEND _names "${_name}")
  list(APPEND _sources "${_source}")
endforeach()
set(MMAKE_PROGRAM_SOURCES "${_sources}")
set(MMAKE_PROGRAM_NAMES "${_names}")
set(MMAKE_PROGRAM_INPUTS "${_inputs}")
list(APPEND MMAKE_PROGRAM_FIELDS SOURCES NAMES INPUTS CONFIG_OPTIONAL_INPUTS)
set(_content "# Generated target-program metadata\n")
foreach(_field IN LISTS MMAKE_PROGRAM_FIELDS)
  string(APPEND _content "set(MMAKE_PROGRAM_${_field} [==[${MMAKE_PROGRAM_${_field}}]==])\n")
endforeach()
file(WRITE "${OUTPUT_FILE}.tmp" "${_content}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUTPUT_FILE}.tmp" "${OUTPUT_FILE}"
  COMMAND_ERROR_IS_FATAL ANY)
file(REMOVE "${OUTPUT_FILE}.tmp")
