cmake_minimum_required(VERSION 3.20)
include("${CONTEXT_FILE}")
include("${CMAKE_CURRENT_LIST_DIR}/AROSModule.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AROSProgramDiscovery.cmake")
aros_discover_program_graph(_graph ROOT "${PROGRAM_GRAPH_ROOT}")
set(_content "set(PROGRAM_GRAPH_ROOT [==[${_graph_ROOT}]==])\nset(PROGRAM_GRAPH_PROGRAMS [==[${_graph_PROGRAMS}]==])\nset(PROGRAM_GRAPH_NODES [==[${_graph_NODES}]==])\n")
foreach(_node IN LISTS _graph_NODES)
  string(SHA256 _key "${_node}")
  string(APPEND _content "set(PROGRAM_GRAPH_DEPENDS_${_key} [==[${_graph_DEPENDS_${_key}}]==])\n")
endforeach()
file(WRITE "${OUTPUT_FILE}" "${_content}")
