cmake_minimum_required(VERSION 3.20)
include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeBuild.cmake")

# Run in a separate CMake process so build-time parser context cannot leak
# into the configure-time module registry.
include("${CONTEXT_FILE}")
_aros_get_target_context()
if(NOT MODULE_MMAKEFILE)
  set(MODULE_MMAKEFILE "${AROS_SOURCE_DIR}/${MODULE_PATH}/mmakefile.src")
endif()
get_filename_component(_module_dir_name "${MODULE_PATH}" NAME)
aros_layering_collect_resolved_module_layer_mmakefiles(
  "${_module_dir_name}" "${MODULE_MMAKE_NAME}"
  MODULE_RESOLVED_LAYER_MMAKEFILES MODULE_RESOLVED_LAYERS MODULE_RESOLVED_REACHABLE_ALIASES
)

function(_emit name value)
  file(APPEND "${OUTPUT_FILE}" "set(${name} [==[${value}]==])\n")
endfunction()

_aros_parse_mmake_module("${MODULE_MMAKEFILE}")
if(NOT MODULE_MMAKE_PARSED_KIND MATCHES "^(prog|linklib)$"
   OR NOT MODULE_MMAKE_PARSED_COMPILER MATCHES "^(host|kernel)$"
   OR NOT MODULE_MMAKE_PARSED_FILES)
  message(FATAL_ERROR "Expected a host/kernel %build_prog or %build_linklib: ${MODULE_MMAKEFILE} (${MODULE_MMAKE_NAME})")
endif()
set(_base_files "${MODULE_MMAKE_PARSED_FILES}")
set(_base_flags ${MODULE_MMAKE_PARSED_USER_CPPFLAGS}
  ${MODULE_MMAKE_PARSED_USER_INCLUDES} ${MODULE_MMAKE_PARSED_USER_CFLAGS})
set(_link_flags ${MODULE_MMAKE_PARSED_USER_LDFLAGS})
_aros_collect_layer_makeopts("USER_LDFLAGS" _layer_link_flags)
list(APPEND _link_flags ${_layer_link_flags})

file(WRITE "${OUTPUT_FILE}" "# Generated from ${MODULE_MMAKEFILE}\n")
_emit(MMAKE_KIND "${MODULE_MMAKE_PARSED_KIND}")
_emit(MMAKE_OUTPUT_NAME "${MODULE_MMAKE_PARSED_OUTPUT_NAME}")
_emit(MMAKE_OUTPUT_DIR "${MODULE_MMAKE_PARSED_OUTPUT_DIR}")
_emit(MMAKE_USELIBS "${MODULE_MMAKE_PARSED_USELIBS}")
_emit(MMAKE_LINK_FLAGS "${_link_flags}")

set(_inputs "${MODULE_MMAKE_PARSED_INPUTS}")
set(_seen_stems)
set(_ordered_groups)
set(_index 0)
foreach(_manifest IN LISTS MODULE_RESOLVED_LAYER_MMAKEFILES)
  if(_manifest STREQUAL MODULE_MMAKEFILE)
    continue()
  endif()
  list(APPEND _inputs "${_manifest}")
  get_filename_component(_dir "${_manifest}" DIRECTORY)
  if(EXISTS "${_dir}/make.opts")
    list(APPEND _inputs "${_dir}/make.opts")
  endif()
  _aros_parse_mmake_module("${_manifest}")
  list(APPEND _inputs ${MODULE_MMAKE_PARSED_INPUTS})
  foreach(_file IN LISTS MODULE_MMAKE_PARSED_ARCH_FILES)
    get_filename_component(_stem "${_file}" NAME_WE)
    if(_stem IN_LIST _seen_stems)
      continue()
    endif()
    list(APPEND _seen_stems "${_stem}")
    _aros_resolve_source_candidate("${_dir}" "${_file}" _source)
    if(NOT _source)
      message(FATAL_ERROR "Cannot resolve ${_file} from ${_manifest}")
    endif()
    set(_flags)
    foreach(_spec IN LISTS MODULE_MMAKE_PARSED_ARCH_SOURCE_FLAG_SPECS)
      string(FIND "${_spec}" "|" _split)
      string(SUBSTRING "${_spec}" 0 ${_split} _spec_name)
      if(_spec_name STREQUAL _file)
        math(EXPR _split "${_split} + 1")
        string(SUBSTRING "${_spec}" ${_split} -1 _encoded_flags)
        _aros_decode_token_list("${_encoded_flags}" _source_flags)
        list(APPEND _flags ${_source_flags})
      endif()
    endforeach()
    list(APPEND _ordered_groups "${_stem}|${_index}")
    _emit("MMAKE_SOURCES_${_index}" "${_source}")
    _emit("MMAKE_FLAGS_${_index}" "${_flags}")
    math(EXPR _index "${_index} + 1")
  endforeach()
endforeach()

set(_base_sources)
foreach(_file IN LISTS _base_files)
  get_filename_component(_stem "${_file}" NAME_WE)
  if(NOT _stem IN_LIST _seen_stems)
    _aros_resolve_source_candidate("${AROS_SOURCE_DIR}/${MODULE_PATH}" "${_file}" _source)
    if(NOT _source)
      message(FATAL_ERROR "Cannot resolve ${_file} from ${MODULE_MMAKEFILE}")
    endif()
    list(APPEND _base_sources "${_source}")
  endif()
endforeach()
_emit(MMAKE_BASE_SOURCES "${_base_sources}")
_emit(MMAKE_BASE_FLAGS "${_base_flags}")
# %build_prog links base objects first, followed by the sorted arch/*.o set.
list(SORT _ordered_groups)
set(_groups)
foreach(_entry IN LISTS _ordered_groups)
  string(REGEX REPLACE "^.*[|]" "" _group "${_entry}")
  list(APPEND _groups "${_group}")
endforeach()
_emit(MMAKE_GROUPS "${_groups}")
_emit(MMAKE_INPUTS "${_inputs}")
