if(NOT DEFINED LEGACY_TOOLDIR)
  message(FATAL_ERROR "LEGACY_TOOLDIR must be defined")
endif()
if(NOT DEFINED SPECS_TEXT OR SPECS_TEXT STREQUAL "")
  message(FATAL_ERROR "SPECS_TEXT must be defined")
endif()

if(NOT DEFINED STRICT_COMPARE)
  set(STRICT_COMPARE ON)
endif()

find_program(_objcopy NAMES objcopy llvm-objcopy)

string(REPLACE "|" ";" SPECS "${SPECS_TEXT}")

set(_mismatch_count 0)
set(_checked_count 0)
set(_skipped_count 0)
set(_equivalent_count 0)

function(_normalize_output in_file out_file)
  file(READ "${in_file}" _txt)
  string(REGEX REPLACE "([A-Za-z]:)?[^ \n\t]*/([A-Za-z0-9_.+-]+)" "<path>/\\2" _txt "${_txt}")
  file(WRITE "${out_file}" "${_txt}")
endfunction()

function(_behavior_equivalent cmake_bin legacy_bin tool_name out_var)
  set(_tmp "${CMAKE_CURRENT_BINARY_DIR}/.coexist-${tool_name}")
  file(MAKE_DIRECTORY "${_tmp}")
  set(_cout "${_tmp}/cmake.out")
  set(_lout "${_tmp}/legacy.out")
  set(_cout_norm "${_tmp}/cmake.norm.out")
  set(_lout_norm "${_tmp}/legacy.norm.out")

  execute_process(COMMAND "${cmake_bin}" RESULT_VARIABLE _crc OUTPUT_FILE "${_cout}" ERROR_FILE "${_cout}")
  execute_process(COMMAND "${legacy_bin}" RESULT_VARIABLE _lrc OUTPUT_FILE "${_lout}" ERROR_FILE "${_lout}")

  _normalize_output("${_cout}" "${_cout_norm}")
  _normalize_output("${_lout}" "${_lout_norm}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${_cout_norm}" "${_lout_norm}" RESULT_VARIABLE _out_cmp)

  if(_out_cmp EQUAL 0 AND _crc STREQUAL _lrc)
    set(${out_var} TRUE PARENT_SCOPE)
  else()
    set(${out_var} FALSE PARENT_SCOPE)
  endif()
endfunction()

foreach(_spec IN LISTS SPECS)
  string(REPLACE "::" ";" _parts "${_spec}")
  list(LENGTH _parts _parts_len)
  if(NOT _parts_len EQUAL 3)
    message(FATAL_ERROR "Invalid compare spec '${_spec}'. Expected format: name::cmake_path::legacy_filename")
  endif()

  list(GET _parts 0 _name)
  list(GET _parts 1 _cmake_path)
  list(GET _parts 2 _legacy_name)
  set(_legacy_path "${LEGACY_TOOLDIR}/${_legacy_name}")

  if(NOT EXISTS "${_cmake_path}")
    message(FATAL_ERROR "CMake artifact for '${_name}' not found: ${_cmake_path}")
  endif()
  if(NOT EXISTS "${_legacy_path}")
    message(WARNING "[coexist] ${_name}: legacy artifact missing, skipping (${_legacy_path})")
    math(EXPR _skipped_count "${_skipped_count} + 1")
    continue()
  endif()

  math(EXPR _checked_count "${_checked_count} + 1")
  set(_cmp_rv 1)
  if(_objcopy)
    set(_tmp "${CMAKE_CURRENT_BINARY_DIR}/.coexist-${_name}")
    file(MAKE_DIRECTORY "${_tmp}")
    set(_cmake_norm "${_tmp}/cmake.norm")
    set(_legacy_norm "${_tmp}/legacy.norm")
    execute_process(COMMAND "${_objcopy}" --strip-debug --remove-section .comment --remove-section .note.gnu.build-id "${_cmake_path}" "${_cmake_norm}" RESULT_VARIABLE _oc1)
    execute_process(COMMAND "${_objcopy}" --strip-debug --remove-section .comment --remove-section .note.gnu.build-id "${_legacy_path}" "${_legacy_norm}" RESULT_VARIABLE _oc2)
    if(_oc1 EQUAL 0 AND _oc2 EQUAL 0)
      execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${_cmake_norm}" "${_legacy_norm}" RESULT_VARIABLE _cmp_rv)
    endif()
  endif()

  if(_cmp_rv EQUAL 0)
    message(STATUS "[coexist] ${_name}: identical")
  else()
    _behavior_equivalent("${_cmake_path}" "${_legacy_path}" "${_name}" _beh_eq)
    if(_beh_eq)
      math(EXPR _equivalent_count "${_equivalent_count} + 1")
      message(STATUS "[coexist] ${_name}: behavior-equivalent")
    else()
      file(SHA256 "${_cmake_path}" _cmake_sha)
      file(SHA256 "${_legacy_path}" _legacy_sha)
      message(WARNING "[coexist] ${_name}: differs (cmake=${_cmake_sha} legacy=${_legacy_sha})")
      math(EXPR _mismatch_count "${_mismatch_count} + 1")
    endif()
  endif()
endforeach()

if(_mismatch_count GREATER 0 AND STRICT_COMPARE)
  message(FATAL_ERROR "[coexist] ${_mismatch_count}/${_checked_count} artifacts differ between CMake and legacy outputs")
endif()

message(STATUS "[coexist] compared ${_checked_count} artifact(s), mismatches: ${_mismatch_count}, behavior-equivalent: ${_equivalent_count}, skipped: ${_skipped_count}")
