if(NOT DEFINED LEFT_DIR OR NOT DEFINED RIGHT_DIR)
  message(FATAL_ERROR "LEFT_DIR and RIGHT_DIR must be defined")
endif()

if(NOT EXISTS "${LEFT_DIR}")
  message(FATAL_ERROR "LEFT_DIR does not exist: ${LEFT_DIR}")
endif()
if(NOT EXISTS "${RIGHT_DIR}")
  message(FATAL_ERROR "RIGHT_DIR does not exist: ${RIGHT_DIR}")
endif()

if(NOT DEFINED FAIL_ON_DIFF)
  set(FAIL_ON_DIFF ON)
endif()

function(_collect_files root out_var)
  get_filename_component(_root_abs "${root}" ABSOLUTE)
  file(GLOB_RECURSE _abs_files RELATIVE "${_root_abs}" "${_root_abs}/*")
  set(_files)
  foreach(_f IN LISTS _abs_files)
    if(NOT IS_DIRECTORY "${_root_abs}/${_f}")
      list(APPEND _files "${_f}")
    endif()
  endforeach()
  list(SORT _files)
  set(${out_var} "${_files}" PARENT_SCOPE)
endfunction()

_collect_files("${LEFT_DIR}" _left_files)
_collect_files("${RIGHT_DIR}" _right_files)

set(_missing_in_right)
set(_missing_in_left)
set(_diff_files)
set(_same_count 0)

foreach(_f IN LISTS _left_files)
  if(NOT EXISTS "${RIGHT_DIR}/${_f}" AND NOT IS_SYMLINK "${RIGHT_DIR}/${_f}")
    list(APPEND _missing_in_right "${_f}")
    continue()
  endif()

  if(IS_SYMLINK "${LEFT_DIR}/${_f}" OR IS_SYMLINK "${RIGHT_DIR}/${_f}")
    if(NOT (IS_SYMLINK "${LEFT_DIR}/${_f}" AND IS_SYMLINK "${RIGHT_DIR}/${_f}"))
      list(APPEND _diff_files "${_f}")
      continue()
    endif()
    file(READ_SYMLINK "${LEFT_DIR}/${_f}" _llink)
    file(READ_SYMLINK "${RIGHT_DIR}/${_f}" _rlink)
    if(NOT _llink STREQUAL _rlink)
      list(APPEND _diff_files "${_f}")
    else()
      math(EXPR _same_count "${_same_count} + 1")
    endif()
    continue()
  endif()

  file(SIZE "${LEFT_DIR}/${_f}" _lsize)
  file(SIZE "${RIGHT_DIR}/${_f}" _rsize)
  if(NOT _lsize EQUAL _rsize)
    list(APPEND _diff_files "${_f}")
    continue()
  endif()

  file(SHA256 "${LEFT_DIR}/${_f}" _lsha)
  file(SHA256 "${RIGHT_DIR}/${_f}" _rsha)
  if(NOT _lsha STREQUAL _rsha)
    list(APPEND _diff_files "${_f}")
  else()
    math(EXPR _same_count "${_same_count} + 1")
  endif()
endforeach()

foreach(_f IN LISTS _right_files)
  if(NOT EXISTS "${LEFT_DIR}/${_f}" AND NOT IS_SYMLINK "${LEFT_DIR}/${_f}")
    list(APPEND _missing_in_left "${_f}")
  endif()
endforeach()

list(LENGTH _missing_in_right _miss_r_n)
list(LENGTH _missing_in_left _miss_l_n)
list(LENGTH _diff_files _diff_n)
list(LENGTH _left_files _left_n)
list(LENGTH _right_files _right_n)

message(STATUS "[parity] left files:  ${_left_n}")
message(STATUS "[parity] right files: ${_right_n}")
message(STATUS "[parity] identical:   ${_same_count}")
message(STATUS "[parity] missing right: ${_miss_r_n}")
message(STATUS "[parity] missing left:  ${_miss_l_n}")
message(STATUS "[parity] differing:     ${_diff_n}")

if(_miss_r_n GREATER 0)
  message(STATUS "[parity] sample missing in right:")
  list(SUBLIST _missing_in_right 0 20 _sample)
  foreach(_f IN LISTS _sample)
    message(STATUS "  - ${_f}")
  endforeach()
endif()

if(_miss_l_n GREATER 0)
  message(STATUS "[parity] sample missing in left:")
  list(SUBLIST _missing_in_left 0 20 _sample)
  foreach(_f IN LISTS _sample)
    message(STATUS "  - ${_f}")
  endforeach()
endif()

if(_diff_n GREATER 0)
  message(STATUS "[parity] sample differing files:")
  list(SUBLIST _diff_files 0 20 _sample)
  foreach(_f IN LISTS _sample)
    message(STATUS "  - ${_f}")
  endforeach()
endif()

if(FAIL_ON_DIFF AND (_miss_r_n GREATER 0 OR _miss_l_n GREATER 0 OR _diff_n GREATER 0))
  message(FATAL_ERROR "[parity] output trees differ")
endif()
