cmake_minimum_required(VERSION 3.20)
if(MODULE_LINK_MANIFEST)
  include("${MODULE_LINK_MANIFEST}")
endif()

if(KICKSTART_OUTPUT)
  include("${CMAKE_CURRENT_LIST_DIR}/AROSMmakeBuild.cmake")
  _aros_find_toolchain_program(collect-aros _collect)
  _aros_find_toolchain_program(objcopy _objcopy)
  _aros_find_toolchain_program(nm _nm)
  if(NOT _collect OR NOT _objcopy OR NOT _nm)
    message(FATAL_ERROR "Kickstart objects require collect-aros, objcopy and nm in ${AROS_TOOLCHAIN_DIR}")
  endif()
  get_filename_component(_output_dir "${KICKSTART_OUTPUT}" DIRECTORY)
  file(MAKE_DIRECTORY "${_output_dir}")
  set(_link_command "${_collect}" -Ur -o "${KICKSTART_OUTPUT}" ${_module_kobj_objects}
    ${_module_kobj_ldflags}
    "-L${AROS_NATIVE_PUBLIC_LIB_DIR}" "-L${AROS_NATIVE_PRIVATE_LIB_DIR}" "-L${AROS_NATIVE_REL_LIB_DIR}")
  foreach(_lib IN LISTS _module_kobj_libs)
    list(APPEND _link_command "-l${_lib}")
  endforeach()
endif()

execute_process(COMMAND ${_link_command} RESULT_VARIABLE _result COMMAND_ECHO STDOUT)
if(NOT _result EQUAL 0)
  message(FATAL_ERROR "Module link failed (${_result})")
endif()

if(KICKSTART_OUTPUT)
  execute_process(COMMAND "${_nm}" "${KICKSTART_OUTPUT}"
    OUTPUT_VARIABLE _symbols RESULT_VARIABLE _result)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Cannot inspect kickstart symbols")
  endif()
  set(_local_symbols DOSBase IntuitionBase LayersBase GfxBase OOPBase
    UtilityBase ExpansionBase KeymapBase KernelBase)
  string(REPLACE "\n" ";" _symbol_lines "${_symbols}")
  foreach(_line IN LISTS _symbol_lines)
    if(_line MATCHES "[ \t](__.*_(LIST|END)__|__aros_lib[^ \t\r]*)\r?$")
      list(APPEND _local_symbols "${CMAKE_MATCH_1}")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES _local_symbols)
  set(_localize_args)
  foreach(_symbol IN LISTS _local_symbols)
    list(APPEND _localize_args -L "${_symbol}")
  endforeach()
  execute_process(COMMAND "${_objcopy}" "${KICKSTART_OUTPUT}" ${_localize_args}
    RESULT_VARIABLE _result COMMAND_ECHO STDOUT)
elseif(_module_strip)
  execute_process(COMMAND "${_module_strip}" --strip-unneeded -R.comment "${MODULE_OUTPUT}"
    RESULT_VARIABLE _result)
endif()
if(NOT _result EQUAL 0)
  message(FATAL_ERROR "Module post-link processing failed (${_result})")
endif()
