if(NOT DEFINED AROS_SOURCE_DIR OR NOT DEFINED AROS_BINARY_DIR OR NOT DEFINED AROS_TARGET)
  message(FATAL_ERROR "AROS_SOURCE_DIR, AROS_BINARY_DIR, and AROS_TARGET must be defined")
endif()

set(_aros_config_build_dir "${AROS_BINARY_DIR}")
if(DEFINED AROS_CONFIG_BUILD_DIR AND AROS_CONFIG_BUILD_DIR)
  set(_aros_config_build_dir "${AROS_CONFIG_BUILD_DIR}")
endif()

set(_aros_target_cfg "${_aros_config_build_dir}/bin/${AROS_TARGET}/gen/config/target.cfg")
if(NOT EXISTS "${_aros_target_cfg}")
  message(FATAL_ERROR "Target configuration not found: ${_aros_target_cfg}. Run target aros-configure first.")
endif()

string(REPLACE "-" ";" _aros_target_parts "${AROS_TARGET}")
list(LENGTH _aros_target_parts _aros_target_parts_len)
if(_aros_target_parts_len LESS 2)
  message(FATAL_ERROR "AROS_TARGET must be in form <arch>-<cpu>[-<variant>], got: ${AROS_TARGET}")
endif()

list(GET _aros_target_parts 0 _aros_arch)
list(GET _aros_target_parts 1 _aros_cpu)
set(_aros_variant "")
if(_aros_target_parts_len GREATER 2)
  list(SUBLIST _aros_target_parts 2 -1 _aros_variant_parts)
  string(REPLACE ";" "-" _aros_variant "${_aros_variant_parts}")
endif()

file(STRINGS "${_aros_target_cfg}" _aros_family_line REGEX "^FAMILY[ \t]*:=")
if(_aros_family_line)
  string(REGEX REPLACE "^FAMILY[ \t]*:=[ \t]*" "" _aros_family "${_aros_family_line}")
  string(STRIP "${_aros_family}" _aros_family)
else()
  set(_aros_family "${_aros_arch}")
endif()

set(_aros_alias_layers)
if(_aros_variant)
  list(APPEND _aros_alias_layers "${_aros_arch}-${_aros_cpu}-${_aros_variant}")
endif()
list(APPEND _aros_alias_layers "${_aros_arch}-${_aros_cpu}")
if(_aros_variant)
  list(APPEND _aros_alias_layers "${_aros_arch}-${_aros_variant}")
endif()
list(APPEND _aros_alias_layers "${_aros_arch}" "${_aros_family}" "${_aros_cpu}")
list(REMOVE_DUPLICATES _aros_alias_layers)

set(_aros_dir_layers)
if(_aros_variant)
  list(APPEND _aros_dir_layers "${_aros_cpu}-${_aros_arch}-${_aros_variant}")
endif()
list(APPEND _aros_dir_layers "${_aros_cpu}-${_aros_arch}" "all-${_aros_arch}" "all-${_aros_family}" "${_aros_cpu}-all")
list(REMOVE_DUPLICATES _aros_dir_layers)

message(STATUS "AROS layering report")
message(STATUS "  target : ${AROS_TARGET}")
message(STATUS "  arch   : ${_aros_arch}")
message(STATUS "  cpu    : ${_aros_cpu}")
message(STATUS "  family : ${_aros_family}")
if(_aros_variant)
  message(STATUS "  variant: ${_aros_variant}")
else()
  message(STATUS "  variant: <none>")
endif()

message(STATUS "  alias chain (MetaMake target order):")
foreach(_aros_layer IN LISTS _aros_alias_layers)
  message(STATUS "    - ${_aros_layer}")
endforeach()

message(STATUS "  resolved arch directory candidates:")
set(_aros_existing_layers)
foreach(_aros_layer IN LISTS _aros_dir_layers)
  set(_aros_layer_dir "${AROS_SOURCE_DIR}/arch/${_aros_layer}")
  if(EXISTS "${_aros_layer_dir}")
    list(APPEND _aros_existing_layers "${_aros_layer}")
    message(STATUS "    - ${_aros_layer} (exists)")
  else()
    message(STATUS "    - ${_aros_layer} (missing)")
  endif()
endforeach()

message(STATUS "  rom-related layer directories:")
foreach(_aros_layer IN LISTS _aros_existing_layers)
  set(_aros_layer_dir "${AROS_SOURCE_DIR}/arch/${_aros_layer}")
  if(EXISTS "${_aros_layer_dir}")
    file(GLOB _aros_layer_children RELATIVE "${_aros_layer_dir}" "${_aros_layer_dir}/*")
    set(_aros_printed FALSE)
    foreach(_aros_child IN LISTS _aros_layer_children)
      if(IS_DIRECTORY "${_aros_layer_dir}/${_aros_child}" AND EXISTS "${AROS_SOURCE_DIR}/rom/${_aros_child}")
        if(NOT _aros_printed)
          message(STATUS "    arch/${_aros_layer}:")
          set(_aros_printed TRUE)
        endif()
        message(STATUS "      - ${_aros_child} (overrides rom/${_aros_child})")
      endif()
    endforeach()
  endif()
endforeach()
